/**
 * Sign-in-House habit audit data for Eclipse Teaching Mode.
 * 
 * Each sign has core "expired habit" patterns. When filtered through a house,
 * they become concrete, personal examples the user can recognize in their life.
 * 
 * Structure: SIGN_HOUSE_HABITS[sign][house] = string[]
 * Each string is a plain-language example of that sign's shadow habit
 * showing up in that house's life area.
 */

export type SignHouseHabits = Record<string, Record<number, string[]>>;

export const SIGN_HOUSE_HABITS: SignHouseHabits = {
  Virgo: {
    1: [
      "Constantly monitoring your body for what's 'wrong' — the mole, the bloating, the fatigue — instead of listening to what your body actually needs",
      "Editing yourself before you speak, dress, or act — running every impulse through an internal 'is this good enough?' filter",
      "Maintaining a 'healthy' routine that's actually rigid and joyless — you do it because you 'should,' not because it makes you feel alive",
      "Presenting a polished, competent version of yourself while hiding the messy, uncertain parts that make you human",
      "Over-identifying with being 'the responsible one' or 'the one who has it together' to the point where asking for help feels like failure",
    ],
    2: [
      "Tracking every dollar, every calorie, every expense in spreadsheets — but never actually feeling secure no matter how precise the numbers are",
      "Undercharging or undervaluing yourself because your inner critic says your work 'could always be better'",
      "Buying the practical option instead of the one you actually want — because wanting nice things feels 'irresponsible'",
      "Saving compulsively while denying yourself small pleasures, as if enjoying money means you'll lose it",
      "Defining your worth by your productivity — if you didn't accomplish anything today, you feel like you don't deserve to rest",
    ],
    3: [
      "Editing texts and emails five times before sending — agonizing over the 'right' word when any word would do",
      "Over-explaining yourself in conversation because you're afraid of being misunderstood",
      "Mentally cataloging everything your siblings or neighbors do 'wrong' while keeping your critique internal",
      "Reading and researching endlessly instead of forming your own opinion — because what if you're wrong?",
      "Turning every casual conversation into a problem-solving session instead of just connecting",
    ],
    4: [
      "Keeping the house perfectly clean and organized as a way to feel in control when your emotional life is chaotic",
      "Mothering or caretaking your family members to the point where they can't (or won't) take care of themselves",
      "Criticizing how family members load the dishwasher, fold laundry, or cook — because it's not 'right' unless it's YOUR way",
      "Burying emotional needs under domestic productivity — 'I'm fine, I just need to reorganize the pantry'",
      "Maintaining the family schedule, meal plans, and logistics while quietly resenting that no one else notices the work",
    ],
    5: [
      "Refusing to create, play, or perform unless you can do it 'perfectly' — which means you rarely do it at all",
      "Editing the fun out of hobbies by turning them into optimization projects (the joy of painting becomes a technique study)",
      "Being so critical of your creative output that you never share it — the novel stays in the drawer, the song stays unrecorded",
      "Parenting through correction rather than celebration — focusing on what your child needs to 'improve' instead of what they're already doing well",
      "Dating with a mental checklist instead of being present — analyzing compatibility instead of feeling chemistry",
    ],
    6: [
      "This is Virgo's home house — so the habits here are DEEPLY ingrained. You may be running the most sophisticated optimization system for your daily life and still feel like it's never enough",
      "Perfecting your health routine to the point where it becomes its own source of stress — the supplements, the tracking, the guilt when you 'slip'",
      "Doing everyone else's job at work because 'it's faster if I just do it myself' — and then resenting them for not helping",
      "Treating your body like a machine to be maintained rather than a living thing to be inhabited — efficiency over pleasure, always",
      "Staying in a job that underutilizes you because at least you're 'useful' — confusing being needed with being valued",
    ],
    7: [
      "Keeping a mental scorecard of everything your partner does wrong — the unwashed dishes, the forgotten dates, the imprecise language",
      "Trying to 'fix' or 'improve' your partner instead of accepting them as they are — love as a renovation project",
      "Withholding full commitment because you're waiting for the 'perfect' relationship — one that doesn't exist",
      "Offering helpful advice when your partner just wants you to listen — solving instead of connecting",
      "Staying in a partnership where you do all the emotional and practical labor because leaving would mean you 'failed'",
    ],
    8: [
      "Micromanaging shared finances, joint accounts, or debts — controlling money as a way to manage the anxiety of depending on someone else",
      "Analyzing your emotional wounds so thoroughly that understanding them becomes a substitute for actually healing them",
      "Using therapy language to keep people at arm's length — 'I'm processing' as a way to avoid vulnerability",
      "Researching death, taxes, or insurance compulsively instead of sitting with the uncertainty that these topics trigger",
      "Keeping meticulous track of who owes what in shared resources — because true emotional merging feels terrifyingly imprecise",
    ],
    9: [
      "Studying spirituality or philosophy as an intellectual exercise — reading ABOUT wisdom without actually practicing it",
      "Critiquing other belief systems or teaching methods rather than committing to your own path",
      "Over-preparing for travel, courses, or adventures to the point where the preparation replaces the experience",
      "Correcting people's facts, grammar, or logic in conversations about meaning — missing the forest for the trees",
      "Pursuing degrees, certifications, and credentials as proof of worth — learning as a way to feel 'ready' when you were ready years ago",
    ],
    10: [
      "Building your career on being indispensable — the person who catches every error, fills every gap — while burning out silently",
      "Refusing to delegate or accept 'good enough' work from others, so you end up doing everything yourself",
      "Defining success by how hard you work rather than what you actually create or contribute",
      "Maintaining a flawless public reputation while your private life crumbles from neglect",
      "Staying in a career that values your competence but not your passion — because competence is safe and passion is risky",
    ],
    11: [
      "Being the reliable friend who organizes everything, remembers everything, and follows up on everything — while nobody does the same for you",
      "Joining groups and communities for self-improvement rather than genuine connection — friendships as personal development projects",
      "Critiquing your social circle's choices, lifestyles, or politics internally while keeping your judgments private and your smile perfect",
      "Volunteering for every committee, task force, and organizing effort until your 'service to the community' has consumed your personal life",
      "Setting impossibly high standards for friendships — so nobody quite measures up and you stay safely on the periphery",
    ],
    12: [
      "Using meditation, journaling, or spiritual practice as another thing to optimize — tracking your 'growth' metrics instead of surrendering to the process",
      "Analyzing your dreams, synchronicities, and intuitions so thoroughly that you intellectualize away the mystery they're trying to show you",
      "Keeping your inner world meticulously organized — categorizing emotions, labeling patterns — as a way to avoid actually FEELING them",
      "Self-isolating under the guise of 'needing alone time' when what you really need is to let someone see the unpolished version of you",
      "Treating rest as something you have to earn — even your downtime has a purpose and a schedule",
    ],
  },

  Pisces: {
    1: [
      "Absorbing everyone else's emotions until you've lost track of which feelings are actually yours",
      "Drifting through identity changes — chameleon-style — because committing to being ONE person feels limiting",
      "Using spirituality or 'going with the flow' as an excuse to avoid making concrete decisions about your life",
      "Neglecting your physical body because you live so much in your imagination, your emotions, or your spiritual life",
      "Presenting yourself as easygoing and flexible when you're actually overwhelmed and dissociating",
    ],
    2: [
      "Being vague about money — not knowing what you earn, what you spend, or what you owe — because numbers feel 'unspiritual'",
      "Giving away your resources, time, and energy to anyone who asks — then wondering why you never have enough for yourself",
      "Undercharging because you feel guilty profiting from work that 'should' be offered freely",
      "Fantasizing about future abundance instead of managing present reality — the vision board replaces the budget",
      "Confusing financial sacrifice with spiritual virtue — as if being broke proves you're a good person",
    ],
    3: [
      "Communicating in vague, impressionistic ways and then feeling hurt when people misunderstand you",
      "Avoiding difficult conversations by retreating into silence, tears, or mystical non-answers",
      "Absorbing information passively without ever forming your own clear opinion or boundary",
      "Over-romanticizing childhood, siblings, or your neighborhood instead of seeing them clearly",
      "Using creative or poetic language to obscure what you actually mean — beauty as avoidance",
    ],
    4: [
      "Making your home a refuge from reality to the point where you rarely want to leave",
      "Carrying your family's emotional weight — their sadness, their anxiety, their unresolved grief — as if it were your own",
      "Idealizing your parents or childhood instead of seeing the complicated truth",
      "Using substances, screens, or sleep to 'escape' when home life becomes stressful",
      "Creating such a nurturing environment for others that you forget to nurture yourself within it",
    ],
    5: [
      "Starting creative projects with enormous inspiration and then abandoning them when the mundane work begins",
      "Romanticizing love to the point where real partners can never live up to the fantasy",
      "Using creativity as an escape from reality rather than a way to engage with it",
      "Giving your children everything emotionally while struggling to provide practical structure",
      "Losing yourself in entertainment, gaming, or fantasy worlds instead of creating your own",
    ],
    6: [
      "Neglecting your health routine because structure feels suffocating — then dealing with preventable problems",
      "Absorbing your coworkers' stress and drama until you dread going to work",
      "Doing work that is spiritually meaningful but practically unsustainable — passion without a plan",
      "Ignoring symptoms, deadlines, and details because dealing with them feels overwhelming",
      "Serving others at work to the point of self-neglect — then calling in sick because you've given everything away",
    ],
    7: [
      "Merging so completely with your partner that you lose your individual identity",
      "Staying in relationships long past their expiration because you feel everything your partner feels and can't bear causing them pain",
      "Idealizing partners and then feeling betrayed when they turn out to be human",
      "Avoiding conflict by going along with whatever your partner wants — then resenting them silently",
      "Seeking a 'soulmate' or 'twin flame' instead of building a real partnership with a real person",
    ],
    8: [
      "Getting lost in emotional or sexual intensity — using merging as a way to avoid your own individual wounds",
      "Using psychic or intuitive gifts without grounding — picking up on everyone's shadow without knowing what to do with it",
      "Avoiding practical conversations about money, wills, or shared resources because they feel 'heavy'",
      "Spiritual bypassing around death, loss, and grief — 'they're in a better place' instead of actually grieving",
      "Giving away your power in intimate relationships because boundaries feel like walls",
    ],
    9: [
      "Collecting spiritual practices like stamps without committing deeply to any single path",
      "Using spiritual beliefs to avoid engaging with the practical, material world",
      "Idealizing teachers, gurus, or distant cultures instead of finding wisdom in your own experience",
      "Traveling or studying to escape your current reality rather than to genuinely expand",
      "Believing that understanding the meaning of life is a substitute for actually living it",
    ],
    10: [
      "Having a beautiful vision for your career but struggling to take the concrete steps to build it",
      "Resisting structure, titles, and authority because they feel like cages — even when they'd actually support your work",
      "Being seen as unreliable professionally because you follow inspiration rather than deadlines",
      "Sacrificing career advancement because your work 'isn't about money' — while struggling financially",
      "Absorbing your boss's or organization's dysfunction as if it were your own emotional responsibility",
    ],
    11: [
      "Losing yourself in group causes and collective emotions — unable to distinguish your own hopes from the group's",
      "Befriending people who need rescuing rather than people who can show up for you equally",
      "Having grand visions for changing the world but struggling to follow through on the practical steps",
      "Idealizing community while avoiding the mundane work of maintaining real friendships",
      "Using social media or online communities as a substitute for genuine face-to-face connection",
    ],
    12: [
      "This is Pisces' home house — so these patterns run DEEP, often invisibly. You may not even realize you're doing them",
      "Retreating into your inner world so completely that you lose touch with external reality for days at a time",
      "Using substances, sleep, fantasy, or spiritual practice to escape pain instead of processing it",
      "Carrying collective grief, ancestral wounds, or spiritual burdens that aren't yours to carry alone",
      "Refusing to set boundaries because you experience other people's pain as your own — and saying 'no' feels like causing suffering",
    ],
  },

  Aries: {
    1: ["Reacting to everything with aggression or urgency — treating every situation like a battle to be won", "Refusing to slow down, rest, or show vulnerability because it feels like weakness", "Starting new identities, looks, or lifestyles impulsively and abandoning them just as fast", "Making everything about you — not from narcissism, but from the inability to see situations from others' perspectives", "Using anger as your default emotion because it feels safer than sadness, fear, or need"],
    2: ["Impulsive spending — buying things in the heat of the moment and regretting them later", "Equating your worth with your ability to compete, win, or dominate in earning", "Hoarding resources aggressively or refusing to share because scarcity triggers your survival instinct", "Demanding immediate financial results instead of building wealth patiently", "Treating money as a score in a competition rather than a tool for living well"],
    3: ["Dominating conversations — talking over people, finishing their sentences, or redirecting to your point", "Arguing to win rather than to understand — every discussion becomes a debate", "Rushing through learning without absorbing the material because you want to move on to the next thing", "Using words as weapons when frustrated — sharp comments that cut deeper than you realize", "Being impatient with siblings, neighbors, or daily interactions that move slower than you want"],
    4: ["Running the household like a military operation — efficiency over warmth", "Losing your temper at home because it's the only 'safe' place to express frustration", "Resisting emotional vulnerability with family — showing strength when what they need is tenderness", "Cutting off family members abruptly when conflicts arise instead of working through them", "Treating your home as a place to crash between activities rather than a place to truly live"],
    5: ["Competing with your own children or creative projects instead of nurturing them", "Turning every hobby into a competition — even leisure has to be won", "Burning through romances at high speed — the chase is thrilling but you bail when it slows down", "Creating for impact or attention rather than for the joy of the process itself", "Pushing your kids to be first, best, or fastest because you're projecting your own competitive drive"],
    6: ["Pushing through illness, injury, or exhaustion because stopping feels like defeat", "Being aggressive or impatient with coworkers who move at a different pace", "Starting health kicks with intense enthusiasm and abandoning them within weeks", "Creating a work environment that's high-energy but hostile — your urgency becomes everyone else's stress", "Refusing to delegate because nobody does it fast enough for your standards"],
    7: ["Starting fights with your partner to create excitement — mistaking conflict for passion", "Competing with your partner instead of collaborating — relationships as a power struggle", "Leaving relationships the moment they become boring or require patience", "Expecting your partner to match your energy and pace at all times — and resenting them when they can't", "Being attracted to conquest rather than connection — the chase matters more than the relationship"],
    8: ["Using emotional intensity as a weapon — weaponizing vulnerability or intimacy", "Rushing through grief or crisis instead of letting yourself fully process loss", "Dominating shared financial decisions — 'my way or the highway' with joint resources", "Turning emotional confrontations into battles to be won rather than wounds to be healed", "Using sexual energy as power rather than connection"],
    9: ["Being dogmatic about your beliefs — treating your worldview as the only valid one", "Rushing through education or travel without letting the experience change you", "Arguing about philosophy, religion, or politics with combative energy", "Starting grand adventures without planning and ending up in preventable crises", "Treating spiritual growth as a competition — who's further along the path"],
    10: ["Burning bridges in your career through impulsive decisions or aggressive confrontations", "Chasing titles, promotions, and status as if your worth depends on being #1", "Leading through force rather than inspiration — people follow you out of fear, not respect", "Quitting jobs impulsively when you feel constrained instead of working within the system strategically", "Building a reputation as someone who gets things done — at any cost, including relationships"],
    11: ["Taking over groups and organizations with forceful leadership that doesn't leave room for others", "Burning through friend groups when conflicts arise — cutting people off rather than repairing", "Pursuing social causes with warrior energy that alienates the people you're trying to help", "Needing to be the leader in every group setting — struggling to be a team player", "Using your social network as a competitive arena rather than a support system"],
    12: ["Suppressing anger until it explodes in unexpected ways — the pressure cooker effect", "Using busyness and action to avoid your inner world — always doing, never being", "Fighting against rest, solitude, and stillness as if they were the enemy", "Carrying unconscious rage that manifests as headaches, accidents, or confrontations", "Treating your subconscious mind as something to conquer rather than something to listen to"],
  },

  Taurus: {
    1: ["Resisting any change to your appearance, habits, or self-presentation — even when you've outgrown them", "Moving so slowly that opportunities pass you by while you're still 'thinking about it'", "Using comfort and routine as armor — if nothing changes, nothing can hurt you", "Stubbornly maintaining a self-image that no longer reflects who you're becoming", "Confusing patience with inertia — you're not waiting for the right time, you're avoiding all time"],
    2: ["Hoarding money, possessions, or resources far beyond what you actually need for security", "Refusing to invest, spend, or risk because holding on feels safer than letting go", "Defining your self-worth entirely through material possessions — you are what you own", "Overindulging in food, shopping, or sensory pleasure as a substitute for emotional fulfillment", "Staying in an underpaying but comfortable financial situation because change feels threatening"],
    3: ["Being so fixed in your opinions that you stop learning — mistaking stubbornness for conviction", "Communicating in a slow, measured way that becomes stonewalling when you're upset", "Refusing to engage with ideas that challenge your worldview", "Repeating the same stories and perspectives without updating them", "Avoiding difficult conversations by going silent — the 'I'm fine' that means 'I refuse to discuss this'"],
    4: ["Clinging to a family home, family traditions, or family dynamics that no longer serve anyone", "Creating such a comfortable home environment that it becomes a gilded cage", "Resisting moves, renovations, or family changes because 'this is how we've always done it'", "Using cooking, decorating, or homemaking as a way to control your environment when emotions get messy", "Staying in a living situation that's materially comfortable but emotionally dead"],
    5: ["Refusing to try new creative approaches because the old ones are comfortable", "Turning creative joy into a commercial product — monetizing the fun out of your art", "Being possessive in romance — treating partners as belongings rather than free agents", "Resisting creative risk because failure feels like a waste of resources", "Spoiling children with material things instead of emotional presence"],
    6: ["Staying in a health routine that stopped working years ago because changing it feels overwhelming", "Eating the same meals, walking the same route, doing the same exercises — comfort masquerading as discipline", "Resisting workplace changes that would actually improve your daily life", "Using 'I'm just a creature of habit' as an excuse for never challenging yourself in daily practices", "Prioritizing physical comfort at work over growth, challenge, or meaning"],
    7: ["Staying in a relationship long past its expiration because leaving feels too disruptive", "Possessiveness disguised as devotion — needing to know your partner is 'yours'", "Refusing to renegotiate relationship terms because 'we agreed on this years ago'", "Valuing stability in partnership over truth — choosing comfort over honesty", "Making your partner responsible for your sense of security"],
    8: ["Refusing to let go of shared assets, inheritances, or financial entanglements", "Using material security to avoid emotional vulnerability — 'I'll share my money but not my fears'", "Resisting therapeutic or transformative processes because they threaten your comfort zone", "Hoarding emotional energy — feeling things deeply but refusing to express or release them", "Staying in a dead intimacy pattern because it's familiar"],
    9: ["Clinging to beliefs you inherited rather than exploring what you actually think", "Refusing to travel, study, or expand because your current worldview feels safe enough", "Treating your faith or philosophy as finished — nothing new to learn", "Avoiding big-picture thinking because it threatens the small, comfortable world you've built", "Collecting wisdom without letting it change your actual behavior"],
    10: ["Staying in the same career for decades because the routine is comfortable — not because it's fulfilling", "Building professional security at the expense of professional growth", "Resisting promotions, pivots, or new opportunities because the known feels safer", "Defining your legacy by material accomplishments rather than genuine impact", "Being the reliable one at work to the point where people take you for granted"],
    11: ["Sticking with the same friend group for years even when you've outgrown each other", "Resisting new social circles or communities because familiar friends feel safer", "Contributing money or resources to causes instead of your time, presence, or voice", "Avoiding group settings that challenge your values or perspective", "Being the stable, dependable friend while secretly resenting that nobody checks on you"],
    12: ["Resisting spiritual practices that ask you to let go of material attachments", "Using sleep, food, or physical comfort to escape emotional or spiritual pain", "Holding onto grudges, grief, or past hurts because releasing them feels like losing something", "Avoiding solitude because stillness surfaces all the uncomfortable feelings you've been suppressing with sensory pleasure", "Treating the subconscious as irrelevant — 'I deal with what's real, not what's imagined'"],
  },

  Gemini: {
    1: ["Presenting different versions of yourself to different people and losing track of which one is real", "Using humor, charm, or cleverness to deflect anything that might require genuine emotional engagement", "Changing your mind so often that people can't rely on what you say", "Staying permanently 'young' or 'lighthearted' to avoid the depth that maturity requires", "Filling every silence with words because stillness feels unbearable"],
    2: ["Having multiple income streams that keep you busy but never building real financial depth", "Rationalizing purchases with clever justifications instead of checking in with what you actually need", "Talking about financial plans without executing them — the plan becomes the product", "Valuing cleverness and versatility over genuine expertise — a jack of all trades, master of none", "Spending on information, courses, and books instead of investing in lasting security"],
    3: ["Talking about everything but committing to nothing — words without weight", "Knowing a little about a lot but refusing to go deep on anything", "Gossiping as a form of social currency — trading information instead of building trust", "Intellectualizing emotions — analyzing feelings instead of feeling them", "Using constant communication (texting, posting, chatting) as a substitute for genuine connection"],
    4: ["Having such a busy mental life that you're rarely emotionally present at home", "Treating family relationships as sources of information rather than emotional bonds", "Moving homes frequently because the novelty wears off and restlessness sets in", "Keeping the household atmosphere light and chatty to avoid deeper family tensions", "Rationalizing away childhood wounds instead of processing them emotionally"],
    5: ["Starting ten creative projects and finishing none — the beginning is fun, the middle is boring", "Intellectualizing romance — analyzing attraction instead of experiencing it", "Being so witty on dates that nobody gets past your surface to the real you", "Parenting through information and explanation rather than emotional presence", "Treating love like a puzzle to solve rather than an experience to surrender to"],
    6: ["Multitasking so aggressively at work that nothing gets your full attention", "Job-hopping because routine becomes intolerable — even healthy routine", "Using information about health instead of actual healthy habits — knowing what to do but not doing it", "Nervously managing every detail instead of trusting a system to handle the mundane", "Creating elaborate organizational systems that are more work to maintain than the work itself"],
    7: ["Keeping relationships light to avoid the heavy conversations that build real intimacy", "Being attracted to people who stimulate your mind but never challenge your heart", "Using logic and debate to win relationship arguments instead of actually resolving them", "Having one foot out the door in every relationship because commitment feels like a trap", "Talking about relationship problems with everyone except your partner"],
    8: ["Intellectualizing trauma, grief, and loss — understanding them conceptually but not processing them emotionally", "Using dark humor to deflect from genuine pain or vulnerability", "Researching psychology and transformation without actually doing the inner work", "Talking about intimacy rather than being intimate — narrating the experience instead of having it", "Flitting between emotional depths and surface-level distractions to avoid sustained intensity"],
    9: ["Sampling every philosophy and belief system without committing to any of them", "Arguing about truth more than seeking it — debate as sport", "Planning trips and studies that never happen — the itinerary replaces the journey", "Using intellectual frameworks to avoid the experiential wisdom that only comes from living", "Citing experts instead of developing your own authority"],
    10: ["Building a career on versatility rather than mastery — being useful but never essential", "Juggling so many professional projects that none reach their full potential", "Using networking and communication skills to advance while avoiding the deep expertise your field requires", "Rebranding yourself every few years instead of building a coherent professional identity", "Being known as the clever one rather than the wise one"],
    11: ["Being the social connector who knows everyone but is truly close to no one", "Using friend groups for stimulation rather than genuine support", "Spreading yourself across so many communities that you belong to none", "Gossiping or information-sharing as a substitute for real group contribution", "Avoiding causes that require sustained commitment — showing up for the rally but not the follow-through"],
    12: ["Using constant mental stimulation to avoid the stillness your subconscious needs", "Analyzing dreams, intuitions, and spiritual experiences until the mystery is explained away", "Nervously filling spiritual practices with chatter, notes, and intellectual frameworks", "Avoiding meditation or contemplation because your mind won't 'shut up'", "Treating the inner world as another information source to be processed rather than a realm to be experienced"],
  },

  Cancer: {
    1: ["Defining your identity through who needs you rather than who you are", "Using emotional sensitivity as armor — 'I'm too sensitive for this' as a way to avoid challenge", "Withdrawing into your shell at the first sign of conflict instead of engaging", "Clinging to an outdated version of yourself because it feels safe and familiar", "Letting your mood dictate your actions, your day, and your relationships"],
    2: ["Hoarding resources and money 'just in case' — driven by a scarcity fear that never resolves", "Emotional spending — shopping to soothe anxiety, sadness, or loneliness", "Tying your self-worth to your ability to provide for or feed others", "Being unable to enjoy wealth because you're always afraid it could disappear", "Refusing to invest or risk because security feels more important than growth"],
    3: ["Communicating from emotion rather than clarity — what you say depends on your mood", "Taking everything personally in daily interactions — the barista's tone becomes an emotional event", "Avoiding honest conversations because you're afraid of hurting feelings (yours or theirs)", "Ruminating on past conversations and interactions instead of being present", "Using nostalgia and sentiment to avoid making clear, direct statements"],
    4: ["Making your family's problems your identity — 'I am my family's keeper'", "Refusing to leave the family home, family town, or family patterns even when they're suffocating you", "Creating a home environment that's nurturing for everyone except yourself", "Using family obligations as an excuse to avoid your own dreams and development", "Replicating your mother's patterns — good and bad — without examining them"],
    5: ["Nurturing your children or creative projects to the point of smothering them", "Being unable to play, create, or romance without emotional attachment turning it heavy", "Taking creative rejection as personal rejection — criticism of your art feels like criticism of your soul", "Being so emotionally invested in your children that their struggles become your crises", "Needing creative output to be emotionally meaningful — struggling to make things that are simply fun"],
    6: ["Bringing your emotions to work and expecting coworkers to accommodate your moods", "Caretaking at work — taking on others' tasks because you 'feel bad' if they're struggling", "Using food as medicine, comfort, and coping mechanism to the point where eating is emotional, not nourishing", "Avoiding confrontation at work even when it means your needs go unmet", "Neglecting your own health while obsessively worrying about everyone else's"],
    7: ["Mothering your partner instead of being their equal", "Using emotional needs to control the relationship — 'if you loved me you'd...'", "Choosing partners who need rescuing because it gives you a clear role", "Being unable to differentiate between love and codependence", "Retreating into hurt silence when your partner disappoints instead of communicating directly"],
    8: ["Merging emotionally with partners to the point of drowning — you can't tell where you end and they begin", "Using emotional intensity as a form of control in intimate relationships", "Carrying ancestral grief, family secrets, or inherited trauma as if they're your personal responsibility", "Avoiding financial conversations in partnerships because money + emotions = overwhelm", "Using emotional caretaking to avoid your own deep transformation"],
    9: ["Clinging to the beliefs and values you were raised with without questioning them", "Being unable to explore new philosophies because they challenge your emotional security", "Traveling only to familiar places — or not traveling at all — because the unknown feels unsafe", "Defining your spirituality through family tradition rather than personal discovery", "Getting emotionally attached to teachers, gurus, or mentors in ways that replicate parental dynamics"],
    10: ["Building a career on being needed — the indispensable caretaker who can't be fired", "Letting fear of rejection keep you from pursuing the career you actually want", "Taking professional criticism personally and withdrawing rather than adapting", "Prioritizing emotional safety over professional ambition — choosing the comfortable path", "Using 'I need to take care of my family' to justify avoiding your own public-facing goals"],
    11: ["Being the 'mom friend' who takes care of everyone in the group but never receives care in return", "Choosing friends who need you rather than friends who challenge or inspire you", "Avoiding group settings that feel emotionally unsafe — even when they'd stretch your growth", "Taking group conflicts personally and withdrawing rather than working through them", "Confusing community involvement with emotional obligation"],
    12: ["Absorbing everyone's feelings until you can't tell whose pain is whose", "Using emotional sensitivity as a reason to isolate — 'I need to protect my energy' as permanent withdrawal", "Carrying subconscious grief that isn't yours — family patterns, ancestral sorrow, collective pain", "Using nostalgia and memory as a retreat from present reality", "Refusing to examine subconscious patterns because feeling them all at once is too overwhelming"],
  },

  Leo: {
    1: ["Needing constant validation for your identity — if nobody's watching, does it count?", "Dramatizing ordinary life events because the narrative feels too quiet without a story arc", "Being unable to be ordinary, invisible, or unremarkable — even for a day", "Using charisma and performance to cover up deep insecurity about whether you're enough", "Making your appearance, presence, or impact the center of every situation — even when it's not about you"],
    2: ["Spending lavishly to project an image of success — even when the bank account tells a different story", "Needing expensive, impressive, or visible possessions to feel worthy", "Being generous to a fault — giving gifts and buying rounds to maintain your image as the magnanimous one", "Refusing to ask for financial help because it would damage your pride", "Equating your self-worth with your earning power or your ability to impress"],
    3: ["Dominating conversations with your stories, your experiences, your perspective", "Being unable to listen fully because you're preparing what you'll say next", "Using communication as performance — everything you say is crafted for impact", "Taking offense when others don't respond to your ideas with enthusiasm", "Making casual interactions into stages for your personality"],
    4: ["Creating a home that's impressive but not necessarily warm — the show house vs. the real home", "Needing to be the center of family attention — family events revolve around your feelings", "Parenting as performance — doing it well so it's SEEN, not just experienced", "Being unable to relax at home because even private life needs to feel special", "Competing with family members for attention, status, or the starring role"],
    5: ["Creating art for applause rather than genuine expression", "Being unable to play without an audience — if no one sees it, what's the point?", "Teaching children to perform and achieve rather than to explore and fail safely", "Dramatic romantic gestures that are more about how you appear in love than how you actually feel", "Competing with your own children for the spotlight"],
    6: ["Refusing mundane or unglamorous work because it's 'beneath you'", "Needing recognition for every task you complete — even routine ones", "Making your health journey a public narrative rather than a private practice", "Being unable to serve without being seen, thanked, or celebrated for it", "Creating unnecessary drama at work to keep things exciting"],
    7: ["Needing a partner who makes you look good — relationships as accessories to your image", "Competing with your partner instead of complementing them", "Expecting admiration and adoration from your partner and feeling unloved without it", "Making every relationship conflict about your wounded pride rather than the actual issue", "Being unable to be wrong, apologize, or back down in partnerships"],
    8: ["Using emotional intensity and sexual charisma as power plays", "Being unable to be vulnerable because it threatens your image of strength", "Dramatizing crises and transformations rather than quietly processing them", "Needing to control shared resources because giving up control feels like losing status", "Making your transformation journey a performance rather than a private evolution"],
    9: ["Needing to be the teacher, the guru, the one with the answers — never the student", "Treating your beliefs and worldview as superior to others'", "Traveling for impressive experiences and stories rather than genuine growth", "Publishing, teaching, or sharing your philosophy for recognition rather than service", "Being unable to say 'I don't know' about matters of meaning"],
    10: ["Building a career on image rather than substance — the appearance of success over actual contribution", "Needing public recognition, awards, and status markers to feel professionally fulfilled", "Being unable to work behind the scenes or support someone else's vision", "Taking credit for team accomplishments because sharing the spotlight feels diminishing", "Choosing career paths for prestige rather than genuine passion"],
    11: ["Needing to be the leader, the most popular, or the most visible member of every group", "Choosing friends who serve as an audience rather than as genuine peers", "Using social causes for personal brand-building rather than genuine contribution", "Being unable to participate in groups where you're not special or central", "Dramatizing group dynamics — creating factions, rivalries, or loyalty tests"],
    12: ["Fearing invisibility, anonymity, or irrelevance — the idea of being forgotten feels like death", "Being unable to rest, retreat, or be alone because solitude threatens your sense of self", "Dramatizing your inner world — even private journaling becomes a performance", "Resisting the ego-dissolution that spiritual growth requires because your ego IS your identity", "Using creative expression to avoid genuine spiritual surrender — making art about transcendence instead of experiencing it"],
  },

  Libra: {
    1: ["Defining yourself through other people's eyes — you are who they think you are", "Being unable to make decisions without consulting others first", "Performing pleasantness so consistently that nobody knows what you actually think or feel", "Avoiding conflict at all costs — even when conflict would lead to necessary change", "Spending so much energy on being liked that you've forgotten what you actually like"],
    2: ["Spending to create beauty, harmony, or an aesthetic lifestyle that you can't actually afford", "Being unable to negotiate for higher pay because it feels confrontational", "Valuing fairness in financial matters to the point of self-sacrifice — 'I'll take less so nobody feels bad'", "Buying things to match an ideal lifestyle rather than your real one", "Defining your worth through the quality of your aesthetic, your taste, or your social grace"],
    3: ["Saying what people want to hear instead of what's true", "Over-qualifying every statement to avoid offending anyone — 'but that's just my opinion'", "Being unable to have a direct conversation about something uncomfortable", "Using diplomatic language so carefully that your actual message gets lost", "Gossiping indirectly — phrasing complaints as concerned observations"],
    4: ["Maintaining a beautiful, harmonious home at the expense of authentic emotional expression", "Avoiding family conflict by smoothing everything over — the peacekeeper at personal cost", "Decorating and arranging your living space to perfection while the emotional foundation crumbles", "Being unable to set boundaries with family because it might cause tension", "Sacrificing your own comfort at home to accommodate everyone else's preferences"],
    5: ["Creating art that's beautiful and pleasing but emotionally safe — nothing that risks rejection", "Dating for the idea of partnership rather than genuine connection", "Being unable to pursue creative interests that aren't considered tasteful or refined", "Teaching children to be polite and pleasant rather than authentic and bold", "Romantic relationships that look perfect from the outside but lack real passion or depth"],
    6: ["Over-compromising at work — doing tasks that aren't yours to maintain workplace harmony", "Being unable to give direct feedback to coworkers because it feels unkind", "Balancing your health approach so carefully between options that you never commit to anything", "Putting more energy into being pleasant at work than into doing excellent work", "Avoiding necessary confrontations about workload, boundaries, or credit"],
    7: ["Losing yourself completely in partnerships — becoming what your partner needs rather than who you are", "Staying in relationships that are beautiful on the surface but empty underneath", "Being unable to end a relationship because breaking someone's heart feels worse than losing yourself", "Choosing partners for compatibility on paper rather than genuine emotional resonance", "Performing the role of 'perfect partner' instead of being a real, flawed human in love"],
    8: ["Avoiding emotional depth in shared intimacy — keeping things pleasant and manageable", "Being unable to confront the shadow side of your relationships", "Using charm and diplomacy to manage power dynamics instead of addressing them directly", "Keeping shared finances 'fair' to the cent — avoiding the messiness of genuine financial merging", "Treating transformation as something that should be graceful and aesthetically pleasing"],
    9: ["Adopting beliefs that are socially acceptable rather than personally true", "Being unable to take a strong philosophical position because someone might disagree", "Studying multiple perspectives without ever committing to your own", "Traveling to culturally refined destinations rather than places that would challenge you", "Seeking the 'balanced' view on everything — including situations that demand a clear stance"],
    10: ["Building a career on being diplomatic and well-liked rather than being genuinely excellent", "Avoiding professional risk because failure would damage your curated public image", "Being unable to lead decisively — always seeking consensus when someone needs to just decide", "Choosing careers in aesthetics, mediation, or social grace because they match your persona", "Letting concern about 'fairness' keep you from pursuing the promotion, the raise, or the recognition you've earned"],
    11: ["Being the diplomatic friend who keeps the peace in the group but never expresses their own preferences", "Joining groups for social access rather than genuine shared values", "Being unable to confront friends who've crossed your boundaries", "Curating your social circle for aesthetic or status harmony rather than authentic connection", "Avoiding causes that are controversial — even important ones — because they might make people uncomfortable"],
    12: ["Avoiding solitude because being alone forces you to confront who you are without others to reflect off of", "Using relationships and partnerships to distract from inner work", "Being unable to sit with discomfort, ugliness, or chaos — even in dreams and meditation", "Suppressing anger, ugliness, and unfairness into your subconscious where it festers", "Performing spiritual practices for their beauty and ritual rather than genuine transformation"],
  },

  Scorpio: {
    1: ["Using intensity as a wall — you're so deep that nobody can get close enough to actually see you", "Controlling your image so tightly that any vulnerability feels like exposure", "Being unable to be lighthearted, casual, or simple — everything must be meaningful", "Using your penetrating gaze and emotional intensity to intimidate rather than connect", "Holding grudges against people who've seen the 'real' you and stayed — punishing intimacy"],
    2: ["Being secretive about your finances — nobody knows what you earn, owe, or own", "Using money as a power tool — lending with strings attached, giving conditionally", "Obsessing over financial security to the point of paranoia", "Being unable to enjoy material pleasure without guilt or suspicion — 'if I have this, something bad will happen'", "Defining your worth through survival — 'I've been through more than you, therefore I'm stronger'"],
    3: ["Communicating with hidden agendas — saying one thing to discover another", "Using silence as manipulation — letting people fill the void while you observe", "Being unable to have a surface-level conversation — everything must go deep or it's 'fake'", "Probing others with questions while deflecting any directed at you", "Weaponizing information — storing observations about people for later use"],
    4: ["Controlling the emotional atmosphere at home — your mood dictates the household", "Keeping family secrets that are more about power than protection", "Being unable to forgive family members for past betrayals — holding onto wounds as identity", "Creating a home environment that feels like a fortress — safe but impenetrable", "Passing emotional intensity and survival patterns to your children without realizing it"],
    5: ["Being so intense in romance that partners feel consumed rather than loved", "Using sex and emotional intensity as substitutes for genuine playfulness", "Being unable to create art that's just fun — everything must have depth, darkness, or cathartic weight", "Teaching children that the world is dangerous — transmitting your hypervigilance", "All-or-nothing patterns in love — either you're completely merged or completely gone"],
    6: ["Working with an intensity that burns out coworkers and eventually yourself", "Being unable to do your job without also controlling how everyone else does theirs", "Health anxiety that fixates on worst-case scenarios — every symptom is potential disaster", "Refusing help at work because accepting it means owing someone, and owing feels dangerous", "Using your job as a way to maintain power, control, or status rather than genuine service"],
    7: ["Testing your partner's loyalty through manufactured crises or emotional provocations", "Being unable to trust fully — one betrayal (real or imagined) and you withdraw completely", "Possessiveness disguised as deep love — 'I just care about you so intensely'", "Using emotional or sexual power dynamics to maintain control in the relationship", "Choosing to be betrayed rather than risk being vulnerable — creating the very thing you fear"],
    8: ["This is Scorpio's home house — patterns here are extremely deep. You may identify so completely with transformation that you resist stability", "Using crisis and emotional intensity as proof that you're 'doing the work' — chaos as growth", "Being unable to share power, resources, or emotional control without feeling threatened", "Obsessing over death, endings, and the shadow to the point where you miss what's alive and present", "Holding onto emotional pain as a form of depth — releasing it would feel like losing your identity"],
    9: ["Turning spiritual seeking into an obsessive quest for ultimate truth — nothing less will do", "Being unable to hold multiple truths simultaneously — your worldview is fixed and defended fiercely", "Approaching education or travel as investigations rather than explorations", "Using your beliefs as a way to feel superior — 'I see what others can't'", "Refusing to share your deepest beliefs because exposing them feels dangerously vulnerable"],
    10: ["Building a career on strategic control rather than genuine contribution", "Being feared rather than respected in your professional field", "Using professional power to compensate for personal vulnerability", "Refusing to show any weakness in your public role — the mask never comes off", "Sabotaging your own career before it can be sabotaged by others — preemptive destruction"],
    11: ["Being the powerful member of the group that everyone's slightly afraid of", "Conducting loyalty tests on friends — probing for betrayal that may not exist", "Using group dynamics to maintain power rather than build genuine community", "Being unable to be casual or lighthearted in friendships — everything is life-or-death", "Withdrawing from groups and communities at the first sign of untrustworthiness"],
    12: ["Holding onto subconscious pain as if releasing it would unravel your identity", "Using psychic sensitivity and emotional depth as reasons to isolate", "Being terrified of losing control — even in dreams, meditation, or moments of surrender", "Carrying the shadow side of every relationship you've ever had without clearing it", "Treating the subconscious as a dangerous territory to be controlled rather than explored with compassion"],
  },

  Sagittarius: {
    1: ["Using optimism and humor to avoid acknowledging real pain or limitation", "Being unable to commit to a single identity — you're always becoming the next version", "Exaggerating, overselling, or inflating your self-presentation because ordinary feels insufficient", "Treating every setback as 'just part of the journey' instead of actually sitting with the disappointment", "Using restlessness as identity — 'I'm a free spirit' as an excuse to avoid roots and responsibility"],
    2: ["Being reckless with money because you trust the universe will provide — until it doesn't", "Overextending financially on adventures, courses, and experiences at the expense of basic security", "Being unable to save because delayed gratification feels like deprivation", "Valuing freedom and experience over financial stability — even when stability is genuinely needed", "Justifying overspending with philosophy — 'money is just energy, it'll come back'"],
    3: ["Lecturing instead of conversing — every talk becomes a TED talk", "Exaggerating stories for dramatic effect until the truth gets lost", "Being impatient with small talk, details, or everyday logistics", "Dominating discussions with opinions delivered as universal truths", "Promising to follow up, send the article, make the call — and then forgetting because you've moved on"],
    4: ["Being restless at home — always wanting to be somewhere else", "Treating your home as a launchpad rather than a destination", "Importing cultures, philosophies, and lifestyles into your home environment without grounding them", "Being emotionally present only in bursts — intense connection followed by long absences", "Resisting domestic routine because it feels like a cage"],
    5: ["Starting creative projects with explosive enthusiasm and abandoning them when the novelty fades", "Teaching your children that adventure matters more than follow-through", "Romantic relationships that are more about the story than the substance", "Being unable to enjoy quiet, simple pleasures — everything needs to be an event", "Using humor and levity to avoid the emotional labor that creative work and love require"],
    6: ["Resisting daily routines, health regimens, and practical obligations because they feel constraining", "Over-committing to work projects because saying no feels limiting", "Treating your body like a vehicle for adventures rather than something that needs consistent care", "Being so focused on the big picture that important daily details fall through the cracks", "Quitting health programs, diets, or exercise routines the moment they become boring"],
    7: ["Needing a partner who shares your love of freedom — and resenting them when they don't", "Committing to relationships with one foot out the door — always aware of the exit", "Using philosophy or humor to avoid the emotional work that partnership requires", "Being attracted to people from other cultures or backgrounds for the novelty rather than the person", "Lecturing your partner about life, growth, and possibility instead of listening to their experience"],
    8: ["Using philosophy and optimism to bypass genuine grief, loss, and emotional pain", "Being unable to stay in the dark long enough to actually transform — always rushing toward the light", "Treating death, endings, and shared finances with a cavalier attitude that masks real fear", "Using humor to deflect during moments that require emotional gravity", "Approaching deep psychological work as another adventure rather than a genuine confrontation with shadow"],
    9: ["This is Sagittarius' home house — so these habits are deeply ingrained. You may believe you've already 'figured it out'", "Being so devoted to your worldview that you've stopped questioning whether it's still true", "Collecting beliefs, degrees, and travel experiences as trophies rather than as genuine growth", "Teaching or preaching to others while refusing to apply the lessons to your own life", "Using perpetual seeking as a way to avoid arriving — because arriving means you'd have to do something with what you've found"],
    10: ["Building a career on vision, charisma, and inspiration while neglecting the boring-but-essential details", "Over-promising what you can deliver professionally because your enthusiasm outpaces your capacity", "Resisting management, structure, and accountability because they feel like bureaucratic constraints", "Changing career directions so often that you never build deep expertise in anything", "Using 'I haven't found my calling yet' as a way to avoid the discipline of mastery"],
    11: ["Being the inspiring friend who fires everyone up but disappears when consistent support is needed", "Joining and leaving groups rapidly — always looking for the next community that matches your evolving worldview", "Using social causes for personal growth rather than genuine service to the cause", "Over-promising community involvement and under-delivering", "Being unable to handle group conflict — leaving rather than staying to work through disagreement"],
    12: ["Using spiritual practices as entertainment or intellectual stimulation rather than genuine devotion", "Running from solitude, stillness, and the limitations of the physical body", "Treating meditation retreats as adventures rather than opportunities for genuine surrender", "Being unable to sit with boredom, emptiness, or meaninglessness — rushing to fill the void with philosophy", "Escaping reality through optimism — 'everything happens for a reason' as a way to avoid processing pain"],
  },

  Capricorn: {
    1: ["Defining yourself entirely through your achievements, title, and reputation", "Being unable to be playful, spontaneous, or unproductive — even rest is scheduled", "Presenting a controlled, competent exterior while suppressing exhaustion, loneliness, or grief", "Aging yourself before your time by taking on too much responsibility too young", "Mistaking seriousness for maturity — you've forgotten how to be light"],
    2: ["Obsessing over financial security to the point where accumulation replaces living", "Being unable to spend on pleasure because every dollar must serve the long-term plan", "Defining your worth entirely through your net worth or professional earnings", "Working multiple jobs or endless overtime because 'enough' is never actually enough", "Using material success to compensate for emotional deprivation"],
    3: ["Being so careful with your words that you come across as cold, distant, or withholding", "Dismissing others' ideas unless they're practical, proven, or strategically useful", "Communicating in commands and directives rather than conversation", "Being unable to make small talk because it feels like a waste of time", "Editing your communication for professional impact while losing personal warmth"],
    4: ["Running your household like a business — efficiency and structure over warmth and emotional messiness", "Being the responsible parent/child who holds the family together while privately crumbling", "Suppressing emotions at home because showing them feels like losing control", "Creating a home that's impressive and well-maintained but emotionally sparse", "Inheriting a family legacy of 'work hard, don't complain' that you're passing to the next generation"],
    5: ["Being unable to play without a purpose — even hobbies must produce something useful", "Suppressing creative impulses because they're not 'practical' or 'profitable'", "Approaching romance with a checklist — compatibility, stability, future prospects — instead of passion", "Parenting through structure and discipline while struggling to be emotionally warm", "Feeling guilty about joy, pleasure, or fun — as if enjoying life means you're not working hard enough"],
    6: ["Working to the point of burnout and treating it as normal — 'this is just what adults do'", "Maintaining a rigid health and work routine that leaves no room for spontaneity or joy", "Being unable to call in sick or take a day off without guilt", "Micromanaging your health to the point where wellness becomes another job to excel at", "Treating coworkers as productivity units rather than people"],
    7: ["Choosing partners for stability and status rather than genuine love", "Being the 'responsible one' in every relationship — handling all the logistics while your partner handles... nothing", "Building relationships on obligation and duty rather than desire", "Being unable to show vulnerability in partnerships — strength is all you know how to offer", "Maintaining a relationship that's functional but emotionally disconnected because it 'works on paper'"],
    8: ["Controlling shared resources with an iron grip — needing to be the financial authority", "Being unable to surrender in intimacy — vulnerability feels like weakness", "Using emotional stoicism during crises as strength when it's actually disconnection", "Approaching grief, loss, and endings as things to be managed rather than felt", "Treating therapy or deep psychological work as another achievement to complete"],
    9: ["Dismissing spiritual or philosophical exploration as impractical — 'what does this actually accomplish?'", "Limiting your worldview to what's proven, tested, and materially verifiable", "Approaching education purely for career advancement rather than genuine wisdom", "Being unable to travel for pleasure — every trip must serve a purpose", "Treating beliefs as strategies rather than genuine sources of meaning"],
    10: ["This is Capricorn's home house — these patterns may define your entire life. You may have built everything on achievement without noticing what you sacrificed", "Being unable to separate your identity from your career — without the job title, who are you?", "Sacrificing health, relationships, and personal life for professional success", "Refusing to retire, slow down, or let others lead because your value IS your work", "Building a legacy that impresses the world but doesn't nourish you personally"],
    11: ["Being the responsible friend who everyone relies on but nobody truly knows", "Approaching friendships strategically — networking disguised as connection", "Being unable to join groups for fun — every community involvement must serve a goal", "Maintaining a small, curated circle rather than risking the messiness of broader connection", "Dismissing social causes or activism as naive while privately envying the hope behind them"],
    12: ["Being terrified of losing control — sleep, meditation, and surrender all feel dangerous", "Working through exhaustion because resting feels like failing", "Suppressing dreams, intuition, and spiritual experiences because they can't be measured or controlled", "Carrying the weight of the world on your shoulders and refusing to put it down — even privately", "Treating your inner world as another territory to be conquered rather than a space to be inhabited with gentleness"],
  },

  Aquarius: {
    1: ["Defining yourself through your difference — 'I'm not like other people' as identity rather than observation", "Using intellectual detachment to avoid emotional engagement with your own life", "Being contrarian for its own sake — opposing mainstream views whether or not you actually believe the alternative", "Curating an identity around being unconventional while secretly craving acceptance", "Treating emotions as inconvenient data points rather than valid experiences"],
    2: ["Being detached from money and possessions as a philosophical stance — while being financially unstable", "Refusing to participate in conventional financial systems even when it would genuinely help you", "Valuing ideas and innovation over financial security — your mind is rich but your bank account isn't", "Being unable to receive material support because accepting it feels like losing independence", "Dismissing material comfort as shallow while privately feeling the stress of scarcity"],
    3: ["Talking about ideas rather than feelings — intellectual exchange replacing emotional connection", "Being unable to explain things simply — over-complicating to demonstrate your intelligence", "Contrarian communication — disagreeing with the majority position automatically", "Using detachment and objectivity to avoid personal conversations that require vulnerability", "Being so committed to original thinking that you dismiss useful conventional wisdom"],
    4: ["Creating an unconventional home life as rebellion rather than genuine preference", "Being emotionally detached from family — observing family dynamics rather than participating in them", "Resisting domestic traditions, family expectations, and inherited ways of living without examining which ones might actually serve you", "Using intellectual frameworks to analyze family relationships instead of feeling them", "Prioritizing community, causes, and friendships over the intimate emotional work of home life"],
    5: ["Intellectualizing creative expression — art as concept rather than felt experience", "Being attracted to unusual, unavailable, or unconventional partners because 'normal' love feels boring", "Parenting with progressive ideals while struggling to provide the mundane emotional consistency children need", "Refusing to create within existing forms — everything must be revolutionary, which means nothing gets finished", "Using irony and detachment to avoid the vulnerability that genuine creative expression requires"],
    6: ["Experimenting with health approaches so unconventional that you miss the basics that would actually help", "Being unable to maintain a routine because it feels oppressively conformist", "Approaching work as a platform for innovation while ignoring the everyday tasks that keep things running", "Detaching from body sensations — living so much in your mind that you miss physical signals", "Dismissing conventional medicine or wellness advice because it's 'mainstream' — even when it works"],
    7: ["Needing so much independence in relationships that genuine intimacy never develops", "Being attracted to the idea of someone rather than the actual person", "Using intellectual compatibility as the only metric — dismissing emotional and physical connection", "Creating unconventional relationship structures to avoid the vulnerability of traditional commitment", "Being so afraid of losing your individuality that you never fully merge with another person"],
    8: ["Intellectualizing grief, death, and transformation instead of processing them emotionally", "Detaching during moments of deep intimacy — observing the experience instead of being in it", "Using philosophical frameworks to explain away pain rather than sitting with it", "Being unable to share resources or power without it feeling like a threat to your autonomy", "Approaching psychological depth as an intellectual exercise rather than a lived transformation"],
    9: ["Being so committed to innovation that you've lost connection with the wisdom traditions that preceded you", "Treating all belief systems as equally valid to the point where you believe nothing deeply", "Using education as a platform for your ideas rather than genuine learning", "Traveling for exposure to different ideas while remaining emotionally unchanged by any of them", "Confusing contrarianism with wisdom — opposing for sport rather than principle"],
    10: ["Building a career around being the disruptor or innovator without building sustainable structures", "Resisting authority and hierarchy so strongly that you sabotage your own advancement", "Being unable to play the professional game — even basic networking feels like conformist theater", "Creating a public image around rebellion that prevents people from seeing your actual substance", "Using 'I don't care what people think' as armor — when you actually care deeply"],
    11: ["This is Aquarius' home house — these patterns may be invisible to you because they feel like truth, not habit", "Defining yourself entirely through your social circle, cause, or community identity", "Being so focused on collective good that you neglect individual relationships", "Using group belonging to avoid the scarier work of one-on-one intimacy", "Treating friendship as ideological alignment rather than genuine human connection"],
    12: ["Using intellectual frameworks to avoid genuine spiritual surrender", "Being unable to let go of mental control — even in meditation, you're analyzing the process", "Treating mystical or spiritual experiences with suspicion because they can't be rationally verified", "Dissociating from emotions and calling it 'objectivity' or 'mindfulness'", "Avoiding the irrational, messy, emotional dimensions of the subconscious because they can't be organized into a theory"],
  },
};

/**
 * Get house-specific habit examples for a given sign in a given house.
 * Falls back gracefully if the sign or house isn't mapped yet.
 */
export function getSignHouseHabits(sign: string, house: number): string[] | null {
  return SIGN_HOUSE_HABITS[sign]?.[house] || null;
}
