// Jan Spiller "Astrology for the Soul" — North Node Framework
// Source attribution on every entry for traceability
// Each sign entry covers: overview, past-life story, desires/needs,
// tendencies to leave behind, tendencies to develop, relationships, and healing affirmations.

export const SPILLER_SOURCE = 'Jan Spiller, Astrology for the Soul';

export interface SpillerNodeData {
  sign: string;
  pastLifeStory: string;
  overview: string;
  desires: string[];
  needs: string[];
  tendenciesToLeaveBehind: string[];
  tendenciesToDevelop: string[];
  relationships: string;
  healingAffirmations: string[];
  pitfalls: string[];
  whatWorksAgainstYou: string;
  whatWorksForYou: string;
}

export const SPILLER_NODE_DATA: Record<string, SpillerNodeData> = {
  Aries: {
    sign: 'Aries',
    pastLifeStory: 'In past lives you were the diplomat, the peacemaker, the partner. You defined yourself through relationships and learned to see every side of every issue. You became so skilled at compromise that you lost your own identity in the process. Now you must learn to stand alone.',
    overview: 'Your soul is learning to develop a strong sense of self — to act on impulse, take the initiative, and discover what YOU want without consulting anyone. The universe rewards you when you take independent action, even clumsily. It withholds when you wait for permission or consensus.',
    desires: [
      'To be supported by others',
      'To have someone else take the lead',
      'To have approval before acting',
      'To keep everything harmonious and fair',
    ],
    needs: [
      'To develop self-identity apart from relationships',
      'To act on impulse and instinct',
      'To cultivate healthy selfishness',
      'To make decisions without weighing every side',
    ],
    tendenciesToLeaveBehind: [
      'Codependency and over-accommodation',
      'Indecision and endless deliberation',
      'Defining yourself through your partner',
      'People-pleasing at the expense of your own needs',
      'Expecting others to make you happy',
      'Giving in to avoid conflict',
    ],
    tendenciesToDevelop: [
      'Self-awareness and self-assertion',
      'Acting on instinct without over-thinking',
      'Saying "I want" and "I need" clearly',
      'Taking leadership roles',
      'Embracing healthy competition',
      'Making decisions alone and quickly',
    ],
    relationships: 'Your biggest lesson in relationships is learning NOT to lose yourself. You tend to merge with partners, mirror their desires, and abandon your own direction to keep the peace. Paradoxically, relationships improve dramatically when you focus on yourself first. Partners are drawn to your independence, not your accommodation. The more you develop your own identity, the more magnetic you become.',
    healingAffirmations: [
      'I am allowed to put myself first',
      'My instincts are trustworthy',
      'I do not need anyone\'s permission to be who I am',
      'Conflict is not the enemy — losing myself is',
    ],
    pitfalls: [
      'Waiting for a partner to "complete" you',
      'Over-compromising until you resent everyone',
      'Inability to be alone',
      'Swinging between total sacrifice and sudden selfishness',
    ],
    whatWorksAgainstYou: 'Putting relationships first, seeking approval, trying to make everyone happy, waiting for others to act, being "fair" at your own expense.',
    whatWorksForYou: 'Independent action, trusting your gut, doing things alone, physical activity, being direct, starting new projects without asking permission.',
  },
  Taurus: {
    sign: 'Taurus',
    pastLifeStory: 'In past lives you were the transformer, the healer, the crisis manager. You navigated intense emotional depths, power dynamics, and cycles of death and rebirth. You mastered the underworld. Now you must learn to live peacefully on the surface.',
    overview: 'Your soul is learning to build stability, enjoy simplicity, and discover your own values independent of intense emotional entanglements. The universe rewards you for patience, gratitude, and enjoying sensory pleasure without guilt.',
    desires: [
      'To feel intensely alive through crisis',
      'To have power and control in relationships',
      'To merge deeply with others financially and emotionally',
      'To uncover hidden motives and secrets',
    ],
    needs: [
      'To build your own resources and self-worth',
      'To enjoy simple physical pleasures',
      'To develop patience and stability',
      'To release the need for emotional intensity',
    ],
    tendenciesToLeaveBehind: [
      'Creating crises to feel alive',
      'Manipulating through emotional intensity',
      'Obsessing over others\' motivations',
      'Using sex or money as tools of control',
      'Resistance to simple happiness',
      'All-or-nothing extremism',
    ],
    tendenciesToDevelop: [
      'Gratitude for what you already have',
      'Building material security through your own efforts',
      'Patience and persistence',
      'Enjoying nature, food, music, and beauty',
      'A sense of personal values',
      'Financial self-sufficiency',
    ],
    relationships: 'You tend to attract or create intense, consuming relationships because calm feels boring. You may unconsciously test partners through jealousy, power plays, or emotional extremes. The lesson: choose stability over intensity. A relationship that feels "boring" at first may actually be healthy. Learn to appreciate a partner who is reliable rather than dramatic.',
    healingAffirmations: [
      'Peace is not boring — it is earned',
      'I can feel alive without crisis',
      'My worth is not measured by my intensity',
      'Simplicity is a spiritual achievement',
    ],
    pitfalls: [
      'Sabotaging peace because it feels empty',
      'Testing partners until they break',
      'Financial entanglement used for control',
      'Refusing to enjoy life because suffering feels more "real"',
    ],
    whatWorksAgainstYou: 'Seeking intensity, stirring up drama, obsessing over what\'s hidden, trying to control outcomes through emotional manipulation.',
    whatWorksForYou: 'Building things slowly, spending time in nature, developing your own money and talents, choosing comfort over chaos, practicing gratitude daily.',
  },
  Gemini: {
    sign: 'Gemini',
    pastLifeStory: 'In past lives you were the philosopher, the preacher, the traveler, the guru. You held strong convictions and taught others what to believe. You lived by a code and expected others to follow. Now you must learn to listen, to be curious, and to value questions over answers.',
    overview: 'Your soul is learning mental flexibility, genuine curiosity, and the art of communication. The universe rewards you when you ask questions, listen to diverse viewpoints, and stay engaged with your immediate environment rather than chasing the horizon.',
    desires: [
      'To be seen as wise and knowledgeable',
      'To have the "right" answer',
      'To convert others to your worldview',
      'To find THE truth',
    ],
    needs: [
      'To develop genuine curiosity',
      'To listen more than you speak',
      'To value multiple perspectives equally',
      'To communicate clearly and humbly',
    ],
    tendenciesToLeaveBehind: [
      'Preachiness and self-righteousness',
      'Assuming you know better',
      'Restlessness and inability to focus locally',
      'Over-promising and under-delivering',
      'Using "truth" as a weapon',
      'Talking AT people instead of WITH them',
    ],
    tendenciesToDevelop: [
      'Active listening skills',
      'Curiosity about everyday things',
      'Writing, journaling, or blogging',
      'Engaging with siblings, neighbors, and local community',
      'Mental versatility and adaptability',
      'Asking questions instead of giving answers',
    ],
    relationships: 'You tend to relate by teaching — positioning yourself as the wise one. Partners may initially admire this but eventually feel talked down to. The lesson: your partner knows things you don\'t. Ask what they think. Be genuinely curious about their world. The best conversations are mutual explorations, not lectures.',
    healingAffirmations: [
      'I don\'t have to have all the answers',
      'Listening is more powerful than speaking',
      'There are many truths, not just mine',
      'Curiosity is a form of love',
    ],
    pitfalls: [
      'Becoming the "expert" in every conversation',
      'Dismissing others\' perspectives as shallow',
      'Restlessly seeking the next big truth instead of being present',
      'Using philosophical frameworks to avoid personal vulnerability',
    ],
    whatWorksAgainstYou: 'Moralizing, being "right," chasing the big picture while ignoring the details, speaking without listening, assuming you\'ve already figured it out.',
    whatWorksForYou: 'Asking genuine questions, reading widely, writing to process thoughts, engaging with your neighborhood, staying curious, letting others teach you.',
  },
  Cancer: {
    sign: 'Cancer',
    pastLifeStory: 'In past lives you were the authority figure, the builder, the achiever. You mastered structure, discipline, and public accomplishment. You earned respect through control and competence. Now you must learn that feelings matter more than achievements.',
    overview: 'Your soul is learning to nurture, to be vulnerable, and to create emotional safety — for yourself and others. The universe rewards you when you express genuine feelings, create a loving home, and allow yourself to need other people.',
    desires: [
      'To be in control and in charge',
      'To earn respect through accomplishment',
      'To maintain emotional composure at all times',
      'To have authority and status',
    ],
    needs: [
      'To develop emotional intelligence and vulnerability',
      'To create a nurturing home environment',
      'To allow yourself to be cared for',
      'To prioritize feelings over achievements',
    ],
    tendenciesToLeaveBehind: [
      'Using achievement as emotional armor',
      'Controlling situations to avoid vulnerability',
      'Workaholism and status-seeking',
      'Emotional coldness or detachment',
      'Judging people by their accomplishments',
      'Refusing to ask for help',
    ],
    tendenciesToDevelop: [
      'Emotional honesty and vulnerability',
      'Nurturing yourself and others',
      'Building a warm, safe home life',
      'Empathy and compassion',
      'Trusting feelings as valid intelligence',
      'Allowing yourself to receive care',
    ],
    relationships: 'You tend to manage relationships like projects — with goals, timelines, and performance reviews. You may choose partners who need managing, which keeps you in control. The lesson: love isn\'t a job. Let your partner see you at your most vulnerable. Cry in front of someone. Ask to be held. The strength you\'ve spent lifetimes building now needs to serve tenderness.',
    healingAffirmations: [
      'My feelings are my greatest strength',
      'I am worthy of love without earning it',
      'Vulnerability is courage, not weakness',
      'Home is where I let my guard down',
    ],
    pitfalls: [
      'Overworking to avoid feeling',
      'Choosing partners you can "manage"',
      'Refusing comfort when offered',
      'Defining worth through titles and achievements',
    ],
    whatWorksAgainstYou: 'Overworking, maintaining control, suppressing emotions, keeping things "professional," avoiding domestic life, prioritizing status over connection.',
    whatWorksForYou: 'Creating a nurturing home, cooking for people, expressing emotions honestly, letting others take care of you, spending time with family, trusting your feelings.',
  },
  Leo: {
    sign: 'Leo',
    pastLifeStory: 'In past lives you were the humanitarian, the revolutionary, the group leader. You championed causes, innovated for the collective, and found your identity through social movements. You learned to value the group above yourself. Now you must learn to value YOUR unique creative spark.',
    overview: 'Your soul is learning to shine as an individual — to create from the heart, take center stage, and follow personal joy. The universe rewards you when you take creative risks, express romance, and dare to be special.',
    desires: [
      'To belong to a group or cause',
      'To be accepted for fitting in',
      'To maintain intellectual detachment',
      'To pursue ideals over personal feelings',
    ],
    needs: [
      'To develop personal creative expression',
      'To follow your heart, not just your head',
      'To risk being seen and admired',
      'To experience romantic love and joy',
    ],
    tendenciesToLeaveBehind: [
      'Hiding behind group identity',
      'Emotional detachment as a defense',
      'Rebelling just to be different',
      'Treating love as an intellectual exercise',
      'Fear of personal attention or spotlight',
      'Prioritizing ideals over personal feelings',
    ],
    tendenciesToDevelop: [
      'Creative self-expression in any form',
      'The courage to be seen and celebrated',
      'Romance, play, and spontaneous joy',
      'Following your heart over group consensus',
      'Warmth, generosity, and personal magnetism',
      'Taking center stage unapologetically',
    ],
    relationships: 'You tend to keep romantic partners at arm\'s length — friends more than lovers, companions more than passionate partners. You may prioritize "friendship" in romance because it feels safer than vulnerability. The lesson: let yourself fall in love dramatically, foolishly, completely. Be the star in someone\'s eyes. Accept adoration without intellectualizing it.',
    healingAffirmations: [
      'I am allowed to be special',
      'My creative expression matters',
      'Joy is not frivolous — it is my purpose',
      'I can shine without dimming anyone else',
    ],
    pitfalls: [
      'Hiding your light to fit in with the group',
      'Intellectualizing feelings to avoid vulnerability',
      'Choosing causes over personal happiness',
      'Treating romance as friendship to stay safe',
    ],
    whatWorksAgainstYou: 'Hiding in groups, maintaining emotional distance, prioritizing ideals over personal joy, avoiding the spotlight, treating love as a concept rather than an experience.',
    whatWorksForYou: 'Creative projects, performing, romantic gestures, following your heart, accepting praise, playing with children, taking center stage, being generous.',
  },
  Virgo: {
    sign: 'Virgo',
    pastLifeStory: 'In past lives you were the mystic, the healer, the martyr. You dissolved boundaries between yourself and the divine, served through spiritual surrender, and may have escaped into addiction, fantasy, or institutional life. You mastered transcendence. Now you must learn to function on earth.',
    overview: 'Your soul is learning practical service, discernment, and the sacred discipline of daily life. The universe rewards you for organizing, analyzing, and serving others in tangible, hands-on ways.',
    desires: [
      'To escape into fantasy, art, or spirituality',
      'To merge with the divine and avoid mundane reality',
      'To rescue or be rescued',
      'To feel without boundaries',
    ],
    needs: [
      'To develop practical skills and routines',
      'To serve others in concrete, visible ways',
      'To build healthy boundaries',
      'To find the sacred in the ordinary',
    ],
    tendenciesToLeaveBehind: [
      'Escapism through substances, sleep, or fantasy',
      'Playing the victim or the savior',
      'Avoiding practical responsibilities',
      'Losing yourself in others\' pain',
      'Confusion and disorganization',
      'Using "spirituality" to avoid real-world engagement',
    ],
    tendenciesToDevelop: [
      'Practical problem-solving',
      'Healthy daily routines (diet, exercise, sleep)',
      'Discernment — knowing what is your responsibility and what isn\'t',
      'Organizational skills',
      'Precision and attention to detail',
      'Hands-on service to others',
    ],
    relationships: 'You tend to idealize partners or play rescuer — attracting those who need "saving." You may fall for the fantasy of love rather than the reality of a person. The lesson: choose a partner who functions well in daily life. Love that requires constant rescue isn\'t love — it\'s codependency. The most romantic thing you can do is build a healthy life together.',
    healingAffirmations: [
      'The mundane is sacred',
      'I can serve without losing myself',
      'Boundaries are an act of love',
      'My daily routines are spiritual practices',
    ],
    pitfalls: [
      'Rescuing others to feel needed',
      'Idealizing partners beyond recognition',
      'Avoiding practical responsibilities through escapism',
      'Confusing enmeshment with love',
    ],
    whatWorksAgainstYou: 'Escaping into fantasy, avoiding routine, playing victim or savior, refusing to deal with details, using substances to cope, neglecting your physical health.',
    whatWorksForYou: 'Organizing your environment, establishing routines, volunteering in practical ways, developing a craft, eating well, exercising, keeping a clean and ordered space.',
  },
  Libra: {
    sign: 'Libra',
    pastLifeStory: 'In past lives you were the warrior, the pioneer, the lone adventurer. You depended only on yourself, fought your own battles, and operated entirely on instinct. You mastered independence. Now you must learn that cooperation creates more than competition.',
    overview: 'Your soul is learning partnership, diplomacy, and the art of seeing through another person\'s eyes. The universe rewards you when you compromise, cooperate, and create harmony — but authentically, not as surrender.',
    desires: [
      'To be self-sufficient and independent',
      'To act first and think later',
      'To win through force of will',
      'To go it alone',
    ],
    needs: [
      'To develop genuine partnership skills',
      'To practice empathy and active listening',
      'To create beauty, balance, and harmony',
      'To see situations through others\' perspectives',
    ],
    tendenciesToLeaveBehind: [
      'Aggressive self-interest',
      'Impulsiveness and impatience with others',
      'Competitiveness in relationships',
      'Insensitivity to others\' feelings',
      'Going it alone when collaboration would serve better',
      'Using anger as a first response',
    ],
    tendenciesToDevelop: [
      'Active listening and genuine empathy',
      'The art of compromise (without losing yourself)',
      'Appreciating beauty, art, and refinement',
      'Collaborative decision-making',
      'Patience with others\' processes',
      'Creating win-win solutions',
    ],
    relationships: 'You tend to compete with partners or dominate the relationship. You may be attracted to strong-willed people, then fight them for control. The lesson: the strongest stance in a relationship is partnership, not domination. True power comes from creating something TOGETHER that neither could build alone.',
    healingAffirmations: [
      'Cooperation multiplies what competition divides',
      'I can be strong and gentle at the same time',
      'My partner is my equal, not my opponent',
      'Beauty and harmony are forms of strength',
    ],
    pitfalls: [
      'Competing with the person who loves you most',
      'Refusing to consider your partner\'s perspective',
      'Using independence as a weapon',
      'Attracting conflict to feel alive',
    ],
    whatWorksAgainstYou: 'Going it alone, being combative, refusing to compromise, dominating conversations, acting impulsively, treating life as a battle.',
    whatWorksForYou: 'Genuine collaboration, asking for input, creating beauty, slowing down before reacting, studying diplomacy and negotiation, investing in partnerships.',
  },
  Scorpio: {
    sign: 'Scorpio',
    pastLifeStory: 'In past lives you were the builder, the provider, the stabilizer. You created material security, valued the tangible, and held onto what was yours with determination. You mastered the physical world. Now you must learn that true security comes from transformation, not accumulation.',
    overview: 'Your soul is learning to go deep — emotionally, psychologically, sexually, and spiritually. The universe rewards you for sharing resources, embracing vulnerability, and allowing transformation even when it means letting go of comfort.',
    desires: [
      'To hold onto what\'s familiar and comfortable',
      'To maintain financial and emotional self-sufficiency',
      'To avoid emotional exposure',
      'To keep things pleasant and stable',
    ],
    needs: [
      'To develop emotional depth and psychological honesty',
      'To share resources — financial, emotional, spiritual',
      'To embrace transformation and change',
      'To trust others with your vulnerability',
    ],
    tendenciesToLeaveBehind: [
      'Stubbornness and resistance to change',
      'Possessiveness of people and things',
      'Material hoarding as emotional protection',
      'Refusing to let others in',
      'Comfort addiction — choosing the known over the unknown',
      'Measuring life by what you own',
    ],
    tendenciesToDevelop: [
      'Emotional depth and psychological awareness',
      'The ability to share and merge with others',
      'Letting go of what no longer serves you',
      'Embracing the death-rebirth cycle',
      'Exploring therapy, depth psychology, or occult studies',
      'Trusting the process of transformation',
    ],
    relationships: 'You tend to hold onto relationships long past their expiration — staying because it\'s comfortable, not because it\'s alive. You may withhold your deepest feelings to maintain control. The lesson: real intimacy requires surrender. Let your partner see what you\'re afraid to show. Merge finances, share secrets, and risk being truly known.',
    healingAffirmations: [
      'I can let go and still be safe',
      'Transformation is not loss — it is growth',
      'Sharing makes me richer, not poorer',
      'My vulnerability is my greatest power',
    ],
    pitfalls: [
      'Staying in dead situations because change is scary',
      'Using money or possessions to feel safe',
      'Refusing to share your inner life',
      'Equating comfort with happiness',
    ],
    whatWorksAgainstYou: 'Clinging to possessions, resisting change, emotional withholding, choosing comfort over growth, staying in your comfort zone, refusing to share resources.',
    whatWorksForYou: 'Therapy and depth work, sharing your vulnerabilities, joint financial planning, studying psychology, allowing change, practicing letting go daily.',
  },
  Sagittarius: {
    sign: 'Sagittarius',
    pastLifeStory: 'In past lives you were the communicator, the networker, the information gatherer. You mastered language, data, and social connections. You knew a little about everything and everyone. Now you must develop a personal philosophy through direct experience, not secondhand knowledge.',
    overview: 'Your soul is learning to seek meaning through firsthand experience — travel, higher education, spiritual quests, and the development of personal truth. The universe rewards you for taking leaps of faith toward what you believe in.',
    desires: [
      'To know all the facts before committing',
      'To stay in your familiar neighborhood',
      'To communicate rather than experience',
      'To keep your options open indefinitely',
    ],
    needs: [
      'To develop faith and personal philosophy',
      'To have direct experiences that expand your worldview',
      'To travel — literally and intellectually',
      'To speak from conviction, not just information',
    ],
    tendenciesToLeaveBehind: [
      'Superficiality and information overload',
      'Gossip and nervous chatter',
      'Scattered energy and inability to commit',
      'Intellectualizing to avoid direct experience',
      'Staying safe in your comfort zone',
      'Talking about life instead of living it',
    ],
    tendenciesToDevelop: [
      'Personal philosophy and worldview',
      'Adventure and willingness to take risks',
      'Higher education or deep study',
      'Faith — in life, in yourself, in something larger',
      'Speaking from experience, not just information',
      'The courage to commit to a truth',
    ],
    relationships: 'You tend to keep relationships light and communicative but avoid depth. You might have many surface connections but resist the vulnerability of one deep bond. The lesson: choose a partner who expands your world — who takes you on adventures, challenges your beliefs, and pushes you toward your own truth. Avoid partners who keep you small and local.',
    healingAffirmations: [
      'I trust the journey even when I can\'t see the destination',
      'My direct experience is more valuable than any secondhand knowledge',
      'I am ready to commit to what I believe',
      'Faith is not the absence of doubt — it is action in the face of it',
    ],
    pitfalls: [
      'Gathering information instead of having experiences',
      'Staying local when your soul needs expansion',
      'Keeping relationships superficial',
      'Endless hedging and refusal to commit to a truth',
    ],
    whatWorksAgainstYou: 'Overthinking, staying in your neighborhood, avoiding commitment, gathering facts instead of experiences, keeping things light, gossiping.',
    whatWorksForYou: 'Travel, higher education, developing a personal philosophy, speaking from the heart, taking leaps of faith, committing to a spiritual practice.',
  },
  Capricorn: {
    sign: 'Capricorn',
    pastLifeStory: 'In past lives you were the caretaker, the mother figure, the emotional anchor. You mastered nurturing, created safe emotional spaces, and defined yourself through family bonds. Now you must build something in the outer world that stands on its own merit.',
    overview: 'Your soul is learning mastery, discipline, and the responsible use of authority. The universe rewards you when you take charge, build structures, and pursue goals with patience and integrity — especially when no one is watching.',
    desires: [
      'To stay home and be nurtured',
      'To have others take care of you',
      'To avoid public exposure and responsibility',
      'To maintain emotional safety at all costs',
    ],
    needs: [
      'To develop discipline and long-term vision',
      'To build public credibility and authority',
      'To take responsibility for your life direction',
      'To set and achieve ambitious goals',
    ],
    tendenciesToLeaveBehind: [
      'Using emotional needs to avoid responsibility',
      'Hiding from the world behind family obligations',
      'Moodiness and emotional manipulation',
      'Fear of public judgment or failure',
      'Clinging to the past and childhood patterns',
      'Expecting to be taken care of',
    ],
    tendenciesToDevelop: [
      'Long-range planning and goal-setting',
      'Professional excellence and mastery',
      'Emotional maturity and self-reliance',
      'Leadership through competence, not control',
      'Building a reputation through integrity',
      'Patience — trusting that time is your ally',
    ],
    relationships: 'You tend to choose partners who parent you — or you parent them. Either way, the relationship recreates family dynamics rather than adult partnership. The lesson: build something together in the world. Respect each other\'s ambitions. A relationship where both people are growing professionally and personally is far more exciting than one where someone is always being "taken care of."',
    healingAffirmations: [
      'I am responsible for my own success',
      'Discipline is love made visible',
      'The world needs what I have to build',
      'I can be tender and still be tough',
    ],
    pitfalls: [
      'Retreating into family to avoid career challenges',
      'Using moodiness to get others to do the hard things',
      'Choosing partners who keep you comfortable instead of growing',
      'Fear of public failure preventing you from starting',
    ],
    whatWorksAgainstYou: 'Staying home, avoiding responsibility, relying on others emotionally, wallowing in feelings, hiding behind family, refusing to grow up.',
    whatWorksForYou: 'Setting ambitious goals, developing expertise, taking on leadership, building professional relationships, creating long-term plans, earning respect through competence.',
  },
  Aquarius: {
    sign: 'Aquarius',
    pastLifeStory: 'In past lives you were the star, the performer, the beloved. You mastered personal magnetism, creative expression, and the art of being adored. You lived from the heart and received standing ovations. Now you must learn that your gifts serve the whole, not just your ego.',
    overview: 'Your soul is learning objectivity, humanitarian service, and the power of the collective. The universe rewards you when you contribute to groups, champion innovation, and treat everyone as an equal rather than an audience.',
    desires: [
      'To be the center of attention',
      'To be loved and admired personally',
      'To express yourself dramatically',
      'To follow your heart over your head',
    ],
    needs: [
      'To develop objectivity and emotional detachment',
      'To serve humanitarian causes',
      'To build genuine friendships based on equality',
      'To innovate for the benefit of the collective',
    ],
    tendenciesToLeaveBehind: [
      'Needing to be the star of every show',
      'Drama and emotional manipulation for attention',
      'Romantic obsession and ego-driven love affairs',
      'Taking things too personally',
      'Creating dependency through charm',
      'Pride that prevents learning from others',
    ],
    tendenciesToDevelop: [
      'Genuine friendship and equality in relationships',
      'Objectivity and emotional intelligence',
      'Commitment to causes larger than yourself',
      'Innovation and forward-thinking',
      'Collaboration over competition',
      'Treating everyone with equal respect and interest',
    ],
    relationships: 'You tend to approach romance as a drama — the grand passion, the sweeping gesture, the all-consuming love story where you are the protagonist. The lesson: the deepest connection often comes through friendship. Choose a partner who is your equal, not your fan. Build a relationship on shared vision and mutual respect rather than personal adoration.',
    healingAffirmations: [
      'My gifts are for the world, not just for me',
      'I can be unique without needing to be the center',
      'Friendship is the highest form of love',
      'I serve the future, not just my ego',
    ],
    pitfalls: [
      'Making every group about you',
      'Choosing dramatic love over stable friendship',
      'Using charm to manipulate rather than connect',
      'Refusing to be "just one of the group"',
    ],
    whatWorksAgainstYou: 'Seeking the spotlight, dramatizing emotions, needing special treatment, romantic obsession, taking criticism personally, pride.',
    whatWorksForYou: 'Group involvement, humanitarian causes, innovation, treating everyone as equals, developing genuine friendships, thinking about the future, contributing to the collective.',
  },
  Pisces: {
    sign: 'Pisces',
    pastLifeStory: 'In past lives you were the analyst, the perfectionist, the fixer. You mastered order, detail, and practical service. You could diagnose any problem and prescribe a solution. You lived in a world of precision and control. Now you must learn to let go — of certainty, of control, and of the illusion that everything can be fixed.',
    overview: 'Your soul is learning surrender, spiritual faith, and compassion without condition. The universe rewards you for trusting the mystery, creating art from feeling, and accepting that some things cannot be analyzed — only experienced.',
    desires: [
      'To have everything organized and under control',
      'To fix problems through analysis',
      'To maintain perfect routines',
      'To understand before accepting',
    ],
    needs: [
      'To develop spiritual faith and trust',
      'To create from emotion and imagination',
      'To practice unconditional compassion',
      'To release the need for perfection',
    ],
    tendenciesToLeaveBehind: [
      'Perfectionism and chronic self-criticism',
      'Over-analyzing emotions instead of feeling them',
      'Anxiety and worry as default settings',
      'Trying to control everything through detail',
      'Criticizing others\' "flaws"',
      'Living entirely in the rational mind',
    ],
    tendenciesToDevelop: [
      'Spiritual practice — meditation, prayer, contemplation',
      'Artistic expression — music, visual art, poetry, dance',
      'Compassion without judgment',
      'Trust in the unseen and unknowable',
      'Emotional fluidity — letting feelings flow',
      'Imagination as a way of knowing',
    ],
    relationships: 'You tend to critique partners — noticing their flaws, suggesting improvements, offering "helpful" feedback that feels like judgment. You may choose partners who need "fixing" so you can stay in your comfort zone of analysis. The lesson: love your partner exactly as they are. Stop trying to improve them. The most profound act of love you can offer is acceptance without conditions.',
    healingAffirmations: [
      'I don\'t need to understand to accept',
      'Imperfection is the doorway to the divine',
      'I trust the flow of life beyond my control',
      'My heart knows what my mind cannot grasp',
    ],
    pitfalls: [
      'Analyzing love instead of feeling it',
      'Choosing partners you can "fix"',
      'Using worry as a substitute for faith',
      'Criticizing yourself and others into paralysis',
    ],
    whatWorksAgainstYou: 'Over-analysis, perfectionism, worry, trying to control through details, criticizing, living only in the rational mind, avoiding emotions.',
    whatWorksForYou: 'Meditation, creating art, being near water, practicing compassion, letting go of the need to fix, trusting intuition, surrendering to the mystery.',
  },
};

// North Node in House overlays — how the NN sign themes play out in specific life areas
export const SPILLER_HOUSE_OVERLAYS: Record<number, { focus: string; description: string; lifeLesson: string }> = {
  1: {
    focus: 'Self-Discovery',
    description: 'Your North Node in the 1st house means your soul\'s growth comes through developing a strong sense of SELF — independent identity, personal initiative, and the courage to be seen as you truly are.',
    lifeLesson: 'Stop defining yourself through others. Every time you take independent action — even when it feels selfish — you are moving toward your destiny. Your body, your appearance, and your instincts are your spiritual tools this lifetime.',
  },
  2: {
    focus: 'Self-Worth & Values',
    description: 'Your North Node in the 2nd house means your soul\'s growth comes through developing your OWN resources, values, and sense of worth — independent of what others give you or what you share.',
    lifeLesson: 'Build your own financial and emotional security. Stop depending on others\' resources, inheritances, or shared assets. Your self-worth must come from what YOU build, earn, and value.',
  },
  3: {
    focus: 'Communication & Learning',
    description: 'Your North Node in the 3rd house means your soul\'s growth comes through COMMUNICATION — writing, speaking, teaching, learning, and engaging with your immediate environment.',
    lifeLesson: 'Stay curious and connected locally. Instead of always seeking the grand truth or distant horizon, find wisdom in everyday conversations, your neighborhood, and continuous learning.',
  },
  4: {
    focus: 'Home & Emotional Roots',
    description: 'Your North Node in the 4th house means your soul\'s growth comes through creating EMOTIONAL SECURITY — building a home, healing family patterns, and developing your private, inner life.',
    lifeLesson: 'Your career and public life have been mastered in previous lives. Now build inward. Create a home that nourishes your soul. Heal your relationship with family. Your deepest fulfillment comes from emotional safety, not professional achievement.',
  },
  5: {
    focus: 'Creative Joy & Self-Expression',
    description: 'Your North Node in the 5th house means your soul\'s growth comes through CREATIVE SELF-EXPRESSION — art, romance, children, play, and anything done purely for the joy of it.',
    lifeLesson: 'Stop hiding behind group identity or humanitarian causes. Your soul needs to create something uniquely YOURS. Take creative risks. Fall in love dramatically. Let yourself be celebrated.',
  },
  6: {
    focus: 'Service & Daily Practice',
    description: 'Your North Node in the 6th house means your soul\'s growth comes through PRACTICAL SERVICE — health routines, daily work, helping others in tangible ways, and finding the sacred in the ordinary.',
    lifeLesson: 'Your spiritual gifts from past lives must now be grounded in practical action. Develop healthy routines. Serve others through doing, not just feeling. Your daily discipline IS your spiritual practice.',
  },
  7: {
    focus: 'Partnership & Relating',
    description: 'Your North Node in the 7th house means your soul\'s growth comes through PARTNERSHIP — learning to cooperate, compromise, and see through another\'s eyes without losing yourself.',
    lifeLesson: 'You\'ve mastered independence. Now learn that the most powerful things are built together. Your partner is not your opponent but your teacher. True strength includes softness.',
  },
  8: {
    focus: 'Transformation & Intimacy',
    description: 'Your North Node in the 8th house means your soul\'s growth comes through DEEP TRANSFORMATION — sharing resources, merging emotionally with others, and allowing yourself to be fundamentally changed by life.',
    lifeLesson: 'Stop holding on to material security and self-sufficiency. Your destiny requires vulnerability, psychological depth, and the willingness to let everything transform. Share what you have — financially, emotionally, spiritually.',
  },
  9: {
    focus: 'Meaning & Expansion',
    description: 'Your North Node in the 9th house means your soul\'s growth comes through EXPANSION — travel, higher education, philosophy, and the development of personal faith through direct experience.',
    lifeLesson: 'Stop gathering information and start having experiences. Your soul craves the big picture — not facts, but MEANING. Travel, study broadly, develop your own philosophy, and speak from conviction.',
  },
  10: {
    focus: 'Public Achievement & Legacy',
    description: 'Your North Node in the 10th house means your soul\'s growth comes through WORLDLY ACHIEVEMENT — building a career, developing authority, and contributing to the public sphere.',
    lifeLesson: 'Stop hiding behind family, emotion, and private life. The world needs what you have to offer. Build something visible, lasting, and publicly meaningful. Your emotional depth is the foundation — now build the tower.',
  },
  11: {
    focus: 'Community & Vision',
    description: 'Your North Node in the 11th house means your soul\'s growth comes through GROUP INVOLVEMENT — joining causes, building friendships, and contributing your creative gifts to the collective.',
    lifeLesson: 'Your creative talents and personal magnetism are meant for the world, not just for you. Join groups, champion innovations, and treat everyone as equals. Your vision for the future IS your purpose.',
  },
  12: {
    focus: 'Spiritual Surrender',
    description: 'Your North Node in the 12th house means your soul\'s growth comes through SPIRITUAL SURRENDER — meditation, art, compassion, and the willingness to dissolve the boundaries of ego.',
    lifeLesson: 'Stop trying to fix, organize, and control everything. Your perfectionism is the obstacle, not the solution. Let go. Trust the mystery. Your greatest power comes through surrender, not analysis.',
  },
};
