/**
 * Planetary Mythology & Archetypes Encyclopedia
 * 
 * A comprehensive teaching reference covering the mythological origins,
 * archetypal patterns, and symbolic meanings of celestial bodies used
 * in astrological practice.
 */

export interface MythologyEntry {
  name: string;
  symbol: string;
  greekName: string;
  romanName: string;
  otherNames?: string[];
  category: 'luminary' | 'personal' | 'social' | 'transpersonal' | 'centaur' | 'asteroid' | 'point';
  archetype: string;
  tagline: string;
  myth: string;
  symbolism: string[];
  psychologicalFunction: string;
  shadowExpression: string;
  giftExpression: string;
  rulesSign: string[];
  keywords: string[];
  animals?: string[];
  plants?: string[];
  metals?: string[];
  dayOfWeek?: string;
  bodyParts?: string[];
  colors?: string[];
  tarotCorrespondence?: string;
}

export const PLANETARY_MYTHOLOGY: MythologyEntry[] = [
  {
    name: 'Sun',
    symbol: '☉',
    greekName: 'Helios / Apollo',
    romanName: 'Sol',
    category: 'luminary',
    archetype: 'The Hero / The King',
    tagline: 'The conscious self and creative sovereignty',
    myth: `In the oldest Greek tradition, Helios was the titan who drove the golden chariot of the sun across the sky each day, seeing everything from his vantage point above the world. He was the all-seeing witness — nothing could hide from his light. Later, Apollo inherited the solar role and became the god of music, prophecy, healing, and truth. Apollo slew the great serpent Python at Delphi, claiming the oracle for himself — the hero who defeats the primordial darkness to establish conscious order. But Apollo's light cast the sharpest shadows: his love affairs ended tragically (Daphne turned into a laurel tree to escape him; Hyacinth died from a discus), teaching that the radiant ego, unchecked, can burn what it tries to possess.`,
    symbolism: [
      'The golden chariot — the vehicle of conscious will moving through time',
      'The laurel crown — victory, but also the memory of what was lost in pursuit',
      'The lyre — creativity as the highest expression of solar energy',
      'The all-seeing eye — nothing hidden from awareness',
    ],
    psychologicalFunction: 'The Sun represents the core identity, the conscious ego, and the vital force that animates the personality. It is what you are becoming — the central organizing principle of the psyche.',
    shadowExpression: 'Narcissism, ego inflation, need for constant admiration, inability to see others as separate beings, burning out by refusing to rest.',
    giftExpression: 'Authentic self-expression, generous leadership, creative vitality, the courage to be visible, warming presence that helps others shine.',
    rulesSign: ['Leo'],
    keywords: ['identity', 'vitality', 'purpose', 'ego', 'creativity', 'father', 'authority', 'visibility'],
    dayOfWeek: 'Sunday',
    metals: ['Gold'],
    bodyParts: ['Heart', 'spine', 'right eye'],
    colors: ['Gold', 'yellow', 'orange'],
    animals: ['Lion', 'eagle', 'hawk'],
    tarotCorrespondence: 'The Sun (XIX)',
  },
  {
    name: 'Moon',
    symbol: '☽',
    greekName: 'Selene / Artemis',
    romanName: 'Luna / Diana',
    category: 'luminary',
    archetype: 'The Mother / The Huntress',
    tagline: 'The emotional body and the rhythm of belonging',
    myth: `Selene, the titan goddess of the Moon, drove her silver chariot across the night sky, illuminating the darkness with reflected light. She fell deeply in love with the mortal shepherd Endymion, and begged Zeus to grant him eternal sleep so she could visit him each night — a story of the Moon's devotion to what is vulnerable, dreaming, and unconscious. Artemis, who inherited the lunar role, was the fierce virgin huntress of the wild forests, protector of young animals and children, goddess of the threshold between civilization and wilderness. She demanded absolute respect for boundaries — when the hunter Actaeon stumbled upon her bathing, she transformed him into a stag and let his own hounds devour him. The Moon protects what is sacred and private with instinctual ferocity.`,
    symbolism: [
      'The silver chariot — emotional navigation through darkness',
      'The crescent — receptivity, the cup that holds feeling',
      'The sleeping shepherd — devotion to the unconscious and vulnerable',
      'The wild forest — the untamed emotional interior',
    ],
    psychologicalFunction: 'The Moon represents the emotional body, instinctual reactions, habits, memory, and the need for safety and belonging. It is how you were nurtured and how you nurture.',
    shadowExpression: 'Emotional manipulation, smothering, inability to let go, moodiness as control, retreating into victimhood, devouring attachment.',
    giftExpression: 'Deep empathy, emotional intelligence, nurturing presence, intuitive knowing, capacity to hold space for vulnerability.',
    rulesSign: ['Cancer'],
    keywords: ['emotions', 'instinct', 'mother', 'home', 'memory', 'cycles', 'nurturing', 'receptivity'],
    dayOfWeek: 'Monday',
    metals: ['Silver'],
    bodyParts: ['Stomach', 'breasts', 'left eye', 'womb'],
    colors: ['Silver', 'white', 'pale blue'],
    animals: ['Crab', 'owl', 'hare', 'cat'],
    tarotCorrespondence: 'The High Priestess (II)',
  },
  {
    name: 'Mercury',
    symbol: '☿',
    greekName: 'Hermes',
    romanName: 'Mercurius',
    otherNames: ['Thoth (Egyptian)', 'Odin (Norse)', 'Nabu (Babylonian)'],
    category: 'personal',
    archetype: 'The Trickster / The Messenger',
    tagline: 'The mind that bridges worlds',
    myth: `Hermes was born at dawn in a cave on Mount Cyllene, and by noon on his first day of life, he had invented the lyre from a tortoise shell, stolen Apollo's sacred cattle, and talked his way out of punishment by making Zeus laugh. He was the only god who could freely travel between Olympus, the mortal world, and the Underworld — the psychopomp who guided dead souls to Hades. As the god of boundaries and the crossing of boundaries, Hermes presided over travelers, merchants, thieves, and orators. He invented language itself, the alphabet, and the art of making fire. His caduceus — two serpents entwined around a staff — represents the reconciliation of opposites through communication. Hermes teaches that intelligence is morally neutral: it can heal or deceive, connect or manipulate.`,
    symbolism: [
      'The caduceus — reconciliation of opposites, healing through communication',
      'Winged sandals — speed of thought, mental agility',
      'The crossroads — choice points, liminal spaces',
      'The tortoise-shell lyre — turning the mundane into art through wit',
    ],
    psychologicalFunction: 'Mercury represents the rational mind, perception, communication, learning style, and the ability to make connections between disparate things. It is how you think and how you speak.',
    shadowExpression: 'Lying, manipulation, intellectual superiority, nervous anxiety, scattered attention, using cleverness to avoid feeling.',
    giftExpression: 'Brilliant communication, quick learning, adaptability, humor, translation between different worlds and perspectives.',
    rulesSign: ['Gemini', 'Virgo'],
    keywords: ['communication', 'intellect', 'commerce', 'travel', 'trickster', 'language', 'perception', 'duality'],
    dayOfWeek: 'Wednesday',
    metals: ['Mercury / Quicksilver'],
    bodyParts: ['Nervous system', 'lungs', 'hands', 'intestines'],
    colors: ['Yellow', 'multicolored', 'iridescent'],
    animals: ['Rooster', 'tortoise', 'ram'],
    tarotCorrespondence: 'The Magician (I)',
  },
  {
    name: 'Venus',
    symbol: '♀',
    greekName: 'Aphrodite',
    romanName: 'Venus',
    otherNames: ['Inanna (Sumerian)', 'Ishtar (Babylonian)', 'Freya (Norse)'],
    category: 'personal',
    archetype: 'The Lover / The Artist',
    tagline: 'Beauty as power, desire as compass',
    myth: `Aphrodite was born from the sea-foam that formed when Kronos castrated his father Ouranos and cast his severed genitals into the ocean. From violence and severance, beauty was born — the oldest Venus myth tells us that love and desire emerge from primal disruption, not from peace. In her most ancient form as Inanna/Ishtar, she was a goddess of BOTH love AND war, who descended into the Underworld, was stripped naked at each of seven gates, died, and was reborn — the original death-and-resurrection myth. Aphrodite's power was so great that even Zeus feared her ability to make gods and mortals fall helplessly in love. Her girdle (the cestus) could make anyone irresistible. Her affair with Ares (Mars) — beauty drawn to raw aggression — produced Harmonia (harmony) and Eros (desire), teaching that love requires the tension of opposites.`,
    symbolism: [
      'Sea-foam birth — beauty born from disruption and primal chaos',
      'The golden apple — the prize that starts wars (judgment of Paris)',
      'The mirror — self-reflection, vanity, and the courage to see clearly',
      'The seven gates — love requires surrendering layers of armor',
    ],
    psychologicalFunction: 'Venus represents values, attraction, aesthetics, relational style, and what you find beautiful and worthy. She governs both romantic love and financial resources — what you value enough to invest in.',
    shadowExpression: 'Vanity, possessiveness, manipulation through beauty or charm, codependency, valuing appearances over substance, using love as currency.',
    giftExpression: 'Capacity for deep love, artistic sensitivity, ability to create harmony and beauty, magnetic presence, knowing what truly matters.',
    rulesSign: ['Taurus', 'Libra'],
    keywords: ['love', 'beauty', 'values', 'money', 'pleasure', 'harmony', 'attraction', 'art'],
    dayOfWeek: 'Friday',
    metals: ['Copper'],
    bodyParts: ['Throat', 'kidneys', 'ovaries', 'skin'],
    colors: ['Green', 'pink', 'rose', 'copper'],
    animals: ['Dove', 'swan', 'sparrow'],
    tarotCorrespondence: 'The Empress (III)',
  },
  {
    name: 'Mars',
    symbol: '♂',
    greekName: 'Ares',
    romanName: 'Mars',
    otherNames: ['Tyr (Norse)', 'Nergal (Babylonian)'],
    category: 'personal',
    archetype: 'The Warrior / The Initiator',
    tagline: 'The courage to act and the fire that defends',
    myth: `Ares was the most despised god on Olympus — even his own father Zeus called him the most hateful of all the gods. Unlike Athena, who represented strategic warfare, Ares embodied the raw, bloody chaos of battle — the berserker rage, the adrenaline rush, the willingness to charge forward without a plan. He was the lover of Aphrodite (desire and aggression are always intertwined), and their union produced both Harmony and Fear. When Ares was trapped in a bronze jar by the giants Otus and Ephialtes for thirteen months, he nearly died — teaching that unchecked aggression eventually imprisons itself. In Rome, Mars was far more honored: he was the father of Romulus and Remus, and March (his month) began the year. The Roman Mars teaches that directed will, disciplined courage, and protective aggression are the foundations of civilization.`,
    symbolism: [
      'The spear and shield — offensive action and defensive boundaries',
      'The bronze jar — aggression turned inward becomes self-imprisonment',
      'The red planet — the color of blood, passion, and vital force',
      'The wolf — instinctual courage and pack loyalty',
    ],
    psychologicalFunction: 'Mars represents desire, drive, anger, sexuality, assertiveness, and the ability to take action. It is your survival instinct and your capacity to fight for what matters.',
    shadowExpression: 'Uncontrolled rage, violence, cruelty, recklessness, domination, passive-aggression when suppressed.',
    giftExpression: 'Courage, decisive action, healthy boundaries, passionate engagement, protective strength, the ability to start and sustain effort.',
    rulesSign: ['Aries', 'Scorpio (traditional)'],
    keywords: ['action', 'desire', 'anger', 'courage', 'sexuality', 'competition', 'drive', 'boundaries'],
    dayOfWeek: 'Tuesday',
    metals: ['Iron'],
    bodyParts: ['Muscles', 'blood', 'adrenal glands', 'head'],
    colors: ['Red', 'scarlet'],
    animals: ['Wolf', 'vulture', 'woodpecker', 'ram'],
    tarotCorrespondence: 'The Tower (XVI)',
  },
  {
    name: 'Jupiter',
    symbol: '♃',
    greekName: 'Zeus',
    romanName: 'Jupiter / Jove',
    otherNames: ['Thor (Norse)', 'Marduk (Babylonian)'],
    category: 'social',
    archetype: 'The King / The Sage',
    tagline: 'Expansion, meaning, and the search for truth',
    myth: `Zeus was the youngest son of the titans Kronos and Rhea. His father, having been warned that one of his children would overthrow him, swallowed each child at birth. Rhea hid baby Zeus on the island of Crete, where he was raised by nymphs and fed on honey and the milk of the goat Amalthea. When he grew strong enough, Zeus freed his siblings from Kronos's belly and led the Olympians in a ten-year war against the Titans — the Titanomachy. After victory, he divided the cosmos with his brothers: he took the sky, Poseidon the sea, Hades the underworld. Zeus became the king of gods and the guardian of cosmic justice (Themis) and sacred hospitality (xenia). But his power came with excess — his endless love affairs produced dozens of children and drove Hera to jealous fury. Zeus teaches that expansion without wisdom becomes tyranny, and that true authority serves justice, not appetite.`,
    symbolism: [
      'The thunderbolt — sudden illumination, divine authority, breakthrough insight',
      'The eagle — the highest perspective, sovereignty over the visible world',
      'The oak tree — endurance, sacred shelter, deep roots supporting great reach',
      'Mount Olympus — the aspiration toward meaning and cosmic order',
    ],
    psychologicalFunction: 'Jupiter represents the search for meaning, faith, philosophy, higher education, travel, and the impulse to grow beyond current limitations. It is where you seek to understand the bigger picture.',
    shadowExpression: 'Excess, overindulgence, self-righteousness, blind optimism, moral superiority, promises without follow-through, playing god.',
    giftExpression: 'Wisdom, generosity, optimism, faith in life, ability to see the big picture, cultural breadth, inspirational teaching, good fortune.',
    rulesSign: ['Sagittarius', 'Pisces (traditional)'],
    keywords: ['expansion', 'wisdom', 'faith', 'abundance', 'philosophy', 'travel', 'justice', 'meaning'],
    dayOfWeek: 'Thursday',
    metals: ['Tin'],
    bodyParts: ['Liver', 'hips', 'thighs'],
    colors: ['Royal blue', 'purple', 'indigo'],
    animals: ['Eagle', 'horse', 'whale'],
    tarotCorrespondence: 'Wheel of Fortune (X)',
  },
  {
    name: 'Saturn',
    symbol: '♄',
    greekName: 'Kronos',
    romanName: 'Saturnus',
    otherNames: ['Ninurta (Babylonian)'],
    category: 'social',
    archetype: 'The Elder / The Gatekeeper',
    tagline: 'Time, limitation, and the mastery born from discipline',
    myth: `Kronos was the youngest and most cunning of the Titans. His mother Gaia, furious that her husband Ouranos had imprisoned their monstrous children in Tartarus, gave Kronos an adamantine sickle. He castrated his father and seized control of the cosmos, ushering in the legendary Golden Age — a time of peace and plenty. But power breeds paranoia: when Kronos learned that his own child would overthrow him, he devoured each of his children as they were born — Hestia, Demeter, Hera, Hades, Poseidon — one by one. His wife Rhea finally tricked him with a stone wrapped in swaddling clothes, saving Zeus. Kronos teaches the dual nature of time: it creates the conditions for growth (the Golden Age), but unchecked fear of the future consumes everything, including your own creations. Saturn asks: what are you so afraid of losing that you're destroying it by holding on too tight?`,
    symbolism: [
      'The sickle — cutting away what no longer serves, harvest after patient labor',
      'The swallowed children — fear of being replaced, consuming your own potential',
      'The Golden Age — the promise that discipline leads to lasting achievement',
      'The rings — boundaries, limitations, and the beauty of structure',
    ],
    psychologicalFunction: 'Saturn represents structure, responsibility, discipline, time, maturity, and the reality principle. It shows where you must do the work, face your fears, and earn your authority through experience.',
    shadowExpression: 'Rigidity, depression, excessive control, harsh self-criticism, fear of failure, cold emotional withdrawal, authoritarianism.',
    giftExpression: 'Discipline, perseverance, wisdom earned through experience, integrity, responsible authority, the ability to build things that last.',
    rulesSign: ['Capricorn', 'Aquarius (traditional)'],
    keywords: ['discipline', 'time', 'structure', 'responsibility', 'limitation', 'maturity', 'karma', 'mastery'],
    dayOfWeek: 'Saturday',
    metals: ['Lead'],
    bodyParts: ['Bones', 'teeth', 'knees', 'skin (aging)'],
    colors: ['Black', 'dark brown', 'grey'],
    animals: ['Goat', 'crow', 'crocodile'],
    tarotCorrespondence: 'The World (XXI)',
  },
  {
    name: 'Uranus',
    symbol: '♅',
    greekName: 'Ouranos',
    romanName: 'Caelus',
    category: 'transpersonal',
    archetype: 'The Awakener / The Revolutionary',
    tagline: 'Liberation through rupture, genius born from chaos',
    myth: `Ouranos was the primordial sky god, born from Gaia (Earth) herself — or in some versions, emerging from Chaos alongside her. He mated with Gaia endlessly, producing the Titans, the Cyclopes, and the hundred-handed Hecatoncheires. But Ouranos was horrified by his monstrous children and forced them back into Gaia's womb (Tartarus), causing her terrible pain. Gaia forged an adamantine sickle and asked her children for help. Only Kronos was brave enough. He ambushed Ouranos at nightfall and castrated him — the severed flesh falling into the sea to birth Aphrodite, and the blood falling on earth to spawn the Furies and the Giants. Ouranos screams from the sky that his children will pay for this — and they do, generation after generation. The myth teaches that suppression of what is new, strange, or "monstrous" leads to violent revolution. What you refuse to birth willingly will eventually overthrow you.`,
    symbolism: [
      'The castration — severance from the past that gives birth to the new (Aphrodite)',
      'The sky — infinite possibility, detachment from earthly limitation',
      'Lightning — sudden insight that shatters old structures',
      'The monstrous children — the genius, innovation, and difference we try to suppress',
    ],
    psychologicalFunction: 'Uranus represents the urge for freedom, individuation, sudden insight, rebellion against convention, and the capacity for genius. It is where you must break free from inherited patterns.',
    shadowExpression: 'Emotional detachment, chronic rebellion without purpose, instability, eccentricity as armor, inability to commit, shocking behavior for its own sake.',
    giftExpression: 'Originality, brilliant insight, humanitarian vision, courage to be different, technological innovation, liberation from outworn structures.',
    rulesSign: ['Aquarius'],
    keywords: ['revolution', 'freedom', 'genius', 'disruption', 'innovation', 'awakening', 'individuation', 'electricity'],
    metals: ['Uranium', 'platinum'],
    bodyParts: ['Nervous system (higher octave)', 'ankles', 'circulatory system'],
    colors: ['Electric blue', 'neon', 'ultraviolet'],
    animals: ['Albatross', 'electric eel'],
    tarotCorrespondence: 'The Fool (0) / The Star (XVII)',
  },
  {
    name: 'Neptune',
    symbol: '♆',
    greekName: 'Poseidon',
    romanName: 'Neptunus',
    category: 'transpersonal',
    archetype: 'The Mystic / The Dreamer',
    tagline: 'The dissolution of boundaries and the longing for the infinite',
    myth: `Poseidon received dominion over the sea when the cosmos was divided after the defeat of the Titans. He was second only to Zeus in power, and his temper was legendary — striking the earth with his trident caused earthquakes, storms, and tidal waves. He competed with Athena for patronage of Athens: she offered the olive tree (wisdom, civilization); he struck a rock and produced a saltwater spring (impressive but useless). He lost, and his resentment shaped the Odyssey — Poseidon's rage against Odysseus for blinding his son Polyphemus drove the hero to wander the seas for ten years. But Poseidon also created the horse (wild, beautiful, powerful) and was lord of all that lies beneath the surface — the vast unconscious, the depths where treasures and monsters coexist. Neptune teaches that what lies beneath the surface is vaster than what appears above it, and that surrendering to currents larger than yourself can carry you home — or drown you.`,
    symbolism: [
      'The trident — power over the three realms of consciousness (waking, dreaming, deep sleep)',
      'The ocean — the collective unconscious, boundlessness, dissolution',
      'The horse — instinctual power yoked to beauty',
      'The fog — confusion that precedes mystical clarity',
    ],
    psychologicalFunction: 'Neptune represents the longing for transcendence, spiritual connection, imagination, compassion, and the dissolution of ego boundaries. It is where you seek union with something greater than yourself.',
    shadowExpression: 'Escapism (addiction, fantasy, denial), deception, martyrdom, victim consciousness, confusion, inability to maintain boundaries.',
    giftExpression: 'Spiritual vision, artistic inspiration, unconditional compassion, mystical experience, imagination, music, healing through surrender.',
    rulesSign: ['Pisces'],
    keywords: ['transcendence', 'illusion', 'spirituality', 'dreams', 'compassion', 'dissolution', 'imagination', 'fog'],
    metals: ['Neptune (no traditional metal)', 'Platinum'],
    bodyParts: ['Pineal gland', 'feet', 'lymphatic system'],
    colors: ['Sea green', 'turquoise', 'lavender', 'iridescent'],
    animals: ['Fish', 'dolphin', 'seahorse'],
    tarotCorrespondence: 'The Hanged Man (XII)',
  },
  {
    name: 'Pluto',
    symbol: '♇',
    greekName: 'Hades',
    romanName: 'Pluto',
    otherNames: ['Ereshkigal (Sumerian, underworld queen)'],
    category: 'transpersonal',
    archetype: 'The Transformer / The Lord of the Underworld',
    tagline: 'Death, rebirth, and the hidden wealth of the shadow',
    myth: `Hades was the eldest son of Kronos and Rhea — the first to be swallowed and the last to be freed. When the cosmos was divided, he received the underworld — not as punishment, but as responsibility. He was lord of all that lies below: buried treasure, seeds germinating in darkness, the souls of the dead, and the secret riches of the earth. His most famous myth is the abduction of Persephone — he erupted from the earth in his black chariot, seized Demeter's daughter, and dragged her below. Demeter's grief caused all growing things to die. Eventually, a compromise was reached: Persephone would spend part of the year below (winter) and part above (spring). But what most forget is that Persephone became QUEEN of the underworld — she was not merely a victim. She gained sovereignty over the dead, became a formidable goddess in her own right, and chose to eat the pomegranate seeds. Pluto teaches that what is taken from us in the dark often becomes our greatest source of power.`,
    symbolism: [
      'The pomegranate — voluntary descent, binding yourself to the depths',
      'The Helm of Darkness — invisibility, operating from the shadows, unseen power',
      'The black chariot — the vehicle of transformation that erupts without warning',
      'Buried treasure — wealth and resources that can only be found underground',
    ],
    psychologicalFunction: 'Pluto represents the process of death and rebirth, transformation through crisis, power dynamics, the shadow, obsession, and the capacity to regenerate. It is where you must die to who you were in order to become who you are meant to be.',
    shadowExpression: 'Obsessive control, manipulation, power abuse, paranoia, destructiveness, refusing to let go, psychological coercion.',
    giftExpression: 'Profound transformation, psychological depth, resilience, capacity to heal deep wounds, empowerment, fearless truth-telling.',
    rulesSign: ['Scorpio'],
    keywords: ['transformation', 'death/rebirth', 'power', 'shadow', 'obsession', 'regeneration', 'depth', 'hidden wealth'],
    metals: ['Plutonium'],
    bodyParts: ['Reproductive organs', 'colon', 'DNA'],
    colors: ['Black', 'dark red', 'maroon'],
    animals: ['Scorpion', 'snake', 'phoenix', 'raven'],
    tarotCorrespondence: 'Death (XIII) / Judgement (XX)',
  },
  {
    name: 'Chiron',
    symbol: '⚷',
    greekName: 'Kheiron',
    romanName: 'Chiron',
    category: 'centaur',
    archetype: 'The Wounded Healer',
    tagline: 'The wound that becomes medicine for others',
    myth: `Chiron was unique among the centaurs — while others were wild, drunken, and violent, Chiron was wise, gentle, and civilized. He was the son of Kronos (who had taken the form of a horse to seduce the nymph Philyra), making him an immortal half-brother to Zeus. Chiron became the greatest teacher in the Greek world: he tutored Achilles, Asclepius (god of medicine), Jason, and Hercules in music, medicine, archery, and ethics. But when Hercules accidentally wounded him with an arrow dipped in the Hydra's poisonous blood, Chiron could not heal himself — despite being the greatest healer alive. As an immortal, he could not die to escape the pain. He suffered endlessly until he offered to trade his immortality to free Prometheus from his rock. Zeus honored this sacrifice by placing him among the stars as the constellation Centaurus. Chiron teaches that our deepest wound, the one we cannot fix in ourselves, becomes the source of our greatest gift to others.`,
    symbolism: [
      'The incurable wound — suffering that cannot be bypassed, only transmuted through service',
      'The centaur form — bridging animal instinct and higher wisdom',
      'The exchange with Prometheus — liberation through voluntary sacrifice',
      'The teacher — wounds that qualify us to guide others through similar terrain',
    ],
    psychologicalFunction: 'Chiron represents the core wound — often from early life — that resists healing but drives us to develop expertise, compassion, and the ability to help others with similar pain.',
    shadowExpression: 'Identifying as permanently broken, using wounds as excuses, rescuing others to avoid your own pain, bitterness about what can never be fixed.',
    giftExpression: 'Deep empathy born from experience, mentorship, holistic healing ability, bridging conventional and alternative approaches, transforming suffering into wisdom.',
    rulesSign: ['Associated with Virgo and Sagittarius'],
    keywords: ['wound', 'healing', 'teaching', 'mentorship', 'bridge', 'sacrifice', 'initiation', 'holistic'],
    animals: ['Horse', 'centaur'],
    tarotCorrespondence: 'The Hermit (IX)',
  },
  {
    name: 'Eris',
    symbol: '⯰',
    greekName: 'Eris',
    romanName: 'Discordia',
    category: 'transpersonal',
    archetype: 'The Disruptor / The Uninvited Truth',
    tagline: 'She reveals what has been excluded from the table',
    myth: `Eris, goddess of discord and strife, was the only deity NOT invited to the wedding of Peleus and Thetis (the parents of Achilles). Every other god received an invitation — but Eris, associated with conflict and disruption, was deliberately excluded. Rather than accept her exclusion quietly, she appeared at the feast uninvited and rolled a golden apple among the guests inscribed with the words "For the Fairest." Three goddesses — Hera, Athena, and Aphrodite — each claimed the apple, and the dispute was given to the mortal Paris to judge. His choice (Aphrodite, who bribed him with Helen) triggered the Trojan War. The myth reveals that what you exclude, deny, or refuse to invite to the table doesn't disappear — it returns with catastrophic force. Eris doesn't CREATE discord; she reveals the discord that was already there, hidden beneath the polite surface. She asks: who isn't at YOUR table? What truth are you refusing to acknowledge?`,
    symbolism: [
      'The golden apple — the question that exposes hidden competition and desire',
      'The uninvited guest — whatever is excluded from consciousness returns as disruption',
      'The Trojan War — the catastrophic consequences of refusing to face uncomfortable truths',
      'Discord — not chaos for its own sake, but the friction that forces authenticity',
    ],
    psychologicalFunction: 'Eris represents the function of disruption in service of truth — the part of the psyche that refuses to play along with false harmony and forces confrontation with what has been denied or excluded.',
    shadowExpression: 'Creating drama for attention, chronic contrarianism, deliberate sabotage, enjoying conflict, unable to accept belonging.',
    giftExpression: 'Radical honesty, the courage to name what everyone else is avoiding, catalyst for necessary change, justice for the marginalized.',
    rulesSign: ['Associated with Aries (by position and theme)'],
    keywords: ['discord', 'disruption', 'exclusion', 'truth', 'catalyst', 'uninvited', 'golden apple', 'revelation'],
    tarotCorrespondence: 'The Tower (XVI)',
  },
  {
    name: 'Lilith (Black Moon)',
    symbol: '⚸',
    greekName: 'Lilith (Hebrew/Mesopotamian)',
    romanName: 'N/A',
    otherNames: ['Black Moon Lilith', 'Lilitu (Babylonian)'],
    category: 'point',
    archetype: 'The Exile / The Wild Feminine',
    tagline: 'What was banished for refusing to submit',
    myth: `In the earliest versions of the Genesis story (the Alphabet of Ben Sira), Lilith was Adam's first wife, created from the same earth as him — his equal. When Adam insisted she lie beneath him during intercourse, Lilith refused, arguing that they were made of the same substance and she should not be subordinate. When Adam tried to force her, Lilith spoke the ineffable name of God, grew wings, and flew away to the shores of the Red Sea, where she lived freely among demons and gave birth to hundreds of children. God sent three angels to bring her back, threatening to kill a hundred of her children each day. Lilith refused to return, preferring exile and suffering to subjugation. She became a night demon in later traditions — feared, demonized, and blamed for infant death and male nocturnal emissions. But the original story is about autonomy: Lilith chose freedom over security, wildness over domestication, sovereignty over belonging.`,
    symbolism: [
      'The refusal — the primal "no" to subjugation, regardless of consequences',
      'The wings — escape from structures that demand submission',
      'The Red Sea shore — exile as the price of autonomy',
      'The demonized feminine — what patriarchal culture cannot control, it calls evil',
    ],
    psychologicalFunction: 'Black Moon Lilith represents what was exiled from the personality for being too wild, too sexual, too autonomous, or too threatening. It is where you were shamed and where you hold raw, untamed power.',
    shadowExpression: 'Destructive rage, sexual manipulation, compulsive rebellion, inability to cooperate, sabotaging intimacy to maintain control.',
    giftExpression: 'Fierce autonomy, raw creative and sexual power, refusal to betray the self for acceptance, reclaiming what was shamed.',
    rulesSign: ['Associated with Scorpio and Capricorn themes'],
    keywords: ['exile', 'autonomy', 'sexuality', 'rebellion', 'shame', 'wildness', 'taboo', 'raw power'],
    tarotCorrespondence: 'The High Priestess (II, reversed) / Strength (VIII)',
  },
  {
    name: 'Ceres',
    symbol: '⚳',
    greekName: 'Demeter',
    romanName: 'Ceres',
    category: 'asteroid',
    archetype: 'The Great Mother / The Griever',
    tagline: 'Nourishment, loss, and the cycles of letting go',
    myth: `Demeter was the goddess of grain, harvest, and the fertility of the earth. When her daughter Persephone was abducted by Hades, Demeter's grief was so total that she withdrew her gifts from the world — crops died, trees withered, famine spread, and humanity began to starve. She wandered the earth disguised as an old woman, searching for her daughter, refusing food, refusing comfort. The gods begged her to relent, but she declared that nothing would grow until Persephone was returned. Zeus was forced to intervene. The compromise — Persephone spending part of the year underground — gave us the seasons: life and growth when mother and daughter are reunited, death and dormancy when they are apart. Demeter teaches that grief is not weakness — it is the most powerful force in nature. A mother's love, when thwarted, can stop the world.`,
    symbolism: [
      'The grain sheaf — nourishment, sustenance, what feeds body and soul',
      'The famine — grief so deep it stops all growth',
      'The seasons — the eternal cycle of attachment, loss, return, and renewal',
      'The torch — the search for what has been taken, refusing to give up',
    ],
    psychologicalFunction: 'Ceres represents nourishment — how you feed and are fed (literally and emotionally), attachment, loss, separation anxiety, food relationships, and the cycle of holding on and letting go.',
    shadowExpression: 'Smothering control, using food as love/punishment, inability to let children/projects grow independently, grief that becomes self-destruction.',
    giftExpression: 'Deep nurturing capacity, attunement to physical and emotional needs, understanding of natural cycles, fierce love that transforms the world.',
    rulesSign: ['Associated with Virgo and Cancer'],
    keywords: ['nourishment', 'harvest', 'grief', 'mothering', 'seasons', 'food', 'attachment', 'fertility'],
    tarotCorrespondence: 'The Empress (III)',
  },
  {
    name: 'Pallas',
    symbol: '⚴',
    greekName: 'Pallas Athena',
    romanName: 'Minerva',
    category: 'asteroid',
    archetype: 'The Strategist / The Pattern-Seer',
    tagline: 'Creative intelligence and the warrior mind',
    myth: `Athena was born from Zeus's head — literally. After Zeus swallowed her pregnant mother Metis (wisdom personified, whom he feared would bear a son more powerful than himself), Athena grew inside his skull until Hephaestus split it open with an axe and she emerged fully armored, ready for battle. She was the goddess of wisdom, strategic warfare, weaving, and civilization — the thinking warrior who won through intelligence rather than brute force. She invented the bridle (taming wild horses), the plow, the chariot, and the art of weaving. In the contest with Poseidon for Athens, she offered the olive tree — practical, sustaining, and civilizing. Athena never lost a battle because she never fought without a plan. But she was also fierce: she turned Medusa into a monster (some say to protect her, others to punish her) and guided heroes like Perseus and Odysseus through impossible tasks.`,
    symbolism: [
      'The owl — wisdom that sees in the dark, pattern recognition',
      "The aegis with Medusa's head — using fear strategically, the power of the gaze",
      'The olive tree — practical wisdom that sustains civilization',
      'The loom — weaving patterns from chaos, seeing the whole design',
    ],
    psychologicalFunction: 'Pallas represents creative intelligence, pattern recognition, strategic thinking, and the ability to see the whole picture. It shows where you solve problems through insight rather than force.',
    shadowExpression: 'Cold rationality, dismissing emotions as weakness, over-identification with the father, using intelligence to dominate.',
    giftExpression: 'Brilliant strategy, artistic vision, political wisdom, ability to see patterns others miss, mentorship, civilizing influence.',
    rulesSign: ['Associated with Aquarius and Libra'],
    keywords: ['strategy', 'wisdom', 'patterns', 'crafts', 'politics', 'justice', 'mentorship', 'intelligence'],
    tarotCorrespondence: 'Justice (XI)',
  },
  {
    name: 'Juno',
    symbol: '⚵',
    greekName: 'Hera',
    romanName: 'Juno',
    category: 'asteroid',
    archetype: 'The Queen / The Committed Partner',
    tagline: 'Sacred partnership and the politics of loyalty',
    myth: `Hera was the queen of the gods, sister and wife of Zeus, and guardian of marriage, women, and childbirth. She endured Zeus's constant infidelities — affairs with mortals, nymphs, goddesses, and even boys — and her rage at these betrayals defined much of Greek mythology. She persecuted Hercules (Zeus's son by the mortal Alcmene) from birth, sending serpents to his crib and driving him mad so that he killed his own children. She punished Echo (who distracted her so Zeus could philander) by taking away her voice. Yet Hera's fury was not merely jealousy — it was the righteous anger of sacred commitments violated, of a queen whose sovereignty was constantly undermined. In her own right, Hera was worshipped as a powerful goddess of sovereignty and female authority long before her marriage to Zeus. The myth teaches that partnership requires mutual respect, and that betrayal in committed relationships unleashes the most destructive forces in human experience.`,
    symbolism: [
      'The peacock — beauty and pride, but also the hundred eyes of vigilance (Argos)',
      'The pomegranate — fertility, but also binding oaths',
      'The crown/diadem — sovereignty within partnership, equal authority',
      'The cow — sacred feminine power, nurturing strength',
    ],
    psychologicalFunction: 'Juno represents committed partnership, marriage dynamics, fairness in relationship, jealousy, betrayal patterns, and the need for equal power in intimate bonds.',
    shadowExpression: 'Jealousy, possessiveness, revenge against perceived rivals, sacrificing identity for partnership, staying in toxic bonds out of duty.',
    giftExpression: 'Capacity for deep commitment, advocating for fairness in relationships, queenly dignity, loyalty that transforms both partners.',
    rulesSign: ['Associated with Libra and Scorpio'],
    keywords: ['marriage', 'partnership', 'jealousy', 'commitment', 'loyalty', 'betrayal', 'sovereignty', 'equality'],
    tarotCorrespondence: 'The Lovers (VI)',
  },
  {
    name: 'Vesta',
    symbol: '⚶',
    greekName: 'Hestia',
    romanName: 'Vesta',
    category: 'asteroid',
    archetype: 'The Priestess / The Sacred Flame',
    tagline: 'Devotion, inner sanctuary, and what you tend with quiet discipline',
    myth: `Hestia was the firstborn child of Kronos and Rhea — and therefore the first to be swallowed, and the last to be freed. Both Poseidon and Apollo courted her, but she swore an eternal oath of virginity upon Zeus's head and was granted the honor of receiving the first portion of every sacrifice. She was the goddess of the hearth fire — the sacred center of every home and temple. Unlike other Olympians, Hestia had no dramatic myths, no love affairs, no wars. She simply remained. Her power was in presence, not action. When Dionysus arrived on Olympus, Hestia quietly gave up her throne among the Twelve so there would be no conflict — the ultimate act of self-possession. The Vestal Virgins of Rome tended her eternal flame; if it went out, Rome itself was endangered. Hestia teaches that the most sacred things require quiet, sustained devotion — and that true power sometimes means knowing when to step back.`,
    symbolism: [
      'The eternal flame — what must never go out, the sacred center',
      'The hearth — home, inner sanctuary, the still point of the turning world',
      'Virginity — wholeness unto oneself, not defined by relationship to others',
      'The first and last offering — honored at the beginning and end of all things',
    ],
    psychologicalFunction: 'Vesta represents devotion, focus, sacred service, spiritual practice, and the capacity for self-containment. It shows where you tend the inner flame and what you are devoted to with quiet, sustained attention.',
    shadowExpression: 'Isolation, fanatical devotion, burn-out from over-commitment, using spiritual practice to avoid relationship, rigidity.',
    giftExpression: 'Deep focus, spiritual devotion, creating sacred space, self-sufficiency, the warmth that makes a house a home.',
    rulesSign: ['Associated with Virgo and Scorpio'],
    keywords: ['devotion', 'focus', 'sacred', 'hearth', 'virginity', 'service', 'sanctuary', 'discipline'],
    tarotCorrespondence: 'The Hermit (IX)',
  },
  {
    name: 'Sedna',
    symbol: '⏣',
    greekName: 'N/A',
    romanName: 'N/A',
    otherNames: ['Sanna', 'Arnakuagsak', 'Nuliajuk'],
    category: 'transpersonal',
    archetype: 'The Betrayed One / The Deep Sea Mother',
    tagline: 'Betrayal, deep transformation, and the life that sustains from the abyss',
    myth: `Sedna is not Greek or Roman — she comes from Inuit tradition, which is fitting for the most distant known object in our solar system. In the most common version, Sedna was a beautiful young woman who refused all suitors. A mysterious stranger (sometimes a bird-spirit) lured her away with promises of a beautiful home. When her father came to rescue her in his kayak, the stranger pursued them, conjuring a terrible storm. In terror, her father threw Sedna overboard to save himself. When she clung to the side of the kayak, he chopped off her fingers, joint by joint. Her severed fingers became the seals, walruses, and whales — the marine life that sustains Arctic peoples. Sedna sank to the bottom of the ocean and became its ruler. Shamans must journey to the sea floor to comb the tangles from her hair (caused by human transgressions) so she will release the animals for hunting. Sedna teaches that the deepest betrayals — by those who should protect us — can become the source of life for entire communities.`,
    symbolism: [
      'The severed fingers — what is taken from us through betrayal becomes sustenance for others',
      'The ocean floor — the deepest possible descent, far below conscious awareness',
      'The tangled hair — accumulated grief, neglect, and transgression that blocks abundance',
      "The shaman's journey — the necessity of going to the very bottom to restore balance",
    ],
    psychologicalFunction: 'Sedna represents the deepest layers of ancestral and collective trauma — betrayals so profound they reshape the ecosystem of the psyche. It shows where we must journey to the absolute bottom to find what sustains life.',
    shadowExpression: 'Frozen grief, inability to trust, identifying permanently as victim, ecological disconnection, spiritual bypass of deep wounds.',
    giftExpression: 'Transmuting the deepest betrayals into sources of nourishment for others, ecological consciousness, connection to ancestral wisdom, the courage to go where no one else will go.',
    rulesSign: ['Associated with Pisces/Scorpio themes (deep water, transformation)'],
    keywords: ['betrayal', 'depth', 'ecology', 'ancestral trauma', 'ocean', 'sustenance', 'shamanic journey', 'transformation'],
  },
  // ========== DWARF PLANETS & TNOs ==========
  {
    name: 'Makemake',
    symbol: '🜨',
    greekName: 'N/A',
    romanName: 'N/A',
    otherNames: ['Make-Make'],
    category: 'transpersonal',
    archetype: 'The Creator God / The Birdman',
    tagline: 'Primal creation, environmental stewardship, and the sacred competition',
    myth: `Makemake is the creator god of Rapa Nui (Easter Island), the supreme deity who created humanity and brought the first birds to the island. The Tangata Manu (Birdman) cult centered on an annual competition where warriors swam through shark-infested waters to a small islet to retrieve the first egg of the sooty tern. The winner became the Birdman — the living representative of Makemake for that year, granted sacred authority. This was a meritocratic transfer of power, replacing hereditary kingship with earned divine favor. Makemake's creation was intimately tied to the natural world: fertility of the land, the return of migratory birds, the cycles of abundance and scarcity.`,
    symbolism: [
      'The egg — potential, new creation, the prize that must be earned through risk',
      'The Birdman — divine authority earned, not inherited',
      'Shark-infested waters — the dangers in the creative process',
      'Migratory birds — the dependence of creation on natural cycles',
    ],
    psychologicalFunction: 'Makemake represents the primal creative impulse and our relationship with the natural world as sacred. It shows where we must earn our authority through courageous action aligned with ecological awareness.',
    shadowExpression: 'Exploitation of natural resources, treating creation as entitlement, disconnection from environmental consequences, hoarding fertility.',
    giftExpression: 'Sacred creativity, environmental consciousness, earning authority through service, connecting human purpose with natural cycles.',
    rulesSign: ['Associated with earth/environmental themes'],
    keywords: ['creation', 'environment', 'fertility', 'earned authority', 'ecology', 'sacred competition', 'birds', 'primal force'],
  },
  {
    name: 'Haumea',
    symbol: '🜵',
    greekName: 'N/A',
    romanName: 'N/A',
    otherNames: ['Papa'],
    category: 'transpersonal',
    archetype: 'The Birth Mother / The Regenerator',
    tagline: 'Endless rebirth, creative fertility, and the body that keeps giving',
    myth: `Haumea is the Hawaiian goddess of childbirth and fertility, a primal creatrix whose body itself is the source of new life. She gave birth to numerous gods, islands, and living things — not through sexual union alone, but from different parts of her own body. She could transform her age at will, becoming young again to take new lovers and bear more children. When she grew old, she would simply renew herself. Haumea's children include Pele (goddess of volcanoes) and Hi'iaka (goddess of dance and sorcery). She represents the earth itself as a perpetually regenerating mother — creation that never exhausts itself because it draws from an infinite source.`,
    symbolism: [
      'Birth from the body — creativity that comes from the self, not external sources',
      'Self-renewal — the ability to regenerate and begin again',
      'Multiple births — prolific creativity, abundance without depletion',
      'The volcanic islands — creation through dramatic transformation',
    ],
    psychologicalFunction: 'Haumea represents the capacity for continual regeneration and rebirth. It shows where we can create endlessly from our own substance, and where we refuse to accept depletion as final.',
    shadowExpression: 'Compulsive fertility, inability to stop producing, neglecting existing creations for new ones, denial of aging and natural endings.',
    giftExpression: 'Perpetual renewal, abundance consciousness, creative fertility, resilience through transformation, honoring the body as source.',
    rulesSign: ['Associated with Cancer/fertility themes'],
    keywords: ['rebirth', 'fertility', 'regeneration', 'motherhood', 'transformation', 'renewal', 'abundance', 'creation'],
  },
  {
    name: 'Quaoar',
    symbol: '🝾',
    greekName: 'N/A',
    romanName: 'N/A',
    category: 'transpersonal',
    archetype: 'The Sacred Singer / The Rhythm Creator',
    tagline: 'Creation through song, sacred rhythm, and the dance that brings worlds into being',
    myth: `Quaoar is the creation god of the Tongva people (indigenous to the Los Angeles basin). In the beginning, there was only chaos — formless, silent void. Quaoar looked upon this emptiness and was saddened. So he began to sing. And as he sang, he danced. His song and dance brought order from chaos. First he created Weywot (Sky), then Chehooit (Earth), and finally all living things. But Quaoar did not impose creation through force or will — he sang it into existence through beauty and rhythm. Creation was not labor; it was art. The Tongva understood that the world is maintained by continued singing — that reality itself is a song being perpetually performed.`,
    symbolism: [
      'Song — creation through vibration and beauty, not force',
      'Dance — embodied rhythm as the organizing principle of reality',
      'The void — the necessary emptiness before creation',
      'Continued singing — reality requires ongoing participation to maintain',
    ],
    psychologicalFunction: 'Quaoar represents the power of creative rhythm and sacred play. It shows where reality responds to beauty rather than force, and where we must participate in the ongoing song of creation.',
    shadowExpression: 'Forcing creation rather than allowing it, disconnection from natural rhythm, imposing order through violence rather than beauty.',
    giftExpression: 'Creating through joy and rhythm, understanding reality as participatory, sacred artistry, the ability to bring order through beauty.',
    rulesSign: ['Associated with Sagittarius/creative themes'],
    keywords: ['creation', 'song', 'rhythm', 'sacred dance', 'manifestation', 'beauty', 'order from chaos', 'participation'],
  },
  {
    name: 'Orcus',
    symbol: '🝿',
    greekName: 'Orcus',
    romanName: 'Orcus',
    otherNames: ['The Anti-Pluto'],
    category: 'transpersonal',
    archetype: 'The Oath-Keeper / The Underworld Judge',
    tagline: 'Sacred promises, karmic contracts, and the price of broken vows',
    myth: `Orcus was a Roman god of the underworld, a punisher of broken oaths. While Pluto ruled the dead with sovereignty, Orcus specifically dealt with those who violated their word. His domain was the consequences of broken promises — the karmic debt that accumulates when commitments are betrayed. In Roman homes, oaths were sworn "by Orcus," making him witness to every sacred promise. Orcus was often depicted as a hairy, bearded giant — monstrous but just. He didn't create suffering; he enforced the natural consequences of dishonor. His name survives in "ogre" — the terrifying enforcer who appears when agreements are violated.`,
    symbolism: [
      'The oath — the sacred power of the spoken word and commitment',
      'The underworld judge — consequences that cannot be escaped',
      'The ogre — the terrifying face of accountability',
      'Broken vows — karmic debt that accumulates across lifetimes',
    ],
    psychologicalFunction: 'Orcus represents integrity, sacred commitments, and the consequences of broken promises. It shows where we carry karmic contracts and where our word must become unbreakable.',
    shadowExpression: 'Rigid moralism, punishing others for perceived betrayals, inability to forgive or release old contracts, becoming the enforcer rather than the teacher.',
    giftExpression: 'Impeccable integrity, honoring commitments, understanding karmic patterns, the courage to keep promises even when difficult.',
    rulesSign: ['Associated with Scorpio/karmic themes'],
    keywords: ['oaths', 'integrity', 'karma', 'promises', 'accountability', 'contracts', 'consequences', 'honor'],
  },
  {
    name: 'Ixion',
    symbol: '⯳',
    greekName: 'Ixion',
    romanName: 'Ixion',
    category: 'transpersonal',
    archetype: 'The Ingrate / The Boundary Violator',
    tagline: 'Entitlement versus gratitude, and the wheel of consequence',
    myth: `Ixion was a Thessalian king who committed the first murder of a family member in Greek mythology — he killed his father-in-law by pushing him into a pit of burning coals to avoid paying a bride price. When no mortal or god would purify him of this crime, Zeus himself took pity and invited Ixion to dine at the table of the gods. Instead of gratitude, Ixion attempted to seduce Hera, Zeus's wife. Zeus tested him by creating a cloud in Hera's form (Nephele), and Ixion coupled with it, producing the centaurs. For this ultimate act of ingratitude — repaying divine mercy with attempted violation — Zeus bound Ixion to a fiery wheel spinning eternally through the sky.`,
    symbolism: [
      'The spinning wheel — repeating cycles of consequence, going nowhere',
      'The false Hera — pursuing illusions, mistaking desire for reality',
      'Murder of kin — the original violation that begins the cycle',
      'Divine hospitality betrayed — ingratitude as the root of suffering',
    ],
    psychologicalFunction: 'Ixion represents where we repeat destructive patterns of entitlement, where we take what is offered and demand more, and where gratitude is the missing medicine.',
    shadowExpression: 'Chronic entitlement, inability to feel grateful, repeating the same violations, boundary-crossing disguised as desire.',
    giftExpression: 'Learning gratitude, breaking repetitive cycles, understanding that mercy received creates obligation, transforming entitlement into appreciation.',
    rulesSign: ['Associated with Sagittarius/ethical themes'],
    keywords: ['entitlement', 'gratitude', 'repetition', 'boundaries', 'consequence', 'ethics', 'cycles', 'ingratitude'],
  },
  {
    name: 'Varuna',
    symbol: '⯴',
    greekName: 'N/A',
    romanName: 'N/A',
    otherNames: ['Vedic sky god'],
    category: 'transpersonal',
    archetype: 'The All-Seeing / The Cosmic Law',
    tagline: 'Universal truth, vast vision, and the order that holds everything together',
    myth: `Varuna is one of the oldest Vedic gods — the sovereign ruler of cosmic order (Rta), the law that governs the universe, the tides, the stars, and moral truth. Varuna had a thousand eyes, seeing everything, everywhere, at all times. He could bind transgressors with his noose (pasha) and was greatly feared as the enforcer of cosmic law. But Varuna was not merely punitive — he was the upholder of truth itself. Those who confessed and sought forgiveness were released. In later Hinduism, Varuna was demoted to lord of the ocean, but his original function was far greater: he was the moral order of the universe made conscious.`,
    symbolism: [
      'A thousand eyes — omniscience, nothing escapes awareness',
      'The noose (pasha) — binding consequences of deception',
      'Cosmic order (Rta) — the law behind all laws',
      'The ocean — the vastness that contains everything',
    ],
    psychologicalFunction: 'Varuna represents where we encounter universal law and truth — forces too vast to resist or manipulate. It shows where we must align with cosmic order or be bound by consequences.',
    shadowExpression: 'Paranoia about being watched, rigid legalism, using "truth" as a weapon, delusions of omniscience, playing god.',
    giftExpression: 'Vast perspective, alignment with truth, ability to see the big picture, moral clarity, understanding that honesty is the path to freedom.',
    rulesSign: ['Associated with Aquarius/universal themes'],
    keywords: ['truth', 'cosmic law', 'vision', 'omniscience', 'order', 'vastness', 'morality', 'alignment'],
  },
  // ========== CENTAURS ==========
  {
    name: 'Pholus',
    symbol: '⯛',
    greekName: 'Pholos',
    romanName: 'Pholus',
    category: 'centaur',
    archetype: 'The Catalyst / The Uncorked Bottle',
    tagline: 'Small cause, massive effect — the turning point you cannot take back',
    myth: `Pholus was a civilized centaur, like Chiron, who lived in a cave on Mount Pholoe. When Heracles visited during his fourth labor (the Erymanthian Boar), Pholus offered him roasted meat but hesitated to open the communal wine jar that belonged to all the centaurs. Heracles insisted, and when the jar was opened, the scent of the wine drove the other centaurs into a frenzy. A bloody battle ensued. Pholus, examining one of Heracles' poisoned arrows after the fight, accidentally dropped it on his foot and died instantly. A small act — opening a bottle, picking up an arrow — triggered an irreversible catastrophe. Pholus is the butterfly effect made mythic.`,
    symbolism: [
      'The uncorked wine — releasing something that cannot be contained again',
      'The poisoned arrow — the danger in examining things too closely without protection',
      'Small cause → massive effect — the butterfly effect, cascading consequences',
      'The communal jar — shared resources that carry collective power',
    ],
    psychologicalFunction: 'Pholus represents turning points and catalytic moments where a small action creates irreversible change. It shows where one gesture, one word, one decision opens a cascade.',
    shadowExpression: 'Recklessness, not understanding the power of small actions, triggering others without awareness, carelessness with powerful forces.',
    giftExpression: 'Understanding leverage points, recognizing turning moments, respecting the power of small actions, becoming a conscious catalyst for transformation.',
    rulesSign: ['Associated with Sagittarius/catalyst themes'],
    keywords: ['catalyst', 'turning point', 'butterfly effect', 'irreversible', 'small cause', 'big effect', 'wine', 'release'],
  },
  {
    name: 'Nessus',
    symbol: '⯜',
    greekName: 'Nessos',
    romanName: 'Nessus',
    category: 'centaur',
    archetype: 'The Cycle-Breaker / "The Buck Stops Here"',
    tagline: 'Ending inherited abuse patterns — the poison that ultimately heals',
    myth: `Nessus was a centaur who worked as a ferryman, carrying travelers across a river. When Heracles and his wife Deianeira needed to cross, Nessus carried Deianeira and attempted to assault her. Heracles shot him with a poisoned arrow. As Nessus lay dying, he whispered to Deianeira to collect his blood (now mixed with the Hydra's poison from the arrow), telling her it would act as a love charm if Heracles ever strayed. Years later, when Heracles took a concubine, Deianeira smeared Nessus's blood on a shirt and gave it to Heracles. The poison burned him alive. The abuser's final act — his "gift" — perpetuated the cycle of violation. Nessus in astrology marks where abuse cycles end.`,
    symbolism: [
      'The poisoned gift — abuse disguised as help, passed from abuser to victim',
      'The ferry crossing — the transition point where violation occurs',
      'The burning shirt — the inherited poison that destroys from within',
      'Death of the hero — even the strongest cannot escape the cycle without awareness',
    ],
    psychologicalFunction: 'Nessus represents inherited patterns of abuse, violation, and the place where cycles of harm must end. "The buck stops here" is its core teaching.',
    shadowExpression: 'Perpetuating abuse cycles, accepting poisoned gifts, becoming the abuser, inability to recognize violation as violation.',
    giftExpression: 'Breaking generational trauma, refusing to pass the poison forward, naming violation for what it is, healing ancestral wounds.',
    rulesSign: ['Associated with Scorpio/healing themes'],
    keywords: ['abuse cycles', 'generational trauma', 'the buck stops here', 'violation', 'healing', 'poison', 'accountability', 'cycle-breaking'],
  },
  {
    name: 'Chariklo',
    symbol: '⚳',
    greekName: 'Chariklo',
    romanName: 'Chariklo',
    category: 'centaur',
    archetype: 'The Compassionate Witness / The Healer\'s Partner',
    tagline: 'The one who stays, holds space, and loves what is wounded',
    myth: `Chariklo was a water nymph, the wife of Chiron. While Chiron is celebrated as the Wounded Healer, Chariklo is the one who stayed beside him — who held space for his eternal wound without trying to fix it, who loved him not despite his pain but with full knowledge of it. She was also connected to the myth of Tiresias: when her son Tiresias accidentally saw Athena bathing and was blinded, Chariklo begged Athena for mercy. Athena could not undo the blinding but granted Tiresias the gift of prophecy — sight beyond sight. Chariklo represents the person who advocates, who stands beside the wounded, who negotiates with the gods on behalf of those who suffer.`,
    symbolism: [
      'The wife who stays — unconditional presence, love without conditions',
      'Water nymph — emotional fluency and intuitive healing',
      'Advocacy — speaking to power on behalf of the wounded',
      'Sight beyond sight — the compensation that comes through compassion',
    ],
    psychologicalFunction: 'Chariklo represents the capacity to hold space for others\' wounds without absorbing them, the art of compassionate witnessing, and the power of steady, loving presence.',
    shadowExpression: 'Codependency, losing yourself in another\'s wound, enabling suffering, inability to set boundaries while holding space.',
    giftExpression: 'Compassionate witnessing, unconditional presence, advocating for the wounded, knowing how to stay without drowning.',
    rulesSign: ['Associated with Pisces/compassion themes'],
    keywords: ['compassion', 'witnessing', 'holding space', 'advocacy', 'presence', 'healing partner', 'unconditional love', 'boundaries'],
  },
  // ========== LOVE & SOUL ASTEROIDS ==========
  {
    name: 'Psyche',
    symbol: 'Ψ',
    greekName: 'Psyche',
    romanName: 'Psyche',
    category: 'asteroid',
    archetype: 'The Soul / The One Who Must See',
    tagline: 'The soul\'s journey through love, loss, and the demand to see clearly',
    myth: `Psyche was a mortal woman so beautiful that people worshipped her instead of Aphrodite. The jealous goddess sent her son Eros to make Psyche fall in love with something hideous, but Eros himself fell in love with her. He took her to his palace and visited only in darkness, forbidding her to see his face. Psyche's sisters convinced her to look, and when she lit a lamp, a drop of hot oil fell on the sleeping Eros. He woke and fled. To win him back, Psyche had to complete four impossible tasks set by Aphrodite — sorting seeds (discernment), gathering golden fleece (courage without force), filling a flask from the River Styx (containing infinity), and descending to the Underworld (facing death). She completed all four and was made immortal.`,
    symbolism: [
      'The lamp — the need to see truth, even when it destroys comfort',
      'The four tasks — the soul\'s initiatory journey through discernment, courage, containment, and death',
      'The forbidden gaze — love that demands darkness cannot sustain',
      'Immortality earned — the soul that perseveres through trials transcends mortality',
    ],
    psychologicalFunction: 'Psyche represents the soul\'s journey toward wholeness through love\'s trials. It shows where we must see clearly even when the seeing costs us, and where initiation through suffering leads to transformation.',
    shadowExpression: 'Refusing to look, staying in comfortable darkness, giving up when trials come, letting others\' voices override soul-knowing.',
    giftExpression: 'Soul courage, completing the journey, earning love through trials, integrating all parts of the self, transformation through persistence.',
    rulesSign: ['Associated with Virgo/soul themes'],
    keywords: ['soul', 'seeing', 'trials', 'love earned', 'initiation', 'persistence', 'transformation', 'clarity'],
  },
  {
    name: 'Eros',
    symbol: '♡',
    greekName: 'Eros',
    romanName: 'Cupid',
    category: 'asteroid',
    archetype: 'The Erotic Force / The Arrow of Desire',
    tagline: 'Raw desire, the pull toward merging, and the creative force of attraction',
    myth: `Eros is one of the oldest gods — Hesiod names him as a primordial force present at creation, the power that drives all things toward union. In later myth, he became Aphrodite's son, the mischievous archer whose arrows caused instant desire. But the earlier Eros is far more powerful: he is the cosmic force of attraction itself, without which nothing comes together, nothing is created, nothing lives. His arrows are not playful — they are compulsive, overwhelming, and transformative. When Eros strikes, rational thought dissolves. This is not romantic love (that's Venus) — this is the erotic force, the primal hunger to merge with another.`,
    symbolism: [
      'The arrow — desire that strikes without warning, bypassing the rational mind',
      'Wings — the elevation and volatility of desire',
      'The torch — the burning quality of erotic attraction',
      'Primordial force — desire as a fundamental creative power, not just emotion',
    ],
    psychologicalFunction: 'Eros represents the force of desire, erotic attraction, and the compulsive pull toward merging. It shows what we hunger for with our whole being — not what we choose, but what chooses us.',
    shadowExpression: 'Compulsive desire, objectification, confusing intensity with love, addiction to the hit of attraction, inability to sustain desire into intimacy.',
    giftExpression: 'Passionate aliveness, creative fire, the courage to desire fully, understanding attraction as a creative and spiritual force.',
    rulesSign: ['Associated with Scorpio/Aries themes'],
    keywords: ['desire', 'attraction', 'eros', 'passion', 'merging', 'creative force', 'compulsion', 'aliveness'],
  },
  {
    name: 'Amor',
    symbol: '♥',
    greekName: 'N/A',
    romanName: 'Amor',
    category: 'asteroid',
    archetype: 'Unconditional Love / The Open Heart',
    tagline: 'Love without conditions, the capacity to love regardless of reciprocation',
    myth: `Amor is the Latin word for love — but not the dramatic, arrow-struck passion of Eros/Cupid. Amor represents love as a state of being rather than an action or event. In the philosophical traditions, Amor was connected to "amor fati" — love of fate, the acceptance and embrace of everything life brings. This is love that doesn't need to possess, doesn't need to be returned, doesn't need an object at all. It is the capacity of the heart to remain open regardless of circumstances.`,
    symbolism: [
      'The open heart — love as a state of being, not a transaction',
      'Amor fati — loving fate itself, embracing what comes',
      'Non-possessive love — giving without expecting return',
      'The universal heart — love that extends beyond the personal',
    ],
    psychologicalFunction: 'Amor represents where we can love unconditionally — where the heart remains open regardless of reciprocation. It shows our capacity for selfless love and acceptance.',
    shadowExpression: 'Martyrdom, loving to the point of self-erasure, using unconditional love as spiritual bypass, refusing to protect the heart.',
    giftExpression: 'Genuine unconditional love, amor fati, holding the heart open in difficult times, love as a practice rather than a feeling.',
    rulesSign: ['Associated with Pisces/Libra themes'],
    keywords: ['unconditional love', 'amor fati', 'acceptance', 'open heart', 'selfless', 'devotion', 'non-attachment', 'compassion'],
  },
  {
    name: 'Hygiea',
    symbol: '⚕',
    greekName: 'Hygieia',
    romanName: 'Hygiea',
    category: 'asteroid',
    archetype: 'The Healer Through Prevention / Sacred Hygiene',
    tagline: 'Health as wholeness, prevention over cure, the wisdom of daily practice',
    myth: `Hygieia was the daughter of Asclepius (god of medicine) and granddaughter of Apollo. While her father was associated with curing disease, Hygieia embodied the prevention of illness through clean living, proper habits, and the maintenance of health. She was depicted feeding a sacred serpent from a bowl — the serpent representing regenerative wisdom, the bowl representing the daily practice of nourishment. The word "hygiene" comes directly from her name. Hygieia's teaching is radical in its simplicity: the best medicine is not needing medicine.`,
    symbolism: [
      'The serpent and bowl — the symbol of pharmacy and healing (still used today)',
      'Prevention — wisdom is avoiding illness, not just curing it',
      'Daily practice — health as an ongoing discipline, not an emergency response',
      'Wholeness — health as the integration of body, mind, and spirit',
    ],
    psychologicalFunction: 'Hygiea represents the relationship between daily habits and long-term wellbeing. It shows where prevention, routine, and self-care practices maintain wholeness.',
    shadowExpression: 'Health anxiety, orthorexia, obsessive cleanliness, using health practices as control, judging others for their habits.',
    giftExpression: 'Wise self-care, preventive awareness, understanding the body\'s signals, maintaining health through mindful daily practice.',
    rulesSign: ['Associated with Virgo/health themes'],
    keywords: ['health', 'prevention', 'hygiene', 'daily practice', 'wholeness', 'self-care', 'body wisdom', 'maintenance'],
  },
  // ========== CALCULATED POINTS ==========
  {
    name: 'North Node',
    symbol: '☊',
    greekName: 'Caput Draconis',
    romanName: 'Head of the Dragon',
    otherNames: ['Rahu', 'Dragon\'s Head'],
    category: 'point',
    archetype: 'The Destiny Point / The Growing Edge',
    tagline: 'Where your soul is headed — uncomfortable, necessary, and full of potential',
    myth: `In Vedic mythology, the nodes are the severed body of the demon Rahu, who disguised himself as a god to drink the nectar of immortality. Vishnu discovered the deception and hurled his discus, severing Rahu's head from his body. But because Rahu had already swallowed the nectar, both pieces remained alive — the head (North Node/Rahu) forever hungry, consuming, reaching; the tail (South Node/Ketu) forever releasing, dissolving, letting go. The North Node is the head: it devours experience, craving growth, pulling us toward unfamiliar territory. In Western astrology, the North Node represents the soul's evolutionary direction — where we must grow, even though it feels awkward and unnatural.`,
    symbolism: [
      'The dragon\'s head — insatiable hunger for growth and new experience',
      'The eclipse point — where light is swallowed, where fate intervenes',
      'The growing edge — the direction that feels hardest but is most rewarding',
      'Dharma — the path of purpose and right action',
    ],
    psychologicalFunction: 'The North Node represents the soul\'s evolutionary direction — qualities, experiences, and ways of being that feel unfamiliar but are essential for growth in this lifetime.',
    shadowExpression: 'Avoiding growth, clinging to comfort, mistaking the unfamiliar for wrong, spiritual laziness.',
    giftExpression: 'Stepping into destiny, embracing the unfamiliar, soul growth, aligning with purpose, the courage to evolve.',
    rulesSign: ['Transits through all signs on 18.6-year cycle'],
    keywords: ['destiny', 'growth', 'dharma', 'purpose', 'evolution', 'unfamiliar', 'future', 'soul direction'],
    tarotCorrespondence: 'The Wheel of Fortune (X)',
  },
  {
    name: 'South Node',
    symbol: '☋',
    greekName: 'Cauda Draconis',
    romanName: 'Tail of the Dragon',
    otherNames: ['Ketu', 'Dragon\'s Tail'],
    category: 'point',
    archetype: 'The Past Life Gifts / The Comfort Zone',
    tagline: 'What you came in knowing — your gifts, your crutch, and what must be released',
    myth: `The South Node is the tail of the severed demon Rahu — Ketu in Vedic tradition. Where the head hungers, the tail releases. Ketu represents what has already been consumed and digested: past-life skills, karmic patterns, inherited abilities that feel effortless because they have been practiced across many lifetimes. But Ketu also represents spiritual detachment — the capacity to let go, to dissolve ego attachments, to merge with the infinite. The danger of the South Node is regression: returning to what feels comfortable rather than growing toward what the North Node demands.`,
    symbolism: [
      'The dragon\'s tail — what trails behind us, what we drag along',
      'Past lives — inherited skills and patterns from before this incarnation',
      'The comfort zone — effortless ability that can become a trap',
      'Release — what must be let go for evolution to occur',
    ],
    psychologicalFunction: 'The South Node represents inherited gifts, past-life talents, and karmic comfort zones. It shows what comes naturally but may hold us back if we cling to it.',
    shadowExpression: 'Regression, defaulting to old patterns, using past-life gifts as an excuse not to grow, spiritual stagnation.',
    giftExpression: 'Accessing deep wisdom, using inherited talents in service of growth, letting go gracefully, understanding karma without being bound by it.',
    rulesSign: ['Opposite the North Node, 18.6-year cycle'],
    keywords: ['past lives', 'karma', 'comfort zone', 'release', 'inherited gifts', 'regression', 'letting go', 'wisdom'],
    tarotCorrespondence: 'The Wheel of Fortune (X)',
  },
  {
    name: 'Part of Fortune',
    symbol: '⊕',
    greekName: 'Kleros Tuches',
    romanName: 'Pars Fortunae',
    otherNames: ['Lot of Fortune'],
    category: 'point',
    archetype: 'The Worldly Blessing / The Joy Point',
    tagline: 'Where Sun, Moon, and Ascendant align to produce your greatest ease and abundance',
    myth: `The Part of Fortune is one of the Arabic Parts (or Lots), mathematical points used since Hellenistic astrology. It is calculated from the relationship between the Sun (conscious will), Moon (emotional nature), and Ascendant (physical incarnation). When these three align harmoniously, the result is the Part of Fortune — a point of natural ease, worldly success, and physical wellbeing. Ancient astrologers considered it the most important calculated point, representing where life flows most naturally, where effort meets luck, where the body and soul are in agreement.`,
    symbolism: [
      'The three-fold integration — Sun (spirit) + Moon (soul) + Ascendant (body) in harmony',
      'The lot — fortune as something allotted, a gift from the cosmos',
      'Natural ease — where effort meets grace',
      'Physical wellbeing — the body\'s point of greatest vitality',
    ],
    psychologicalFunction: 'The Part of Fortune represents where life flows most naturally, where we find worldly success with relative ease, and where body, emotions, and will are integrated.',
    shadowExpression: 'Taking gifts for granted, laziness in areas of natural ease, expecting luck without effort, materialism.',
    giftExpression: 'Natural abundance, physical vitality, integration of will and instinct, areas where life supports your efforts.',
    rulesSign: ['Calculated from Sun, Moon, and Ascendant'],
    keywords: ['fortune', 'luck', 'ease', 'abundance', 'integration', 'vitality', 'worldly success', 'flow'],
  },
  {
    name: 'Vertex',
    symbol: 'Vx',
    greekName: 'N/A',
    romanName: 'N/A',
    otherNames: ['The Electric Axis', 'The Fated Point'],
    category: 'point',
    archetype: 'The Destiny Gate / The Fated Encounter',
    tagline: 'The point where fate walks in the door — encounters you didn\'t seek but were meant to have',
    myth: `The Vertex has no ancient mythology because it is a modern mathematical point — the intersection of the ecliptic and the prime vertical in the western hemisphere of the chart. But its experiential mythology is vivid: the Vertex marks fated encounters, people and events that arrive uninvited and change the course of your life. It is the point of "meant to be" — not the destiny you consciously pursue (that's the North Node), but the destiny that finds you. Transits and synastry contacts to the Vertex often coincide with meetings that feel electric, inevitable, and transformative.`,
    symbolism: [
      'The intersection — where two planes of existence cross',
      'The uninvited guest — fate that arrives without being summoned',
      'The western hemisphere — what comes from outside ourselves',
      'The electric charge — the unmistakable feeling of significance',
    ],
    psychologicalFunction: 'The Vertex represents fated encounters and turning points that arrive from outside our conscious planning. It shows where destiny intervenes through people and events we didn\'t seek.',
    shadowExpression: 'Passivity, waiting for fate instead of acting, confusing every encounter with destiny, giving away agency to "meant to be."',
    giftExpression: 'Recognizing genuinely fated moments, openness to transformative encounters, trusting the intelligence of life\'s unplanned events.',
    rulesSign: ['Calculated from birth time and location'],
    keywords: ['fate', 'destiny', 'encounters', 'turning points', 'synchronicity', 'meant to be', 'uninvited', 'transformative'],
  },
  {
    name: 'Gonggong',
    symbol: '🝻',
    greekName: 'N/A',
    romanName: 'N/A',
    otherNames: ['Kung-Kung'],
    category: 'transpersonal',
    archetype: 'The Flood Bringer / The Necessary Destroyer',
    tagline: 'The chaos that rearranges the world — catastrophe as reset',
    myth: `Gonggong is a Chinese water god and cosmic troublemaker. In the most famous myth, Gonggong fought with Zhu Rong (fire god) for supremacy and lost. In his rage and shame, he smashed his head against Mount Buzhou, one of the pillars holding up the sky. The sky tilted, causing the stars to shift, rivers to change course, and floods to cover the earth. The goddess Nüwa had to melt five-colored stones to repair the sky. Gonggong's act was destructive but transformative — it literally changed the tilt of the world. The resulting floods washed away the old order and required divine intervention to establish a new one.`,
    symbolism: [
      'Smashing the cosmic pillar — actions that change the fundamental structure of reality',
      'The tilted sky — the world is literally never the same after',
      'Floods — emotional overwhelm, collective cleansing, forced surrender',
      'The five-colored stones — the repair that comes after, more beautiful than the original',
    ],
    psychologicalFunction: 'Gonggong represents catastrophic disruption that fundamentally alters the landscape — the flood that forces a complete rebuild. It shows where destruction precedes necessary transformation.',
    shadowExpression: 'Destruction from shame or rage, taking everyone down with you, refusing to accept defeat gracefully, creating chaos to avoid accountability.',
    giftExpression: 'Understanding that some structures must fall, allowing floods to cleanse, accepting that the world after catastrophe can be more beautiful.',
    rulesSign: ['Associated with Pisces/water themes'],
    keywords: ['catastrophe', 'floods', 'destruction', 'reset', 'upheaval', 'transformation', 'chaos', 'rebuild'],
  },
  {
    name: 'Salacia',
    symbol: '🝼',
    greekName: 'Amphitrite',
    romanName: 'Salacia',
    category: 'transpersonal',
    archetype: 'The Ocean Queen / The Hidden Depths',
    tagline: 'The mystery beneath the surface — what lies in the deep and refuses to be seen',
    myth: `Salacia was the Roman goddess of the sea, consort of Neptune. When Neptune pursued her, she fled and hid in the depths of the ocean. It took a dolphin to find her and persuade her to return. Unlike Neptune's chaotic, overwhelming ocean, Salacia represents the calm, hidden depths — the part of the ocean where sunlight never reaches, where strange and beautiful creatures exist unseen. She chose hiddenness. Her mythology is about what refuses to be surfaced, what is powerful precisely because it remains unseen, and the negotiation between visibility and mystery.`,
    symbolism: [
      'The ocean depths — what lies far below the surface of consciousness',
      'Hiding from Neptune — choosing mystery over merging',
      'The dolphin messenger — what finally bridges the depths and the surface',
      'The deep-sea realm — beauty and power that needs no audience',
    ],
    psychologicalFunction: 'Salacia represents the parts of ourselves that are powerful in their hiddenness — what we protect by keeping it private, and the wisdom of not exposing everything.',
    shadowExpression: 'Pathological secrecy, hiding gifts out of fear, refusing all intimacy, using mystery as a wall.',
    giftExpression: 'Sacred privacy, protecting the deep self, understanding that not everything needs to be seen, the power of mystery.',
    rulesSign: ['Associated with Pisces/hidden themes'],
    keywords: ['mystery', 'depths', 'hidden power', 'privacy', 'ocean', 'unseen', 'sacred secrecy', 'inner world'],
  },
];

export const MYTHOLOGY_CATEGORIES = {
  luminary: { label: 'Luminaries', description: 'The two great lights that anchor consciousness', icon: '☉☽' },
  personal: { label: 'Personal Planets', description: 'The inner workings of daily life', icon: '☿♀♂' },
  social: { label: 'Social Planets', description: 'Where personal meets collective', icon: '♃♄' },
  transpersonal: { label: 'Transpersonal & TNOs', description: 'Forces beyond individual control', icon: '♅♆♇' },
  centaur: { label: 'Centaurs', description: 'Bridging the known and unknown', icon: '⚷' },
  asteroid: { label: 'Asteroids & Archetypes', description: 'The feminine, soul, and desire restored', icon: '⚳Ψ♡' },
  point: { label: 'Calculated Points', description: 'Mathematical shadows with mythic weight', icon: '☊⊕' },
};

export type MythologyCategory = keyof typeof MYTHOLOGY_CATEGORIES;
