// Planet Encyclopedia — comprehensive data for all celestial bodies

export interface PlanetEncyclopediaData {
  name: string;
  symbol: string;
  nickname: string;           // "The Messenger", "The Warrior", etc.
  ruledSigns: string[];
  ruledHouses: number[];
  bodyParts: string[];
  color: string;
  crystal: string;
  day: string;
  metal: string;
  orbitInfo: string;          // key astronomical fact
  mythology: string;
  careers: string[];
  whatItRules: string[];      // key domains
  gift: string;
  shadow: string;
  teaching: string;           // deep paragraph
  howToRead: string;          // practical guide for reading this in your chart
  category: 'personal' | 'social' | 'transpersonal' | 'point' | 'asteroid';
}

export const PLANET_ENCYCLOPEDIA: PlanetEncyclopediaData[] = [
  // ═══════════════════════════════════════════
  // PERSONAL PLANETS
  // ═══════════════════════════════════════════
  {
    name: 'Sun',
    symbol: '☉',
    nickname: 'The Self',
    ruledSigns: ['Leo'],
    ruledHouses: [5],
    bodyParts: ['Heart', 'Spine', 'Eyes', 'Vitality'],
    color: 'Gold / Orange',
    crystal: 'Citrine, Amber, Tiger\'s Eye',
    day: 'Sunday',
    metal: 'Gold',
    orbitInfo: 'The Sun is the center of the solar system. It takes Earth one year to orbit it, so the Sun moves through all 12 signs in 12 months — spending about 30 days in each sign. Your Sun sign is the sign the Sun was in at your birth.',
    mythology: 'Apollo (Greek) / Sol (Roman) — the god of light, truth, prophecy, healing, and music. The Sun illuminates everything it touches. In your chart, it represents the essential truth of who you are becoming.',
    careers: ['CEO', 'Performer', 'Leader', 'Actor', 'Director', 'Cardiologist', 'Gold trader', 'Any role where you are SEEN'],
    whatItRules: ['Identity', 'Ego', 'Vitality', 'Life purpose', 'Father / Authority figures', 'Willpower', 'Creativity', 'Self-expression'],
    gift: 'Radiance, leadership, creative power, the ability to shine and inspire others',
    shadow: 'Ego inflation, narcissism, need for constant validation, domineering behavior, burning others with too much intensity',
    teaching: 'Your Sun sign is NOT who you are — it\'s who you\'re BECOMING. It\'s the identity you\'re building through lived experience. A 20-year-old and a 50-year-old with the same Sun sign express it completely differently because the Sun is a process, not a fixed trait. Your Sun\'s house shows WHERE you\'re building this identity. Its aspects show WHAT helps or challenges the process. If you don\'t feel like your Sun sign, you may be living more through your Moon or Rising — which is common, especially in Night Charts where the Moon runs the show.',
    howToRead: 'Look at your Sun\'s sign (HOW you express identity), house (WHERE identity unfolds), and aspects (what supports or challenges your self-expression). The Sun\'s condition — dignified in Leo, exalted in Aries, in detriment in Aquarius, in fall in Libra — tells you how easily this identity-building process comes to you.',
    category: 'personal',
  },
  {
    name: 'Moon',
    symbol: '☽',
    nickname: 'The Emotional Body',
    ruledSigns: ['Cancer'],
    ruledHouses: [4],
    bodyParts: ['Stomach', 'Breasts', 'Uterus', 'Bodily fluids', 'Lymph system'],
    color: 'Silver / White / Pearl',
    crystal: 'Moonstone, Pearl, Selenite',
    day: 'Monday',
    metal: 'Silver',
    orbitInfo: 'The fastest-moving body in astrology — the Moon changes signs every 2.5 days and completes a full cycle through all 12 signs in about 28 days. This is why your mood shifts constantly. Your Moon sign is the sign the Moon was in at the exact moment of your birth.',
    mythology: 'Artemis/Diana (Greek/Roman) — goddess of the hunt, the wilderness, childbirth, and the moon itself. She protected the vulnerable and punished those who violated boundaries. In your chart, the Moon is your instinctual self — the one who reacts before you think.',
    careers: ['Nurse', 'Chef', 'Therapist', 'Real estate', 'Childcare', 'Hospitality', 'Marine biology', 'Historian', 'Any caregiving role'],
    whatItRules: ['Emotions', 'Instincts', 'Mother / Nurturing figures', 'Habits', 'Comfort needs', 'Memory', 'The unconscious', 'Home & family', 'The body\'s rhythms'],
    gift: 'Emotional intelligence, empathy, nurturing ability, intuition, ability to create safety for others',
    shadow: 'Moodiness, emotional manipulation, clinginess, living in the past, taking everything personally, codependency',
    teaching: 'Your Moon sign describes what you need to feel SAFE. Not happy — safe. It\'s the emotional operating system running in the background of every decision. In a Night Chart (Sun below the horizon), the Moon becomes your chart ruler — it\'s the dominant planet in your life, governing your daily patterns, relationships, and career instincts more than your Sun. Most people relate more to their Moon sign than their Sun sign in private. Your Moon\'s house shows WHERE you seek emotional security. Its aspects show what nourishes or disrupts your inner peace.',
    howToRead: 'Check your Moon\'s sign (your emotional language), house (where you seek comfort), and aspects (what feeds or starves your emotional needs). The Moon in water signs (Cancer, Scorpio, Pisces) feels everything intensely. In fire signs, emotions drive action. In earth signs, emotions need physical expression. In air signs, emotions get intellectualized first.',
    category: 'personal',
  },
  {
    name: 'Mercury',
    symbol: '☿',
    nickname: 'The Messenger',
    ruledSigns: ['Gemini', 'Virgo'],
    ruledHouses: [3, 6],
    bodyParts: ['Lungs', 'Central nervous system', 'Arms', 'Hands', 'Tongue', 'Intestines'],
    color: 'Yellow / Mixed colors',
    crystal: 'Citrine, Topaz, Agate, Fluorite',
    day: 'Wednesday',
    metal: 'Mercury (Quicksilver)',
    orbitInfo: 'The fastest planet — Mercury never travels more than 28° from the Sun, so it will ALWAYS be within one sign of your Sun sign. It orbits the Sun in just 88 days. This closeness to the Sun is why your thinking style (Mercury) is always closely related to your core identity (Sun). Mercury goes retrograde 3-4 times per year for about 3 weeks each time.',
    mythology: 'Hermes (Greek) / Mercury (Roman) — the winged messenger god who ruled over trade, travel, thieves, and communication between the worlds of gods and humans. He could move between realms — including the underworld — making him the patron of all boundary-crossers, translators, and tricksters.',
    careers: ['Writer', 'Journalist', 'Lawyer', 'Educator', 'Sales', 'Transportation', 'Postal service', 'Technology', 'Translator', 'Analyst', 'Editor', 'Programmer', 'Trader'],
    whatItRules: ['Communication', 'Thinking style', 'Learning', 'Perception', 'Reasoning', 'Analysis', 'Discrimination', 'Organization of information', 'Short travel', 'Siblings', 'Neighborhood'],
    gift: 'Mental agility, wit, communication skill, ability to connect ideas and people, versatility, quick learning',
    shadow: 'Known as the trickster — can be critical, argumentative, gossipy, scattered, superficial, anxious, and generally negative when stressed. The uncontrolled Mercury mind never stops analyzing, criticizing, and worrying.',
    teaching: 'Mercury is the planet of the rational mind and intellect — the messenger of the senses. It describes HOW you think, not WHAT you think. Look at your Mercury sign to understand how your mind naturally operates: how you process information, your style of communication, and your learning preferences. The ELEMENT of your Mercury sign describes your intellectual temperament — fire Mercury thinks in visions and hunches, earth Mercury thinks in practical steps, air Mercury thinks in abstract concepts, water Mercury thinks through feelings and impressions. Mercury\'s HOUSE is your best learning environment — where your mind comes alive. Meditation training is the best remedy for an overactive Mercury, as it tames the restless mind and deepens concentration abilities.',
    howToRead: 'Mercury\'s sign = your communication style and how you process. Mercury\'s house = where you\'re most curious and communicative. Mercury\'s aspects = what enhances or disrupts your thinking. Mercury conjunct Sun = your mind and identity are fused. Mercury in a different sign from Sun = you think differently from how you present.',
    category: 'personal',
  },
  {
    name: 'Venus',
    symbol: '♀',
    nickname: 'The Lover',
    ruledSigns: ['Taurus', 'Libra'],
    ruledHouses: [2, 7],
    bodyParts: ['Throat', 'Kidneys', 'Skin', 'Thyroid', 'Ovaries'],
    color: 'Pink / Green / Copper',
    crystal: 'Rose Quartz, Emerald, Jade',
    day: 'Friday',
    metal: 'Copper',
    orbitInfo: 'Venus never travels more than 48° from the Sun. It orbits in 225 days. As a Morning Star (rising before the Sun), Venus is bold and direct in love. As an Evening Star (setting after the Sun), Venus is receptive and magnetic. Venus traces a perfect five-pointed star (pentagram) in the sky over 8 years — the Venus Star Point.',
    mythology: 'Aphrodite (Greek) / Venus (Roman) — goddess of love, beauty, pleasure, and fertility. She was born from sea foam, irresistible to gods and mortals alike. But Aphrodite was not passive — she chose her lovers, started wars, and demanded beauty as a standard.',
    careers: ['Artist', 'Designer', 'Musician', 'Fashion', 'Beauty industry', 'Diplomacy', 'Mediation', 'Luxury goods', 'Florist', 'Interior design', 'Matchmaker', 'Financial advisor'],
    whatItRules: ['Love', 'Attraction', 'Beauty', 'Values', 'Money', 'Pleasure', 'Aesthetics', 'Relationships', 'Harmony', 'Art', 'What you find beautiful', 'Self-worth'],
    gift: 'Ability to attract, create beauty, love deeply, appreciate pleasure, bring people together, value things rightly',
    shadow: 'Vanity, materialism, laziness, people-pleasing, codependency, jealousy, using charm to manipulate, equating love with possession',
    teaching: 'Venus describes what you LOVE, how you LOVE, and what you VALUE. It\'s your relationship style, your aesthetic preferences, and your relationship to money and self-worth. Venus in your chart answers: What makes you feel beautiful? What do you find attractive? How do you show love? What do you spend money on? Venus sign = your love language. Venus house = where you seek beauty and connection. In Taurus, Venus expresses through the body and senses. In Libra, through partnership and aesthetics. Venus is about RECEPTIVITY — what you allow in, what you attract, what you enjoy.',
    howToRead: 'Venus sign = how you love and what you value. Venus house = where you seek pleasure and connection. Venus aspects = what eases or complicates your love life. Venus retrograde natal = you may internalize love rather than express it, or revisit past relationships for closure.',
    category: 'personal',
  },
  {
    name: 'Mars',
    symbol: '♂',
    nickname: 'The Warrior',
    ruledSigns: ['Aries', 'Scorpio (traditional)'],
    ruledHouses: [1, 8],
    bodyParts: ['Muscles', 'Adrenal glands', 'Blood', 'Head', 'Genitals'],
    color: 'Red',
    crystal: 'Garnet, Bloodstone, Red Jasper, Carnelian',
    day: 'Tuesday',
    metal: 'Iron',
    orbitInfo: 'Mars orbits the Sun in about 2 years, spending roughly 6-7 weeks in each sign. Mars retrogrades every 2 years for about 10 weeks — these are periods when your drive and assertion turn inward, and old anger or desire resurfaces.',
    mythology: 'Ares (Greek) / Mars (Roman) — god of war, aggression, and physical courage. Unlike Athena (strategic warfare), Ares was raw, visceral, and sometimes reckless. In your chart, Mars is your survival instinct — the part of you that fights, competes, desires, and takes action.',
    careers: ['Athlete', 'Surgeon', 'Military', 'Firefighter', 'Engineer', 'Butcher', 'Mechanic', 'Entrepreneur', 'Martial arts instructor', 'Competitive sports', 'Emergency medicine'],
    whatItRules: ['Action', 'Drive', 'Anger', 'Sexual energy', 'Ambition', 'Competition', 'Physical vitality', 'Courage', 'How you fight', 'What you pursue', 'Survival instinct'],
    gift: 'Raw energy, courage, ability to act decisively, sexual magnetism, competitive drive, physical vitality, ability to protect',
    shadow: 'Aggression, violence, impulsivity, rage, recklessness, sexual compulsion, bullying, inability to rest, burning out',
    teaching: 'Mars describes HOW you go after what you want. It\'s your action style, your anger style, and your sexual expression. Mars sign = how you assert yourself. In fire signs, Mars is explosive and direct. In earth signs, Mars is patient and persistent. In air signs, Mars fights with words and ideas. In water signs, Mars operates through emotional force and sometimes passive aggression. Mars house = where you invest the most energy and where conflicts arise. A well-integrated Mars gives you healthy boundaries, the ability to say no, and the courage to pursue what you desire. An unconscious Mars acts out through rage, accidents, or attracting aggressive people.',
    howToRead: 'Mars sign = your assertive and sexual style. Mars house = where you fight, compete, and spend energy. Mars aspects = what fuels or frustrates your drive. Mars-Venus aspects describe the interplay between desire and attraction in relationships.',
    category: 'personal',
  },

  // ═══════════════════════════════════════════
  // SOCIAL PLANETS
  // ═══════════════════════════════════════════
  {
    name: 'Jupiter',
    symbol: '♃',
    nickname: 'The Teacher',
    ruledSigns: ['Sagittarius', 'Pisces (traditional)'],
    ruledHouses: [9, 12],
    bodyParts: ['Liver', 'Hips', 'Thighs', 'Pituitary gland', 'Fat tissue'],
    color: 'Purple / Royal Blue',
    crystal: 'Amethyst, Lapis Lazuli, Turquoise',
    day: 'Thursday',
    metal: 'Tin',
    orbitInfo: 'Jupiter takes 12 years to orbit the Sun, spending about 1 year in each sign. Your Jupiter Return (age ~12, 24, 36, 48, 60) marks major expansion cycles. Jupiter is the largest planet — its gravity shields Earth from asteroids, a cosmic protector.',
    mythology: 'Zeus (Greek) / Jupiter (Roman) — king of the gods, ruler of the sky, thunder, law, and justice. Zeus was expansive, generous, philandering, and excessive. In your chart, Jupiter shows where blessings come easily — and where you may overdo it.',
    careers: ['Professor', 'Judge', 'Clergy', 'Publisher', 'Travel guide', 'Philosopher', 'International business', 'Philanthropist', 'Advertising', 'Coach', 'Motivational speaker'],
    whatItRules: ['Expansion', 'Luck', 'Growth', 'Wisdom', 'Philosophy', 'Religion', 'Higher education', 'Foreign travel', 'Abundance', 'Optimism', 'Faith', 'Generosity'],
    gift: 'Natural optimism, faith, ability to see the big picture, generosity, luck, wisdom, ability to find meaning in everything',
    shadow: 'Excess, overindulgence, arrogance, self-righteousness, blind optimism, overpromising, wastefulness, entitlement',
    teaching: 'Jupiter shows where life gives you MORE — more opportunity, more abundance, more growth. But "more" isn\'t always better. Jupiter\'s sign shows HOW you grow: in fire signs, through bold action; in earth signs, through practical expansion; in air signs, through ideas and connections; in water signs, through emotional and spiritual depth. Jupiter\'s house is your area of greatest natural abundance — where things come relatively easily. The danger is taking this area for granted or expanding beyond sustainable limits. Jupiter aspects show what amplifies in your life. Jupiter-Saturn aspects are especially important: they describe the tension between growth and structure in your biography.',
    howToRead: 'Jupiter sign = your growth style and what you have faith in. Jupiter house = where luck and abundance naturally flow. Jupiter aspects = what expands (for better or worse). Jupiter retrograde natal = your expansion is internal first — you grow through reflection before external experience.',
    category: 'social',
  },
  {
    name: 'Saturn',
    symbol: '♄',
    nickname: 'The Teacher of Hard Lessons',
    ruledSigns: ['Capricorn', 'Aquarius (traditional)'],
    ruledHouses: [10, 11],
    bodyParts: ['Bones', 'Skeleton', 'Teeth', 'Knees', 'Skin (structure)', 'Joints'],
    color: 'Black / Dark Brown / Grey',
    crystal: 'Onyx, Obsidian, Jet, Garnet',
    day: 'Saturday',
    metal: 'Lead',
    orbitInfo: 'Saturn takes 29.5 years to orbit the Sun — the Saturn Return (age ~29, 58, 87) is the most significant developmental transit in astrology. Saturn spends about 2.5 years in each sign, marking generational themes of discipline and restructuring.',
    mythology: 'Kronos (Greek) / Saturn (Roman) — the titan who devoured his own children to prevent being overthrown. Eventually, Zeus defeated him. Saturn represents TIME — the structures that hold you up and the limitations that test you. Father Time, the Grim Reaper, and the wise elder are all Saturn archetypes.',
    careers: ['CEO', 'Architect', 'Engineer', 'Government', 'Accountant', 'Dentist', 'Orthopedist', 'Farmer', 'Builder', 'Judge', 'Manager', 'Mining', 'Geology'],
    whatItRules: ['Discipline', 'Structure', 'Responsibility', 'Time', 'Authority', 'Karma', 'Boundaries', 'Maturity', 'Father/Authority', 'Limitations', 'Hard work', 'Mastery'],
    gift: 'Discipline, perseverance, earned authority, wisdom through experience, ability to build lasting structures, patience, integrity',
    shadow: 'Rigidity, fear, depression, coldness, workaholism, excessive self-criticism, pessimism, controlling behavior, emotional withholding',
    teaching: 'Saturn is not your enemy — it\'s the Beast who becomes the Prince. In the fairytale of Beauty and the Beast, the Beast must be loved for his own sake before he can transform — and this is Saturn\'s deepest secret. Where Saturn sits in your chart is where you will be tested, repeatedly, until you develop mastery. But here is the paradox that astrologer Liz Greene illuminated: Saturn has TWO faces. The "Beast" is Saturn\'s unconscious expression — fear, rigidity, control, coldness, depression, and the crushing weight of inadequacy. The "Prince" is Saturn\'s conscious expression — earned authority, hard-won wisdom, unshakeable integrity, and the deep self-respect that comes only from having faced your worst fears. Saturn\'s house is your area of greatest insecurity AND greatest eventual authority. Early in life (before age 29), Saturn feels like restriction. After the first Saturn Return, Saturn becomes your source of hard-won confidence. The level of consciousness with which you approach your Saturn is NOT fixed — it is always possible to transform lead into gold.',
    howToRead: 'Saturn sign = your fear style and discipline style. Saturn house = where life demands maturity and where you\'ll eventually become an authority (look for the Beast/Prince duality here). Saturn aspects = what you must earn (nothing is free with Saturn). Saturn Return (age 29, 58) = major life restructuring. Ask: "Where am I the Beast? Where am I becoming the Prince?"',
    category: 'social',
  },

  // ═══════════════════════════════════════════
  // TRANSPERSONAL / OUTER PLANETS
  // ═══════════════════════════════════════════
  {
    name: 'Uranus',
    symbol: '♅',
    nickname: 'The Awakener',
    ruledSigns: ['Aquarius'],
    ruledHouses: [11],
    bodyParts: ['Nervous system (electrical)', 'Ankles', 'Circulatory system', 'Pineal gland'],
    color: 'Electric Blue / Neon',
    crystal: 'Labradorite, Aquamarine, Clear Quartz',
    day: 'No traditional day',
    metal: 'Uranium / Platinum',
    orbitInfo: 'Uranus takes 84 years to orbit the Sun, spending about 7 years in each sign. It was discovered in 1781 during the American and French Revolutions — its energy is revolutionary. The Uranus opposition (age ~42) is the classic "midlife crisis" transit.',
    mythology: 'Ouranos (Greek) — the primordial sky god who was overthrown by his son Kronos (Saturn). Uranus represents the force that shatters old structures to make way for new ones. It\'s the lightning bolt, the sudden insight, the revolution.',
    careers: ['Inventor', 'Programmer', 'Astrologer', 'Electrician', 'Activist', 'Scientist', 'Aerospace', 'Futurist', 'Disruptor', 'Social media pioneer', 'Technologist'],
    whatItRules: ['Revolution', 'Rebellion', 'Innovation', 'Freedom', 'Sudden change', 'Technology', 'Individuality', 'The unconventional', 'Genius', 'Awakening', 'The future'],
    gift: 'Originality, genius, ability to see the future, freedom from convention, innovative thinking, humanitarian vision',
    shadow: 'Emotional detachment, erratic behavior, rebellion for rebellion\'s sake, instability, alienation, inability to commit, anxiety',
    teaching: 'Uranus in your chart shows where you REFUSE to conform — and where life periodically disrupts your comfort zone through sudden, unexpected events. Uranus transits feel like earthquakes: terrifying in the moment, liberating afterward. Uranus house = where you\'re most unconventional and where sudden changes occur. Uranus aspects = what gets electrified or disrupted. Because Uranus spends 7 years in each sign, your Uranus sign is generational — it describes how YOUR generation rebels and innovates. The house placement makes it personal.',
    howToRead: 'Uranus sign = generational rebellion style. Uranus house = where you need freedom and where surprises happen. Uranus aspects to personal planets = where your life is most unpredictable and original.',
    category: 'transpersonal',
  },
  {
    name: 'Neptune',
    symbol: '♆',
    nickname: 'The Mystic',
    ruledSigns: ['Pisces'],
    ruledHouses: [12],
    bodyParts: ['Pineal gland', 'Feet', 'Lymphatic system', 'Immune system'],
    color: 'Sea Green / Iridescent / Lavender',
    crystal: 'Amethyst, Opal, Aquamarine, Lepidolite',
    day: 'No traditional day',
    metal: 'Neptunium / Platinum',
    orbitInfo: 'Neptune takes 165 years to orbit the Sun, spending about 14 years in each sign. It was discovered in 1846, coinciding with the rise of photography, anesthesia, and spiritualism — all Neptune themes of illusion, altered states, and unseen realities.',
    mythology: 'Poseidon (Greek) / Neptune (Roman) — god of the sea, earthquakes, and horses. The ocean is Neptune\'s domain: boundless, mysterious, creative, and dangerous. You can float in it or drown in it.',
    careers: ['Artist', 'Musician', 'Filmmaker', 'Spiritual healer', 'Psychic', 'Photographer', 'Pharmacist', 'Addiction counselor', 'Poet', 'Nurse', 'Dancer', 'Marine biologist'],
    whatItRules: ['Spirituality', 'Imagination', 'Dreams', 'Illusion', 'Compassion', 'Addiction', 'Transcendence', 'Music & film', 'Escapism', 'The unconscious', 'Mysticism', 'Sacrifice'],
    gift: 'Artistic genius, spiritual connection, compassion, imagination, ability to transcend ordinary reality, healing through art and love',
    shadow: 'Escapism, addiction, delusion, martyrdom, deception, victim consciousness, inability to face reality, boundary dissolution',
    teaching: 'Neptune dissolves whatever it touches. In your chart, Neptune\'s house is where boundaries blur — where you experience both transcendence and confusion. Neptune sign is generational (14 years per sign). Neptune aspects to personal planets are where you experience: artistic inspiration OR delusion, spiritual awakening OR escapism, compassion OR martyrdom. Neptune is the most difficult planet to work with consciously because its nature is UNCONSCIOUS. The key to Neptune is developing a container for it — art, meditation, service — so the dissolving energy creates beauty instead of chaos.',
    howToRead: 'Neptune sign = generational spiritual/creative trend. Neptune house = where you\'re most idealistic, creative, AND confused. Neptune aspects = where you experience inspiration/delusion. Hard Neptune aspects to Sun/Moon = identity/emotional boundaries need conscious work.',
    category: 'transpersonal',
  },
  {
    name: 'Pluto',
    symbol: '♇',
    nickname: 'The Transformer',
    ruledSigns: ['Scorpio'],
    ruledHouses: [8],
    bodyParts: ['Reproductive organs', 'Colon', 'Elimination systems', 'DNA', 'Cellular regeneration'],
    color: 'Black / Deep Red / Maroon',
    crystal: 'Obsidian, Smoky Quartz, Black Tourmaline, Malachite',
    day: 'No traditional day (Tuesday by Scorpio association)',
    metal: 'Plutonium',
    orbitInfo: 'Pluto takes 248 years to orbit the Sun, spending 12-31 years in each sign (due to its elliptical orbit). It was discovered in 1930 during the rise of nuclear power, psychoanalysis, and totalitarian regimes — all Pluto themes of hidden power and transformation.',
    mythology: 'Hades (Greek) / Pluto (Roman) — god of the underworld, death, and hidden wealth. Pluto doesn\'t destroy — it composts. What dies under Pluto transits feeds what\'s trying to grow. Pluto is the phoenix cycle: death, descent, transformation, rebirth.',
    careers: ['Psychologist', 'Surgeon', 'Detective', 'Researcher', 'Occultist', 'Crisis manager', 'Oncologist', 'Forensics', 'Mortician', 'Mining', 'Wealth management', 'Investigative journalist'],
    whatItRules: ['Transformation', 'Power', 'Death & rebirth', 'The unconscious', 'Obsession', 'Control', 'Taboos', 'Hidden wealth', 'Psychology', 'Sexuality', 'Survival', 'Evolution'],
    gift: 'Psychological depth, ability to transform and regenerate, empowerment, ability to see through facades, resilience, healing through crisis',
    shadow: 'Manipulation, power abuse, obsession, destructiveness, paranoia, control, vengefulness, inability to let go',
    teaching: 'Pluto in your chart shows where you will be fundamentally transformed — often through experiences you didn\'t choose. Pluto\'s house is your area of deepest power AND deepest vulnerability. It\'s where you may have experienced trauma, and where you develop the most profound wisdom. Pluto aspects to personal planets intensify everything — these are the aspects of psychological depth, compulsive patterns, and ultimate transformation. Working with Pluto means learning to let go of control while reclaiming your power. Pluto transits are the most intense in astrology — they dismantle what\'s inauthentic so the real you can emerge.',
    howToRead: 'Pluto sign = generational transformation theme. Pluto house = where you\'re most powerful, most vulnerable, and most transformed. Pluto aspects = what gets intensified to the extreme. Pluto conjunct or square personal planets = major life themes of power, transformation, and psychological depth.',
    category: 'transpersonal',
  },

  // ═══════════════════════════════════════════
  // POINTS & SPECIAL BODIES
  // ═══════════════════════════════════════════
  {
    name: 'Chiron',
    symbol: '⚷',
    nickname: 'The Wounded Healer',
    ruledSigns: ['Virgo (some say)', 'Sagittarius (some say)'],
    ruledHouses: [6, 9],
    bodyParts: ['Wherever chronic pain or sensitivity manifests', 'Immune system', 'Psychosomatic symptoms'],
    color: 'Teal / Deep Green',
    crystal: 'Chrysocolla, Turquoise, Malachite',
    day: 'No traditional day',
    metal: 'No traditional metal',
    orbitInfo: 'Chiron orbits between Saturn and Uranus, taking about 50-51 years to complete a cycle. The Chiron Return at age 50-51 is a profound healing crisis and wisdom integration. Chiron was discovered in 1977, during the rise of holistic medicine, trauma therapy, and alternative healing.',
    mythology: 'Chiron was the wisest centaur in Greek mythology — a healer, teacher, and mentor to heroes (Achilles, Hercules, Jason). He was accidentally wounded by a poisoned arrow and, being immortal, could not die from it. He lived with chronic pain, using it as the source of his healing wisdom. Eventually, he traded his immortality to free Prometheus.',
    careers: ['Therapist', 'Healer', 'Alternative medicine', 'Counselor', 'Mentor', 'Teacher of the wounded', 'Social worker', 'Trauma specialist', 'Bodyworker', 'Hospice care'],
    whatItRules: ['Core wounds', 'Healing ability', 'Teaching through experience', 'Vulnerability', 'Bridging the gap', 'Shamanic initiation', 'Where you help others but struggle yourself'],
    gift: 'The ability to heal others through your own wounding. Your deepest pain becomes your greatest gift to the world. Chiron people make the best healers, teachers, and mentors because they KNOW suffering from the inside.',
    shadow: 'Identifying with your wound so completely that you never heal. Playing the victim. Helping everyone else while neglecting your own recovery. Projecting your pain onto others.',
    teaching: 'Chiron shows where you carry a wound that never fully heals — but it does transform into wisdom. Chiron\'s sign shows the NATURE of the wound. Chiron\'s house shows WHERE it manifests. Chiron in Aries = wound around identity and the right to exist. Chiron in the 7th house = wound around partnership and being chosen. The key insight: you cannot heal this wound by avoiding it. You heal it by turning toward it, understanding it, and eventually offering what you learned to others. The wound becomes the teaching. This is the "wounded healer" archetype.',
    howToRead: 'Chiron sign = the nature of your core wound and how it expresses. Chiron house = the life area most affected. Chiron aspects = what triggers or soothes the wound. Chiron Return (age 50-51) = the integration point where wound becomes wisdom.',
    category: 'point',
  },
  {
    name: 'North Node',
    symbol: '☊',
    nickname: 'The Soul\'s Direction',
    ruledSigns: [],
    ruledHouses: [],
    bodyParts: [],
    color: 'Indigo',
    crystal: 'Lapis Lazuli',
    day: '',
    metal: '',
    orbitInfo: 'The Lunar Nodes are not physical bodies — they are the two points where the Moon\'s orbit crosses the ecliptic (the Sun\'s apparent path). They move BACKWARD through the zodiac, taking about 18.6 years to complete a cycle. Your Nodal Return at age ~18.6, ~37, ~56 marks major destiny activations.',
    mythology: 'In Vedic astrology, the North Node is Rahu — the head of the dragon, always hungry, always seeking. Rahu represents insatiable desire for new experience. The North Node is your soul\'s growth edge — what you\'re learning to embody in this lifetime.',
    careers: [],
    whatItRules: ['Soul purpose', 'Growth direction', 'What feels unfamiliar but necessary', 'Destiny', 'Future potential', 'What you\'re learning to become'],
    gift: 'A compass pointing toward your most fulfilling life — the experiences your soul chose to master this time around',
    shadow: 'The North Node always feels uncomfortable because it\'s unfamiliar. You may avoid it your entire life, defaulting to the South Node\'s comfort instead.',
    teaching: 'The North Node is NOT what you\'re naturally good at — it\'s what you\'re learning. It feels awkward, foreign, and sometimes frightening. But every time you lean into your North Node, you feel a deep sense of rightness, as if your soul is saying "yes, this." The South Node (directly opposite) shows what you already mastered — your default mode, your comfort zone, your "been there done that" energy. Growth means moving FROM South Node patterns TOWARD North Node territory.',
    howToRead: 'North Node sign = the quality you\'re developing. North Node house = the area of life where destiny calls. South Node (opposite) = your comfort zone and past-life mastery. Eclipses near your nodes = fated turning points.',
    category: 'point',
  },
  {
    name: 'Black Moon Lilith',
    symbol: '⚸',
    nickname: 'The Wild Feminine',
    ruledSigns: [],
    ruledHouses: [],
    bodyParts: ['Reproductive system', 'Shadow body', 'Primal instincts'],
    color: 'Black / Deep Purple',
    crystal: 'Black Obsidian, Smoky Quartz, Black Moonstone',
    day: '',
    metal: '',
    orbitInfo: 'Black Moon Lilith is not a planet — it\'s the lunar apogee, the point in the Moon\'s orbit farthest from Earth. It takes about 9 years to complete a cycle. At its farthest point from Earth, the Moon\'s influence is at its most raw, untamed, and primal.',
    mythology: 'In Jewish mythology, Lilith was Adam\'s first wife who refused to be subordinate and was cast out of Eden. She represents the part of the feminine that refuses to submit — the wild, untamed, sexually sovereign, fiercely independent force that patriarchal systems tried to suppress.',
    careers: [],
    whatItRules: ['Raw feminine power', 'Sexual sovereignty', 'Rage', 'What you refuse to domesticate', 'Where you\'ve been shamed', 'The taboo', 'Rejection', 'Shadow sexuality', 'Primal instincts'],
    gift: 'Authentic power that comes from refusing to be tamed. The ability to own your desire, your darkness, and your anger without apology. Magnetic, raw, compelling energy.',
    shadow: 'Destructive rage, shame spirals, compulsive behavior around the Lilith themes, attracting persecution for being "too much," self-exile',
    teaching: 'Lilith in your chart shows where you carry primal rage and power — often around experiences of being shamed, rejected, or told you were "too much." Lilith\'s sign shows HOW this energy expresses. Lilith\'s house shows WHERE in life you refuse to conform and may have experienced rejection for it. When unconscious, Lilith acts out through destructive behavior, compulsive patterns, or chronic shame. When integrated, Lilith is your most authentic power — the part of you that says "I will not be diminished" and means it. Working with Lilith means reclaiming what you were shamed for.',
    howToRead: 'Lilith sign = the flavor of your wildness and where you\'ve been shamed. Lilith house = the life area where you refuse to conform. Lilith aspects = what triggers your primal response. Lilith conjunct personal planets = a major theme of reclaiming power.',
    category: 'point',
  },

  // ═══════════════════════════════════════════
  // GODDESS ASTEROIDS
  // ═══════════════════════════════════════════
  {
    name: 'Ceres',
    symbol: '⚳',
    nickname: 'The Great Mother',
    ruledSigns: ['Virgo (some say)', 'Cancer (some say)'],
    ruledHouses: [6, 4],
    bodyParts: ['Stomach', 'Breasts', 'Nurturing systems', 'Digestion'],
    color: 'Green / Earth tones',
    crystal: 'Green Aventurine, Moss Agate',
    day: '',
    metal: '',
    orbitInfo: 'Ceres orbits in the asteroid belt between Mars and Jupiter, taking about 4.6 years to complete a cycle. It was reclassified as a dwarf planet in 2006. Ceres is the largest body in the asteroid belt.',
    mythology: 'Demeter (Greek) / Ceres (Roman) — the goddess of grain, harvest, and motherly love. When her daughter Persephone was taken to the underworld, Demeter\'s grief caused winter. The myth is about the cycle of loss, grief, letting go, and reunion.',
    careers: ['Nutritionist', 'Farmer', 'Midwife', 'Chef', 'Childcare', 'Environmental scientist', 'Food industry', 'Gardener'],
    whatItRules: ['Nurturing style', 'Food & nourishment', 'Loss & grief', 'Mother-child bond', 'Self-care', 'What feeds you', 'The harvest cycle', 'How you care for others'],
    gift: 'Deep nurturing ability, connection to natural cycles, ability to nourish and sustain life, resilience through grief',
    shadow: 'Smothering, controlling through food/care, using nurturing as manipulation, grief that becomes identity, eating disorders',
    teaching: 'Ceres shows HOW you nurture and HOW you need to be nurtured. Its sign describes your caregiving style. Its house shows where you need to feel nourished. Ceres aspects reveal what supports or blocks your ability to give and receive care. The Ceres myth teaches that love includes letting go — and that every winter ends.',
    howToRead: 'Ceres sign = your nurturing language. Ceres house = where you give/need care most. Ceres aspects = what supports or disrupts your ability to nourish.',
    category: 'asteroid',
  },
  {
    name: 'Pallas',
    symbol: '⚴',
    nickname: 'The Strategist',
    ruledSigns: ['Aquarius (some say)', 'Libra (some say)'],
    ruledHouses: [11, 7],
    bodyParts: ['Brain (strategic thinking)', 'Eyes (pattern recognition)', 'Immune system'],
    color: 'Silver / Grey-Blue',
    crystal: 'Blue Lace Agate, Sodalite',
    day: '',
    metal: '',
    orbitInfo: 'Pallas Athena orbits in the asteroid belt, taking about 4.6 years to complete a cycle. It was the second asteroid discovered (1802).',
    mythology: 'Athena (Greek) / Minerva (Roman) — goddess of wisdom, strategy, craft, and justified warfare. Born fully armored from Zeus\'s head, Athena represents intelligence that serves justice. Unlike Ares (brute force), Athena wins through strategy and wisdom.',
    careers: ['Strategist', 'Pattern analyst', 'Politician', 'Artisan', 'Weaver/textile designer', 'Lawyer', 'Mediator', 'Data scientist', 'Game designer'],
    whatItRules: ['Strategy', 'Pattern recognition', 'Creative intelligence', 'Political skill', 'Craftsmanship', 'Wisdom in conflict', 'The father-daughter dynamic'],
    gift: 'Ability to see patterns others miss, strategic brilliance, creative problem-solving, wisdom in conflict, diplomatic genius',
    shadow: 'Over-intellectualizing emotions, being "too smart" for intimacy, using strategy to avoid vulnerability, father complex',
    teaching: 'Pallas shows your style of creative intelligence and strategic thinking. Its sign reveals HOW you problem-solve. Its house shows WHERE your strategic gifts shine. Pallas aspects indicate what enhances or blocks your ability to see the big picture. Strong Pallas people are natural pattern-recognizers — they see the chess board when others see individual pieces.',
    howToRead: 'Pallas sign = your strategy style. Pallas house = where you\'re the strategist. Pallas aspects = what enhances/blocks pattern recognition.',
    category: 'asteroid',
  },
  {
    name: 'Juno',
    symbol: '⚵',
    nickname: 'The Partner',
    ruledSigns: ['Libra', 'Scorpio'],
    ruledHouses: [7, 8],
    bodyParts: ['Reproductive system (partnership aspect)', 'Hormonal balance'],
    color: 'Rose / Magenta',
    crystal: 'Rose Quartz, Rhodonite',
    day: '',
    metal: '',
    orbitInfo: 'Juno orbits in the asteroid belt, taking about 4.4 years to complete a cycle. Discovered in 1804.',
    mythology: 'Hera (Greek) / Juno (Roman) — queen of the gods, goddess of marriage and commitment. Hera endured Zeus\'s infidelities while maintaining the institution of partnership. She represents the complex reality of committed relationships — loyalty, jealousy, power dynamics, and the need for equality.',
    careers: ['Marriage counselor', 'Divorce lawyer', 'Wedding planner', 'Couples therapist', 'Contract negotiator', 'Partnership manager'],
    whatItRules: ['Committed partnership', 'Marriage', 'Equality in relationships', 'Jealousy & loyalty', 'What you need from a partner', 'Power dynamics in love', 'Contractual agreements'],
    gift: 'Deep commitment, loyalty, ability to sustain long-term partnerships, understanding of relationship dynamics, devotion',
    shadow: 'Jealousy, possessiveness, staying in unequal partnerships, sacrificing self for the relationship, power struggles in love',
    teaching: 'Juno shows what you NEED in a committed partner — not what you\'re attracted to (that\'s Venus), but what you require for a lasting bond. Juno\'s sign describes the qualities you need in a partner. Juno\'s house shows where partnership themes dominate. Juno aspects reveal the dynamics of your committed relationships. A strong Juno placement means partnership is a central life theme — you grow most through long-term commitment.',
    howToRead: 'Juno sign = what you need in a committed partner. Juno house = where partnership is the central theme. Juno aspects = relationship dynamics and patterns.',
    category: 'asteroid',
  },
  {
    name: 'Vesta',
    symbol: '⚶',
    nickname: 'The Sacred Flame',
    ruledSigns: ['Virgo', 'Scorpio'],
    ruledHouses: [6, 8],
    bodyParts: ['Metabolic fire', 'Small intestine', 'Reproductive health (sacred)'],
    color: 'Orange-Red / Flame',
    crystal: 'Carnelian, Fire Opal',
    day: '',
    metal: '',
    orbitInfo: 'Vesta orbits in the asteroid belt, taking about 3.6 years to complete a cycle. Discovered in 1807. Vesta is the brightest asteroid — sometimes visible to the naked eye.',
    mythology: 'Hestia (Greek) / Vesta (Roman) — goddess of the hearth, home, and sacred fire. The Vestal Virgins tended the eternal flame in Rome — if it went out, Rome would fall. Vesta represents devoted focus, sacred service, and the flame you tend without recognition.',
    careers: ['Monk/nun', 'Dedicated researcher', 'Sacred arts', 'Keeper of traditions', 'Focused specialist', 'Yoga/meditation teacher', 'Shrine keeper', 'Hospice worker'],
    whatItRules: ['Devotion', 'Sacred focus', 'What you tend without recognition', 'Sexual energy as creative fire', 'The inner flame', 'Purification', 'Where you work alone', 'Sacrifice for a calling'],
    gift: 'Profound focus, devotion to a calling, ability to maintain inner fire regardless of external circumstances, sacred service',
    shadow: 'Workaholism disguised as devotion, sexual denial or shame, burnout from tending others\' flames while neglecting your own, isolation',
    teaching: 'Vesta shows what you\'re devoted to — what you tend with sacred focus. Its sign describes the nature of your devotion. Its house shows where you work with monk-like focus and where you may sacrifice personal needs for a higher purpose. Vesta can indicate sexual energy channeled into creative or spiritual work. The key: Vesta burns cleanly when the devotion is genuine, and destructively when it\'s compulsive.',
    howToRead: 'Vesta sign = the flavor of your devotion. Vesta house = where you focus with sacred intensity. Vesta aspects = what supports or depletes your inner flame.',
    category: 'asteroid',
  },
];

export const PLANET_CATEGORIES = [
  { key: 'personal', label: 'Personal Planets', description: 'Shape your individual personality, daily life, and relationships' },
  { key: 'social', label: 'Social Planets', description: 'Bridge personal and collective — growth, discipline, and social role' },
  { key: 'transpersonal', label: 'Transpersonal Planets', description: 'Generational forces — revolution, mysticism, and transformation' },
  { key: 'point', label: 'Special Points', description: 'Sensitive points carrying deep karmic and psychological significance' },
  { key: 'asteroid', label: 'Goddess Asteroids', description: 'Feminine archetypes — nurturing, strategy, partnership, and devotion' },
] as const;
