// Detailed Planet-in-Sign expressions - HOW each planet expresses through each sign

export const PLANET_IN_SIGN: Record<string, Record<string, string>> = {
  Sun: {
    Aries: 'Identity blazes with pioneering courage. You lead by instinct, act before thinking, and need to be first. Life force expresses through combat, initiative, and raw self-assertion.',
    Taurus: 'Identity roots in sensual presence and material security. You build slowly, value deeply, and resist change. Life force expresses through patience, pleasure, and steadfast determination.',
    Gemini: 'Identity sparkles through words and ideas. You adapt endlessly, communicate constantly, and need mental stimulation. Life force expresses through curiosity, duality, and intellectual exploration.',
    Cancer: 'Identity flows through emotional connection and nurturing. You protect fiercely, feel deeply, and need belonging. Life force expresses through caring, intuition, and creating sanctuary.',
    Leo: 'Identity radiates like the sun itself. You create, perform, and need to be seen and appreciated. Life force expresses through generosity, drama, and magnetic self-expression.',
    Virgo: 'Identity refines through service and analysis. You improve, discern, and need to be useful. Life force expresses through precision, humility, and devotion to craft.',
    Libra: 'Identity mirrors through relationship. You harmonize, beautify, and need partnership to feel complete. Life force expresses through diplomacy, aesthetics, and balancing opposites.',
    Scorpio: 'Identity forges through intensity and transformation. You penetrate, control, and need emotional truth. Life force expresses through power, investigation, and psychological depth.',
    Sagittarius: 'Identity expands through adventure and meaning. You explore, philosophize, and need freedom to grow. Life force expresses through optimism, truth-seeking, and boundless enthusiasm.',
    Capricorn: 'Identity crystallizes through achievement and structure. You build, endure, and need tangible accomplishment. Life force expresses through ambition, discipline, and mastering the material world.',
    Aquarius: 'Identity electrifies through innovation and independence. You rebel, envision, and need to be authentically different. Life force expresses through humanitarian ideals, genius, and breaking conventions.',
    Pisces: 'Identity dissolves into universal compassion. You merge, dream, and need transcendence. Life force expresses through imagination, spirituality, and boundless empathy.',
  },
  Moon: {
    Aries: 'Emotions ignite instantly and demand immediate action. Nurturing feels like protecting and fighting for loved ones. Comfort comes through independence and physical activity.',
    Taurus: 'Emotions settle into steady rhythms. Nurturing feels like providing comfort, food, and stability. Comfort comes through sensory pleasure, routine, and material security.',
    Gemini: 'Emotions need to be talked through and understood. Nurturing feels like teaching and engaging the mind. Comfort comes through conversation, variety, and mental stimulation.',
    Cancer: 'Emotions run oceanic and deeply intuitive. Nurturing is second nature—protective, devoted, sometimes smothering. Comfort comes through home, family, and emotional safety.',
    Leo: 'Emotions need to shine and be witnessed. Nurturing feels like celebrating and adoring. Comfort comes through creative expression, play, and being the center of someone\'s world.',
    Virgo: 'Emotions get analyzed and organized. Nurturing feels like helping and improving. Comfort comes through order, health routines, and being of service.',
    Libra: 'Emotions seek balance and harmony. Nurturing feels like creating beauty and peace. Comfort comes through partnership, aesthetics, and avoiding conflict.',
    Scorpio: 'Emotions run volcanic beneath a controlled surface. Nurturing feels like fierce protection and deep bonding. Comfort comes through intensity, intimacy, and emotional truth.',
    Sagittarius: 'Emotions need space and meaning. Nurturing feels like inspiring and giving freedom. Comfort comes through adventure, learning, and philosophical understanding.',
    Capricorn: 'Emotions are structured and controlled. Nurturing feels like providing structure and achievement. Comfort comes through accomplishment, status, and practical results.',
    Aquarius: 'Emotions are observed from a distance. Nurturing feels like respecting autonomy and ideals. Comfort comes through friendship, causes, and intellectual connection.',
    Pisces: 'Emotions are boundless and absorbing. Nurturing feels like merging and healing. Comfort comes through imagination, music, spirituality, and escape.',
  },
  Mercury: {
    Aries: 'Mind is quick, direct, and competitive. Communication cuts straight to the point. Thinks by acting, speaks before filtering, argues to win.',
    Taurus: 'Mind is methodical, practical, and grounded. Communication is deliberate and sensual. Thinks in concrete terms, speaks with weight, values common sense.',
    Gemini: 'Mind is lightning-fast and endlessly curious. Communication is witty and adaptable. Thinks in connections, speaks in streams, learns by sampling everything.',
    Cancer: 'Mind is intuitive and memory-oriented. Communication carries emotional undertones. Thinks through feelings, speaks from the heart, remembers everything.',
    Leo: 'Mind is creative and confident. Communication is dramatic and warm. Thinks in big pictures, speaks with authority, persuades through charisma.',
    Virgo: 'Mind is analytical and precise. Communication is detailed and helpful. Thinks systematically, speaks carefully, excels at criticism and improvement.',
    Libra: 'Mind weighs all sides before deciding. Communication is diplomatic and aesthetic. Thinks in relationships, speaks pleasingly, avoids harsh statements.',
    Scorpio: 'Mind penetrates to hidden truths. Communication is probing and strategic. Thinks psychologically, speaks with intent, keeps secrets well.',
    Sagittarius: 'Mind sees the big picture and meaning. Communication is enthusiastic and philosophical. Thinks expansively, speaks bluntly, inspires through vision.',
    Capricorn: 'Mind is structured and goal-oriented. Communication is authoritative and practical. Thinks strategically, speaks with purpose, values useful knowledge.',
    Aquarius: 'Mind is innovative and unconventional. Communication is progressive and detached. Thinks futuristically, speaks originally, values intellectual freedom.',
    Pisces: 'Mind is imaginative and impressionistic. Communication is poetic and intuitive. Thinks in images and feelings, speaks symbolically, absorbs information psychically.',
  },
  Venus: {
    Aries: 'Loves through pursuit and conquest. Values independence and directness. Attracted to confidence, passion, and those who can match your fire. Love feels like a thrilling chase.',
    Taurus: 'Loves through devotion and sensuality. Values beauty, comfort, and loyalty. Attracted to stability, physical presence, and quality. Love feels like warm contentment.',
    Gemini: 'Loves through conversation and curiosity. Values wit, variety, and mental connection. Attracted to intelligence, humor, and versatility. Love feels like fascinating exchange.',
    Cancer: 'Loves through nurturing and protection. Values emotional safety and devotion. Attracted to sensitivity, family orientation, and emotional depth. Love feels like coming home.',
    Leo: 'Loves through adoration and grand gestures. Values loyalty, romance, and appreciation. Attracted to confidence, creativity, and those who make you shine. Love feels like celebration.',
    Virgo: 'Loves through service and attention to detail. Values competence, health, and improvement. Attracted to intelligence, humility, and those you can help. Love feels like devotion.',
    Libra: 'Loves through partnership and harmony. Values beauty, balance, and fairness. Attracted to grace, culture, and romantic ideals. Love feels like completion.',
    Scorpio: 'Loves through intensity and transformation. Values depth, loyalty, and emotional truth. Attracted to power, mystery, and those who can match your intensity. Love feels like merging.',
    Sagittarius: 'Loves through adventure and expansion. Values freedom, honesty, and growth. Attracted to wisdom, humor, and fellow travelers. Love feels like endless possibility.',
    Capricorn: 'Loves through commitment and building together. Values achievement, maturity, and reliability. Attracted to ambition, status, and those who age well. Love feels like investment.',
    Aquarius: 'Loves through friendship and intellectual connection. Values independence, uniqueness, and ideals. Attracted to originality, humanitarianism, and unconventional souls. Love feels like liberation.',
    Pisces: 'Loves through merging and transcendence. Values compassion, creativity, and spiritual connection. Attracted to artists, healers, and dreamers. Love feels like dissolving into oneness.',
  },
  Mars: {
    Aries: 'Acts with instinctive courage and competitive fire. Fights for independence and the thrill of victory. Anger is explosive but brief. Drive is direct and unstoppable.',
    Taurus: 'Acts with patient determination and sensual drive. Fights for security and what you possess. Anger builds slowly but erupts powerfully. Drive is steady and enduring.',
    Gemini: 'Acts through words, ideas, and versatility. Fights with wit and mental agility. Anger expresses through sharp words. Drive scatters across multiple interests.',
    Cancer: 'Acts to protect and nurture. Fights for family and emotional security. Anger is defensive and moody. Drive flows with emotional tides.',
    Leo: 'Acts with dramatic confidence and creative fire. Fights for recognition and pride. Anger is proud and commanding. Drive needs audience and appreciation.',
    Virgo: 'Acts with precise efficiency and critical analysis. Fights for improvement and perfection. Anger is critical and anxious. Drive channels into work and service.',
    Libra: 'Acts through diplomacy and partnership. Fights for justice and balance. Anger is passive-aggressive and aestheticized. Drive needs a partner or cause.',
    Scorpio: 'Acts with strategic intensity and psychological power. Fights for control and truth. Anger is volcanic and vengeful. Drive is obsessive and transformative.',
    Sagittarius: 'Acts with enthusiastic expansion and bold risk. Fights for truth and freedom. Anger is righteous and quickly forgotten. Drive needs meaning and adventure.',
    Capricorn: 'Acts with disciplined ambition and strategic patience. Fights for achievement and authority. Anger is cold and controlled. Drive is relentless and goal-oriented.',
    Aquarius: 'Acts for revolution and humanitarian causes. Fights for independence and ideals. Anger is detached and rebellious. Drive needs a cause larger than self.',
    Pisces: 'Acts through inspiration and compassion. Fights for the underdog and spiritual ideals. Anger is confused and escapist. Drive flows with imagination and empathy.',
  },
  Jupiter: {
    Aries: 'Expands through bold initiative and pioneering action. Luck comes through courage, leadership, and being first. Growth happens by taking risks and trusting instincts.',
    Taurus: 'Expands through patient accumulation and sensual appreciation. Luck comes through material values and steadfast effort. Growth happens by building wealth and enjoying abundance.',
    Gemini: 'Expands through learning, communication, and variety. Luck comes through connections, curiosity, and versatility. Growth happens by gathering information and making links.',
    Cancer: 'Expands through nurturing and emotional generosity. Luck comes through family, intuition, and home. Growth happens by caring for others and building security.',
    Leo: 'Expands through creative self-expression and generous leadership. Luck comes through confidence, creativity, and heart. Growth happens by inspiring others and shining brightly.',
    Virgo: 'Expands through service, improvement, and practical skills. Luck comes through attention to detail and being useful. Growth happens by refining techniques and serving others.',
    Libra: 'Expands through partnership and diplomatic grace. Luck comes through relationships, beauty, and fairness. Growth happens by collaborating and creating harmony.',
    Scorpio: 'Expands through transformation and psychological depth. Luck comes through crisis, investigation, and shared resources. Growth happens by facing shadows and regenerating.',
    Sagittarius: 'Expands through philosophy, adventure, and truth-seeking. Luck comes through travel, higher education, and faith. Growth happens by following your vision and staying optimistic.',
    Capricorn: 'Expands through discipline, achievement, and social position. Luck comes through hard work, patience, and authority. Growth happens by mastering the system and building structures.',
    Aquarius: 'Expands through innovation, groups, and humanitarian vision. Luck comes through friends, technology, and progressive ideals. Growth happens by embracing the unconventional.',
    Pisces: 'Expands through compassion, imagination, and spiritual faith. Luck comes through surrender, intuition, and artistic vision. Growth happens by dissolving boundaries and trusting the universe.',
  },
  Saturn: {
    Aries: 'Learns through restraining impulse and developing patience with initiative. Challenges around identity, leadership, and independence. Mastery comes through disciplined courage.',
    Taurus: 'Learns through developing true values and earning security. Challenges around money, possessions, and self-worth. Mastery comes through patient accumulation.',
    Gemini: 'Learns through focused thinking and disciplined communication. Challenges around learning, speaking, and mental focus. Mastery comes through structured knowledge.',
    Cancer: 'Learns through emotional maturity and family responsibilities. Challenges around nurturing, home, and vulnerability. Mastery comes through building inner security.',
    Leo: 'Learns through humble self-expression and earned recognition. Challenges around ego, creativity, and being seen. Mastery comes through authentic leadership.',
    Virgo: 'Learns through perfecting service and health disciplines. Challenges around criticism, work, and perfectionism. Mastery comes through practical excellence.',
    Libra: 'Learns through committed partnership and fair judgment. Challenges around relationships, balance, and decisions. Mastery comes through mature relating.',
    Scorpio: 'Learns through controlled transformation and facing shadows. Challenges around power, trust, and intimacy. Mastery comes through psychological depth.',
    Sagittarius: 'Learns through grounded wisdom and tested beliefs. Challenges around truth, freedom, and philosophy. Mastery comes through earned knowledge.',
    Capricorn: 'Learns through ultimate discipline and authentic authority. Challenges around ambition, responsibility, and limitation. Mastery comes through becoming the master.',
    Aquarius: 'Learns through structured innovation and responsible freedom. Challenges around individuality, groups, and ideals. Mastery comes through sustainable revolution.',
    Pisces: 'Learns through disciplined spirituality and grounded compassion. Challenges around boundaries, escape, and sacrifice. Mastery comes through structured transcendence.',
  },
  Uranus: {
    Aries: 'Revolutionizes through radical self-expression and pioneering innovation. Awakens through sudden identity shifts and courageous breaks from the past.',
    Taurus: 'Revolutionizes through transforming values and material structures. Awakens through unexpected financial or physical changes. Disrupts comfort for liberation.',
    Gemini: 'Revolutionizes through radical ideas and communication breakthroughs. Awakens through sudden insights and unconventional thinking. Disrupts normal mental patterns.',
    Cancer: 'Revolutionizes through transforming home and emotional patterns. Awakens through family upheaval and breaking ancestral patterns. Disrupts for emotional freedom.',
    Leo: 'Revolutionizes through creative genius and radical self-expression. Awakens through sudden creative downloads and unexpected recognition. Disrupts for authentic expression.',
    Virgo: 'Revolutionizes through transforming work and health systems. Awakens through innovative techniques and service breakthroughs. Disrupts for practical improvement.',
    Libra: 'Revolutionizes through unconventional relationships and social change. Awakens through sudden partnerships or separations. Disrupts for relational freedom.',
    Scorpio: 'Revolutionizes through psychological breakthroughs and power transformations. Awakens through sudden crises that liberate. Disrupts for deeper truth.',
    Sagittarius: 'Revolutionizes through radical beliefs and philosophical breakthroughs. Awakens through sudden expansion and truth revelations. Disrupts for ultimate freedom.',
    Capricorn: 'Revolutionizes through transforming structures and authority systems. Awakens through career upheaval and institutional change. Disrupts for authentic achievement.',
    Aquarius: 'Revolutionizes through pure innovation and humanitarian awakening. Awakens through sudden group connections and technological breakthroughs. In its home sign—most electric.',
    Pisces: 'Revolutionizes through spiritual awakening and dissolving old realities. Awakens through mystical experiences and collective healing. Disrupts for transcendence.',
  },
  Neptune: {
    Aries: 'Spiritualizes the warrior, dreams of heroic action. Can confuse identity or inspire divine courage. The mystic pioneer dissolving ego through bold faith.',
    Taurus: 'Spiritualizes material values, dreams of earthly paradise. Can confuse finances or inspire sacred beauty. The mystic gardener finding divinity in nature.',
    Gemini: 'Spiritualizes communication, dreams in poetry and symbolism. Can confuse thinking or inspire channeled wisdom. The mystic messenger speaking from beyond.',
    Cancer: 'Spiritualizes home and family, dreams of perfect sanctuary. Can confuse boundaries or inspire healing nurturing. The mystic mother dissolving into devotion.',
    Leo: 'Spiritualizes creativity, dreams of divine performance. Can confuse ego or inspire sacred art. The mystic creator channeling beauty from beyond.',
    Virgo: 'Spiritualizes service, dreams of perfect healing. Can confuse health or inspire sacred work. The mystic healer serving the divine in daily life.',
    Libra: 'Spiritualizes relationship, dreams of ideal partnership. Can confuse love or inspire soul-level connection. The mystic lover seeking divine in the other.',
    Scorpio: 'Spiritualizes transformation, dreams of death and rebirth. Can confuse power or inspire shamanic healing. The mystic transformer diving into collective depths.',
    Sagittarius: 'Spiritualizes meaning, dreams of ultimate truth. Can confuse beliefs or inspire prophetic vision. The mystic seeker traveling toward God.',
    Capricorn: 'Spiritualizes achievement, dreams of meaningful structures. Can confuse ambition or inspire sacred purpose. The mystic builder creating temples.',
    Aquarius: 'Spiritualizes humanity, dreams of collective awakening. Can confuse ideals or inspire visionary technology. The mystic revolutionary serving the future.',
    Pisces: 'Spiritualizes everything, dreams as the ocean of being. In its home sign—the mystic dissolving back into source. Pure compassion and transcendence.',
  },
  Pluto: {
    Aries: 'Transforms through will and survival instinct. Power expressed through pioneering force. Death and rebirth around identity, independence, and raw courage.',
    Taurus: 'Transforms through material crisis and value reconstruction. Power expressed through wealth and resources. Death and rebirth around security and self-worth.',
    Gemini: 'Transforms through mental intensity and communication power. Power expressed through information and influence. Death and rebirth around thinking and perception.',
    Cancer: 'Transforms through emotional depth and family dynamics. Power expressed through nurturing and protection. Death and rebirth around home, roots, and vulnerability.',
    Leo: 'Transforms through creative power and ego death. Power expressed through magnetic charisma. Death and rebirth around self-expression and recognition.',
    Virgo: 'Transforms through crisis in work and health. Power expressed through service and precision. Death and rebirth around perfectionism and usefulness.',
    Libra: 'Transforms through relationship intensity and power dynamics. Power expressed through partnership and justice. Death and rebirth around balance and relating.',
    Scorpio: 'Transforms in its most primal expression. Power is raw, magnetic, and regenerative. Death and rebirth as way of life. The phoenix rising.',
    Sagittarius: 'Transforms through belief crisis and truth discovery. Power expressed through conviction and vision. Death and rebirth around meaning and philosophy.',
    Capricorn: 'Transforms through authority crisis and structural breakdown. Power expressed through achievement and control. Death and rebirth around ambition and responsibility.',
    Aquarius: 'Transforms through revolution and collective upheaval. Power expressed through innovation and humanitarian force. Death and rebirth around ideals, technology, and group consciousness. The current transit (2024-2044) transforms society itself.',
    Pisces: 'Transforms through spiritual crisis and ego dissolution. Power expressed through surrender and compassion. Death and rebirth around boundaries, spirituality, and collective unconscious.',
  },
};

// Get detailed planet-in-sign expression
export const getPlanetInSignExpression = (planet: string, sign: string): string => {
  const normalizedPlanet = planet.charAt(0).toUpperCase() + planet.slice(1).toLowerCase();
  if (PLANET_IN_SIGN[normalizedPlanet]?.[sign]) {
    return PLANET_IN_SIGN[normalizedPlanet][sign];
  }
  
  // Generate meaningful fallback instead of vague generic phrase
  const signBehaviors: Record<string, string> = {
    'Aries': 'acts with bold initiative and pioneering courage—quick to start, impatient with delays, needs independence.',
    'Taurus': 'moves with patient determination and sensual groundedness—slow but unstoppable, values stability and pleasure.',
    'Gemini': 'operates through curiosity and communication—mentally agile, versatile, needs variety and mental stimulation.',
    'Cancer': 'functions through emotional depth and protective instinct—nurturing, security-seeking, deeply intuitive.',
    'Leo': 'expresses with dramatic confidence and creative flair—needs recognition, generous, heart-centered.',
    'Virgo': 'works through careful analysis and practical service—detail-oriented, helpful, improvement-focused.',
    'Libra': 'operates through balance and partnership—diplomatic, aesthetic, relationship-oriented.',
    'Scorpio': 'functions with intense focus and transformative power—penetrating, strategic, all-or-nothing.',
    'Sagittarius': 'moves through adventure and meaning-seeking—optimistic, philosophical, freedom-loving.',
    'Capricorn': 'operates with disciplined ambition and strategic patience—goal-oriented, responsible, mastery-focused.',
    'Aquarius': 'functions through innovation and humanitarian vision—unconventional, future-oriented, group-conscious.',
    'Pisces': 'moves with compassionate sensitivity and spiritual openness—imaginative, empathic, boundary-dissolving.'
  };
  return `${normalizedPlanet} in ${sign} ${signBehaviors[sign] || 'takes on this sign\'s qualities in its expression.'}`;
};
