/**
 * Planetary Mythology & Archetypes Encyclopedia
 * 
 * A comprehensive teaching reference covering the mythological origins,
 * archetypal patterns, and symbolic meanings of celestial bodies used
 * in astrological practice.
 */

export interface MythologyEntry {
  name: string;
  symbol: string;
  greekName: string;
  romanName: string;
  otherNames?: string[];
  category: 'luminary' | 'personal' | 'social' | 'transpersonal' | 'centaur' | 'asteroid' | 'point';
  archetype: string;
  tagline: string;
  myth: string;
  symbolism: string[];
  psychologicalFunction: string;
  shadowExpression: string;
  giftExpression: string;
  rulesSign: string[];
  keywords: string[];
  animals?: string[];
  plants?: string[];
  metals?: string[];
  dayOfWeek?: string;
  bodyParts?: string[];
  colors?: string[];
  tarotCorrespondence?: string;
}

export const PLANETARY_MYTHOLOGY: MythologyEntry[] = [
  {
    name: 'Sun',
    symbol: '☉',
    greekName: 'Helios / Apollo',
    romanName: 'Sol',
    category: 'luminary',
    archetype: 'The Hero / The King',
    tagline: 'The conscious self and creative sovereignty',
    myth: `In the oldest Greek tradition, Helios was the titan who drove the golden chariot of the sun across the sky each day, seeing everything from his vantage point above the world. He was the all-seeing witness — nothing could hide from his light. Later, Apollo inherited the solar role and became the god of music, prophecy, healing, and truth. Apollo slew the great serpent Python at Delphi, claiming the oracle for himself — the hero who defeats the primordial darkness to establish conscious order. But Apollo's light cast the sharpest shadows: his love affairs ended tragically (Daphne turned into a laurel tree to escape him; Hyacinth died from a discus), teaching that the radiant ego, unchecked, can burn what it tries to possess.`,
    symbolism: [
      'The golden chariot — the vehicle of conscious will moving through time',
      'The laurel crown — victory, but also the memory of what was lost in pursuit',
      'The lyre — creativity as the highest expression of solar energy',
      'The all-seeing eye — nothing hidden from awareness',
    ],
    psychologicalFunction: 'The Sun represents the core identity, the conscious ego, and the vital force that animates the personality. It is what you are becoming — the central organizing principle of the psyche.',
    shadowExpression: 'Narcissism, ego inflation, need for constant admiration, inability to see others as separate beings, burning out by refusing to rest.',
    giftExpression: 'Authentic self-expression, generous leadership, creative vitality, the courage to be visible, warming presence that helps others shine.',
    rulesSign: ['Leo'],
    keywords: ['identity', 'vitality', 'purpose', 'ego', 'creativity', 'father', 'authority', 'visibility'],
    dayOfWeek: 'Sunday',
    metals: ['Gold'],
    bodyParts: ['Heart', 'spine', 'right eye'],
    colors: ['Gold', 'yellow', 'orange'],
    animals: ['Lion', 'eagle', 'hawk'],
    tarotCorrespondence: 'The Sun (XIX)',
  },
  {
    name: 'Moon',
    symbol: '☽',
    greekName: 'Selene / Artemis',
    romanName: 'Luna / Diana',
    category: 'luminary',
    archetype: 'The Mother / The Huntress',
    tagline: 'The emotional body and the rhythm of belonging',
    myth: `Selene, the titan goddess of the Moon, drove her silver chariot across the night sky, illuminating the darkness with reflected light. She fell deeply in love with the mortal shepherd Endymion, and begged Zeus to grant him eternal sleep so she could visit him each night — a story of the Moon's devotion to what is vulnerable, dreaming, and unconscious. Artemis, who inherited the lunar role, was the fierce virgin huntress of the wild forests, protector of young animals and children, goddess of the threshold between civilization and wilderness. She demanded absolute respect for boundaries — when the hunter Actaeon stumbled upon her bathing, she transformed him into a stag and let his own hounds devour him. The Moon protects what is sacred and private with instinctual ferocity.`,
    symbolism: [
      'The silver chariot — emotional navigation through darkness',
      'The crescent — receptivity, the cup that holds feeling',
      'The sleeping shepherd — devotion to the unconscious and vulnerable',
      'The wild forest — the untamed emotional interior',
    ],
    psychologicalFunction: 'The Moon represents the emotional body, instinctual reactions, habits, memory, and the need for safety and belonging. It is how you were nurtured and how you nurture.',
    shadowExpression: 'Emotional manipulation, smothering, inability to let go, moodiness as control, retreating into victimhood, devouring attachment.',
    giftExpression: 'Deep empathy, emotional intelligence, nurturing presence, intuitive knowing, capacity to hold space for vulnerability.',
    rulesSign: ['Cancer'],
    keywords: ['emotions', 'instinct', 'mother', 'home', 'memory', 'cycles', 'nurturing', 'receptivity'],
    dayOfWeek: 'Monday',
    metals: ['Silver'],
    bodyParts: ['Stomach', 'breasts', 'left eye', 'womb'],
    colors: ['Silver', 'white', 'pale blue'],
    animals: ['Crab', 'owl', 'hare', 'cat'],
    tarotCorrespondence: 'The High Priestess (II)',
  },
  {
    name: 'Mercury',
    symbol: '☿',
    greekName: 'Hermes',
    romanName: 'Mercurius',
    otherNames: ['Thoth (Egyptian)', 'Odin (Norse)', 'Nabu (Babylonian)'],
    category: 'personal',
    archetype: 'The Trickster / The Messenger',
    tagline: 'The mind that bridges worlds',
    myth: `Hermes was born at dawn in a cave on Mount Cyllene, and by noon on his first day of life, he had invented the lyre from a tortoise shell, stolen Apollo's sacred cattle, and talked his way out of punishment by making Zeus laugh. He was the only god who could freely travel between Olympus, the mortal world, and the Underworld — the psychopomp who guided dead souls to Hades. As the god of boundaries and the crossing of boundaries, Hermes presided over travelers, merchants, thieves, and orators. He invented language itself, the alphabet, and the art of making fire. His caduceus — two serpents entwined around a staff — represents the reconciliation of opposites through communication. Hermes teaches that intelligence is morally neutral: it can heal or deceive, connect or manipulate.`,
    symbolism: [
      'The caduceus — reconciliation of opposites, healing through communication',
      'Winged sandals — speed of thought, mental agility',
      'The crossroads — choice points, liminal spaces',
      'The tortoise-shell lyre — turning the mundane into art through wit',
    ],
    psychologicalFunction: 'Mercury represents the rational mind, perception, communication, learning style, and the ability to make connections between disparate things. It is how you think and how you speak.',
    shadowExpression: 'Lying, manipulation, intellectual superiority, nervous anxiety, scattered attention, using cleverness to avoid feeling.',
    giftExpression: 'Brilliant communication, quick learning, adaptability, humor, translation between different worlds and perspectives.',
    rulesSign: ['Gemini', 'Virgo'],
    keywords: ['communication', 'intellect', 'commerce', 'travel', 'trickster', 'language', 'perception', 'duality'],
    dayOfWeek: 'Wednesday',
    metals: ['Mercury / Quicksilver'],
    bodyParts: ['Nervous system', 'lungs', 'hands', 'intestines'],
    colors: ['Yellow', 'multicolored', 'iridescent'],
    animals: ['Rooster', 'tortoise', 'ram'],
    tarotCorrespondence: 'The Magician (I)',
  },
  {
    name: 'Venus',
    symbol: '♀',
    greekName: 'Aphrodite',
    romanName: 'Venus',
    otherNames: ['Inanna (Sumerian)', 'Ishtar (Babylonian)', 'Freya (Norse)'],
    category: 'personal',
    archetype: 'The Lover / The Artist',
    tagline: 'Beauty as power, desire as compass',
    myth: `Aphrodite was born from the sea-foam that formed when Kronos castrated his father Ouranos and cast his severed genitals into the ocean. From violence and severance, beauty was born — the oldest Venus myth tells us that love and desire emerge from primal disruption, not from peace. In her most ancient form as Inanna/Ishtar, she was a goddess of BOTH love AND war, who descended into the Underworld, was stripped naked at each of seven gates, died, and was reborn — the original death-and-resurrection myth. Aphrodite's power was so great that even Zeus feared her ability to make gods and mortals fall helplessly in love. Her girdle (the cestus) could make anyone irresistible. Her affair with Ares (Mars) — beauty drawn to raw aggression — produced Harmonia (harmony) and Eros (desire), teaching that love requires the tension of opposites.`,
    symbolism: [
      'Sea-foam birth — beauty born from disruption and primal chaos',
      'The golden apple — the prize that starts wars (judgment of Paris)',
      'The mirror — self-reflection, vanity, and the courage to see clearly',
      'The seven gates — love requires surrendering layers of armor',
    ],
    psychologicalFunction: 'Venus represents values, attraction, aesthetics, relational style, and what you find beautiful and worthy. She governs both romantic love and financial resources — what you value enough to invest in.',
    shadowExpression: 'Vanity, possessiveness, manipulation through beauty or charm, codependency, valuing appearances over substance, using love as currency.',
    giftExpression: 'Capacity for deep love, artistic sensitivity, ability to create harmony and beauty, magnetic presence, knowing what truly matters.',
    rulesSign: ['Taurus', 'Libra'],
    keywords: ['love', 'beauty', 'values', 'money', 'pleasure', 'harmony', 'attraction', 'art'],
    dayOfWeek: 'Friday',
    metals: ['Copper'],
    bodyParts: ['Throat', 'kidneys', 'ovaries', 'skin'],
    colors: ['Green', 'pink', 'rose', 'copper'],
    animals: ['Dove', 'swan', 'sparrow'],
    tarotCorrespondence: 'The Empress (III)',
  },
  {
    name: 'Mars',
    symbol: '♂',
    greekName: 'Ares',
    romanName: 'Mars',
    otherNames: ['Tyr (Norse)', 'Nergal (Babylonian)'],
    category: 'personal',
    archetype: 'The Warrior / The Initiator',
    tagline: 'The courage to act and the fire that defends',
    myth: `Ares was the most despised god on Olympus — even his own father Zeus called him the most hateful of all the gods. Unlike Athena, who represented strategic warfare, Ares embodied the raw, bloody chaos of battle — the berserker rage, the adrenaline rush, the willingness to charge forward without a plan. He was the lover of Aphrodite (desire and aggression are always intertwined), and their union produced both Harmony and Fear. When Ares was trapped in a bronze jar by the giants Otus and Ephialtes for thirteen months, he nearly died — teaching that unchecked aggression eventually imprisons itself. In Rome, Mars was far more honored: he was the father of Romulus and Remus, and March (his month) began the year. The Roman Mars teaches that directed will, disciplined courage, and protective aggression are the foundations of civilization.`,
    symbolism: [
      'The spear and shield — offensive action and defensive boundaries',
      'The bronze jar — aggression turned inward becomes self-imprisonment',
      'The red planet — the color of blood, passion, and vital force',
      'The wolf — instinctual courage and pack loyalty',
    ],
    psychologicalFunction: 'Mars represents desire, drive, anger, sexuality, assertiveness, and the ability to take action. It is your survival instinct and your capacity to fight for what matters.',
    shadowExpression: 'Uncontrolled rage, violence, cruelty, recklessness, domination, passive-aggression when suppressed.',
    giftExpression: 'Courage, decisive action, healthy boundaries, passionate engagement, protective strength, the ability to start and sustain effort.',
    rulesSign: ['Aries', 'Scorpio (traditional)'],
    keywords: ['action', 'desire', 'anger', 'courage', 'sexuality', 'competition', 'drive', 'boundaries'],
    dayOfWeek: 'Tuesday',
    metals: ['Iron'],
    bodyParts: ['Muscles', 'blood', 'adrenal glands', 'head'],
    colors: ['Red', 'scarlet'],
    animals: ['Wolf', 'vulture', 'woodpecker', 'ram'],
    tarotCorrespondence: 'The Tower (XVI)',
  },
  {
    name: 'Jupiter',
    symbol: '♃',
    greekName: 'Zeus',
    romanName: 'Jupiter / Jove',
    otherNames: ['Thor (Norse)', 'Marduk (Babylonian)'],
    category: 'social',
    archetype: 'The King / The Sage',
    tagline: 'Expansion, meaning, and the search for truth',
    myth: `Zeus was the youngest son of the titans Kronos and Rhea. His father, having been warned that one of his children would overthrow him, swallowed each child at birth. Rhea hid baby Zeus on the island of Crete, where he was raised by nymphs and fed on honey and the milk of the goat Amalthea. When he grew strong enough, Zeus freed his siblings from Kronos's belly and led the Olympians in a ten-year war against the Titans — the Titanomachy. After victory, he divided the cosmos with his brothers: he took the sky, Poseidon the sea, Hades the underworld. Zeus became the king of gods and the guardian of cosmic justice (Themis) and sacred hospitality (xenia). But his power came with excess — his endless love affairs produced dozens of children and drove Hera to jealous fury. Zeus teaches that expansion without wisdom becomes tyranny, and that true authority serves justice, not appetite.`,
    symbolism: [
      'The thunderbolt — sudden illumination, divine authority, breakthrough insight',
      'The eagle — the highest perspective, sovereignty over the visible world',
      'The oak tree — endurance, sacred shelter, deep roots supporting great reach',
      'Mount Olympus — the aspiration toward meaning and cosmic order',
    ],
    psychologicalFunction: 'Jupiter represents the search for meaning, faith, philosophy, higher education, travel, and the impulse to grow beyond current limitations. It is where you seek to understand the bigger picture.',
    shadowExpression: 'Excess, overindulgence, self-righteousness, blind optimism, moral superiority, promises without follow-through, playing god.',
    giftExpression: 'Wisdom, generosity, optimism, faith in life, ability to see the big picture, cultural breadth, inspirational teaching, good fortune.',
    rulesSign: ['Sagittarius', 'Pisces (traditional)'],
    keywords: ['expansion', 'wisdom', 'faith', 'abundance', 'philosophy', 'travel', 'justice', 'meaning'],
    dayOfWeek: 'Thursday',
    metals: ['Tin'],
    bodyParts: ['Liver', 'hips', 'thighs'],
    colors: ['Royal blue', 'purple', 'indigo'],
    animals: ['Eagle', 'horse', 'whale'],
    tarotCorrespondence: 'Wheel of Fortune (X)',
  },
  {
    name: 'Saturn',
    symbol: '♄',
    greekName: 'Kronos',
    romanName: 'Saturnus',
    otherNames: ['Ninurta (Babylonian)'],
    category: 'social',
    archetype: 'The Elder / The Gatekeeper',
    tagline: 'Time, limitation, and the mastery born from discipline',
    myth: `Kronos was the youngest and most cunning of the Titans. His mother Gaia, furious that her husband Ouranos had imprisoned their monstrous children in Tartarus, gave Kronos an adamantine sickle. He castrated his father and seized control of the cosmos, ushering in the legendary Golden Age — a time of peace and plenty. But power breeds paranoia: when Kronos learned that his own child would overthrow him, he devoured each of his children as they were born — Hestia, Demeter, Hera, Hades, Poseidon — one by one. His wife Rhea finally tricked him with a stone wrapped in swaddling clothes, saving Zeus. Kronos teaches the dual nature of time: it creates the conditions for growth (the Golden Age), but unchecked fear of the future consumes everything, including your own creations. Saturn asks: what are you so afraid of losing that you're destroying it by holding on too tight?`,
    symbolism: [
      'The sickle — cutting away what no longer serves, harvest after patient labor',
      'The swallowed children — fear of being replaced, consuming your own potential',
      'The Golden Age — the promise that discipline leads to lasting achievement',
      'The rings — boundaries, limitations, and the beauty of structure',
    ],
    psychologicalFunction: 'Saturn represents structure, responsibility, discipline, time, maturity, and the reality principle. It shows where you must do the work, face your fears, and earn your authority through experience.',
    shadowExpression: 'Rigidity, depression, excessive control, harsh self-criticism, fear of failure, cold emotional withdrawal, authoritarianism.',
    giftExpression: 'Discipline, perseverance, wisdom earned through experience, integrity, responsible authority, the ability to build things that last.',
    rulesSign: ['Capricorn', 'Aquarius (traditional)'],
    keywords: ['discipline', 'time', 'structure', 'responsibility', 'limitation', 'maturity', 'karma', 'mastery'],
    dayOfWeek: 'Saturday',
    metals: ['Lead'],
    bodyParts: ['Bones', 'teeth', 'knees', 'skin (aging)'],
    colors: ['Black', 'dark brown', 'grey'],
    animals: ['Goat', 'crow', 'crocodile'],
    tarotCorrespondence: 'The World (XXI)',
  },
  {
    name: 'Uranus',
    symbol: '♅',
    greekName: 'Ouranos',
    romanName: 'Caelus',
    category: 'transpersonal',
    archetype: 'The Awakener / The Revolutionary',
    tagline: 'Liberation through rupture, genius born from chaos',
    myth: `Ouranos was the primordial sky god, born from Gaia (Earth) herself — or in some versions, emerging from Chaos alongside her. He mated with Gaia endlessly, producing the Titans, the Cyclopes, and the hundred-handed Hecatoncheires. But Ouranos was horrified by his monstrous children and forced them back into Gaia's womb (Tartarus), causing her terrible pain. Gaia forged an adamantine sickle and asked her children for help. Only Kronos was brave enough. He ambushed Ouranos at nightfall and castrated him — the severed flesh falling into the sea to birth Aphrodite, and the blood falling on earth to spawn the Furies and the Giants. Ouranos screams from the sky that his children will pay for this — and they do, generation after generation. The myth teaches that suppression of what is new, strange, or "monstrous" leads to violent revolution. What you refuse to birth willingly will eventually overthrow you.`,
    symbolism: [
      'The castration — severance from the past that gives birth to the new (Aphrodite)',
      'The sky — infinite possibility, detachment from earthly limitation',
      'Lightning — sudden insight that shatters old structures',
      'The monstrous children — the genius, innovation, and difference we try to suppress',
    ],
    psychologicalFunction: 'Uranus represents the urge for freedom, individuation, sudden insight, rebellion against convention, and the capacity for genius. It is where you must break free from inherited patterns.',
    shadowExpression: 'Emotional detachment, chronic rebellion without purpose, instability, eccentricity as armor, inability to commit, shocking behavior for its own sake.',
    giftExpression: 'Originality, brilliant insight, humanitarian vision, courage to be different, technological innovation, liberation from outworn structures.',
    rulesSign: ['Aquarius'],
    keywords: ['revolution', 'freedom', 'genius', 'disruption', 'innovation', 'awakening', 'individuation', 'electricity'],
    metals: ['Uranium', 'platinum'],
    bodyParts: ['Nervous system (higher octave)', 'ankles', 'circulatory system'],
    colors: ['Electric blue', 'neon', 'ultraviolet'],
    animals: ['Albatross', 'electric eel'],
    tarotCorrespondence: 'The Fool (0) / The Star (XVII)',
  },
  {
    name: 'Neptune',
    symbol: '♆',
    greekName: 'Poseidon',
    romanName: 'Neptunus',
    category: 'transpersonal',
    archetype: 'The Mystic / The Dreamer',
    tagline: 'The dissolution of boundaries and the longing for the infinite',
    myth: `Poseidon received dominion over the sea when the cosmos was divided after the defeat of the Titans. He was second only to Zeus in power, and his temper was legendary — striking the earth with his trident caused earthquakes, storms, and tidal waves. He competed with Athena for patronage of Athens: she offered the olive tree (wisdom, civilization); he struck a rock and produced a saltwater spring (impressive but useless). He lost, and his resentment shaped the Odyssey — Poseidon's rage against Odysseus for blinding his son Polyphemus drove the hero to wander the seas for ten years. But Poseidon also created the horse (wild, beautiful, powerful) and was lord of all that lies beneath the surface — the vast unconscious, the depths where treasures and monsters coexist. Neptune teaches that what lies beneath the surface is vaster than what appears above it, and that surrendering to currents larger than yourself can carry you home — or drown you.`,
    symbolism: [
      'The trident — power over the three realms of consciousness (waking, dreaming, deep sleep)',
      'The ocean — the collective unconscious, boundlessness, dissolution',
      'The horse — instinctual power yoked to beauty',
      'The fog — confusion that precedes mystical clarity',
    ],
    psychologicalFunction: 'Neptune represents the longing for transcendence, spiritual connection, imagination, compassion, and the dissolution of ego boundaries. It is where you seek union with something greater than yourself.',
    shadowExpression: 'Escapism (addiction, fantasy, denial), deception, martyrdom, victim consciousness, confusion, inability to maintain boundaries.',
    giftExpression: 'Spiritual vision, artistic inspiration, unconditional compassion, mystical experience, imagination, music, healing through surrender.',
    rulesSign: ['Pisces'],
    keywords: ['transcendence', 'illusion', 'spirituality', 'dreams', 'compassion', 'dissolution', 'imagination', 'fog'],
    metals: ['Neptune (no traditional metal)', 'Platinum'],
    bodyParts: ['Pineal gland', 'feet', 'lymphatic system'],
    colors: ['Sea green', 'turquoise', 'lavender', 'iridescent'],
    animals: ['Fish', 'dolphin', 'seahorse'],
    tarotCorrespondence: 'The Hanged Man (XII)',
  },
  {
    name: 'Pluto',
    symbol: '♇',
    greekName: 'Hades',
    romanName: 'Pluto',
    otherNames: ['Ereshkigal (Sumerian, underworld queen)'],
    category: 'transpersonal',
    archetype: 'The Transformer / The Lord of the Underworld',
    tagline: 'Death, rebirth, and the hidden wealth of the shadow',
    myth: `Hades was the eldest son of Kronos and Rhea — the first to be swallowed and the last to be freed. When the cosmos was divided, he received the underworld — not as punishment, but as responsibility. He was lord of all that lies below: buried treasure, seeds germinating in darkness, the souls of the dead, and the secret riches of the earth. His most famous myth is the abduction of Persephone — he erupted from the earth in his black chariot, seized Demeter's daughter, and dragged her below. Demeter's grief caused all growing things to die. Eventually, a compromise was reached: Persephone would spend part of the year below (winter) and part above (spring). But what most forget is that Persephone became QUEEN of the underworld — she was not merely a victim. She gained sovereignty over the dead, became a formidable goddess in her own right, and chose to eat the pomegranate seeds. Pluto teaches that what is taken from us in the dark often becomes our greatest source of power.`,
    symbolism: [
      'The pomegranate — voluntary descent, binding yourself to the depths',
      'The Helm of Darkness — invisibility, operating from the shadows, unseen power',
      'The black chariot — the vehicle of transformation that erupts without warning',
      'Buried treasure — wealth and resources that can only be found underground',
    ],
    psychologicalFunction: 'Pluto represents the process of death and rebirth, transformation through crisis, power dynamics, the shadow, obsession, and the capacity to regenerate. It is where you must die to who you were in order to become who you are meant to be.',
    shadowExpression: 'Obsessive control, manipulation, power abuse, paranoia, destructiveness, refusing to let go, psychological coercion.',
    giftExpression: 'Profound transformation, psychological depth, resilience, capacity to heal deep wounds, empowerment, fearless truth-telling.',
    rulesSign: ['Scorpio'],
    keywords: ['transformation', 'death/rebirth', 'power', 'shadow', 'obsession', 'regeneration', 'depth', 'hidden wealth'],
    metals: ['Plutonium'],
    bodyParts: ['Reproductive organs', 'colon', 'DNA'],
    colors: ['Black', 'dark red', 'maroon'],
    animals: ['Scorpion', 'snake', 'phoenix', 'raven'],
    tarotCorrespondence: 'Death (XIII) / Judgement (XX)',
  },
  {
    name: 'Chiron',
    symbol: '⚷',
    greekName: 'Kheiron',
    romanName: 'Chiron',
    category: 'centaur',
    archetype: 'The Wounded Healer',
    tagline: 'The wound that becomes medicine for others',
    myth: `Chiron was unique among the centaurs — while others were wild, drunken, and violent, Chiron was wise, gentle, and civilized. He was the son of Kronos (who had taken the form of a horse to seduce the nymph Philyra), making him an immortal half-brother to Zeus. Chiron became the greatest teacher in the Greek world: he tutored Achilles, Asclepius (god of medicine), Jason, and Hercules in music, medicine, archery, and ethics. But when Hercules accidentally wounded him with an arrow dipped in the Hydra's poisonous blood, Chiron could not heal himself — despite being the greatest healer alive. As an immortal, he could not die to escape the pain. He suffered endlessly until he offered to trade his immortality to free Prometheus from his rock. Zeus honored this sacrifice by placing him among the stars as the constellation Centaurus. Chiron teaches that our deepest wound, the one we cannot fix in ourselves, becomes the source of our greatest gift to others.`,
    symbolism: [
      'The incurable wound — suffering that cannot be bypassed, only transmuted through service',
      'The centaur form — bridging animal instinct and higher wisdom',
      'The exchange with Prometheus — liberation through voluntary sacrifice',
      'The teacher — wounds that qualify us to guide others through similar terrain',
    ],
    psychologicalFunction: 'Chiron represents the core wound — often from early life — that resists healing but drives us to develop expertise, compassion, and the ability to help others with similar pain.',
    shadowExpression: 'Identifying as permanently broken, using wounds as excuses, rescuing others to avoid your own pain, bitterness about what can never be fixed.',
    giftExpression: 'Deep empathy born from experience, mentorship, holistic healing ability, bridging conventional and alternative approaches, transforming suffering into wisdom.',
    rulesSign: ['Associated with Virgo and Sagittarius'],
    keywords: ['wound', 'healing', 'teaching', 'mentorship', 'bridge', 'sacrifice', 'initiation', 'holistic'],
    animals: ['Horse', 'centaur'],
    tarotCorrespondence: 'The Hermit (IX)',
  },
  {
    name: 'Eris',
    symbol: '⯰',
    greekName: 'Eris',
    romanName: 'Discordia',
    category: 'transpersonal',
    archetype: 'The Disruptor / The Uninvited Truth',
    tagline: 'She reveals what has been excluded from the table',
    myth: `Eris, goddess of discord and strife, was the only deity NOT invited to the wedding of Peleus and Thetis (the parents of Achilles). Every other god received an invitation — but Eris, associated with conflict and disruption, was deliberately excluded. Rather than accept her exclusion quietly, she appeared at the feast uninvited and rolled a golden apple among the guests inscribed with the words "For the Fairest." Three goddesses — Hera, Athena, and Aphrodite — each claimed the apple, and the dispute was given to the mortal Paris to judge. His choice (Aphrodite, who bribed him with Helen) triggered the Trojan War. The myth reveals that what you exclude, deny, or refuse to invite to the table doesn't disappear — it returns with catastrophic force. Eris doesn't CREATE discord; she reveals the discord that was already there, hidden beneath the polite surface. She asks: who isn't at YOUR table? What truth are you refusing to acknowledge?`,
    symbolism: [
      'The golden apple — the question that exposes hidden competition and desire',
      'The uninvited guest — whatever is excluded from consciousness returns as disruption',
      'The Trojan War — the catastrophic consequences of refusing to face uncomfortable truths',
      'Discord — not chaos for its own sake, but the friction that forces authenticity',
    ],
    psychologicalFunction: 'Eris represents the function of disruption in service of truth — the part of the psyche that refuses to play along with false harmony and forces confrontation with what has been denied or excluded.',
    shadowExpression: 'Creating drama for attention, chronic contrarianism, deliberate sabotage, enjoying conflict, unable to accept belonging.',
    giftExpression: 'Radical honesty, the courage to name what everyone else is avoiding, catalyst for necessary change, justice for the marginalized.',
    rulesSign: ['Associated with Aries (by position and theme)'],
    keywords: ['discord', 'disruption', 'exclusion', 'truth', 'catalyst', 'uninvited', 'golden apple', 'revelation'],
    tarotCorrespondence: 'The Tower (XVI)',
  },
  {
    name: 'Lilith (Black Moon)',
    symbol: '⚸',
    greekName: 'Lilith (Hebrew/Mesopotamian)',
    romanName: 'N/A',
    otherNames: ['Black Moon Lilith', 'Lilitu (Babylonian)'],
    category: 'point',
    archetype: 'The Exile / The Wild Feminine',
    tagline: 'What was banished for refusing to submit',
    myth: `In the earliest versions of the Genesis story (the Alphabet of Ben Sira), Lilith was Adam's first wife, created from the same earth as him — his equal. When Adam insisted she lie beneath him during intercourse, Lilith refused, arguing that they were made of the same substance and she should not be subordinate. When Adam tried to force her, Lilith spoke the ineffable name of God, grew wings, and flew away to the shores of the Red Sea, where she lived freely among demons and gave birth to hundreds of children. God sent three angels to bring her back, threatening to kill a hundred of her children each day. Lilith refused to return, preferring exile and suffering to subjugation. She became a night demon in later traditions — feared, demonized, and blamed for infant death and male nocturnal emissions. But the original story is about autonomy: Lilith chose freedom over security, wildness over domestication, sovereignty over belonging.`,
    symbolism: [
      'The refusal — the primal "no" to subjugation, regardless of consequences',
      'The wings — escape from structures that demand submission',
      'The Red Sea shore — exile as the price of autonomy',
      'The demonized feminine — what patriarchal culture cannot control, it calls evil',
    ],
    psychologicalFunction: 'Black Moon Lilith represents what was exiled from the personality for being too wild, too sexual, too autonomous, or too threatening. It is where you were shamed and where you hold raw, untamed power.',
    shadowExpression: 'Destructive rage, sexual manipulation, compulsive rebellion, inability to cooperate, sabotaging intimacy to maintain control.',
    giftExpression: 'Fierce autonomy, raw creative and sexual power, refusal to betray the self for acceptance, reclaiming what was shamed.',
    rulesSign: ['Associated with Scorpio and Capricorn themes'],
    keywords: ['exile', 'autonomy', 'sexuality', 'rebellion', 'shame', 'wildness', 'taboo', 'raw power'],
    tarotCorrespondence: 'The High Priestess (II, reversed) / Strength (VIII)',
  },
  {
    name: 'Ceres',
    symbol: '⚳',
    greekName: 'Demeter',
    romanName: 'Ceres',
    category: 'asteroid',
    archetype: 'The Great Mother / The Griever',
    tagline: 'Nourishment, loss, and the cycles of letting go',
    myth: `Demeter was the goddess of grain, harvest, and the fertility of the earth. When her daughter Persephone was abducted by Hades, Demeter's grief was so total that she withdrew her gifts from the world — crops died, trees withered, famine spread, and humanity began to starve. She wandered the earth disguised as an old woman, searching for her daughter, refusing food, refusing comfort. The gods begged her to relent, but she declared that nothing would grow until Persephone was returned. Zeus was forced to intervene. The compromise — Persephone spending part of the year underground — gave us the seasons: life and growth when mother and daughter are reunited, death and dormancy when they are apart. Demeter teaches that grief is not weakness — it is the most powerful force in nature. A mother's love, when thwarted, can stop the world.`,
    symbolism: [
      'The grain sheaf — nourishment, sustenance, what feeds body and soul',
      'The famine — grief so deep it stops all growth',
      'The seasons — the eternal cycle of attachment, loss, return, and renewal',
      'The torch — the search for what has been taken, refusing to give up',
    ],
    psychologicalFunction: 'Ceres represents nourishment — how you feed and are fed (literally and emotionally), attachment, loss, separation anxiety, food relationships, and the cycle of holding on and letting go.',
    shadowExpression: 'Smothering control, using food as love/punishment, inability to let children/projects grow independently, grief that becomes self-destruction.',
    giftExpression: 'Deep nurturing capacity, attunement to physical and emotional needs, understanding of natural cycles, fierce love that transforms the world.',
    rulesSign: ['Associated with Virgo and Cancer'],
    keywords: ['nourishment', 'harvest', 'grief', 'mothering', 'seasons', 'food', 'attachment', 'fertility'],
    tarotCorrespondence: 'The Empress (III)',
  },
  {
    name: 'Pallas',
    symbol: '⚴',
    greekName: 'Pallas Athena',
    romanName: 'Minerva',
    category: 'asteroid',
    archetype: 'The Strategist / The Pattern-Seer',
    tagline: 'Creative intelligence and the warrior mind',
    myth: `Athena was born from Zeus's head — literally. After Zeus swallowed her pregnant mother Metis (wisdom personified, whom he feared would bear a son more powerful than himself), Athena grew inside his skull until Hephaestus split it open with an axe and she emerged fully armored, ready for battle. She was the goddess of wisdom, strategic warfare, weaving, and civilization — the thinking warrior who won through intelligence rather than brute force. She invented the bridle (taming wild horses), the plow, the chariot, and the art of weaving. In the contest with Poseidon for Athens, she offered the olive tree — practical, sustaining, and civilizing. Athena never lost a battle because she never fought without a plan. But she was also fierce: she turned Medusa into a monster (some say to protect her, others to punish her) and guided heroes like Perseus and Odysseus through impossible tasks.`,
    symbolism: [
      'The owl — wisdom that sees in the dark, pattern recognition',
      "The aegis with Medusa's head — using fear strategically, the power of the gaze",
      'The olive tree — practical wisdom that sustains civilization',
      'The loom — weaving patterns from chaos, seeing the whole design',
    ],
    psychologicalFunction: 'Pallas represents creative intelligence, pattern recognition, strategic thinking, and the ability to see the whole picture. It shows where you solve problems through insight rather than force.',
    shadowExpression: 'Cold rationality, dismissing emotions as weakness, over-identification with the father, using intelligence to dominate.',
    giftExpression: 'Brilliant strategy, artistic vision, political wisdom, ability to see patterns others miss, mentorship, civilizing influence.',
    rulesSign: ['Associated with Aquarius and Libra'],
    keywords: ['strategy', 'wisdom', 'patterns', 'crafts', 'politics', 'justice', 'mentorship', 'intelligence'],
    tarotCorrespondence: 'Justice (XI)',
  },
  {
    name: 'Juno',
    symbol: '⚵',
    greekName: 'Hera',
    romanName: 'Juno',
    category: 'asteroid',
    archetype: 'The Queen / The Committed Partner',
    tagline: 'Sacred partnership and the politics of loyalty',
    myth: `Hera was the queen of the gods, sister and wife of Zeus, and guardian of marriage, women, and childbirth. She endured Zeus's constant infidelities — affairs with mortals, nymphs, goddesses, and even boys — and her rage at these betrayals defined much of Greek mythology. She persecuted Hercules (Zeus's son by the mortal Alcmene) from birth, sending serpents to his crib and driving him mad so that he killed his own children. She punished Echo (who distracted her so Zeus could philander) by taking away her voice. Yet Hera's fury was not merely jealousy — it was the righteous anger of sacred commitments violated, of a queen whose sovereignty was constantly undermined. In her own right, Hera was worshipped as a powerful goddess of sovereignty and female authority long before her marriage to Zeus. The myth teaches that partnership requires mutual respect, and that betrayal in committed relationships unleashes the most destructive forces in human experience.`,
    symbolism: [
      'The peacock — beauty and pride, but also the hundred eyes of vigilance (Argos)',
      'The pomegranate — fertility, but also binding oaths',
      'The crown/diadem — sovereignty within partnership, equal authority',
      'The cow — sacred feminine power, nurturing strength',
    ],
    psychologicalFunction: 'Juno represents committed partnership, marriage dynamics, fairness in relationship, jealousy, betrayal patterns, and the need for equal power in intimate bonds.',
    shadowExpression: 'Jealousy, possessiveness, revenge against perceived rivals, sacrificing identity for partnership, staying in toxic bonds out of duty.',
    giftExpression: 'Capacity for deep commitment, advocating for fairness in relationships, queenly dignity, loyalty that transforms both partners.',
    rulesSign: ['Associated with Libra and Scorpio'],
    keywords: ['marriage', 'partnership', 'jealousy', 'commitment', 'loyalty', 'betrayal', 'sovereignty', 'equality'],
    tarotCorrespondence: 'The Lovers (VI)',
  },
  {
    name: 'Vesta',
    symbol: '⚶',
    greekName: 'Hestia',
    romanName: 'Vesta',
    category: 'asteroid',
    archetype: 'The Priestess / The Sacred Flame',
    tagline: 'Devotion, inner sanctuary, and what you tend with quiet discipline',
    myth: `Hestia was the firstborn child of Kronos and Rhea — and therefore the first to be swallowed, and the last to be freed. Both Poseidon and Apollo courted her, but she swore an eternal oath of virginity upon Zeus's head and was granted the honor of receiving the first portion of every sacrifice. She was the goddess of the hearth fire — the sacred center of every home and temple. Unlike other Olympians, Hestia had no dramatic myths, no love affairs, no wars. She simply remained. Her power was in presence, not action. When Dionysus arrived on Olympus, Hestia quietly gave up her throne among the Twelve so there would be no conflict — the ultimate act of self-possession. The Vestal Virgins of Rome tended her eternal flame; if it went out, Rome itself was endangered. Hestia teaches that the most sacred things require quiet, sustained devotion — and that true power sometimes means knowing when to step back.`,
    symbolism: [
      'The eternal flame — what must never go out, the sacred center',
      'The hearth — home, inner sanctuary, the still point of the turning world',
      'Virginity — wholeness unto oneself, not defined by relationship to others',
      'The first and last offering — honored at the beginning and end of all things',
    ],
    psychologicalFunction: 'Vesta represents devotion, focus, sacred service, spiritual practice, and the capacity for self-containment. It shows where you tend the inner flame and what you are devoted to with quiet, sustained attention.',
    shadowExpression: 'Isolation, fanatical devotion, burn-out from over-commitment, using spiritual practice to avoid relationship, rigidity.',
    giftExpression: 'Deep focus, spiritual devotion, creating sacred space, self-sufficiency, the warmth that makes a house a home.',
    rulesSign: ['Associated with Virgo and Scorpio'],
    keywords: ['devotion', 'focus', 'sacred', 'hearth', 'virginity', 'service', 'sanctuary', 'discipline'],
    tarotCorrespondence: 'The Hermit (IX)',
  },
  {
    name: 'Sedna',
    symbol: '⏣',
    greekName: 'N/A',
    romanName: 'N/A',
    otherNames: ['Sanna', 'Arnakuagsak', 'Nuliajuk'],
    category: 'transpersonal',
    archetype: 'The Betrayed One / The Deep Sea Mother',
    tagline: 'Betrayal, deep transformation, and the life that sustains from the abyss',
    myth: `Sedna is not Greek or Roman — she comes from Inuit tradition, which is fitting for the most distant known object in our solar system. In the most common version, Sedna was a beautiful young woman who refused all suitors. A mysterious stranger (sometimes a bird-spirit) lured her away with promises of a beautiful home. When her father came to rescue her in his kayak, the stranger pursued them, conjuring a terrible storm. In terror, her father threw Sedna overboard to save himself. When she clung to the side of the kayak, he chopped off her fingers, joint by joint. Her severed fingers became the seals, walruses, and whales — the marine life that sustains Arctic peoples. Sedna sank to the bottom of the ocean and became its ruler. Shamans must journey to the sea floor to comb the tangles from her hair (caused by human transgressions) so she will release the animals for hunting. Sedna teaches that the deepest betrayals — by those who should protect us — can become the source of life for entire communities.`,
    symbolism: [
      'The severed fingers — what is taken from us through betrayal becomes sustenance for others',
      'The ocean floor — the deepest possible descent, far below conscious awareness',
      'The tangled hair — accumulated grief, neglect, and transgression that blocks abundance',
      "The shaman's journey — the necessity of going to the very bottom to restore balance",
    ],
    psychologicalFunction: 'Sedna represents the deepest layers of ancestral and collective trauma — betrayals so profound they reshape the ecosystem of the psyche. It shows where we must journey to the absolute bottom to find what sustains life.',
    shadowExpression: 'Frozen grief, inability to trust, identifying permanently as victim, ecological disconnection, spiritual bypass of deep wounds.',
    giftExpression: 'Transmuting the deepest betrayals into sources of nourishment for others, ecological consciousness, connection to ancestral wisdom, the courage to go where no one else will go.',
    rulesSign: ['Associated with Pisces/Scorpio themes (deep water, transformation)'],
    keywords: ['betrayal', 'depth', 'ecology', 'ancestral trauma', 'ocean', 'sustenance', 'shamanic journey', 'transformation'],
  },
];

export const MYTHOLOGY_CATEGORIES = {
  luminary: { label: 'Luminaries', description: 'The two great lights that anchor consciousness', icon: '☉☽' },
  personal: { label: 'Personal Planets', description: 'The inner workings of daily life', icon: '☿♀♂' },
  social: { label: 'Social Planets', description: 'Where personal meets collective', icon: '♃♄' },
  transpersonal: { label: 'Transpersonal Planets', description: 'Forces beyond individual control', icon: '♅♆♇' },
  centaur: { label: 'Centaurs', description: 'Bridging the known and unknown', icon: '⚷' },
  asteroid: { label: 'Goddess Asteroids', description: 'The feminine archetypes restored', icon: '⚳⚴⚵⚶' },
  point: { label: 'Calculated Points', description: 'Mathematical shadows with mythic weight', icon: '⚸' },
};

export type MythologyCategory = keyof typeof MYTHOLOGY_CATEGORIES;
