// Complete Sabian Symbols for all 360 degrees of the zodiac
// Based on the Marc Edmund Jones / Dane Rudhyar interpretations

export const SABIAN_SYMBOLS: Record<string, { symbol: string; meaning: string }> = {
  // ARIES (1-30)
  '1-Aries': { symbol: 'A woman rises out of water, a seal embraces her', meaning: 'Emergence from the unconscious. New beginnings rise from emotional depths.' },
  '2-Aries': { symbol: 'A comedian entertains a group', meaning: 'Self-awareness through humor. The ability to see oneself objectively.' },
  '3-Aries': { symbol: 'A cameo profile of a man in the outline of his country', meaning: 'Personal identity shaped by cultural heritage. Individual as microcosm of nation.' },
  '4-Aries': { symbol: 'Two lovers strolling through a secluded walk', meaning: 'Intimate connection away from the world. Private moments of union.' },
  '5-Aries': { symbol: 'A triangle with wings', meaning: 'Aspiration toward higher understanding. Mind seeking transcendence.' },
  '6-Aries': { symbol: 'A square brightly lighted on one side', meaning: 'Focused consciousness. Illumination of one aspect of reality.' },
  '7-Aries': { symbol: 'A man succeeds in expressing himself in two realms', meaning: 'Dual mastery. Integration of different worlds or skills.' },
  '8-Aries': { symbol: 'A large hat with streamers flying, facing east', meaning: 'Receptivity to inspiration. Openness to new spiritual influences.' },
  '9-Aries': { symbol: 'A crystal gazer', meaning: 'Inner vision. Concentration on subtle realities beyond the physical.' },
  '10-Aries': { symbol: 'A teacher gives new symbolic forms to traditional images', meaning: 'Revitalizing old wisdom. Making ancient truths relevant.' },
  '11-Aries': { symbol: 'The president of the country', meaning: 'Social responsibility. Leadership through embodying collective ideals.' },
  '12-Aries': { symbol: 'A flock of wild geese', meaning: 'Cosmic order in nature. Following instinctual patterns of migration.' },
  '13-Aries': { symbol: 'An unexploded bomb reveals an unsuccessful social protest', meaning: 'Unreleased potential energy waiting for the right moment. This degree speaks to passion held in reserve—the wisdom to know that timing matters as much as intention. Rather than forcing change prematurely, there is power in strategic patience and choosing your battles wisely.' },
  '14-Aries': { symbol: 'A serpent coiling near a man and a woman', meaning: 'Temptation and wisdom. Kundalini energy in relationships.' },
  '15-Aries': { symbol: 'An Indian weaving a blanket', meaning: 'Creative self-expression. Weaving one\'s life pattern with skill.' },
  '16-Aries': { symbol: 'Nature spirits are seen at work in the light of sunset', meaning: 'Awareness of subtle forces. Seeing the magical in twilight consciousness.' },
  '17-Aries': { symbol: 'Two prim spinsters', meaning: 'Withdrawal from life\'s passions. Discipline that may become rigidity.' },
  '18-Aries': { symbol: 'An empty hammock', meaning: 'Rest after activity. The value of doing nothing, recuperation.' },
  '19-Aries': { symbol: 'The magic carpet', meaning: 'Imagination as transport. Mind over matter, creative visualization.' },
  '20-Aries': { symbol: 'A young girl feeding birds in winter', meaning: 'Compassionate nurturing. Caring for those in need regardless of circumstance.' },
  '21-Aries': { symbol: 'A pugilist entering the ring', meaning: 'Ready for challenge. Courage to face opposition directly.' },
  '22-Aries': { symbol: 'The gate to the garden of desire', meaning: 'Threshold of fulfillment. Approaching what the heart wants.' },
  '23-Aries': { symbol: 'A woman in pastel colors carrying a heavy and valuable but veiled load', meaning: 'Hidden treasure. Carrying inner riches beneath a gentle exterior.' },
  '24-Aries': { symbol: 'An open window and a net curtain blowing into a cornucopia', meaning: 'Abundance flowing in. Receptivity to life\'s gifts.' },
  '25-Aries': { symbol: 'A double promise reveals its inner and outer meanings', meaning: 'Layers of truth. Understanding the esoteric within the exoteric.' },
  '26-Aries': { symbol: 'A man possessed of more gifts than he can hold', meaning: 'Overwhelmed by talents. The challenge of too much potential.' },
  '27-Aries': { symbol: 'Through imagination a lost opportunity is regained', meaning: 'Creative recovery. Using visualization to reclaim the past.' },
  '28-Aries': { symbol: 'A large disappointed audience', meaning: 'Failed expectations. Learning from collective disillusionment.' },
  '29-Aries': { symbol: 'The music of the spheres', meaning: 'Cosmic harmony. Attunement to universal rhythms.' },
  '30-Aries': { symbol: 'A duck pond and its brood', meaning: 'Natural nurturing. Simple domestic fulfillment.' },

  // TAURUS (1-30)
  '1-Taurus': { symbol: 'A clear mountain stream', meaning: 'Purity of natural flow. Uncontaminated emotional expression.' },
  '2-Taurus': { symbol: 'An electrical storm', meaning: 'Release of tension. Sudden illumination through crisis.' },
  '3-Taurus': { symbol: 'Natural steps lead to a lawn of clover in bloom', meaning: 'Gradual progress toward abundance. Patient ascent to prosperity.' },
  '4-Taurus': { symbol: 'The pot of gold at the end of the rainbow', meaning: 'Promised reward. Faith in reaching the goal.' },
  '5-Taurus': { symbol: 'A widow at an open grave', meaning: 'Confronting loss. Finding meaning in grief and endings.' },
  '6-Taurus': { symbol: 'A bridge being built across a gorge', meaning: 'Connecting opposites. Engineering solutions to separation.' },
  '7-Taurus': { symbol: 'A woman of Samaria', meaning: 'Breaking social barriers. Spiritual truth transcending convention.' },
  '8-Taurus': { symbol: 'A sleigh without snow', meaning: 'Preparation for conditions not yet present. Readiness awaiting circumstance.' },
  '9-Taurus': { symbol: 'A fully decorated Christmas tree', meaning: 'Celebration of abundance. Joy in material and spiritual gifts.' },
  '10-Taurus': { symbol: 'A Red Cross nurse', meaning: 'Compassionate service. Healing without judgment.' },
  '11-Taurus': { symbol: 'A woman watering flowers in her garden', meaning: 'Nurturing growth. Patient cultivation of beauty.' },
  '12-Taurus': { symbol: 'A young couple window-shopping', meaning: 'Dreaming together. Shared visions of the future.' },
  '13-Taurus': { symbol: 'A porter carrying heavy baggage', meaning: 'Service through strength. Bearing others\' burdens.' },
  '14-Taurus': { symbol: 'Shellfish groping and children playing', meaning: 'Different levels of consciousness. Instinct alongside innocence.' },
  '15-Taurus': { symbol: 'A man with a silk hat, muffled, braves a storm', meaning: 'Dignity despite difficulty. Maintaining composure in crisis.' },
  '16-Taurus': { symbol: 'An old man attempting vainly to reveal the Mysteries', meaning: 'Wisdom unheard. Truth that cannot be communicated directly.' },
  '17-Taurus': { symbol: 'A symbolic battle between swords and torches', meaning: 'Intellect versus passion. The conflict of mind and spirit.' },
  '18-Taurus': { symbol: 'A woman holding a bag out of a window', meaning: 'Offering to the world. Generosity extending beyond boundaries.' },
  '19-Taurus': { symbol: 'A new continent rising out of the ocean', meaning: 'Emergence of new possibilities. Undiscovered territory appearing.' },
  '20-Taurus': { symbol: 'Wind clouds and haste', meaning: 'Urgency in the atmosphere. Pressure to move quickly.' },
  '21-Taurus': { symbol: 'A finger pointing in an open book', meaning: 'Guidance found in wisdom. The answer is written.' },
  '22-Taurus': { symbol: 'A white dove over troubled waters', meaning: 'Peace above turmoil. Spirit transcending emotional chaos.' },
  '23-Taurus': { symbol: 'A jewelry shop', meaning: 'Value and beauty displayed. Recognition of worth.' },
  '24-Taurus': { symbol: 'An Indian warrior riding fiercely, scalps hanging at his belt', meaning: 'Conquest and trophy. Victory through aggressive action.' },
  '25-Taurus': { symbol: 'A large well-kept public park', meaning: 'Communal beauty. Nature ordered for collective enjoyment.' },
  '26-Taurus': { symbol: 'A Spaniard serenading his senorita', meaning: 'Romantic pursuit. Courtship through artistic expression.' },
  '27-Taurus': { symbol: 'A squaw selling beads', meaning: 'Cultural exchange. Tradition meeting commerce.' },
  '28-Taurus': { symbol: 'A woman pursued by mature romance', meaning: 'Later love. Relationship opportunity in maturity.' },
  '29-Taurus': { symbol: 'Two cobblers working at a table', meaning: 'Collaborative craft. Practical work shared.' },
  '30-Taurus': { symbol: 'A peacock parading on an ancient lawn', meaning: 'Display of beauty. Pride in one\'s heritage and appearance.' },

  // GEMINI (1-30)
  '1-Gemini': { symbol: 'A glass-bottomed boat in still water', meaning: 'Seeing into depths without diving. Observation of the unconscious.' },
  '2-Gemini': { symbol: 'Santa Claus filling stockings furtively', meaning: 'Secret generosity. Giving without recognition.' },
  '3-Gemini': { symbol: 'The garden of the Tuileries', meaning: 'Formal beauty. Nature arranged by human design.' },
  '4-Gemini': { symbol: 'Holly and mistletoe', meaning: 'Festive duality. The sacred and the social intertwined.' },
  '5-Gemini': { symbol: 'A radical magazine', meaning: 'Challenging ideas. Communication that disrupts the status quo.' },
  '6-Gemini': { symbol: 'Drilling for oil', meaning: 'Seeking hidden resources. Effort to tap deeper value.' },
  '7-Gemini': { symbol: 'An old-fashioned well', meaning: 'Traditional sources of nourishment. Proven ways to access the depths.' },
  '8-Gemini': { symbol: 'An industrial strike', meaning: 'Collective action. Workers united for change.' },
  '9-Gemini': { symbol: 'A quiver filled with arrows', meaning: 'Preparedness. Ideas and resources ready for deployment.' },
  '10-Gemini': { symbol: 'An airplane falling', meaning: 'Loss of elevation. Ideals brought down to earth.' },
  '11-Gemini': { symbol: 'A new path of realism in experience', meaning: 'Practical awakening. Seeing things as they are.' },
  '12-Gemini': { symbol: 'A Topsy saucily asserting herself', meaning: 'Bold self-expression. Refusing to be suppressed.' },
  '13-Gemini': { symbol: 'A famous pianist giving a concert', meaning: 'Mastery displayed. Talent shared with many.' },
  '14-Gemini': { symbol: 'Two people at the moment of first acquaintance', meaning: 'The magic of meeting. Potential in new connection.' },
  '15-Gemini': { symbol: 'Two Dutch children talking', meaning: 'Innocent communication. Pure exchange between equals.' },
  '16-Gemini': { symbol: 'A woman activist in an emotional appeal', meaning: 'Passionate advocacy. Heart-driven persuasion.' },
  '17-Gemini': { symbol: 'The head of health dissolved into the head of mentality', meaning: 'Mind over body. Intellect transcending physical concerns.' },
  '18-Gemini': { symbol: 'Two Chinese men talking Chinese', meaning: 'Specialized communication. Understanding within a closed system.' },
  '19-Gemini': { symbol: 'A large archaic volume', meaning: 'Ancient wisdom. Knowledge preserved from the past.' },
  '20-Gemini': { symbol: 'A cafeteria', meaning: 'Self-service. Choosing what nourishes from available options.' },
  '21-Gemini': { symbol: 'A labor demonstration', meaning: 'Collective voice. Demanding recognition and fair treatment.' },
  '22-Gemini': { symbol: 'A barn dance', meaning: 'Community celebration. Simple joy in togetherness.' },
  '23-Gemini': { symbol: 'Three fledglings in a nest high in a tree', meaning: 'Early development in protected circumstances. Potential before flight.' },
  '24-Gemini': { symbol: 'Children skating on ice', meaning: 'Joyful mastery of challenging conditions. Grace on slippery ground.' },
  '25-Gemini': { symbol: 'A man trimming palms', meaning: 'Shaping growth. Careful cultivation of the exotic.' },
  '26-Gemini': { symbol: 'Winter frost in the woods', meaning: 'Nature in stillness. Beauty in dormancy.' },
  '27-Gemini': { symbol: 'A gypsy coming out of the forest', meaning: 'Free spirit emerging. Unconventional wisdom entering the open.' },
  '28-Gemini': { symbol: 'A bankruptcy granted to society', meaning: 'Fresh start. Release from unsustainable obligations.' },
  '29-Gemini': { symbol: 'The first mockingbird of spring', meaning: 'New voice. Communication heralding renewal.' },
  '30-Gemini': { symbol: 'A parade of bathing beauties', meaning: 'Physical display. Celebration of form and attractiveness.' },

  // CANCER (1-30)
  '1-Cancer': { symbol: 'A man on a ship furling sails', meaning: 'Preparing for port. Adjusting to calmer conditions ahead.' },
  '2-Cancer': { symbol: 'A man suspended over a vast level place', meaning: 'Detached perspective. Seeing the whole from above.' },
  '3-Cancer': { symbol: 'An arctic explorer leads a reindeer', meaning: 'Navigation through harsh conditions. Resourcefulness in extremity.' },
  '4-Cancer': { symbol: 'A cat arguing with a mouse', meaning: 'Power imbalance disguised as dialogue. Unequal negotiation.' },
  '5-Cancer': { symbol: 'An automobile wrecked by a train', meaning: 'Individual versus collective force. Personal plans disrupted by larger powers.' },
  '6-Cancer': { symbol: 'Game birds feathering their nests', meaning: 'Preparing the home. Comfort-building instincts.' },
  '7-Cancer': { symbol: 'Two fairies on a moonlit night', meaning: 'Magical connection. Subtle beings in harmony.' },
  '8-Cancer': { symbol: 'Rabbits dressed in clothes and on parade', meaning: 'Instinct dressed up. Natural behavior in social costume.' },
  '9-Cancer': { symbol: 'A small naked girl bends over a pond trying to catch a fish', meaning: 'Innocent exploration. Trusting approach to emotional depths.' },
  '10-Cancer': { symbol: 'A large diamond not completely cut', meaning: 'Potential not fully realized. Value awaiting refinement.' },
  '11-Cancer': { symbol: 'A clown making grimaces', meaning: 'Exaggerated expression. Using humor to convey truth.' },
  '12-Cancer': { symbol: 'A Chinese woman nursing a baby with a message', meaning: 'Nurturing wisdom. Care that communicates deeper meaning.' },
  '13-Cancer': { symbol: 'One hand slightly flexed with a very prominent thumb', meaning: 'Will power. Determination through subtle strength.' },
  '14-Cancer': { symbol: 'A very old man facing a vast dark space to the northeast', meaning: 'Wisdom contemplating mystery. Experience meeting the unknown.' },
  '15-Cancer': { symbol: 'A group of people who have overeaten and enjoyed it', meaning: 'Sensory indulgence. Satisfaction without guilt.' },
  '16-Cancer': { symbol: 'A man before a square with a manuscript scroll', meaning: 'Teaching in public. Sharing knowledge with the community.' },
  '17-Cancer': { symbol: 'The germ grows into knowledge and life', meaning: 'Seed of understanding developing. Learning that becomes living.' },
  '18-Cancer': { symbol: 'A hen scratching for her chicks', meaning: 'Maternal provision. Finding nourishment for dependents.' },
  '19-Cancer': { symbol: 'A priest performing a marriage ceremony', meaning: 'Sacred union. Official blessing of commitment.' },
  '20-Cancer': { symbol: 'Gondoliers in a serenade', meaning: 'Romantic transport. Emotion carried by music and movement.' },
  '21-Cancer': { symbol: 'A prima donna singing', meaning: 'Emotional expression at its peak. Voice commanding attention.' },
  '22-Cancer': { symbol: 'A woman awaiting a sailboat', meaning: 'Patient anticipation. Watching for arrival from afar.' },
  '23-Cancer': { symbol: 'The meeting of a literary society', meaning: 'Intellectual community. Minds gathered around words.' },
  '24-Cancer': { symbol: 'A woman and two men on a bit of sunlit land facing south', meaning: 'Choice between paths. Triangular dynamics in the light.' },
  '25-Cancer': { symbol: 'A leader of men wrapped in an invisible cloak of power', meaning: 'Unseen authority. Influence that works behind the scenes.' },
  '26-Cancer': { symbol: 'Contentment and happiness in luxury, people reading on a davenport', meaning: 'Comfortable learning. Knowledge absorbed in ease.' },
  '27-Cancer': { symbol: 'A violent storm in a canyon filled with expensive homes', meaning: 'Crisis in privilege. Wealth unable to prevent disruption.' },
  '28-Cancer': { symbol: 'An Indian girl introduces her white lover to the tribe', meaning: 'Cultural bridge. Love crossing boundaries.' },
  '29-Cancer': { symbol: 'A Muse weighing twins', meaning: 'Creative judgment. Inspiration balancing opposites.' },
  '30-Cancer': { symbol: 'A daughter of the American revolution', meaning: 'Heritage identity. Pride in historical lineage.' },

  // LEO (1-30)
  '1-Leo': { symbol: 'A case of apoplexy', meaning: 'Sudden crisis of excess. Vital force overwhelmed.' },
  '2-Leo': { symbol: 'An epidemic of mumps', meaning: 'Collective affliction. Shared vulnerability.' },
  '3-Leo': { symbol: 'A woman having her hair bobbed', meaning: 'Style change. Shedding the old for a new look.' },
  '4-Leo': { symbol: 'A man formally dressed and a deer with its horns folded', meaning: 'Civilization and nature in contrast. Power restrained.' },
  '5-Leo': { symbol: 'Rock formations at the edge of a precipice', meaning: 'Endurance at the edge. Stability where danger looms.' },
  '6-Leo': { symbol: 'An old-fashioned conservative woman confronted by an up-to-date girl', meaning: 'Generation gap. Tradition meets modernity.' },
  '7-Leo': { symbol: 'The constellations in the sky', meaning: 'Cosmic patterns. Meaning written in the heavens.' },
  '8-Leo': { symbol: 'A Bolshevik propagandist', meaning: 'Revolutionary message. Ideas that threaten the order.' },
  '9-Leo': { symbol: 'Glass blowers', meaning: 'Shaping through breath. Creating beauty from raw material.' },
  '10-Leo': { symbol: 'Early morning dew', meaning: 'Fresh beginning. Renewal at dawn.' },
  '11-Leo': { symbol: 'Children on a swing in a huge oak tree', meaning: 'Joy supported by strength. Play grounded in stability.' },
  '12-Leo': { symbol: 'An evening party of adults on a lawn illumined by lanterns', meaning: 'Civilized gathering. Social grace in natural setting.' },
  '13-Leo': { symbol: 'An old sea captain rocking', meaning: 'Rest after voyages. Experience in repose.' },
  '14-Leo': { symbol: 'A human soul awaiting opportunity for expression', meaning: 'Potential seeking form. Spirit before manifestation.' },
  '15-Leo': { symbol: 'A pageant', meaning: 'Historical display. Community celebrating its story.' },
  '16-Leo': { symbol: 'Brilliant sunshine after a storm', meaning: 'Clarity after crisis. Relief and illumination.' },
  '17-Leo': { symbol: 'A volunteer church choir', meaning: 'Willing service to the sacred. Harmony offered freely.' },
  '18-Leo': { symbol: 'A teacher of chemistry', meaning: 'Explaining transformations. Understanding change at fundamental levels.' },
  '19-Leo': { symbol: 'A houseboat party', meaning: 'Mobile celebration. Joy that floats above the depths.' },
  '20-Leo': { symbol: 'American Indians perform a majestic ritual to the sun', meaning: 'Sacred honoring of source. Ceremony acknowledging life-giver.' },
  '21-Leo': { symbol: 'Chickens intoxicated', meaning: 'Disorientation in the flock. Collective confusion.' },
  '22-Leo': { symbol: 'A carrier pigeon', meaning: 'Message bearing. Instinctual communication across distance.' },
  '23-Leo': { symbol: 'A bareback rider', meaning: 'Direct connection. Mastery without artificial aids.' },
  '24-Leo': { symbol: 'A totally concentrated and completely rugged individual', meaning: 'Focused strength. Will condensed into action.' },
  '25-Leo': { symbol: 'A large camel crossing the desert', meaning: 'Endurance for the journey. Resources for the long haul.' },
  '26-Leo': { symbol: 'A rainbow', meaning: 'Promise after storm. Beauty bridging sky and earth.' },
  '27-Leo': { symbol: 'The luminescence of dawn in the eastern sky', meaning: 'First light. Hope appearing on the horizon.' },
  '28-Leo': { symbol: 'Many little birds on the limb of a large tree', meaning: 'Community in support. Many finding home in one.' },
  '29-Leo': { symbol: 'A mermaid', meaning: 'Dual nature. Soul between elements.' },
  '30-Leo': { symbol: 'An unsealed letter', meaning: 'Open communication. Message available to all who look.' },

  // VIRGO (1-30)
  '1-Virgo': { symbol: 'A man\'s head', meaning: 'Pure intellect. Mind as essence.' },
  '2-Virgo': { symbol: 'A large white cross upraised', meaning: 'Sacrifice honored. Spirit triumphing through surrender.' },
  '3-Virgo': { symbol: 'Two guardian angels', meaning: 'Protective presences. Guidance from higher realms.' },
  '4-Virgo': { symbol: 'A colored child playing with white children', meaning: 'Innocence transcending difference. Unity before prejudice.' },
  '5-Virgo': { symbol: 'A man dreaming of fairies', meaning: 'Imagination active. Mind visiting magical realms.' },
  '6-Virgo': { symbol: 'A merry-go-round', meaning: 'Circular journey. Joy in repetitive motion.' },
  '7-Virgo': { symbol: 'A harem', meaning: 'Enclosed beauty. Restricted feminine power.' },
  '8-Virgo': { symbol: 'First dancing instruction', meaning: 'Learning grace. Beginning steps toward harmony.' },
  '9-Virgo': { symbol: 'A man making a futuristic drawing', meaning: 'Vision ahead of time. Imagination designing tomorrow.' },
  '10-Virgo': { symbol: 'Two heads looking out and beyond the shadows', meaning: 'Dual perspective seeking light. Minds transcending darkness.' },
  '11-Virgo': { symbol: 'A boy molded in his mother\'s aspirations for him', meaning: 'Shaped by maternal vision. Identity formed by another\'s dreams.' },
  '12-Virgo': { symbol: 'A bride with her veil snatched away', meaning: 'Illusion removed. Reality exposed unexpectedly.' },
  '13-Virgo': { symbol: 'A strong hand supplanting political hysteria', meaning: 'Calm authority ending chaos. Order restored by will.' },
  '14-Virgo': { symbol: 'A family tree', meaning: 'Lineage traced. Identity in ancestry.' },
  '15-Virgo': { symbol: 'A fine lace ornamental handkerchief', meaning: 'Delicate craft. Beauty in minute detail.' },
  '16-Virgo': { symbol: 'An orangutan', meaning: 'Primal intelligence. Nature\'s problem-solving.' },
  '17-Virgo': { symbol: 'A volcano in eruption', meaning: 'Explosive release. Hidden forces surfacing violently.' },
  '18-Virgo': { symbol: 'A Ouija board', meaning: 'Communication with the unseen. Messages from beyond normal channels.' },
  '19-Virgo': { symbol: 'A swimming race', meaning: 'Emotional competition. Striving through feeling.' },
  '20-Virgo': { symbol: 'A caravan of cars headed to the west coast', meaning: 'Collective journey toward dreams. Mass migration to possibility.' },
  '21-Virgo': { symbol: 'A girls\' basketball team', meaning: 'Feminine teamwork. Cooperative achievement.' },
  '22-Virgo': { symbol: 'A royal coat of arms', meaning: 'Authority emblazoned. Identity through heraldry.' },
  '23-Virgo': { symbol: 'An animal trainer', meaning: 'Mastering instinct. Will commanding nature.' },
  '24-Virgo': { symbol: 'Mary and her white lamb', meaning: 'Innocent devotion. Purity in companionship.' },
  '25-Virgo': { symbol: 'A flag at half-mast', meaning: 'Mourning respected. Honor in grief.' },
  '26-Virgo': { symbol: 'A boy with a censer', meaning: 'Young service to the sacred. Devotion in training.' },
  '27-Virgo': { symbol: 'Grande dames at tea', meaning: 'Refined social ritual. Power in courtesy.' },
  '28-Virgo': { symbol: 'A baldheaded man in uniform has seized power', meaning: 'Stark authority. Leadership stripped of pretense.' },
  '29-Virgo': { symbol: 'A man gaining secret knowledge from a paper', meaning: 'Hidden truth discovered. Information others miss.' },
  '30-Virgo': { symbol: 'Having an urgent task, a man doesn\'t look to distractions', meaning: 'Focused purpose. Mission overriding all else.' },

  // LIBRA (1-30)
  '1-Libra': { symbol: 'A butterfly made perfect by a dart through it', meaning: 'Beauty preserved through sacrifice. Perfection at a cost.' },
  '2-Libra': { symbol: 'The light of the sixth race transmuted to the seventh', meaning: 'Evolution of consciousness. Humanity advancing.' },
  '3-Libra': { symbol: 'The dawn of a new day reveals everything changed', meaning: 'Transformation overnight. New perspective on awakening.' },
  '4-Libra': { symbol: 'A group around a campfire', meaning: 'Primal community. Warmth and stories shared.' },
  '5-Libra': { symbol: 'A man teaching the true inner knowledge', meaning: 'Esoteric instruction. Wisdom transmitted heart to heart.' },
  '6-Libra': { symbol: 'The ideals of a man abundantly crystallized', meaning: 'Vision made manifest. Dreams become form.' },
  '7-Libra': { symbol: 'A woman feeding chickens and protecting them from hawks', meaning: 'Nurturing with vigilance. Care against threats.' },
  '8-Libra': { symbol: 'A blazing fireplace in a deserted home', meaning: 'Warmth in emptiness. Spirit persisting despite absence.' },
  '9-Libra': { symbol: 'Three old masters hanging in an art gallery', meaning: 'Timeless achievement displayed. Mastery honored.' },
  '10-Libra': { symbol: 'A canoe approaching safety through dangerous waters', meaning: 'Skillful navigation of peril. Reaching shore.' },
  '11-Libra': { symbol: 'A professor peering over his glasses', meaning: 'Wisdom assessing. Expertise examining reality.' },
  '12-Libra': { symbol: 'Miners emerging from a deep coal mine', meaning: 'Bringing treasure from darkness. Labor surfacing.' },
  '13-Libra': { symbol: 'Children blowing soap bubbles', meaning: 'Playful creation. Joy in transient beauty.' },
  '14-Libra': { symbol: 'A noon siesta', meaning: 'Rest at peak. Pause at the height of day.' },
  '15-Libra': { symbol: 'Circular paths', meaning: 'Return to origin. Cycles completing.' },
  '16-Libra': { symbol: 'A boat landing in need of reconstruction after a storm', meaning: 'Rebuilding after chaos. Restoration of connection.' },
  '17-Libra': { symbol: 'A retired sea captain', meaning: 'Voyage completed. Experience at rest.' },
  '18-Libra': { symbol: 'Two men placed under arrest', meaning: 'Freedom curtailed. Authority constraining action.' },
  '19-Libra': { symbol: 'A gang of robbers in hiding', meaning: 'Transgression concealed. Outlaws waiting.' },
  '20-Libra': { symbol: 'A Jewish rabbi', meaning: 'Traditional wisdom. Law interpreted with depth.' },
  '21-Libra': { symbol: 'A crowd upon a beach', meaning: 'Mass at the edge. Collective meeting the infinite.' },
  '22-Libra': { symbol: 'A child giving birds a drink at a fountain', meaning: 'Innocent generosity. Nature served with love.' },
  '23-Libra': { symbol: 'Chanticleer', meaning: 'Proud announcement. Voice heralding the new day.' },
  '24-Libra': { symbol: 'A butterfly with a third wing on the left side', meaning: 'Unusual development. Evolution beyond the norm.' },
  '25-Libra': { symbol: 'The sight of an autumn leaf brings sudden awareness', meaning: 'Mortality glimpsed. Change triggering insight.' },
  '26-Libra': { symbol: 'An eagle and a white dove turning into each other', meaning: 'Power and peace exchanging. Opposites becoming one.' },
  '27-Libra': { symbol: 'An airplane hovering overhead', meaning: 'Perspective from above. Overview maintained.' },
  '28-Libra': { symbol: 'A man in the midst of brightening influences', meaning: 'Illumination surrounding. Light increasing around one.' },
  '29-Libra': { symbol: 'Humanity seeking to bridge the span of knowledge', meaning: 'Collective learning. Minds reaching toward understanding.' },
  '30-Libra': { symbol: 'Three mounds of knowledge on a philosopher\'s head', meaning: 'Accumulated wisdom. Learning visible in form.' },

  // SCORPIO (1-30)
  '1-Scorpio': { symbol: 'A crowded sightseeing bus', meaning: 'Collective observation. Many seeing together.' },
  '2-Scorpio': { symbol: 'A broken bottle and spilled perfume', meaning: 'Fragrance released through destruction. Beauty in breakage.' },
  '3-Scorpio': { symbol: 'A house-raising', meaning: 'Community building. Many hands creating shelter.' },
  '4-Scorpio': { symbol: 'A youth carrying a lighted candle', meaning: 'Light carried forward. Hope in young hands.' },
  '5-Scorpio': { symbol: 'A massive rocky shore', meaning: 'Immovable meeting the waves. Endurance against force.' },
  '6-Scorpio': { symbol: 'A gold rush', meaning: 'Collective fever for wealth. Mass pursuit of treasure.' },
  '7-Scorpio': { symbol: 'Deep-sea divers', meaning: 'Exploration of depths. Searching where others cannot breathe.' },
  '8-Scorpio': { symbol: 'A calm lake bathed in moonlight', meaning: 'Emotional stillness reflecting spirit. Peace under night sky.' },
  '9-Scorpio': { symbol: 'A dentist at work', meaning: 'Removing decay. Painful healing.' },
  '10-Scorpio': { symbol: 'A fellowship supper', meaning: 'Communion through sharing. Bonds strengthened by breaking bread.' },
  '11-Scorpio': { symbol: 'A drowning man rescued', meaning: 'Salvation from depths. Life pulled from death.' },
  '12-Scorpio': { symbol: 'An embassy ball', meaning: 'Diplomatic celebration. Nations meeting in festivity.' },
  '13-Scorpio': { symbol: 'An inventor experimenting', meaning: 'Creative exploration. Mind testing possibilities.' },
  '14-Scorpio': { symbol: 'Telephone linemen at work', meaning: 'Connecting communications. Infrastructure of contact.' },
  '15-Scorpio': { symbol: 'Children playing around five mounds of sand', meaning: 'Innocent creation. Play with elemental forms.' },
  '16-Scorpio': { symbol: 'A girl\'s face breaking into a smile', meaning: 'Joy emerging. Happiness surfacing unexpectedly.' },
  '17-Scorpio': { symbol: 'A woman the father of her own child', meaning: 'Self-generation. Creating one\'s own becoming.' },
  '18-Scorpio': { symbol: 'A woods rich in autumn coloring', meaning: 'Beauty in decay. Transformation as spectacle.' },
  '19-Scorpio': { symbol: 'A parrot listening and then talking', meaning: 'Learning by imitation. Wisdom absorbed and repeated.' },
  '20-Scorpio': { symbol: 'A woman drawing two dark curtains aside', meaning: 'Revelation approaching. Preparing to see what was hidden.' },
  '21-Scorpio': { symbol: 'A soldier derelict in duty', meaning: 'Failed responsibility. Obligation abandoned.' },
  '22-Scorpio': { symbol: 'Hunters starting out for ducks', meaning: 'Purposeful pursuit. Setting out to capture.' },
  '23-Scorpio': { symbol: 'A bunny metamorphosed into a fairy', meaning: 'Transformation of innocence. Nature becoming magical.' },
  '24-Scorpio': { symbol: 'Crowds coming down a mountain', meaning: 'Descent from heights. Return from peak experience.' },
  '25-Scorpio': { symbol: 'An X-ray', meaning: 'Seeing through surface. Penetrating vision.' },
  '26-Scorpio': { symbol: 'American Indians making camp', meaning: 'Temporary home. Shelter in mobility.' },
  '27-Scorpio': { symbol: 'A military band on the march', meaning: 'Organized power advancing. Discipline in motion.' },
  '28-Scorpio': { symbol: 'The king of the fairies approaching his domain', meaning: 'Ruler of the subtle realms. Authority in the invisible.' },
  '29-Scorpio': { symbol: 'An Indian squaw pleading for the lives of her children', meaning: 'Desperate protection. Mother\'s ultimate appeal.' },
  '30-Scorpio': { symbol: 'Children in Halloween costumes', meaning: 'Playing with shadows. Innocence exploring the dark.' },

  // SAGITTARIUS (1-30)
  '1-Sagittarius': { symbol: 'Retired army veterans gather', meaning: 'Shared experience recalled. Bonds of past challenges.' },
  '2-Sagittarius': { symbol: 'The ocean covered with whitecaps', meaning: 'Emotional energy displayed. Surface agitation of depths.' },
  '3-Sagittarius': { symbol: 'Two men playing chess', meaning: 'Strategic engagement. Minds in formal contest.' },
  '4-Sagittarius': { symbol: 'A little child learning to walk', meaning: 'First steps. Beginning the journey upright.' },
  '5-Sagittarius': { symbol: 'An old owl in a tree', meaning: 'Wisdom watching. Ancient knowing in stillness.' },
  '6-Sagittarius': { symbol: 'A game of cricket', meaning: 'Civilized competition. Sport with tradition.' },
  '7-Sagittarius': { symbol: 'Cupid knocking at the door', meaning: 'Love arriving. Romance seeking entry.' },
  '8-Sagittarius': { symbol: 'Deep within the earth, new elements are being formed', meaning: 'Hidden transformation. Change in the core.' },
  '9-Sagittarius': { symbol: 'A mother with her children on stairs', meaning: 'Guided ascent. Family moving upward together.' },
  '10-Sagittarius': { symbol: 'A golden-haired goddess of opportunity', meaning: 'Fortune presenting itself. Chance appearing beautifully.' },
  '11-Sagittarius': { symbol: 'The lamp of physical enlightenment at the left temple', meaning: 'Body wisdom illuminated. Instinct honored.' },
  '12-Sagittarius': { symbol: 'A flag that turns into an eagle', meaning: 'Symbol becoming living power. Ideal taking flight.' },
  '13-Sagittarius': { symbol: 'A widow\'s past is brought to light', meaning: 'History revealed. Past coming into present view.' },
  '14-Sagittarius': { symbol: 'The Pyramids and the Sphinx', meaning: 'Ancient mystery enduring. Riddle across ages.' },
  '15-Sagittarius': { symbol: 'The ground hog looking for its shadow', meaning: 'Self-awareness through reflection. Seeking one\'s own sign.' },
  '16-Sagittarius': { symbol: 'Sea gulls watching a ship', meaning: 'Nature observing human endeavor. Freedom watching journey.' },
  '17-Sagittarius': { symbol: 'An Easter sunrise service', meaning: 'Resurrection celebrated. Light returning from darkness.' },
  '18-Sagittarius': { symbol: 'Tiny children in sunbonnets', meaning: 'Protected innocence. Youth shielded from intensity.' },
  '19-Sagittarius': { symbol: 'Pelicans moving their habitat', meaning: 'Mass relocation. Community adapting to change.' },
  '20-Sagittarius': { symbol: 'Men cutting through ice', meaning: 'Breaking frozen conditions. Effort to free flow.' },
  '21-Sagittarius': { symbol: 'A child and a dog with borrowed eyeglasses', meaning: 'Playful perspective shift. Innocence trying on vision.' },
  '22-Sagittarius': { symbol: 'A Chinese laundry', meaning: 'Service in foreign context. Work crossing cultures.' },
  '23-Sagittarius': { symbol: 'Immigrants entering a new country', meaning: 'New beginning in strange land. Courage of relocation.' },
  '24-Sagittarius': { symbol: 'A bluebird standing at the door of the house', meaning: 'Happiness at threshold. Joy ready to enter.' },
  '25-Sagittarius': { symbol: 'A chubby boy on a hobbyhorse', meaning: 'Playful pretense. Imagination riding nowhere.' },
  '26-Sagittarius': { symbol: 'A flag-bearer', meaning: 'Carrying the standard. Embodying the cause.' },
  '27-Sagittarius': { symbol: 'A sculptor', meaning: 'Form from formlessness. Vision made solid.' },
  '28-Sagittarius': { symbol: 'An old bridge over a beautiful stream', meaning: 'Connection enduring. Way across time-tested.' },
  '29-Sagittarius': { symbol: 'A fat boy mowing the lawn', meaning: 'Effort despite condition. Work regardless of form.' },
  '30-Sagittarius': { symbol: 'The Pope blessing the faithful', meaning: 'Spiritual authority extended. Blessing from the heights.' },

  // CAPRICORN (1-30)
  '1-Capricorn': { symbol: 'An Indian chief demanding recognition', meaning: 'Authority asserting itself. Leadership claiming due respect.' },
  '2-Capricorn': { symbol: 'Three stained glass windows in a Gothic church', meaning: 'Light transformed by art. Spirit filtered through beauty.' },
  '3-Capricorn': { symbol: 'The human soul awaiting opportunity for expression', meaning: 'Potential before manifestation. Spirit seeking form.' },
  '4-Capricorn': { symbol: 'A party entering a large canoe', meaning: 'Collective journey beginning. Group embarking together.' },
  '5-Capricorn': { symbol: 'Indians on the warpath', meaning: 'Defensive aggression. Culture protecting itself.' },
  '6-Capricorn': { symbol: 'A dark archway, ten logs at the bottom', meaning: 'Foundation in darkness. Support beneath the threshold.' },
  '7-Capricorn': { symbol: 'A veiled prophet of power', meaning: 'Hidden authority. Wisdom concealed yet potent.' },
  '8-Capricorn': { symbol: 'Birds in the house singing happily', meaning: 'Nature domesticated joyfully. Wildness content in shelter.' },
  '9-Capricorn': { symbol: 'An angel carrying a harp', meaning: 'Divine harmony. Heaven\'s music brought down.' },
  '10-Capricorn': { symbol: 'An albatross feeding from the hand', meaning: 'Wild spirit accepting contact. Trust from the free.' },
  '11-Capricorn': { symbol: 'Pheasants display their brilliant colors', meaning: 'Natural beauty exhibited. Magnificence shown.' },
  '12-Capricorn': { symbol: 'A student of nature lecturing', meaning: 'Knowledge shared. Learning become teaching.' },
  '13-Capricorn': { symbol: 'A fire worshipper', meaning: 'Devotion to transformation. Spirit through flame.' },
  '14-Capricorn': { symbol: 'An ancient bas-relief carved in granite', meaning: 'Permanent record. History in stone.' },
  '15-Capricorn': { symbol: 'A hospital children\'s ward', meaning: 'Care for young vulnerability. Healing the innocent.' },
  '16-Capricorn': { symbol: 'School grounds filled with boys and girls in gym suits', meaning: 'Youth in training. Bodies being developed.' },
  '17-Capricorn': { symbol: 'A girl surreptitiously bathing in the nude', meaning: 'Private naturalness. Innocence hidden from judgment.' },
  '18-Capricorn': { symbol: 'The Union Jack', meaning: 'Empire symbol. Authority through tradition.' },
  '19-Capricorn': { symbol: 'A five-year-old child carrying a bag of groceries', meaning: 'Responsibility beyond years. Early burden.' },
  '20-Capricorn': { symbol: 'A hidden choir singing', meaning: 'Unseen harmony. Music from mystery.' },
  '21-Capricorn': { symbol: 'A relay race', meaning: 'Cooperative speed. Success through handoff.' },
  '22-Capricorn': { symbol: 'A general accepting defeat gracefully', meaning: 'Dignity in loss. Honor despite failure.' },
  '23-Capricorn': { symbol: 'Two awards for bravery in war', meaning: 'Courage recognized. Valor honored.' },
  '24-Capricorn': { symbol: 'A woman entering a convent', meaning: 'Sacred withdrawal. Life devoted to spirit.' },
  '25-Capricorn': { symbol: 'An oriental rug dealer', meaning: 'Exotic commerce. Beauty traded.' },
  '26-Capricorn': { symbol: 'A water sprite', meaning: 'Elemental playfulness. Spirit in the flow.' },
  '27-Capricorn': { symbol: 'A mountain pilgrimage', meaning: 'Sacred ascent. Spirit climbing toward source.' },
  '28-Capricorn': { symbol: 'A large aviary', meaning: 'Diverse creatures contained. Variety in enclosure.' },
  '29-Capricorn': { symbol: 'A woman reading tea leaves', meaning: 'Divination from ordinary. Signs in the mundane.' },
  '30-Capricorn': { symbol: 'A secret business conference', meaning: 'Hidden negotiations. Power meeting privately.' },

  // AQUARIUS (1-30)
  '1-Aquarius': { symbol: 'An old adobe mission', meaning: 'Ancient spiritual outpost. Faith persisting in structure.' },
  '2-Aquarius': { symbol: 'An unexpected thunderstorm', meaning: 'Sudden disruption. Surprise clearing the air.' },
  '3-Aquarius': { symbol: 'A deserter from the navy', meaning: 'Rejection of collective duty. Individual refusing the system.' },
  '4-Aquarius': { symbol: 'A Hindu healer', meaning: 'Ancient medicine. Wisdom healing across tradition.' },
  '5-Aquarius': { symbol: 'A council of ancestors', meaning: 'Elders advising. Past wisdom consulted.' },
  '6-Aquarius': { symbol: 'A performer of a mystery play', meaning: 'Sacred drama enacted. Spirit through theater.' },
  '7-Aquarius': { symbol: 'A child born of an eggshell', meaning: 'Unusual origin. New life from unexpected source.' },
  '8-Aquarius': { symbol: 'Beautifully gowned wax figures', meaning: 'Frozen beauty. Form without life.' },
  '9-Aquarius': { symbol: 'A flag turned into an eagle', meaning: 'Symbol becoming power. Ideal taking living form.' },
  '10-Aquarius': { symbol: 'A popularity that proves ephemeral', meaning: 'Fame that fades. Recognition temporary.' },
  '11-Aquarius': { symbol: 'Man tête-à-tête with his inspiration', meaning: 'Direct communion with muse. Intimate creative contact.' },
  '12-Aquarius': { symbol: 'People on stairs graduated upward', meaning: 'Hierarchy ascending. Levels of development.' },
  '13-Aquarius': { symbol: 'A barometer', meaning: 'Pressure measured. Change predicted.' },
  '14-Aquarius': { symbol: 'A train entering a tunnel', meaning: 'Passage through darkness. Journey into hidden space.' },
  '15-Aquarius': { symbol: 'Two lovebirds sitting on a fence', meaning: 'Companionship poised. Partnership balanced.' },
  '16-Aquarius': { symbol: 'A big businessman at his desk', meaning: 'Authority in commerce. Power through organization.' },
  '17-Aquarius': { symbol: 'A watchdog standing guard', meaning: 'Protective alertness. Loyalty maintaining boundaries.' },
  '18-Aquarius': { symbol: 'A man being unmasked at a masquerade', meaning: 'Identity revealed. Truth exposed at play.' },
  '19-Aquarius': { symbol: 'A forest fire quenched', meaning: 'Destruction stopped. Crisis contained.' },
  '20-Aquarius': { symbol: 'A big white dove, a message bearer', meaning: 'Peace bringing news. Spirit communicating.' },
  '21-Aquarius': { symbol: 'A woman disappointed and disillusioned', meaning: 'Dreams shattered. Reality harsh.' },
  '22-Aquarius': { symbol: 'A rug placed on a floor for children to play on', meaning: 'Safety provided. Space prepared for innocence.' },
  '23-Aquarius': { symbol: 'A big bear sitting down, waving all its paws', meaning: 'Power at rest. Strength in playful display.' },
  '24-Aquarius': { symbol: 'A man, having overcome his passions, teaches deep wisdom', meaning: 'Mastery enabling teaching. Freedom from desire granting insight.' },
  '25-Aquarius': { symbol: 'A butterfly with the right wing more perfectly formed', meaning: 'Uneven development. Beauty asymmetrical.' },
  '26-Aquarius': { symbol: 'A hydrometer', meaning: 'Measurement of density. Testing what is hidden.' },
  '27-Aquarius': { symbol: 'An ancient pottery bowl filled with violets', meaning: 'Old vessel holding fresh beauty. Past containing present sweetness.' },
  '28-Aquarius': { symbol: 'A tree felled and sawed', meaning: 'Growth ended for use. Life becomes material.' },
  '29-Aquarius': { symbol: 'A butterfly emerging from a chrysalis', meaning: 'Transformation complete. New form revealed.' },
  '30-Aquarius': { symbol: 'Deeply rooted in the past, a spiritual aristocracy', meaning: 'Heritage of wisdom. Nobility through lineage of spirit.' },

  // PISCES (1-30)
  '1-Pisces': { symbol: 'A public market', meaning: 'Open exchange. Goods and people mixing.' },
  '2-Pisces': { symbol: 'A squirrel hiding from hunters', meaning: 'Survival instinct. Avoiding threat through concealment.' },
  '3-Pisces': { symbol: 'A petrified forest', meaning: 'Life become stone. Past preserved in mineral.' },
  '4-Pisces': { symbol: 'Heavy traffic on a narrow isthmus', meaning: 'Flow through constriction. Many passing through little.' },
  '5-Pisces': { symbol: 'A church bazaar', meaning: 'Sacred commerce. Spirit meeting material need.' },
  '6-Pisces': { symbol: 'A parade of army officers in full dress', meaning: 'Authority displayed. Power in ceremony.' },
  '7-Pisces': { symbol: 'A cross on rocks', meaning: 'Faith in difficult ground. Spirit on hard foundation.' },
  '8-Pisces': { symbol: 'A girl blowing a bugle', meaning: 'Call sounded. Alert given.' },
  '9-Pisces': { symbol: 'A jockey', meaning: 'Control of power. Skill directing force.' },
  '10-Pisces': { symbol: 'An aviator in the clouds', meaning: 'Flight above earth. Mind in the heights.' },
  '11-Pisces': { symbol: 'Men seeking illumination', meaning: 'Quest for light. Souls pursuing truth.' },
  '12-Pisces': { symbol: 'An examination of initiates', meaning: 'Testing of the ready. Qualification for mysteries.' },
  '13-Pisces': { symbol: 'A sword in a museum', meaning: 'Power preserved. Violence become history.' },
  '14-Pisces': { symbol: 'A lady in a fox fur', meaning: 'Nature adorning civilization. Wild beauty worn.' },
  '15-Pisces': { symbol: 'An officer preparing to drill his men', meaning: 'Authority about to act. Order to be imposed.' },
  '16-Pisces': { symbol: 'The flow of inspiration', meaning: 'Creative current moving. Source to expression.' },
  '17-Pisces': { symbol: 'An Easter promenade', meaning: 'Resurrection celebrated publicly. New life displayed.' },
  '18-Pisces': { symbol: 'A gigantic tent', meaning: 'Temporary shelter for many. Gathering under canvas.' },
  '19-Pisces': { symbol: 'A master instructing his pupil', meaning: 'Wisdom transmitted. Knowledge passed down.' },
  '20-Pisces': { symbol: 'A table set for an evening meal', meaning: 'Nourishment prepared. Sustenance awaiting.' },
  '21-Pisces': { symbol: 'A little white lamb, a child, and a Chinese servant', meaning: 'Innocence served. Purity attended.' },
  '22-Pisces': { symbol: 'A prophet bringing down the new law from Sinai', meaning: 'Divine mandate delivered. Heaven\'s word for earth.' },
  '23-Pisces': { symbol: 'Spiritist phenomena', meaning: 'Other dimensions manifest. Unseen made visible.' },
  '24-Pisces': { symbol: 'An inhabited island', meaning: 'Isolation with life. Separate world complete.' },
  '25-Pisces': { symbol: 'A religious organization succeeds', meaning: 'Spirit in structure works. Faith organized effectively.' },
  '26-Pisces': { symbol: 'A new moon that divides its influences', meaning: 'Beginning with duality. Fresh start with choices.' },
  '27-Pisces': { symbol: 'A harvest moon', meaning: 'Fullness of gathering. Abundance illuminated.' },
  '28-Pisces': { symbol: 'A fertile garden under the full moon', meaning: 'Growth at peak. Nature flourishing in light.' },
  '29-Pisces': { symbol: 'A majestic rock formation resembling a face', meaning: 'Nature as consciousness. Earth showing spirit.' },
  '30-Pisces': { symbol: 'The great stone face', meaning: 'Eternal countenance. Timeless wisdom in form.' },
};

/**
 * Get the Sabian symbol for a given degree and sign.
 * Degrees in astrology are typically 0-29, but Sabian symbols use 1-30.
 * Degree 0 of a sign = Symbol for degree 1.
 */
export const getSabianSymbol = (degree: number, sign: string): { symbol: string; meaning: string } => {
  // Sabian symbols are numbered 1-30, but astrological degrees are 0-29
  // So 0° = 1st degree symbol, 1° = 2nd degree symbol, etc.
  const sabianDegree = Math.floor(degree) + 1;
  const key = `${sabianDegree}-${sign}`;
  
  return SABIAN_SYMBOLS[key] || {
    symbol: `A hidden mystery at ${sabianDegree}° ${sign}`,
    meaning: `This degree activates deep ${sign} themes through subtle, personal resonance.`
  };
};
