// Zodiac Sign Encyclopedia — comprehensive data for all 12 signs

export interface ZodiacSignData {
  name: string;
  symbol: string;       // Unicode glyph ♈ etc.
  animal: string;       // Ram, Bull, etc.
  element: 'Fire' | 'Earth' | 'Air' | 'Water';
  modality: 'Cardinal' | 'Fixed' | 'Mutable';
  polarity: 'Yang' | 'Yin';
  polarityLabels: string[];  // e.g. ["Masculine", "Assertive"]
  rulingPlanet: string;
  planetSymbol: string;
  bodyRegion: string;
  mantra: string;
  affirmation: string;
  shadowMindset: string;
  mnemonic: string;
  superpower: string;
  areasToWorkOn: string[];
  essence: string[];     // multi-paragraph
  needs: string[];
  creativeExpression: string;
  keywords: string[];    // 3-5 core keywords
  highRoadKeywords: string[];  // positive expression keywords
  lowRoadKeywords: string[];   // shadow expression keywords
}

// The 6 sign axes — oppositions that form a spectrum of consciousness
export interface SignAxis {
  sign1: string;
  sign2: string;
  theme: string;
  spectrum: string;       // e.g. "Self ↔ Other"
  description: string;
  asAspect: string;       // what it means when planets oppose on this axis
  interceptedMeaning: string; // what it means if this axis is intercepted
  houses: [number, number]; // natural house rulers
}

export const SIGN_AXES: SignAxis[] = [
  {
    sign1: 'Aries', sign2: 'Libra',
    theme: 'Identity vs. Relationship',
    spectrum: 'Self ↔ Other',
    description: 'The Aries-Libra axis asks: How do I assert myself AND honor others? Aries acts alone; Libra seeks partnership. Mastery means doing both — leading without steamrolling, compromising without disappearing.',
    asAspect: 'Planets opposing across Aries-Libra create tension between independence and cooperation. You may feel pulled between "my way" and "our way." The growth is learning that your needs and others\' needs aren\'t mutually exclusive.',
    interceptedMeaning: 'When Aries-Libra is intercepted, the ability to assert yourself or truly partner feels locked. You may over-accommodate (intercepted Aries) or struggle to compromise (intercepted Libra). This energy develops later in life, often after a defining relationship teaches the lesson.',
    houses: [1, 7],
  },
  {
    sign1: 'Taurus', sign2: 'Scorpio',
    theme: 'Security vs. Transformation',
    spectrum: 'Mine ↔ Ours',
    description: 'Taurus holds on; Scorpio lets go. This axis governs what you own vs. what you share, comfort vs. crisis, building vs. destroying to rebuild. Both signs are fixed — this axis doesn\'t move easily.',
    asAspect: 'Planets opposing across Taurus-Scorpio pull between stability and upheaval. You want safety AND depth. The tension is: clinging to what\'s comfortable blocks transformation, but constant crisis prevents you from enjoying what you\'ve built.',
    interceptedMeaning: 'Intercepted Taurus-Scorpio makes it hard to feel truly secure or truly surrender. You may hoard resources (intercepted Scorpio) or avoid building anything permanent (intercepted Taurus). Trust — in yourself and others — develops slowly.',
    houses: [2, 8],
  },
  {
    sign1: 'Gemini', sign2: 'Sagittarius',
    theme: 'Information vs. Meaning',
    spectrum: 'Facts ↔ Wisdom',
    description: 'Gemini collects data; Sagittarius finds the story. This axis asks: Do you know a lot about a little, or a little about a lot? The integration is becoming someone who can gather information AND see the big picture.',
    asAspect: 'Planets opposing across Gemini-Sagittarius create tension between details and philosophy. You may swing between overthinking small things and making sweeping generalizations. Growth comes from honoring both the footnote and the thesis.',
    interceptedMeaning: 'Intercepted Gemini-Sagittarius can make it hard to speak your truth or find your belief system. Communication may feel stilted (intercepted Gemini) or conviction feels borrowed (intercepted Sagittarius). Travel, teaching, or writing often unlocks this axis.',
    houses: [3, 9],
  },
  {
    sign1: 'Cancer', sign2: 'Capricorn',
    theme: 'Home vs. Career',
    spectrum: 'Private ↔ Public',
    description: 'Cancer nurtures the inner world; Capricorn builds the outer one. This is the parent axis — the mother (Cancer) and the father (Capricorn). It asks: Can you be soft at home and strong in the world?',
    asAspect: 'Planets opposing across Cancer-Capricorn pull between emotional needs and ambition. You feel guilty working when family needs you, and restless at home when you could be building. Integration means redefining success to include both.',
    interceptedMeaning: 'Intercepted Cancer-Capricorn often shows up as confusion about where you belong — neither fully at home nor fully in your career. Parental dynamics may feel unresolved. This axis unlocks when you parent yourself.',
    houses: [4, 10],
  },
  {
    sign1: 'Leo', sign2: 'Aquarius',
    theme: 'Self-Expression vs. Collective',
    spectrum: 'Individual ↔ Community',
    description: 'Leo shines as "me"; Aquarius serves as "we." This axis asks: Can you stand out AND belong? Leo creates from the heart; Aquarius innovates for humanity. Both are fixed — neither bends easily.',
    asAspect: 'Planets opposing across Leo-Aquarius create tension between personal glory and group contribution. You want to be special AND equal. Growth is realizing your unique gifts are your contribution to the collective.',
    interceptedMeaning: 'Intercepted Leo-Aquarius makes it hard to feel seen for who you truly are. You may perform for approval (intercepted Aquarius) or hide your individuality in groups (intercepted Leo). Creative risk-taking unlocks this axis.',
    houses: [5, 11],
  },
  {
    sign1: 'Virgo', sign2: 'Pisces',
    theme: 'Order vs. Surrender',
    spectrum: 'Analyze ↔ Trust',
    description: 'Virgo sorts reality into categories; Pisces dissolves all categories. This is the healing axis — practical medicine (Virgo) meets spiritual faith (Pisces). It asks: Can you plan AND let go?',
    asAspect: 'Planets opposing across Virgo-Pisces pull between perfectionism and acceptance. You want everything precise AND flowing. The tension is: too much Virgo creates anxiety; too much Pisces creates chaos. Integration is "organized compassion."',
    interceptedMeaning: 'Intercepted Virgo-Pisces can make it hard to trust your own competence or your own intuition. You may overwork to compensate (intercepted Pisces) or escape into fantasy (intercepted Virgo). Service work often activates this axis.',
    houses: [6, 12],
  },
];

export const ZODIAC_SIGNS_DATA: ZodiacSignData[] = [
  {
    name: 'Aries',
    symbol: '♈',
    animal: 'Ram',
    element: 'Fire',
    modality: 'Cardinal',
    polarity: 'Yang',
    polarityLabels: ['Masculine', 'Assertive'],
    rulingPlanet: 'Mars',
    planetSymbol: '♂',
    bodyRegion: 'Head, face, eyes, brain',
    mantra: 'I take action',
    affirmation: 'If it can be done, I can do it.',
    shadowMindset: 'Faster is always better.',
    mnemonic: 'The strike of the match — cardinal fire. One quick scratch and the flame leaps to life. It doesn\'t wait. It ignites.',
    superpower: 'Most spontaneous of the signs',
    areasToWorkOn: ['Impatience', 'Impulsivity', 'Listening before acting'],
    essence: [
      'Aries is the initiator of the zodiac — the cardinal fire that lights every beginning. Like the first breath of spring, Aries bursts through winter\'s seal with raw, unfiltered vitality. There is no hesitation here, only action.',
      'Aries people are natural-born leaders, not because they seek followers but because they simply move first. They trust their instincts implicitly, sometimes to their detriment. Their courage is genuine — they run toward what others run from.',
      'The body remembers what the mind forgets: Aries rules the head, and these natives often lead with their forehead (literally and figuratively). Headaches, sinus issues, and eye strain are common Aries complaints. The remedy is physical release — running, boxing, anything that lets the body discharge its restless electrical energy.',
    ],
    needs: ['Independence', 'Physical outlets', 'New challenges', 'To be first', 'Directness from others'],
    creativeExpression: 'Aries creates in bursts — brilliant starts, bold strokes. They are the idea generators, the first drafts, the daring prototypes. Their art is kinetic, competitive, and alive with urgency.',
    keywords: ['Courage', 'Initiative', 'Independence', 'Impulse'],
    highRoadKeywords: ['Active', 'Adventurous', 'Independent', 'Self-motivated', 'Confident', 'Spontaneous', 'Enterprising', 'Leadership', 'Instinctive', 'Courageous', 'Direct', 'Daring', 'Pioneering', 'Bold', 'Energetic', 'Decisive', 'Passionate'],
    lowRoadKeywords: ['Self-centered', 'Egotistical', 'Domineering', 'Impatient', 'Restless', 'Demanding', 'Bullying', 'Starts but doesn\'t finish', 'Combative', 'Insensitive', 'Impulsive', 'Reckless', 'Aggressive', 'Short-tempered', 'Selfish'],
  },
  {
    name: 'Taurus',
    symbol: '♉',
    animal: 'Bull',
    element: 'Earth',
    modality: 'Fixed',
    polarity: 'Yin',
    polarityLabels: ['Feminine', 'Receptive'],
    rulingPlanet: 'Venus',
    planetSymbol: '♀',
    bodyRegion: 'Throat, neck, thyroid, vocal cords',
    mantra: 'I have enough',
    affirmation: 'I deserve beauty, comfort, and stability.',
    shadowMindset: 'Change is dangerous.',
    mnemonic: 'The roots of an ancient tree — fixed earth. They grip the ground so deep nothing can pull them up. Slow, silent, unmovable. They were growing before you arrived and they\'ll be here long after.',
    superpower: 'Most patient and enduring of the signs',
    areasToWorkOn: ['Stubbornness', 'Resistance to change', 'Possessiveness'],
    essence: [
      'Taurus is the fixed earth — the ground beneath your feet, the garden that yields only with patient tending. Where Aries sparks, Taurus sustains. This is the sign that builds empires not through speed but through sheer, unwavering persistence.',
      'The Taurus temperament is sensual in the truest sense: they experience life through touch, taste, smell, sound, and sight. A beautiful meal, soft fabric, a garden in bloom — these are not luxuries to Taurus but necessities. Beauty is oxygen.',
      'Taurus rules the throat, giving many Bulls a distinctive voice — rich, melodic, or commanding. Singers, speakers, and those who make a living by their voice often have strong Taurus placements. When stressed, the throat tightens; sore throats and thyroid issues signal a Taurus body out of alignment.',
    ],
    needs: ['Security', 'Physical comfort', 'Routine', 'Financial stability', 'Sensory pleasure'],
    creativeExpression: 'Taurus creates through craft — pottery, cooking, gardening, music. Their art is tangible, sensual, and built to last. They are the masters of form and texture.',
    keywords: ['Stability', 'Sensuality', 'Patience', 'Endurance'],
    highRoadKeywords: ['Patient', 'Reliable', 'Loyal', 'Sensual', 'Grounded', 'Persistent', 'Artistic', 'Practical', 'Devoted', 'Steady', 'Nurturing', 'Resourceful', 'Calm', 'Thorough', 'Generous'],
    lowRoadKeywords: ['Stubborn', 'Possessive', 'Materialistic', 'Greedy', 'Lazy', 'Resistant to change', 'Indulgent', 'Jealous', 'Inflexible', 'Complacent', 'Hoarding', 'Gluttonous', 'Stagnant'],
  },
  {
    name: 'Gemini',
    symbol: '♊',
    animal: 'Twins',
    element: 'Air',
    modality: 'Mutable',
    polarity: 'Yang',
    polarityLabels: ['Masculine', 'Assertive'],
    rulingPlanet: 'Mercury',
    planetSymbol: '☿',
    bodyRegion: 'Arms, hands, lungs, nervous system',
    mantra: 'I communicate',
    affirmation: 'My curiosity is my greatest gift.',
    shadowMindset: 'If I stop moving, I\'ll miss something.',
    mnemonic: 'The crosswind — mutable air. A breeze that shifts direction mid-gust, carrying pollen from one garden to the next. It pollinates everything it touches.',
    superpower: 'Most versatile and quick-witted of the signs',
    areasToWorkOn: ['Scattered focus', 'Superficiality', 'Nervous restlessness'],
    essence: [
      'Gemini is the mutable air — the mind in motion, the conversation that never ends. They are the connectors of the zodiac, weaving threads between people, ideas, and worlds that would otherwise never meet.',
      'The Twin archetype is misunderstood: it is not duplicity but duality. Gemini holds multiple truths simultaneously. They can see both sides of any argument, which makes them brilliant mediators but sometimes paralyzed decision-makers.',
      'Gemini rules the nervous system, arms, and hands. These people talk with their hands, think with their fingers, and need to write, text, or gesture to process. Carpal tunnel, anxiety, and insomnia are Gemini\'s body signals that the mind needs rest.',
    ],
    needs: ['Mental stimulation', 'Variety', 'Social connection', 'Information', 'Freedom to change'],
    creativeExpression: 'Gemini creates through language — writing, comedy, podcasting, teaching. Their art is verbal, clever, and often arrives in multiple formats simultaneously.',
    keywords: ['Curiosity', 'Versatility', 'Communication', 'Duality'],
    highRoadKeywords: ['Witty', 'Adaptable', 'Curious', 'Communicative', 'Versatile', 'Intellectual', 'Quick-thinking', 'Social', 'Playful', 'Clever', 'Articulate', 'Open-minded', 'Inventive', 'Youthful', 'Charming'],
    lowRoadKeywords: ['Scattered', 'Superficial', 'Gossipy', 'Two-faced', 'Unreliable', 'Nervous', 'Restless', 'Inconsistent', 'Manipulative with words', 'Flighty', 'Non-committal', 'Anxious', 'Deceptive'],
  },
  {
    name: 'Cancer',
    symbol: '♋',
    animal: 'Crab',
    element: 'Water',
    modality: 'Cardinal',
    polarity: 'Yin',
    polarityLabels: ['Feminine', 'Receptive'],
    rulingPlanet: 'Moon',
    planetSymbol: '☽',
    bodyRegion: 'Chest, breasts, stomach, womb',
    mantra: 'I feel',
    affirmation: 'My sensitivity is my strength, not my weakness.',
    shadowMindset: 'If I open up, I\'ll be hurt.',
    mnemonic: 'The first spring rain — cardinal water. It initiates the thaw, breaks through frozen ground, and coaxes life from the earth. Gentle, persistent, life-giving.',
    superpower: 'Most nurturing and emotionally intelligent of the signs',
    areasToWorkOn: ['Moodiness', 'Over-protectiveness', 'Difficulty letting go of the past'],
    essence: [
      'Cancer is the cardinal water — the initiator of emotion, the mother of the zodiac. Like the crab, Cancer approaches sideways, never head-on. Vulnerability is both their greatest gift and deepest fear.',
      'Cancer people create sanctuary wherever they go. Their homes are temples, their kitchens are altars, their memory is ancestral. They carry the emotional DNA of their entire family line, often feeling responsible for everyone\'s well-being.',
      'The stomach and chest are Cancer\'s domain. Gut feelings are literal for this sign — they know truth through their belly before their brain catches up. Digestive issues, chest tightness, and emotional eating all signal a Cancer body processing feelings it hasn\'t been allowed to express.',
    ],
    needs: ['Emotional safety', 'Home', 'Family connection', 'Permission to feel', 'Loyalty'],
    creativeExpression: 'Cancer creates through atmosphere — interior design, cooking, photography, memoir. Their art is intimate, nostalgic, and designed to make others feel held.',
    keywords: ['Nurturing', 'Intuition', 'Protection', 'Memory'],
    highRoadKeywords: ['Nurturing', 'Protective', 'Intuitive', 'Empathetic', 'Loyal', 'Domestic', 'Sentimental', 'Caring', 'Imaginative', 'Tenacious', 'Sympathetic', 'Maternal', 'Supportive', 'Devoted', 'Emotionally intelligent'],
    lowRoadKeywords: ['Moody', 'Clingy', 'Overprotective', 'Manipulative', 'Passive-aggressive', 'Smothering', 'Victim mentality', 'Guilt-tripping', 'Unable to let go', 'Overly sensitive', 'Codependent', 'Crabby', 'Insecure'],
  },
  {
    name: 'Leo',
    symbol: '♌',
    animal: 'Lion',
    element: 'Fire',
    modality: 'Fixed',
    polarity: 'Yang',
    polarityLabels: ['Masculine', 'Assertive'],
    rulingPlanet: 'Sun',
    planetSymbol: '☉',
    bodyRegion: 'Heart, spine, upper back',
    mantra: 'I create',
    affirmation: 'I shine my light so others can find theirs.',
    shadowMindset: 'If I\'m not the center, I don\'t matter.',
    mnemonic: 'The bonfire — fixed fire. Not a spark but a sustained blaze that holds its ground all night. Everyone gathers around it. It doesn\'t chase; it magnetizes.',
    superpower: 'Most generous and radiant of the signs',
    areasToWorkOn: ['Need for validation', 'Pride', 'Drama when ignored'],
    essence: [
      'Leo is the fixed fire — the sustained blaze, the sun itself. Where Aries is the spark, Leo is the roaring hearth that warms the entire household. Leo doesn\'t just want to shine; Leo IS shine.',
      'At their best, Leos are the most generous sign in the zodiac. They give their time, their creativity, their money, and their heart with theatrical abandon. Their love is a performance — not fake, but ceremonial. They make birthdays into events, gifts into experiences.',
      'Leo rules the heart and spine — the literal center of the body. Heart palpitations, upper back pain, and circulation issues tell Leo that they\'re giving too much or not receiving enough recognition. The remedy is always creative expression: painting, theater, dance, anything that lets the inner lion roar.',
    ],
    needs: ['Recognition', 'Creative outlets', 'To be seen', 'Applause (literal or metaphorical)', 'Loyal subjects'],
    creativeExpression: 'Leo creates through performance — acting, directing, fashion, event planning. Their art is dramatic, warm, and designed to be witnessed and applauded.',
    keywords: ['Creativity', 'Generosity', 'Radiance', 'Pride'],
    highRoadKeywords: ['Generous', 'Radiant', 'Creative', 'Confident', 'Warm-hearted', 'Loyal', 'Charismatic', 'Dignified', 'Playful', 'Dramatic', 'Inspirational', 'Passionate', 'Enthusiastic', 'Regal', 'Magnetic'],
    lowRoadKeywords: ['Arrogant', 'Vain', 'Attention-seeking', 'Dramatic', 'Domineering', 'Entitled', 'Prideful', 'Self-absorbed', 'Jealous of spotlight', 'Lazy when uninspired', 'Demanding', 'Condescending', 'Melodramatic'],
  },
  {
    name: 'Virgo',
    symbol: '♍',
    animal: 'Maiden',
    element: 'Earth',
    modality: 'Mutable',
    polarity: 'Yin',
    polarityLabels: ['Feminine', 'Receptive'],
    rulingPlanet: 'Mercury',
    planetSymbol: '☿',
    bodyRegion: 'Digestive system, intestines, nervous system',
    mantra: 'I improve',
    affirmation: 'Good enough IS enough. My worth is not measured by my productivity.',
    shadowMindset: 'If it\'s not perfect, it\'s worthless.',
    mnemonic: 'The sifted soil — mutable earth. Hands running through compost, sorting nutrients from debris, preparing the ground so seeds can actually take root. Quiet, essential labor.',
    superpower: 'Most discerning and service-oriented of the signs',
    areasToWorkOn: ['Perfectionism', 'Self-criticism', 'Analysis paralysis'],
    essence: [
      'Virgo is the mutable earth — the soil that sorts, sifts, and refines until only the essential remains. This is not the earth of mountains (Capricorn) or gardens (Taurus), but the earth of the laboratory — precise, analytical, devoted to improvement.',
      'Virgo\'s genius is pattern recognition. They see what\'s wrong before anyone else notices, which makes them invaluable in medicine, editing, systems design, and healing work. The shadow is obvious: they also see what\'s wrong with themselves, constantly.',
      'The digestive system is Virgo\'s domain — fitting for the sign that processes and breaks down everything into usable parts. IBS, food sensitivities, and anxiety-driven stomach issues are the body\'s way of telling Virgo that not everything needs to be analyzed.',
    ],
    needs: ['Order', 'Useful work', 'To feel helpful', 'Systems', 'Quiet appreciation'],
    creativeExpression: 'Virgo creates through refinement — editing, herbalism, craftsmanship, coding. Their art is in the details others miss and the systems that run invisibly.',
    keywords: ['Precision', 'Service', 'Analysis', 'Refinement'],
    highRoadKeywords: ['Analytical', 'Precise', 'Helpful', 'Humble', 'Diligent', 'Practical', 'Health-conscious', 'Organized', 'Efficient', 'Discerning', 'Thoughtful', 'Dedicated', 'Detail-oriented', 'Reliable', 'Service-minded'],
    lowRoadKeywords: ['Perfectionist', 'Critical', 'Judgmental', 'Anxious', 'Overthinking', 'Nitpicking', 'Self-critical', 'Hypochondriac', 'Uptight', 'Martyring', 'Fussy', 'Nagging', 'Micromanaging'],
  },
  {
    name: 'Libra',
    symbol: '♎',
    animal: 'Scales',
    element: 'Air',
    modality: 'Cardinal',
    polarity: 'Yang',
    polarityLabels: ['Masculine', 'Assertive'],
    rulingPlanet: 'Venus',
    planetSymbol: '♀',
    bodyRegion: 'Kidneys, lower back, skin',
    mantra: 'I balance',
    affirmation: 'I can hold my own truth and still love you.',
    shadowMindset: 'If I disagree, they won\'t love me.',
    mnemonic: 'The first breath of dialogue — cardinal air. The moment you open your mouth to bridge a divide. It initiates connection, creates space between two people, and insists on fairness.',
    superpower: 'Most aesthetically gifted and fair-minded of the signs',
    areasToWorkOn: ['People-pleasing', 'Indecisiveness', 'Avoiding conflict at all costs'],
    essence: [
      'Libra is the cardinal air — the initiator of relationship, the architect of beauty. Everything Libra touches must be harmonized, balanced, and aesthetically considered. This is not superficiality; it is a deep knowing that beauty IS truth.',
      'Libra\'s gift is seeing the other person\'s perspective so clearly that they sometimes forget their own. They are the natural counselors, mediators, and designers of the zodiac — anyone who creates bridges between opposing forces has Libra energy at work.',
      'Libra rules the kidneys (which filter and balance), the lower back (which supports everything above it), and the skin (the boundary between self and world). Lower back pain, skin flare-ups, and kidney issues signal a Libra body that has been carrying someone else\'s emotional weight.',
    ],
    needs: ['Partnership', 'Beauty', 'Fairness', 'Harmony', 'Intellectual stimulation'],
    creativeExpression: 'Libra creates through design — fashion, interior design, law, curation. Their art is elegant, balanced, and always considers how others will receive it.',
    keywords: ['Harmony', 'Partnership', 'Beauty', 'Diplomacy'],
    highRoadKeywords: ['Diplomatic', 'Fair-minded', 'Gracious', 'Charming', 'Romantic', 'Artistic', 'Cooperative', 'Peaceful', 'Refined', 'Social', 'Balanced', 'Idealistic', 'Considerate', 'Elegant', 'Harmonious'],
    lowRoadKeywords: ['Indecisive', 'People-pleasing', 'Codependent', 'Superficial', 'Avoids conflict', 'Passive-aggressive', 'Vain', 'Manipulative', 'Wishy-washy', 'Dependent', 'Resentful beneath politeness', 'Lost without a partner'],
  },
  {
    name: 'Scorpio',
    symbol: '♏',
    animal: 'Scorpion / Eagle / Phoenix',
    element: 'Water',
    modality: 'Fixed',
    polarity: 'Yin',
    polarityLabels: ['Feminine', 'Receptive'],
    rulingPlanet: 'Mars (traditional) / Pluto (modern)',
    planetSymbol: '♂ / ♇',
    bodyRegion: 'Reproductive organs, pelvis, elimination',
    mantra: 'I transform',
    affirmation: 'I can let go and still be whole.',
    shadowMindset: 'Trust no one completely.',
    mnemonic: 'The deep well — fixed water. Still on the surface, but the water goes down farther than anyone can see. Drop a stone and you\'ll wait a long time before you hear it hit bottom.',
    superpower: 'Most psychologically penetrating of the signs',
    areasToWorkOn: ['Control', 'Jealousy', 'Holding grudges', 'Secrecy'],
    essence: [
      'Scorpio is the fixed water — the deep, still lake that harbors currents so powerful they reshape the landscape beneath the surface. Nothing about Scorpio is casual. This sign lives at the edge of life and death, literal and metaphorical.',
      'Scorpio people know things they shouldn\'t know. They read rooms, sense lies, and detect hidden motivations with an almost supernatural accuracy. This is not paranoia but perception — the inherited survival instinct of the sign that guards the soul\'s most vulnerable gates.',
      'Scorpio rules the reproductive system and organs of elimination — the body\'s capacity to create life and release what\'s no longer needed. UTIs, hormonal issues, and chronic tension in the pelvis signal a Scorpio body holding onto something it needs to transform or release.',
    ],
    needs: ['Depth', 'Truth', 'Emotional intimacy', 'Power over self', 'Privacy'],
    creativeExpression: 'Scorpio creates through intensity — psychology, surgery, investigation, taboo art. Their work goes where others are afraid to look.',
    keywords: ['Depth', 'Transformation', 'Intensity', 'Power'],
    highRoadKeywords: ['Intense', 'Perceptive', 'Passionate', 'Resourceful', 'Brave', 'Magnetic', 'Loyal', 'Strategic', 'Transformative', 'Resilient', 'Psychologically astute', 'Determined', 'Deep', 'Healing', 'Powerful'],
    lowRoadKeywords: ['Jealous', 'Controlling', 'Manipulative', 'Vindictive', 'Obsessive', 'Secretive', 'Paranoid', 'Power-hungry', 'Grudge-holding', 'Destructive', 'Possessive', 'Suspicious', 'Ruthless'],
  },
  {
    name: 'Sagittarius',
    symbol: '♐',
    animal: 'Archer / Centaur',
    element: 'Fire',
    modality: 'Mutable',
    polarity: 'Yang',
    polarityLabels: ['Masculine', 'Assertive'],
    rulingPlanet: 'Jupiter',
    planetSymbol: '♃',
    bodyRegion: 'Hips, thighs, liver, sciatic nerve',
    mantra: 'I explore',
    affirmation: 'The meaning I seek is found in the journey, not the destination.',
    shadowMindset: 'Rules don\'t apply to me.',
    mnemonic: 'The wildfire — mutable fire. Flames that leap from treetop to treetop, spreading in every direction, crossing borders, impossible to contain. It follows the wind wherever meaning leads.',
    superpower: 'Most optimistic and philosophically adventurous of the signs',
    areasToWorkOn: ['Over-promising', 'Tactlessness', 'Commitment phobia'],
    essence: [
      'Sagittarius is the mutable fire — the flame that travels, the torch carried across borders. This is the sign of the seeker, the philosopher, the eternal student who knows that wisdom is found in motion, not in arrival.',
      'Sagittarius people are the truth-tellers of the zodiac, sometimes brutally so. Their honesty is not cruel but philosophical: they genuinely believe that truth, however uncomfortable, sets everyone free. The shadow is foot-in-mouth moments that leave others reeling.',
      'The hips, thighs, and liver are Sagittarius territory — the muscles that carry you forward and the organ that processes excess. Hip problems, sciatica, and liver complaints signal a Sagittarius body that has been running too hard or consuming too much (ideas, food, travel, all of it).',
    ],
    needs: ['Freedom', 'Adventure', 'Meaning', 'New horizons', 'Big-picture conversations'],
    creativeExpression: 'Sagittarius creates through teaching — philosophy, travel writing, documentary, comedy. Their art expands horizons and makes people laugh at the absurdity of being human.',
    keywords: ['Freedom', 'Optimism', 'Philosophy', 'Adventure'],
    highRoadKeywords: ['Optimistic', 'Adventurous', 'Philosophical', 'Honest', 'Generous', 'Enthusiastic', 'Open-minded', 'Freedom-loving', 'Jovial', 'Inspiring', 'Visionary', 'Tolerant', 'Humorous', 'Big-hearted', 'Truth-seeking'],
    lowRoadKeywords: ['Blunt', 'Tactless', 'Preachy', 'Over-promising', 'Irresponsible', 'Commitment-phobic', 'Reckless', 'Dogmatic', 'Exaggerating', 'Know-it-all', 'Restless', 'Careless', 'Self-righteous'],
  },
  {
    name: 'Capricorn',
    symbol: '♑',
    animal: 'Sea-Goat',
    element: 'Earth',
    modality: 'Cardinal',
    polarity: 'Yin',
    polarityLabels: ['Feminine', 'Receptive'],
    rulingPlanet: 'Saturn',
    planetSymbol: '♄',
    bodyRegion: 'Bones, knees, joints, teeth, skin',
    mantra: 'I achieve',
    affirmation: 'I am worthy even when I rest.',
    shadowMindset: 'I must earn everything. Nothing is given.',
    mnemonic: 'The first shovel in the ground — cardinal earth. Breaking dirt to lay a foundation. Methodical, deliberate, building something meant to stand for generations.',
    superpower: 'Most disciplined and strategically minded of the signs',
    areasToWorkOn: ['Workaholism', 'Emotional suppression', 'Pessimism'],
    essence: [
      'Capricorn is the cardinal earth — the initiator of structure, the architect of civilization. Where Aries starts with instinct, Capricorn starts with a plan. This is the sign that builds cathedrals — structures designed to outlast their builders.',
      'Capricorn people age in reverse: they are the old souls who carry too much responsibility in youth and gradually lighten, becoming more playful and open as decades pass. Their twenties are often their hardest years; their sixties, their most free.',
      'Bones, joints, knees, and teeth belong to Capricorn — the structural framework of the body. Knee injuries, dental problems, and joint stiffness signal a Capricorn body bearing too much weight, literal or metaphorical. The remedy is rest (the hardest prescription for any Capricorn).',
    ],
    needs: ['Structure', 'Achievement', 'Respect', 'Legacy', 'Solitude for recharging'],
    creativeExpression: 'Capricorn creates through mastery — architecture, business, classical music, strategic planning. Their art is built to endure and earns respect through craft.',
    keywords: ['Discipline', 'Ambition', 'Structure', 'Legacy'],
    highRoadKeywords: ['Disciplined', 'Ambitious', 'Responsible', 'Strategic', 'Patient', 'Wise', 'Authoritative', 'Hardworking', 'Mature', 'Dependable', 'Traditional', 'Masterful', 'Pragmatic', 'Resilient', 'Dignified'],
    lowRoadKeywords: ['Workaholic', 'Cold', 'Pessimistic', 'Controlling', 'Status-obsessed', 'Emotionally repressed', 'Rigid', 'Ruthless', 'Condescending', 'Uses people', 'Melancholic', 'Fear-driven', 'Unforgiving'],
  },
  {
    name: 'Aquarius',
    symbol: '♒',
    animal: 'Water Bearer',
    element: 'Air',
    modality: 'Fixed',
    polarity: 'Yang',
    polarityLabels: ['Masculine', 'Assertive'],
    rulingPlanet: 'Saturn (traditional) / Uranus (modern)',
    planetSymbol: '♄ / ♅',
    bodyRegion: 'Ankles, calves, circulatory system',
    mantra: 'I know',
    affirmation: 'Being different is my contribution, not my burden.',
    shadowMindset: 'Emotions are inefficient.',
    mnemonic: 'The wind inside a closed room — fixed air. You can\'t see it, but the pressure is there. It holds steady, hums with electricity, and when it finally moves, it rearranges everything.',
    superpower: 'Most innovative and humanitarian of the signs',
    areasToWorkOn: ['Emotional detachment', 'Contrarian tendencies', 'Alienation'],
    essence: [
      'Aquarius is the fixed air — the mind that locks onto a vision of the future and refuses to let go. Despite the name, Aquarius is not a water sign but an air sign: it carries water (emotion, humanity) but processes it through intellect and ideology.',
      'Aquarius people feel like they\'re from another planet, and in a sense they are — they\'re always 10 years ahead of the cultural moment. Their gift is seeing systems, patterns, and futures that others can\'t imagine yet. Their curse is feeling perpetually misunderstood.',
      'Ankles, calves, and the circulatory system belong to Aquarius — the parts that keep things flowing and moving. Ankle sprains, poor circulation, and restless legs signal an Aquarian body that feels stuck in a reality too small for its vision.',
    ],
    needs: ['Intellectual freedom', 'Community of like-minds', 'Space to be eccentric', 'Causes to champion', 'Independence within connection'],
    creativeExpression: 'Aquarius creates through innovation — technology, social activism, avant-garde art, community organizing. Their work disrupts the status quo.',
    keywords: ['Innovation', 'Rebellion', 'Humanity', 'Vision'],
    highRoadKeywords: ['Innovative', 'Humanitarian', 'Independent', 'Visionary', 'Progressive', 'Original', 'Intellectual', 'Friendly', 'Objective', 'Inventive', 'Idealistic', 'Unconventional', 'Community-minded', 'Forward-thinking', 'Eccentric'],
    lowRoadKeywords: ['Detached', 'Aloof', 'Contrarian', 'Rebellious for the sake of it', 'Emotionally unavailable', 'Superiority complex', 'Alienating', 'Stubborn', 'Cold', 'Unpredictable', 'Dismissive of feelings', 'Anarchic'],
  },
  {
    name: 'Pisces',
    symbol: '♓',
    animal: 'Two Fish',
    element: 'Water',
    modality: 'Mutable',
    polarity: 'Yin',
    polarityLabels: ['Feminine', 'Receptive'],
    rulingPlanet: 'Jupiter (traditional) / Neptune (modern)',
    planetSymbol: '♃ / ♆',
    bodyRegion: 'Feet, lymphatic system, pineal gland',
    mantra: 'I believe',
    affirmation: 'I can be sensitive and strong at the same time.',
    shadowMindset: 'Reality is too painful — I\'d rather escape.',
    mnemonic: 'The morning mist — mutable water. It drifts, dissolves borders, softens edges, seeps into everything. You can\'t hold it, but you feel it on your skin. It\'s everywhere and nowhere.',
    superpower: 'Most intuitive and spiritually attuned of the signs',
    areasToWorkOn: ['Escapism', 'Boundary dissolution', 'Victim mentality'],
    essence: [
      'Pisces is the mutable water — the ocean that contains all rivers, the final sign that dissolves all boundaries. This is the mystic of the zodiac, the empath, the dreamer who lives between worlds. Where Aquarius thinks about humanity, Pisces FEELS it.',
      'Pisces people absorb their environment like sponges. They cry at commercials, sense tension in rooms they\'ve just entered, and dream in vivid, prophetic narratives. Their gift is compassion so vast it encompasses all living things. Their shadow is that compassion without boundaries becomes self-destruction.',
      'The feet and lymphatic system belong to Pisces — the body\'s grounding point and its purification network. Foot problems, edema, and immune system issues signal a Pisces body that has absorbed too much of the world and needs to discharge. Walking barefoot on earth, Epsom salt baths, and swimming are literal medicine.',
    ],
    needs: ['Solitude', 'Creative/spiritual practice', 'Permission to feel deeply', 'Time near water', 'Boundaries (even though they resist them)'],
    creativeExpression: 'Pisces creates through channeling — music, film, poetry, healing arts. Their work arrives from somewhere beyond the rational mind and touches people in places words cannot reach.',
    keywords: ['Compassion', 'Intuition', 'Mysticism', 'Surrender'],
    highRoadKeywords: ['Compassionate', 'Intuitive', 'Artistic', 'Empathetic', 'Spiritual', 'Imaginative', 'Gentle', 'Selfless', 'Dreamy', 'Healing', 'Forgiving', 'Mystical', 'Romantic', 'Wise', 'Transcendent'],
    lowRoadKeywords: ['Escapist', 'Victim mentality', 'Delusional', 'Boundary-less', 'Addictive tendencies', 'Self-pitying', 'Martyr', 'Passive', 'Easily deceived', 'Avoidant', 'Spacey', 'Codependent', 'Self-destructive'],
  },
];

// Helper to get sign data by name
export function getZodiacSignData(name: string): ZodiacSignData | undefined {
  return ZODIAC_SIGNS_DATA.find(s => s.name === name);
}

// Element color map for consistent styling
export const ELEMENT_COLORS: Record<string, { bg: string; border: string; text: string; badge: string }> = {
  Fire: { bg: 'bg-red-50 dark:bg-red-950/30', border: 'border-red-200 dark:border-red-800', text: 'text-red-700 dark:text-red-400', badge: 'bg-red-100 text-red-800 dark:bg-red-900/50 dark:text-red-300' },
  Earth: { bg: 'bg-emerald-50 dark:bg-emerald-950/30', border: 'border-emerald-200 dark:border-emerald-800', text: 'text-emerald-700 dark:text-emerald-400', badge: 'bg-emerald-100 text-emerald-800 dark:bg-emerald-900/50 dark:text-emerald-300' },
  Air: { bg: 'bg-sky-50 dark:bg-sky-950/30', border: 'border-sky-200 dark:border-sky-800', text: 'text-sky-700 dark:text-sky-400', badge: 'bg-sky-100 text-sky-800 dark:bg-sky-900/50 dark:text-sky-300' },
  Water: { bg: 'bg-blue-50 dark:bg-blue-950/30', border: 'border-blue-200 dark:border-blue-800', text: 'text-blue-700 dark:text-blue-400', badge: 'bg-blue-100 text-blue-800 dark:bg-blue-900/50 dark:text-blue-300' },
};

// Polarity helper
export const SIGN_POLARITY: Record<string, 'Yang' | 'Yin'> = {
  Aries: 'Yang', Taurus: 'Yin', Gemini: 'Yang', Cancer: 'Yin',
  Leo: 'Yang', Virgo: 'Yin', Libra: 'Yang', Scorpio: 'Yin',
  Sagittarius: 'Yang', Capricorn: 'Yin', Aquarius: 'Yang', Pisces: 'Yin',
};
