import { useEffect, useState } from "react";
import { Loader2, Sparkles } from "lucide-react";

interface AskGenerationStatusProps {
  /** When generation started (ms since epoch). */
  startedAt: number;
  /** Latest status from the job poller, or submitting while creating the job row. */
  jobStatus?: "submitting" | "queued" | "processing" | null;
}

/**
 * Honest progress UI for the Ask flow.
 *
 * The backend does NOT report section-level progress, so we do NOT pretend to.
 * We show only what we actually know:
 *   - Whether the job is queued or actively being generated by the AI.
 *   - The real elapsed wall-clock time since submission.
 *   - A typical-duration hint so long waits don't feel broken.
 *
 * Previously this component animated a fake "Section X of 12" counter driven
 * purely by a 30s/section timer. That was misleading — it had no relationship
 * to what the AI was actually doing — and has been removed.
 */

function formatElapsed(ms: number): string {
  const total = Math.max(0, Math.floor(ms / 1000));
  const m = Math.floor(total / 60);
  const s = total % 60;
  return `${m}:${s.toString().padStart(2, "0")}`;
}

export function AskGenerationStatus({ startedAt, jobStatus }: AskGenerationStatusProps) {
  const [now, setNow] = useState(() => Date.now());

  useEffect(() => {
    const id = setInterval(() => setNow(Date.now()), 1000);
    return () => clearInterval(id);
  }, []);

  const elapsedMs = now - startedAt;
  const elapsedSec = Math.floor(elapsedMs / 1000);
  const isSubmitting = jobStatus === "submitting";
  const isQueued = jobStatus === "queued";

  const message = isSubmitting
    ? "Connecting to the report queue…"
    : isQueued
    ? "Queued — waiting for the AI to start…"
    : "Generating your reading…";

  // Typical durations from observed Sonnet runs: 4–6 minutes.
  // Surface a stronger hint after 7 minutes so the user knows it's running long
  // but hasn't necessarily failed.
  const showTypicalHint = !isSubmitting && !isQueued && elapsedSec >= 60 && elapsedSec < 420;
  const showLongHint = elapsedSec >= 420;

  return (
    <div className="flex gap-3">
      <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-primary/10">
        <Sparkles className="h-4 w-4 text-primary" />
      </div>
      <div className="flex flex-col gap-1 rounded-lg bg-muted px-4 py-3 min-w-[300px]">
        <div className="flex items-center gap-2">
          <Loader2 className="h-4 w-4 animate-spin text-muted-foreground" />
          <span className="text-sm text-muted-foreground">{message}</span>
          <span className="ml-auto text-xs font-mono text-muted-foreground/80 tabular-nums">
            {formatElapsed(elapsedMs)}
          </span>
        </div>
        {showTypicalHint && (
          <p className="text-xs text-muted-foreground/70 pl-6">
            Typical wait: 4–6 minutes. You can switch tabs — it keeps generating.
          </p>
        )}
        {showLongHint && (
          <p className="text-xs text-destructive pl-6">
            This is taking longer than usual ({formatElapsed(elapsedMs)}). It will still finish — but if it passes 10 minutes, refresh the page; the result is saved on the server and will load when ready.
          </p>
        )}
      </div>
    </div>
  );
}
