import { useEffect, useRef, useState } from 'react';
import { X, Copy, Check, Trash2, Mail, Loader2, RefreshCw, Download } from 'lucide-react';
import {
  generateCosmicWeatherEmail,
  loadRecipients,
  saveRecipient,
  deleteRecipient,
  type EmailRecipient,
} from '@/lib/cosmicWeatherEmail';
import type { NatalChart } from '@/hooks/useNatalChart';

interface Props {
  date: Date;
  onClose: () => void;
  natalChart?: NatalChart | null;
  chartId?: string;
}

export const EmailReportModal = ({ date, onClose, natalChart, chartId }: Props) => {
  const [recipients, setRecipients] = useState<EmailRecipient[]>(() => loadRecipients());
  const [selectedEmail, setSelectedEmail] = useState<string>('');
  const [newName, setNewName] = useState('');
  const [newEmail, setNewEmail] = useState('');
  const [copied, setCopied] = useState(false);
  const [loading, setLoading] = useState(false);
  const [status, setStatus] = useState<string>('');
  const [subject, setSubject] = useState('Cosmic Weather');
  const [body, setBody] = useState('');
  const [error, setError] = useState<string | null>(null);
  const lastResultRef = useRef<any>(null);

  const selected = recipients.find(r => r.email === selectedEmail) || null;

  const generate = async () => {
    if (!natalChart || !chartId) {
      setError('No chart loaded.');
      return;
    }
    setLoading(true);
    setError(null);
    setBody('');
    try {
      const res = await generateCosmicWeatherEmail(
        { date, natalChart, chartId, recipientName: selected?.name },
        { onProgress: (s) => setStatus(s) },
      );
      setSubject(res.subject);
      setBody(res.body);
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setLoading(false);
      setStatus('');
    }
  };

  // Auto-generate on first open / when recipient changes.
  useEffect(() => {
    void generate();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selectedEmail]);

  const handleAdd = () => {
    if (!newName.trim() || !newEmail.trim()) return;
    const list = saveRecipient({ name: newName.trim(), email: newEmail.trim() });
    setRecipients(list);
    setSelectedEmail(newEmail.trim());
    setNewName('');
    setNewEmail('');
  };

  const handleDelete = (email: string) => {
    setRecipients(deleteRecipient(email));
    if (selectedEmail === email) setSelectedEmail('');
  };

  const handleCopy = async () => {
    await navigator.clipboard.writeText(`Subject: ${subject}\n\n${body}`);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  };

  const mailtoHref = () => {
    const to = selected?.email ? encodeURIComponent(selected.email) : '';
    const s = encodeURIComponent(subject);
    const b = encodeURIComponent(body);
    return `mailto:${to}?subject=${s}&body=${b}`;
  };

  return (
    <div
      className="fixed inset-0 z-[60] flex items-center justify-center bg-foreground/80 p-5"
      onClick={onClose}
    >
      <div
        className="relative w-full max-w-3xl max-h-[90vh] overflow-y-auto rounded-sm bg-background p-6 shadow-xl md:p-8"
        onClick={e => e.stopPropagation()}
      >
        <button
          className="absolute right-4 top-4 p-2 text-muted-foreground hover:text-foreground"
          onClick={onClose}
        >
          <X size={20} />
        </button>

        <h2 className="font-serif text-2xl text-foreground mb-1">Email this Cosmic Weather</h2>
        <p className="text-sm text-muted-foreground mb-5">
          Generated by the same engine that powers the Ask tab — every astrological claim is fact-checked against the ephemeris.
        </p>

        {/* Recipients */}
        <div className="mb-5 rounded-sm border border-border p-4 bg-muted/30">
          <h3 className="text-[11px] uppercase tracking-widest text-muted-foreground mb-3">Saved recipients</h3>
          {recipients.length === 0 && (
            <p className="text-sm text-muted-foreground mb-3">No saved recipients yet.</p>
          )}
          <div className="space-y-1 mb-3">
            {recipients.map(r => (
              <label
                key={r.email}
                className={`flex items-center gap-2 p-2 rounded-sm cursor-pointer ${
                  selectedEmail === r.email ? 'bg-primary/10 border border-primary/40' : 'hover:bg-muted'
                }`}
              >
                <input
                  type="radio"
                  name="recipient"
                  checked={selectedEmail === r.email}
                  onChange={() => setSelectedEmail(r.email)}
                />
                <span className="text-sm font-medium">{r.name}</span>
                <span className="text-xs text-muted-foreground">{r.email}</span>
                <button
                  className="ml-auto text-muted-foreground hover:text-destructive"
                  onClick={(e) => { e.preventDefault(); handleDelete(r.email); }}
                  title="Remove"
                >
                  <Trash2 size={14} />
                </button>
              </label>
            ))}
          </div>

          <div className="grid grid-cols-1 md:grid-cols-[1fr_1fr_auto] gap-2">
            <input
              className="px-3 py-2 text-sm rounded-sm border border-border bg-background"
              placeholder="Name"
              value={newName}
              onChange={e => setNewName(e.target.value)}
              maxLength={80}
            />
            <input
              className="px-3 py-2 text-sm rounded-sm border border-border bg-background"
              placeholder="email@example.com"
              type="email"
              value={newEmail}
              onChange={e => setNewEmail(e.target.value)}
              maxLength={200}
            />
            <button
              className="px-3 py-2 text-sm rounded-sm bg-primary text-primary-foreground hover:bg-primary/90"
              onClick={handleAdd}
            >
              Save
            </button>
          </div>
        </div>

        {/* Subject */}
        <div className="mb-2">
          <div className="text-[10px] uppercase tracking-widest text-muted-foreground mb-1">Subject</div>
          <div className="px-3 py-2 rounded-sm bg-muted/40 text-sm font-medium">{subject}</div>
        </div>

        {/* Body */}
        <div className="mb-4">
          <div className="flex items-center justify-between mb-1">
            <div className="text-[10px] uppercase tracking-widest text-muted-foreground">Body</div>
            <button
              onClick={generate}
              disabled={loading}
              className="inline-flex items-center gap-1 text-xs text-muted-foreground hover:text-foreground disabled:opacity-50"
            >
              <RefreshCw size={12} /> Regenerate
            </button>
          </div>
          {loading ? (
            <div className="flex items-center gap-2 h-[360px] justify-center bg-muted/20 rounded-sm border border-border text-sm text-muted-foreground">
              <Loader2 size={16} className="animate-spin" />
              {status ? `Generating (${status})…` : 'Generating…'}
            </div>
          ) : error ? (
            <div className="h-[360px] p-4 bg-destructive/10 text-destructive rounded-sm border border-destructive/30 text-sm">
              {error}
            </div>
          ) : (
            <textarea
              readOnly
              value={body}
              className="w-full h-[360px] font-mono text-xs p-3 rounded-sm border border-border bg-muted/20 leading-relaxed"
            />
          )}
        </div>

        {/* Actions */}
        <div className="flex flex-wrap gap-2">
          <button
            onClick={handleCopy}
            disabled={loading || !body}
            className="inline-flex items-center gap-2 px-4 py-2 rounded-sm bg-secondary text-secondary-foreground hover:bg-secondary/80 text-sm disabled:opacity-50"
          >
            {copied ? <Check size={16} /> : <Copy size={16} />}
            {copied ? 'Copied!' : 'Copy email'}
          </button>
          <a
            href={mailtoHref()}
            className={`inline-flex items-center gap-2 px-4 py-2 rounded-sm bg-primary text-primary-foreground hover:bg-primary/90 text-sm ${loading || !body ? 'pointer-events-none opacity-50' : ''}`}
          >
            <Mail size={16} />
            {selected ? `Open mail to ${selected.name}` : 'Open in mail app'}
          </a>
        </div>
      </div>
    </div>
  );
};
