/**
 * Shared "What this does not mean" disclosure.
 *
 * One component so Natal, Reading Guide and Synastry all use the same visual
 * grammar for the clarifications generated by the evidence standard.
 */

import { useState } from 'react';
import { ChevronDown, ChevronUp, ShieldQuestion } from 'lucide-react';
import { DOES_NOT_MEAN_HEADING } from '@/lib/interpretation/evidenceStandard';

export const DoesNotMean = ({ lines, className = '' }: { lines: string[]; className?: string }) => {
  const [open, setOpen] = useState(false);
  if (!lines.length) return null;
  return (
    <div className={`mt-2 ${className}`}>
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        className="text-xs text-muted-foreground hover:text-foreground flex items-center gap-1"
      >
        <ShieldQuestion size={12} />
        {DOES_NOT_MEAN_HEADING}
        {open ? <ChevronUp size={12} /> : <ChevronDown size={12} />}
      </button>
      {open && (
        <ul className="mt-1 space-y-1 rounded-md border border-dashed border-border p-2">
          {lines.map((line, i) => (
            <li key={i} className="text-xs text-muted-foreground">• {line}</li>
          ))}
        </ul>
      )}
    </div>
  );
};

export default DoesNotMean;
