// ============================================================================
// 3-CALL RELATIONSHIP READING ORCHESTRATOR
// ============================================================================
// Purpose: Stop SR/natal data bleed in relationship readings by physically
// separating the chart data the model can see in each generation.
//
// Architecture (per user spec):
//   Call A (parallel) — natal chart data ONLY. Author the natal-anchored
//                       sections. Model literally cannot reference SR
//                       positions because they aren't in its user message.
//   Call B (parallel) — SR chart data ONLY. Author the SR/timing sections.
//                       Model literally cannot reference natal positions.
//   Call C (sequential, after A+B) — both charts in user message, explicitly
//                       labeled NATAL CHART vs SOLAR RETURN CHART. Author
//                       overlay sections only.
//
// All three calls share ONE master system prompt (so existing hygiene/gate
// rules stay intact) plus a per-call directive that lists the exact sections
// the call must produce and forbids referencing planet data not in its user
// message.
//
// Persistence:
//   - Each successful call's output is written to ask_jobs.call_*_output
//     immediately so a retry can resume from the failed call only.
//   - call_status tracks {a,b,c}: "done" | "failed" | undefined.
//
// Resilience:
//   - 150 second per-call timeout via AbortSignal.timeout.
//     (Sonnet reliably needs 60–120s per call for one third of a full
//     relationship reading; 45s was too tight and timed out 100% of jobs.)
//   - Up to 2 attempts per call with exponential backoff (1.5s, 4.5s).
//   - On final failure, the whole job is marked failed but successful
//     call outputs remain in their columns for resume.
//
// Polarity / element tallies are NOT generated by the model. They are
// computed deterministically from natal positions in code by the caller
// and merged into the final JSON.
// ============================================================================

const PER_CALL_TIMEOUT_MS = 150_000;
const PER_CALL_MAX_ATTEMPTS = 2;
const RETRY_BACKOFF_MS = [1500, 4500]; // index 0 = before attempt 2, etc.
const ANTHROPIC_URL = "https://api.anthropic.com/v1/messages";
const ANTHROPIC_MODEL = "claude-sonnet-4-6";

export type CallId = "a" | "b" | "c";

export interface PriorCallOutput {
  json: any; // the parsed sections payload returned by that call
}

export interface ThreeCallArgs {
  jobId: string;
  anthropicApiKey: string;
  masterSystemPrompt: string;          // existing SYSTEM_PROMPT
  chartScopedRulesShared: string;      // shared rules (Lilith/Juno gates, SR-year, etc.) WITHOUT chart data
  natalChartBlock: string;             // text block containing only natal chart data
  srChartBlock: string;                // text block containing only SR chart data ("(no SR provided)" if absent)
  effectiveCurrentDate: string;
  userQuestion: string;
  /**
   * Pre-rendered "VERIFIED CROSS-CHART ACTIVATIONS — GROUND TRUTH" block plus
   * the strict rules that follow it. Built deterministically by the caller via
   * computeCrossChartActivations + renderActivationsBlock + buildActivationRulesBlock.
   * Empty string disables the feature (legacy/fallback).
   */
  callCActivationsBlock?: string;
  /**
   * Per-chart deterministic retrograde summary for Call C — replaces the old
   * hardcoded leak ("SR Saturn Rx in Pisces …"). Format:
   *   "Natal retrograde: Jupiter, Chiron\nNatal direct: Sun, Moon, …\n
   *    SR retrograde: Saturn, Uranus, …\nSR direct: Sun, Moon, …"
   * Empty string falls back to no retrograde reminder.
   */
  callCRetrogradeSummary?: string;
  // Persisted output from prior partial run, keyed by call id. If present,
  // that call is skipped and its output is reused.
  priorOutputs?: Partial<Record<CallId, PriorCallOutput>>;
  // Updates ask_jobs row. Caller injects so this module stays storage-agnostic.
  updateJob: (patch: Record<string, any>) => Promise<void>;
}

export interface ThreeCallResult {
  // Merged JSON string ready to drop into the existing parse pipeline.
  // Has the same shape the single-call path produces: a JSON object with
  // a `sections: [...]` array (in canonical order).
  mergedJsonString: string;
  // Per-call diagnostics for the validation log.
  diagnostics: {
    a: { ok: true; from_cache: boolean; attempts: number; ms: number } | { ok: false; error: string; attempts: number };
    b: { ok: true; from_cache: boolean; attempts: number; ms: number } | { ok: false; error: string; attempts: number };
    c: { ok: true; from_cache: boolean; attempts: number; ms: number } | { ok: false; error: string; attempts: number };
    total_ms: number;
  };
}

// ─── Section assignments (from user spec) ───────────────────────────────────
// These titles match the existing relationship template (see SYSTEM_PROMPT in
// index.ts) and the Replit gate's section aliases.
//
// Call A — Natal only:
//   - placement_table  "Natal Key Placements"
//   - narrative_section "The Essence of Your Relationship Style"
//   - narrative_section "How This Person Loves"
//   - narrative_section "Relationship Pattern"
//   - narrative_section "Relationship Needs Profile"
//   - narrative_section "Relationship Contradiction Patterns"
// (modality_element "Natal Elemental & Modal Balance" is NOT generated by the
//  model — it is computed deterministically and injected during merge.)
//
// Call B — SR only:
//   - placement_table  "Solar Return Key Placements"
//   - narrative_section "This Year in Love"
//   - timing_section   "Relationship Timing Windows"
//
// Call C — Overlay (both charts):
//   - narrative_section "Where Natal and Solar Return Connect"
//   - summary_box      "Relationship Strategy Summary"
//
// Final canonical order in merged JSON:
//   1. Natal Key Placements                    [A]
//   2. Solar Return Key Placements             [B]
//   3. The Essence of Your Relationship Style  [A]
//   4. How This Person Loves                   [A]
//   5. Relationship Pattern                    [A]
//   6. Relationship Needs Profile              [A]
//   7. Relationship Contradiction Patterns     [A]
//   8. This Year in Love                       [B]
//   9. Where Natal and Solar Return Connect    [C]
//  10. Relationship Timing Windows             [B]
//  11. Natal Elemental & Modal Balance         [code-injected]
//  12. Relationship Strategy Summary           [C]
// ────────────────────────────────────────────────────────────────────────────

const CALL_A_SECTIONS = [
  { type: "placement_table",   title: "Natal Key Placements" },
  { type: "narrative_section", title: "The Essence of Your Relationship Style" },
  { type: "narrative_section", title: "How This Person Loves" },
  { type: "narrative_section", title: "Relationship Pattern" },
  { type: "narrative_section", title: "Relationship Needs Profile" },
  { type: "narrative_section", title: "Relationship Contradiction Patterns" },
];

const CALL_B_SECTIONS = [
  { type: "placement_table",   title: "Solar Return Key Placements" },
  { type: "narrative_section", title: "This Year in Love" },
  { type: "timing_section",    title: "Relationship Timing Windows" },
];

const CALL_C_SECTIONS = [
  { type: "narrative_section", title: "Where Natal and Solar Return Connect" },
  { type: "summary_box",       title: "Relationship Strategy Summary" },
];

// Final merge order — drives the order sections appear in the merged JSON.
// Each entry is (callId, title) so we can pull the right section from the
// right call's output.
const MERGE_ORDER: Array<{ call: CallId | "code"; title: string }> = [
  { call: "a",    title: "Natal Key Placements" },
  { call: "b",    title: "Solar Return Key Placements" },
  { call: "a",    title: "The Essence of Your Relationship Style" },
  { call: "a",    title: "How This Person Loves" },
  { call: "a",    title: "Relationship Pattern" },
  { call: "a",    title: "Relationship Needs Profile" },
  { call: "a",    title: "Relationship Contradiction Patterns" },
  { call: "b",    title: "This Year in Love" },
  { call: "c",    title: "Where Natal and Solar Return Connect" },
  { call: "b",    title: "Relationship Timing Windows" },
  { call: "code", title: "Natal Elemental & Modal Balance" },
  { call: "c",    title: "Relationship Strategy Summary" },
];

// ─── Per-call directives ────────────────────────────────────────────────────
// Critical line per spec: "The chart data in the user message is the ONLY
// source of truth for planet positions in this call. Do not infer, recall,
// or reference any planet position not present in the chart data provided
// below."

const buildDirective = (
  sectionList: Array<{ type: string; title: string }>,
  callLabel: "NATAL-ONLY" | "SR-ONLY" | "OVERLAY",
  extraInstruction = "",
): string => {
  const sectionLines = sectionList
    .map((s, i) => `  ${i + 1}. type="${s.type}", title="${s.title}"`)
    .join("\n");

  return `=========================================================
PER-CALL DIRECTIVE — ${callLabel} CALL
=========================================================

FOR THIS CALL ONLY you are writing these sections:
${sectionLines}

You MUST emit valid JSON with this exact top-level shape:
{
  "sections": [ /* exactly the ${sectionList.length} section(s) listed above, in that order */ ]
}

The "sections" array must contain ONLY those ${sectionList.length} section(s) — no extras, no substitutions, no merging. Do not include modality_element, do not include polarity counts, do not include element/modality tallies anywhere — those are calculated separately in code and are not your responsibility on this call.

The chart data in the user message is the ONLY source of truth for planet positions in this call. Do not infer, recall, or reference any planet position not present in the chart data provided below. If a placement you would normally cite is not in the chart data for this call, write the section without that placement — do not invent a position from memory or from a different chart.

${extraInstruction}

Output: a single JSON object, no prose before or after, no markdown code fences.`;
};

const DIRECTIVE_A = buildDirective(
  CALL_A_SECTIONS,
  "NATAL-ONLY",
  `This is the NATAL-ONLY call. The user message contains NATAL chart data only. There is NO Solar Return data in your context for this call. Do not write the phrase "Solar Return" anywhere in this call's output. Do not write "this year" framings — those belong to a different call. Write the sections as a portrait of the person's lifelong relational signature based on the natal chart only.

NATAL PLUTO — VERIFY BEFORE WRITING (NON-NEGOTIABLE):
The natal Pluto position is the degree Pluto occupied at the time of birth, NOT its current transiting position. For charts born after 2000, natal Pluto is in Capricorn or late Sagittarius — NEVER in Aquarius. Pluto did not enter Aquarius until 2024, so any natal Pluto in Aquarius implies a birth date in 2024 or later. Before you write any natal Pluto reference, look it up in the placement table provided in the user message and copy the sign and degree verbatim. If you would otherwise write "natal Pluto in Aquarius" for a chart born before 2024, STOP and re-read the placement table.

HARD LENGTH CONSTRAINT — "How This Person Loves":
The body of the "How This Person Loves" narrative_section MUST NOT exceed 2,000 characters total. This is a hard ceiling, not a target. If you would naturally write more, prioritize ruthlessly:
  - Lead with the 2-3 most defining placements (typically Venus, Mars, Moon, 7th-house ruler, or whichever bodies are most aspected/dignified).
  - Cut secondary placements rather than shorten every paragraph into fragments.
  - Do not list every relevant placement — choose the ones that drive behavior.
Treat 1,500 characters as the soft target and 2,000 as the absolute ceiling. Other narrative_section bodies in this call follow their normal length guidance and are not affected by this rule.`,
);

const DIRECTIVE_B = buildDirective(
  CALL_B_SECTIONS,
  "SR-ONLY",
  `This is the SR-ONLY call. The user message contains SOLAR RETURN chart data only. There is NO natal chart data in your context for this call. Write the sections as a portrait of THIS YEAR'S relational weather based on the Solar Return chart only. You may say "this year" / "the next 12 months" / "Solar Return". Do not reference natal placements — they aren't in your context for this call.`,
);

/**
 * Build the per-chart Call C directive. We inject explicit "natal X is Y, never
 * write Z" lines for any planet that the model has historically swapped with
 * its SR counterpart (Venus and Jupiter are the recurring offenders). The
 * verified activations list already contains the correct values, but the model
 * has been pulling SR positions through into "natal" prose, so we restate the
 * constraint planet-by-planet using the activations as the source of truth.
 */
const buildDirectiveC = (pinnedConstraints: string, hasRightNowBlock: boolean): string => buildDirective(
  CALL_C_SECTIONS,
  "OVERLAY",
  `ABSOLUTE CONSTRAINT FOR THIS CALL — NON-NEGOTIABLE:

The VERIFIED CROSS-CHART ACTIVATIONS block in the user
message is the ONLY source of cross-chart aspects you
are permitted to reference.

You MUST NOT:
- Identify any aspect not in the verified list
- State any orb not taken directly from the verified list
- Reference any natal point not in the verified list
- Write "natal Venus at X" unless X matches the
  natalPosition field in the verified list exactly
- Write "natal Pluto at X" unless X matches the
  natalPosition field in the verified list exactly

You MUST:
- For each activation you interpret, copy the srPosition
  and natalPosition values verbatim from the verified list
- If asked to discuss an activation not in the list,
  write "no significant activation this year" instead
${pinnedConstraints}
VIOLATION OF THIS RULE PRODUCES FACTUALLY WRONG OUTPUT
THAT CANNOT BE CORRECTED DOWNSTREAM. Treat the verified
activations as the only ground truth that exists for
this call.

=========================================================
MANDATORY CLOSING PARAGRAPH — "The Year's Overarching Theme"
=========================================================
After writing the body of the "Where Natal and Solar Return Connect" section (which interprets each verified activation), the SAME body string MUST end with one final closing paragraph. This closing paragraph:
- Begins on its own line with the bold heading: **The Year's Overarching Theme**
- Is exactly ONE paragraph (3–5 sentences). Not a list. Not bullets.
- Synthesizes ALL the activations above into one cohesive story — what do they point toward together?
- Names the single most important thing this year is asking of this person in their relationships.
- Uses plain behavioral language (no jargon, no planet names if avoidable, no orbs).
- Is decisive and direct — like a final takeaway, not a recap.
This closing paragraph is part of the "body" string of the same narrative_section, appended to the end. It is NOT a separate section.

=========================================================
"Relationship Strategy Summary" — REQUIRED ITEMS (this call)
=========================================================
The summary_box "items" array MUST contain EXACTLY these six labels in this order, and NO others:
  1. "Who to Move Toward"
  2. "Early Warning Signs"
  3. "Pattern to Break"
  4. "Right Now"
  5. "Best Windows"
  6. "Caution Windows"

The "Right Now" item rules (NON-NEGOTIABLE):
${hasRightNowBlock
  ? `- Use ONLY the transit(s) listed in the "RIGHT NOW TRANSIT WINDOWS" block in the user message. That block contains the 1–2 transits whose exact peak falls within ±14 days of the current date.
- Identify those transit(s) by name in plain language and tell the person — in 2 to 4 sentences — what that specific transit is asking of them in this exact moment (this week / this month). Lead with the lived behavior or feeling first, name the transit second.
- If the block lists more than one transit, weave them into a single coherent "right now" picture — do NOT bullet-list them.
- Do NOT invent transits. Do NOT pull from the verified cross-chart activations list (those are year-long, not "right now"). Do NOT cite any transit not in the RIGHT NOW block.`
  : `- The "RIGHT NOW TRANSIT WINDOWS" block in the user message lists ZERO transits within ±14 days of the current date. Therefore, write the "Right Now" value EXACTLY as: "No major outer-planet transit is within two weeks of exact peak right now — this is a quieter moment to integrate what's already in motion rather than wait for a single window to open." Do NOT invent a transit to fill the slot.`}
- Do NOT include "What This Year Is Best For", "What This Year Asks Of You", or any other label outside the six listed above.`,
);

/**
 * Build a per-chart, planet-by-planet "frozen, non-negotiable" natal positions
 * block from the rendered activations. The model has been pulling SR positions
 * through into "natal" prose for every planet (Venus, Jupiter, Pluto have all
 * been observed offenders), so we restate the natal value for EVERY planet
 * that appears in the activations list AND emit explicit "NEVER write <SR pos>
 * for natal X" guards keyed off the SR positions the model has actually
 * substituted in.
 *
 * Activation lines look like:
 *   "  3. SR Venus opposite natal Jupiter (orb 1.2°) — SR Venus at 9°15' Libra; natal Jupiter at 29°34' Taurus"
 *
 * For every planet we also harvest the SR-side position (e.g. "SR Pluto at
 * 1°22' Aquarius") so the "NEVER write X for natal Pluto" line can name the
 * exact substitution to avoid.
 */
const buildPinnedNatalConstraints = (callCActivationsBlock: string): string => {
  if (!callCActivationsBlock) return "";

  // Cover the full classical set + Chiron. North/South Node and angles are
  // handled by other guards (descendant rewrite, angle-claim rewrite).
  const PLANETS = [
    "Sun", "Moon", "Mercury", "Venus", "Mars",
    "Jupiter", "Saturn", "Uranus", "Neptune", "Pluto", "Chiron",
  ];

  // Per-planet collect: natal position (canonical) + every SR position the
  // model has been seen substituting (i.e. every "SR <planet> at X" line in
  // the activations block, even when that SR planet is paired with a different
  // natal point).
  const natalPos = new Map<string, string>();           // planet -> "X°YY' Sign"
  const srSeenForPlanet = new Map<string, Set<string>>(); // planet -> set of SR positions

  for (const planet of PLANETS) {
    // Capture the natal position whenever this planet appears as the natal
    // side of any activation.
    const natalRe = new RegExp(
      `natal\\s+${planet}\\s+at\\s+([^;\\n]+)`,
      "gi",
    );
    let m: RegExpExecArray | null;
    while ((m = natalRe.exec(callCActivationsBlock)) !== null) {
      const v = m[1].trim();
      if (v && !natalPos.has(planet)) natalPos.set(planet, v);
    }

    // Capture every SR position for this planet — these are the values the
    // model has historically misattributed to the natal side.
    const srRe = new RegExp(
      `SR\\s+${planet}\\s+at\\s+([^;\\n]+)`,
      "gi",
    );
    const seen = new Set<string>();
    while ((m = srRe.exec(callCActivationsBlock)) !== null) {
      const v = m[1].trim();
      if (v) seen.add(v);
    }
    if (seen.size > 0) srSeenForPlanet.set(planet, seen);
  }

  if (natalPos.size === 0) return "";

  const lines: string[] = [];
  for (const planet of PLANETS) {
    const np = natalPos.get(planet);
    if (!np) continue;
    const sr = srSeenForPlanet.get(planet);
    let neverPart = "";
    if (sr) {
      const distinct = [...sr].filter((s) => s !== np);
      if (distinct.length > 0) {
        neverPart = ` — NEVER write ${distinct.join(" or ")} (those are SR positions)`;
      }
    }
    lines.push(`- natal ${planet} = ${np}${neverPart}`);
  }

  if (lines.length === 0) return "";

  return `
=========================================================
NATAL POSITIONS — FROZEN, NON-NEGOTIABLE (do not substitute SR values)
=========================================================
Every natal planet position you reference in this call MUST match the value
below verbatim. Do not pull from any SR position. Do not approximate. Do not
substitute the SR value of the same planet. If a planet is missing from this
list, do not invent a position for it — write the section without that
placement.

${lines.join("\n")}
`;
};

// ─── Anthropic call helper ──────────────────────────────────────────────────

interface SingleCallArgs {
  apiKey: string;
  systemBlocks: Array<Record<string, any>>;
  userMessage: string;
  signal: AbortSignal;
}

interface SingleCallResult {
  // Parsed JSON of the model's response (top-level object with a sections array)
  json: any;
  ms: number;
  attempts: number;
}

const callAnthropicOnce = async (args: SingleCallArgs): Promise<{ raw: string; status: number; ok: boolean }> => {
  // Non-streaming for the 3-call architecture: each call is bounded
  // (~1-3 sections of output) so the streaming overhead isn't worth the
  // complexity. We get the whole response and parse JSON in one go.
  const resp = await fetch(ANTHROPIC_URL, {
    method: "POST",
    headers: {
      "x-api-key": args.apiKey,
      "anthropic-version": "2023-06-01",
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model: ANTHROPIC_MODEL,
      system: args.systemBlocks,
      messages: [{ role: "user", content: args.userMessage }],
      temperature: 0.3,
      max_tokens: 16000, // each call is much smaller than the monolithic 32k
    }),
    signal: args.signal,
  });
  let raw = "";
  try { raw = await resp.text(); } catch { /* */ }
  return { raw, status: resp.status, ok: resp.ok };
};

const extractTextFromAnthropic = (raw: string): string => {
  try {
    const obj = JSON.parse(raw);
    if (Array.isArray(obj?.content)) {
      const text = obj.content
        .filter((c: any) => c?.type === "text" && typeof c?.text === "string")
        .map((c: any) => c.text)
        .join("\n");
      if (text) return text;
    }
  } catch { /* fall through */ }
  return raw;
};

const parseModelJson = (text: string): any => {
  // Strip ```json fences, slice from first { to last }, then JSON.parse.
  let cleaned = text.replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/i, "").trim();
  if (!cleaned.startsWith("{")) {
    const f = cleaned.indexOf("{");
    const l = cleaned.lastIndexOf("}");
    if (f !== -1 && l > f) cleaned = cleaned.slice(f, l + 1);
  }
  return JSON.parse(cleaned);
};

const runOneCallWithRetry = async (
  callId: CallId,
  systemBlocks: Array<Record<string, any>>,
  userMessage: string,
  apiKey: string,
): Promise<SingleCallResult> => {
  const startedAt = Date.now();
  let lastError: Error | null = null;

  for (let attempt = 1; attempt <= PER_CALL_MAX_ATTEMPTS; attempt++) {
    if (attempt > 1) {
      const backoff = RETRY_BACKOFF_MS[attempt - 2] ?? 4500;
      console.warn(`[3call] Call ${callId} attempt ${attempt} after ${backoff}ms backoff (last error: ${lastError?.message})`);
      await new Promise((r) => setTimeout(r, backoff));
    }
    const ctl = AbortSignal.timeout(PER_CALL_TIMEOUT_MS);
    try {
      const { raw, status, ok } = await callAnthropicOnce({
        apiKey,
        systemBlocks,
        userMessage,
        signal: ctl,
      });
      if (!ok) {
        const errMsg = `anthropic ${status}: ${raw.slice(0, 200)}`;
        lastError = new Error(errMsg);
        // 4xx other than 429 are not worth retrying.
        if (status >= 400 && status < 500 && status !== 429) {
          throw lastError;
        }
        continue;
      }
      const text = extractTextFromAnthropic(raw);
      let parsed: any;
      try {
        parsed = parseModelJson(text);
      } catch (parseErr) {
        lastError = new Error(`json parse: ${(parseErr as Error).message}`);
        continue;
      }
      if (!parsed || typeof parsed !== "object" || !Array.isArray(parsed.sections) || parsed.sections.length === 0) {
        lastError = new Error("model returned no sections");
        continue;
      }
      return {
        json: parsed,
        ms: Date.now() - startedAt,
        attempts: attempt,
      };
    } catch (err: any) {
      const isAbort = err?.name === "TimeoutError" || err?.name === "AbortError";
      lastError = new Error(isAbort ? `timeout after ${PER_CALL_TIMEOUT_MS}ms` : (err?.message || String(err)));
      // Hard 4xx already thrown above — fall through to retry on transient.
    }
  }

  throw lastError || new Error(`Call ${callId} failed for unknown reason`);
};

// ─── Orchestrator ───────────────────────────────────────────────────────────

const buildSharedSystemBlocks = (
  masterSystemPrompt: string,
  chartScopedRulesShared: string,
  perCallDirective: string,
  effectiveCurrentDate: string,
): Array<Record<string, any>> => {
  // Block 1: master SYSTEM_PROMPT — identical across A/B/C and across users.
  //          Cacheable. Holds every existing rule (clarity translation,
  //          jargon ban, gate aliases, voice, etc.).
  // Block 2: chart-scoped shared rules (Lilith/Juno gates, SR-year mute) —
  //          identical across A/B/C for THIS chart. Cacheable.
  // Block 3: per-call directive + current-date. Differs per call; uncached.
  const blocks: Array<Record<string, any>> = [
    { type: "text", text: masterSystemPrompt, cache_control: { type: "ephemeral" } },
  ];
  if (chartScopedRulesShared) {
    blocks.push({ type: "text", text: chartScopedRulesShared, cache_control: { type: "ephemeral" } });
  }
  blocks.push({
    type: "text",
    text: `${perCallDirective}\n\n--- CURRENT LOCAL DATE ---\n${effectiveCurrentDate}`,
  });
  return blocks;
};

const buildCallAUserMessage = (natalChartBlock: string, userQuestion: string): string => {
  return `User's question: ${userQuestion}

=========================================================
NATAL CHART — the only chart data available for this call
=========================================================

${natalChartBlock}

(No Solar Return chart data is provided for this call. Do not reference SR positions.)`;
};

const buildCallBUserMessage = (srChartBlock: string, userQuestion: string): string => {
  return `User's question: ${userQuestion}

=========================================================
SOLAR RETURN CHART — the only chart data available for this call
=========================================================

${srChartBlock}

(No natal chart data is provided for this call. Do not reference natal positions.)`;
};

const buildCallCUserMessage = (
  natalChartBlock: string,
  srChartBlock: string,
  userQuestion: string,
  callCActivationsBlock: string,
  callCRetrogradeSummary: string,
  rightNowBlock: string,
  effectiveCurrentDate: string,
): string => {
  const retroBlock = callCRetrogradeSummary
    ? `\n${callCRetrogradeSummary}\n`
    : "";
  const activationsBlock = callCActivationsBlock
    ? `\n\n${callCActivationsBlock}\n`
    : "";
  const rightNow = rightNowBlock
    ? `\n\n${rightNowBlock}\n`
    : "";
  return `User's question: ${userQuestion}

CURRENT DATE (use this for the "Right Now" item): ${effectiveCurrentDate}

REMINDER: You may only interpret activations from the
VERIFIED CROSS-CHART ACTIVATIONS list below. Every
planet degree you write must come from that list.
Do not use degrees from the natal or SR placement
tables for overlay prose — use only the verified list.

You have BOTH charts in this call. They describe the same planets at different positions and are NEVER interchangeable. When you write about a natal placement, pull the value from the NATAL CHART block. When you write about an SR placement, pull the value from the SOLAR RETURN CHART block.

=========================================================
NATAL CHART — use ONLY for natal references
=========================================================

${natalChartBlock}

=========================================================
SOLAR RETURN CHART — use ONLY for SR references
=========================================================

${srChartBlock}
${retroBlock}${activationsBlock}${rightNow}`;
};

/**
 * Compute the "RIGHT NOW TRANSIT WINDOWS" block from Call B's Relationship
 * Timing Windows output. Picks at most 2 transits whose exact peak (parsed
 * from date_range) falls within ±14 days of the current date. Returns a
 * "0 found" block if none qualify so the directive's empty-state branch fires.
 */
const buildRightNowBlock = (callBJson: any, effectiveCurrentDate: string): string => {
  const now = new Date(effectiveCurrentDate);
  const nowMs = isNaN(now.getTime()) ? Date.now() : now.getTime();
  const WINDOW_MS = 14 * 24 * 60 * 60 * 1000;
  const emptyBlock = (reason: string) => `=========================================================
RIGHT NOW TRANSIT WINDOWS — GROUND TRUTH (0 found)
=========================================================
${reason} Write the "Right Now" summary item per the empty-state instruction in the directive.`;

  const sections = Array.isArray(callBJson?.sections) ? callBJson.sections : [];
  const timing = sections.find((s: any) =>
    s?.type === "timing_section"
    && typeof s?.title === "string"
    && /timing\s+windows?/i.test(s.title)
  );
  const transits = Array.isArray(timing?.transits) ? timing.transits : [];
  if (transits.length === 0) {
    return emptyBlock("No timing windows were generated in Call B, so no \"right now\" transit can be cited.");
  }

  const parseRangeMidpoint = (raw: string): number | null => {
    if (!raw || typeof raw !== "string") return null;
    const cleaned = raw.replace(/[–—]/g, "-").trim();
    const tryParse = (s: string): number | null => {
      const d = new Date(s);
      if (!isNaN(d.getTime())) return d.getTime();
      const mY = s.match(/^([A-Za-z]+)\s+(\d{4})$/);
      if (mY) {
        const d2 = new Date(`${mY[1]} 15, ${mY[2]}`);
        if (!isNaN(d2.getTime())) return d2.getTime();
      }
      return null;
    };
    // Split on " to " or " - " (latter only when followed by capital/digit)
    const parts = cleaned.split(/\s+to\s+|\s+-\s+(?=[A-Z0-9])/i);
    if (parts.length >= 2) {
      const yearMatch = parts[parts.length - 1].match(/\b(\d{4})\b/);
      const head = /\d{4}/.test(parts[0])
        ? parts[0]
        : (yearMatch ? `${parts[0]}, ${yearMatch[1]}` : parts[0]);
      const startMs = tryParse(head);
      const endMs = tryParse(parts[parts.length - 1]);
      if (startMs != null && endMs != null) return Math.round((startMs + endMs) / 2);
      if (startMs != null) return startMs;
      if (endMs != null) return endMs;
    }
    return tryParse(cleaned);
  };

  const scored = transits
    .map((t: any) => {
      const peakMs = parseRangeMidpoint(t?.date_range || "");
      if (peakMs == null) return null;
      const distance = Math.abs(peakMs - nowMs);
      return { t, peakMs, distance };
    })
    .filter((x: any) => x && x.distance <= WINDOW_MS)
    .sort((a: any, b: any) => a.distance - b.distance)
    .slice(0, 2);

  if (scored.length === 0) {
    return emptyBlock(`No transit listed in Relationship Timing Windows has its exact peak within ±14 days of the current date (${effectiveCurrentDate}).`);
  }

  const lines = scored.map((s: any, i: number) => {
    const t = s.t;
    const planet = String(t.planet || "").trim();
    const aspect = String(t.aspect || "").trim();
    const natalPoint = String(t.natal_point || "").trim();
    const dateRange = String(t.date_range || "").trim();
    const interp = String(t.interpretation || "").trim().slice(0, 400);
    const days = Math.round(s.distance / (24 * 60 * 60 * 1000));
    return `  ${i + 1}. ${planet} ${aspect} ${natalPoint} — date_range: "${dateRange}" — peak is ~${days} day(s) from current date — Call B's interpretation: "${interp}"`;
  }).join("\n");

  return `=========================================================
RIGHT NOW TRANSIT WINDOWS — GROUND TRUTH (${scored.length} found)
=========================================================
The following transit(s) from Call B's Relationship Timing Windows have their exact peak within ±14 days of the current date (${effectiveCurrentDate}). The "Right Now" item in the Relationship Strategy Summary MUST be written from this list and ONLY from this list.

${lines}

Rules for using this block:
- Lead with the lived behavior the person would feel this week / this month, then name the transit by name (e.g., "Saturn squaring your natal Venus right now").
- Do NOT invent additional transits. Do NOT pull from the verified cross-chart activations list (those are year-long, not "right now").
- 2 to 4 sentences total for the "Right Now" value, regardless of how many transits are in the block.`;
};


export const runThreeCallRelationship = async (args: ThreeCallArgs): Promise<ThreeCallResult> => {
  const overallStart = Date.now();
  const {
    jobId, anthropicApiKey, masterSystemPrompt, chartScopedRulesShared,
    natalChartBlock, srChartBlock, effectiveCurrentDate, userQuestion,
    callCActivationsBlock, callCRetrogradeSummary,
    priorOutputs, updateJob,
  } = args;

  // Build A and B system stacks now. Call C's directive + user message are
  // built AFTER A+B settle so we can derive the "Right Now" block from Call B's
  // Relationship Timing Windows output.
  const sysBlocksA = buildSharedSystemBlocks(masterSystemPrompt, chartScopedRulesShared, DIRECTIVE_A, effectiveCurrentDate);
  const sysBlocksB = buildSharedSystemBlocks(masterSystemPrompt, chartScopedRulesShared, DIRECTIVE_B, effectiveCurrentDate);

  const userMsgA = buildCallAUserMessage(natalChartBlock, userQuestion);
  const userMsgB = buildCallBUserMessage(srChartBlock, userQuestion);

  // Helper that runs a single call, persists its output on success, and
  // patches call_status. Reuses prior output if present.
  const runAndPersist = async (
    callId: CallId,
    sysBlocks: Array<Record<string, any>>,
    userMessage: string,
  ): Promise<SingleCallResult & { from_cache: boolean }> => {
    const prior = priorOutputs?.[callId];
    if (prior?.json) {
      console.info(`[3call] Reusing prior output for call ${callId} (job ${jobId})`);
      return { json: prior.json, ms: 0, attempts: 0, from_cache: true };
    }
    const result = await runOneCallWithRetry(callId, sysBlocks, userMessage, anthropicApiKey);
    // Persist immediately so a future retry can resume from here.
    const colName = `call_${callId}_output` as const;
    const statusPatch: Record<string, any> = {};
    statusPatch[colName] = result.json;
    // Read-modify-write of call_status is racy, but A/B run in parallel and
    // each sets a different key; jsonb_set semantics from supabase-js client
    // would require a custom RPC. Cheaper: send a complete call_status snapshot
    // along with each update. This module owns call_status while the job is
    // running, so collisions are limited to the A/B parallel pair — we resolve
    // via a final reconciliation patch after Promise.all resolves.
    await updateJob(statusPatch);
    return { ...result, from_cache: false };
  };

  // ── Calls A + B in parallel ───────────────────────────────────────────
  const aPromise = runAndPersist("a", sysBlocksA, userMsgA);
  const bPromise = runAndPersist("b", sysBlocksB, userMsgB);

  const settled = await Promise.allSettled([aPromise, bPromise]);
  const aRes = settled[0];
  const bRes = settled[1];

  const aOk = aRes.status === "fulfilled";
  const bOk = bRes.status === "fulfilled";

  // Reconcile call_status now that A and B are both settled.
  const reconciledStatus: Record<string, "done" | "failed"> = {};
  if (priorOutputs?.a) reconciledStatus.a = "done";
  if (priorOutputs?.b) reconciledStatus.b = "done";
  if (priorOutputs?.c) reconciledStatus.c = "done";
  reconciledStatus.a = aOk ? "done" : "failed";
  reconciledStatus.b = bOk ? "done" : "failed";
  await updateJob({ call_status: reconciledStatus });

  if (!aOk || !bOk) {
    const errs: string[] = [];
    if (!aOk) errs.push(`A: ${(aRes as PromiseRejectedResult).reason?.message || "unknown"}`);
    if (!bOk) errs.push(`B: ${(bRes as PromiseRejectedResult).reason?.message || "unknown"}`);
    throw new Error(`3-call generation failed in parallel phase — ${errs.join(" | ")}`);
  }

  const aValue = (aRes as PromiseFulfilledResult<SingleCallResult & { from_cache: boolean }>).value;
  const bValue = (bRes as PromiseFulfilledResult<SingleCallResult & { from_cache: boolean }>).value;

  // ── Build Call C inputs (depend on Call B's output for "Right Now") ───
  const pinnedNatalConstraints = buildPinnedNatalConstraints(callCActivationsBlock || "");
  const rightNowBlock = buildRightNowBlock(bValue.json, effectiveCurrentDate);
  const hasRightNowBlock = /GROUND TRUTH \((?!0 found)/.test(rightNowBlock);
  const directiveC = buildDirectiveC(pinnedNatalConstraints, hasRightNowBlock);
  const sysBlocksC = buildSharedSystemBlocks(masterSystemPrompt, chartScopedRulesShared, directiveC, effectiveCurrentDate);
  const userMsgC = buildCallCUserMessage(
    natalChartBlock,
    srChartBlock,
    userQuestion,
    callCActivationsBlock || "",
    callCRetrogradeSummary || "",
    rightNowBlock,
    effectiveCurrentDate,
  );
  console.info(`[3call] Right Now block built: hasRightNow=${hasRightNowBlock}, blockLen=${rightNowBlock.length}`);

  // ── Call C sequentially after A+B succeed ─────────────────────────────
  // DIAGNOSTIC: confirm the verified-activations ground-truth block actually
  // reaches Call C's user message. If it doesn't, the model has nothing to
  // anchor its overlay prose to and will fall back to inventing aspects.
  {
    const marker = "VERIFIED CROSS-CHART ACTIVATIONS";
    const idx = userMsgC.indexOf(marker);
    const activationsArgLen = (callCActivationsBlock || "").length;
    const head = userMsgC.slice(0, 300).replace(/\s+/g, " ");
    const blockExcerpt = idx >= 0
      ? userMsgC.slice(idx, idx + 400).replace(/\s+/g, " ")
      : "(block not found in userMsgC)";
    // Find the directive block inside the system stack and excerpt it so we
    // can confirm at runtime that the new ABSOLUTE CONSTRAINT directive
    // actually shipped to the model.
    const sysJoined = sysBlocksC
      .map((b) => (typeof b?.text === "string" ? b.text : ""))
      .join("\n---\n");
    const dirMarker = "ABSOLUTE CONSTRAINT FOR THIS CALL";
    const dirIdx = sysJoined.indexOf(dirMarker);
    const directiveExcerpt = dirIdx >= 0
      ? sysJoined.slice(dirIdx, dirIdx + 500).replace(/\s+/g, " ")
      : "(ABSOLUTE CONSTRAINT directive NOT FOUND in system blocks)";
    console.info(
      `[ask-astrology][callC-diag] userMsg length=${userMsgC.length}, activationsBlock arg length=${activationsArgLen}, marker index=${idx}, directive index=${dirIdx}\n  userMsgC head(0..300): "${head}"\n  activations block excerpt: "${blockExcerpt}"\n  directive excerpt: "${directiveExcerpt}"`,
    );
  }
  let cValue: SingleCallResult & { from_cache: boolean };
  try {
    cValue = await runAndPersist("c", sysBlocksC, userMsgC);
    reconciledStatus.c = "done";
    await updateJob({ call_status: reconciledStatus });
  } catch (cErr: any) {
    reconciledStatus.c = "failed";
    await updateJob({ call_status: reconciledStatus });
    throw new Error(`3-call generation failed at overlay (Call C) — ${cErr?.message || String(cErr)}`);
  }

  // ── Merge sections in canonical order ─────────────────────────────────
  // Pluck each (call, title) entry from MERGE_ORDER. Sections that don't
  // exist in the call's output (e.g. SR placements when no SR chart) are
  // silently skipped — the existing pipeline already tolerates missing
  // optional sections.
  const callOutputs: Record<CallId, any> = {
    a: aValue.json,
    b: bValue.json,
    c: cValue.json,
  };

  const findSectionByTitle = (sections: any[], title: string): any | null => {
    if (!Array.isArray(sections)) return null;
    const t = title.toLowerCase().trim();
    for (const s of sections) {
      const st = typeof s?.title === "string" ? s.title.toLowerCase().trim() : "";
      if (st === t) return s;
    }
    // Loose match: contains (handles minor title drift like "The Relationship Pattern")
    for (const s of sections) {
      const st = typeof s?.title === "string" ? s.title.toLowerCase().trim() : "";
      if (st.includes(t) || t.includes(st)) return s;
    }
    return null;
  };

  const mergedSections: any[] = [];
  for (const entry of MERGE_ORDER) {
    if (entry.call === "code") continue; // injected by caller (polarity/elements)
    const out = callOutputs[entry.call as CallId];
    const section = findSectionByTitle(out?.sections, entry.title);
    if (section) {
      // Stamp provenance for debugging.
      section._source_call = entry.call;
      mergedSections.push(section);
    }
  }

  // Top-level metadata: take from any call; prefer A (natal-anchored).
  const merged: any = {
    ...(aValue.json && typeof aValue.json === "object" ? aValue.json : {}),
    sections: mergedSections,
    question_type: "relationship",
    _three_call: {
      enabled: true,
      a: { ms: aValue.ms, attempts: aValue.attempts, from_cache: aValue.from_cache },
      b: { ms: bValue.ms, attempts: bValue.attempts, from_cache: bValue.from_cache },
      c: { ms: cValue.ms, attempts: cValue.attempts, from_cache: cValue.from_cache },
      total_ms: Date.now() - overallStart,
    },
  };

  return {
    mergedJsonString: JSON.stringify(merged),
    diagnostics: {
      a: { ok: true, from_cache: aValue.from_cache, attempts: aValue.attempts, ms: aValue.ms },
      b: { ok: true, from_cache: bValue.from_cache, attempts: bValue.attempts, ms: bValue.ms },
      c: { ok: true, from_cache: cValue.from_cache, attempts: cValue.attempts, ms: cValue.ms },
      total_ms: Date.now() - overallStart,
    },
  };
};

// ─── Deterministic polarity / element / modality computation ───────────────
// Spec: Yang planets always: Sun, Mars, Jupiter, Saturn, Uranus
//       Yin planets always: Moon, Venus, Neptune, Pluto
//       Mercury: neutral, count toward Yang
// So Yang = Sun+Mercury+Mars+Jupiter+Saturn+Uranus = 6 planets always
//    Yin  = Moon+Venus+Neptune+Pluto = 4 planets always
// Total = 10. Sum is structurally guaranteed.

const PLANET_POLARITY: Record<string, "Yang" | "Yin"> = {
  Sun: "Yang", Mercury: "Yang", Mars: "Yang", Jupiter: "Yang", Saturn: "Yang", Uranus: "Yang",
  Moon: "Yin", Venus: "Yin", Neptune: "Yin", Pluto: "Yin",
};

const SIGN_ELEMENT: Record<string, "Fire" | "Earth" | "Air" | "Water"> = {
  Aries: "Fire", Leo: "Fire", Sagittarius: "Fire",
  Taurus: "Earth", Virgo: "Earth", Capricorn: "Earth",
  Gemini: "Air", Libra: "Air", Aquarius: "Air",
  Cancer: "Water", Scorpio: "Water", Pisces: "Water",
};

const SIGN_MODALITY: Record<string, "Cardinal" | "Fixed" | "Mutable"> = {
  Aries: "Cardinal", Cancer: "Cardinal", Libra: "Cardinal", Capricorn: "Cardinal",
  Taurus: "Fixed", Leo: "Fixed", Scorpio: "Fixed", Aquarius: "Fixed",
  Gemini: "Mutable", Virgo: "Mutable", Sagittarius: "Mutable", Pisces: "Mutable",
};

const COUNTED_PLANETS = Object.keys(PLANET_POLARITY); // exactly 10

export interface DeterministicTallies {
  elements: Array<{ name: string; tag: string; count: number; planets: string[] }>;
  modalities: Array<{ name: string; tag: string; count: number; planets: string[] }>;
  polarity: Array<{ name: string; tag: string; count: number; planets: string[] }>;
}

/**
 * Parse natal chart text (lines like "Sun: 12°34' Capricorn (House 1)") and
 * return code-computed element / modality / polarity counts. The polarity
 * tally is fixed by planet identity (never derived from sign), so the total
 * is structurally guaranteed to be 10 regardless of what the AI does.
 */
/**
 * Extract a single planetary-positions block ("NATAL" or "SR") from the
 * full ask-astrology chart context string. Returns the empty string if the
 * requested header is not present. Used so the deterministic balance
 * computation never accidentally folds NATAL planet signs into an SR
 * section (or vice versa) when the full context contains both blocks.
 */
export const extractPositionsBlock = (
  chartContext: string,
  source: "NATAL" | "SR",
): string => {
  if (!chartContext) return "";
  // Match "NATAL Planetary Positions:" or "SR Planetary Positions:" exactly.
  const headerRe =
    source === "SR"
      ? /\bSR Planetary Positions:\s*\n/
      : /\bNATAL Planetary Positions:\s*\n/;
  const headerMatch = chartContext.match(headerRe);
  if (!headerMatch) return "";
  const startIdx = headerMatch.index! + headerMatch[0].length;
  const tail = chartContext.slice(startIdx);
  // Stop at the next blank line or another all-caps section header.
  const endMatch = tail.match(
    /\n\s*\n|\n[A-Z][A-Z ]{6,}:|\nHouse Cusps|\nPlanets In Each|\nRuler Chains|\nVERIFIED|\nSR House Cusps|\nSR-TO-NATAL|\nNATAL Planetary Positions|\nSR Planetary Positions/,
  );
  return endMatch ? tail.slice(0, endMatch.index!) : tail;
};

export const computeDeterministicTallies = (chartBlock: string, opts?: { source?: "NATAL" | "SR" }): DeterministicTallies => {
  // If the caller passes the full chart context (containing both NATAL and
  // SR blocks) and tells us which source they want, slice the right block
  // first. Otherwise use whatever string they passed (back-compat: relationship
  // 3-call already passes a single isolated block).
  const block = opts?.source ? extractPositionsBlock(chartBlock, opts.source) || chartBlock : chartBlock;
  const planetSign: Record<string, string> = {};
  // SR-prefixed lines look like "- SR Sun: 12°34' Capricorn". We strip the
  // optional "SR " prefix so the planet key is just "Sun" (matches NATAL keys
  // and COUNTED_PLANETS).
  const re = /^[\s\-\*•]*(?:SR\s+)?([A-Za-z][A-Za-z\s]*?):\s*\d+°\d+'\s+(Aries|Taurus|Gemini|Cancer|Leo|Virgo|Libra|Scorpio|Sagittarius|Capricorn|Aquarius|Pisces)\b/gm;
  let m: RegExpExecArray | null;
  while ((m = re.exec(block)) !== null) {
    const planet = m[1].trim();
    const sign = m[2];
    if (!planetSign[planet]) planetSign[planet] = sign;
  }

  const elements = { Fire: 0, Earth: 0, Air: 0, Water: 0 };
  const modalities = { Cardinal: 0, Fixed: 0, Mutable: 0 };
  const polarity = { Yang: 0, Yin: 0 };

  const elementPlanets: Record<string, string[]> = { Fire: [], Earth: [], Air: [], Water: [] };
  const modalityPlanets: Record<string, string[]> = { Cardinal: [], Fixed: [], Mutable: [] };
  const polarityPlanets: Record<string, string[]> = { Yang: [], Yin: [] };

  for (const planet of COUNTED_PLANETS) {
    const sign = planetSign[planet];
    if (sign && SIGN_ELEMENT[sign]) {
      elements[SIGN_ELEMENT[sign]]++;
      elementPlanets[SIGN_ELEMENT[sign]].push(planet);
    }
    if (sign && SIGN_MODALITY[sign]) {
      modalities[SIGN_MODALITY[sign]]++;
      modalityPlanets[SIGN_MODALITY[sign]].push(planet);
    }
    polarity[PLANET_POLARITY[planet]]++; // polarity by planet identity, sign-independent
    polarityPlanets[PLANET_POLARITY[planet]].push(planet);
  }

  // Emit BOTH `name` (consumed by hygiene/validators/UI) AND `tag`
  // (legacy field) so every downstream reader works on every reading
  // type. Without `name`, `correctModalityElementCounts`,
  // `enforceNonZeroCoverage`, the Replit gate, and the PDF renderer all
  // see the entries as nameless and report 0 counts even though the
  // integer is correct in the array. The "Yang (Active)" / "Yin
  // (Receptive)" suffix on polarity matches the prompt's stub format so
  // the loose match in correctModalityElementCounts (firstWord = "yang"
  // / "yin") and the explicit lookups still resolve.
  return {
    elements: (["Fire", "Earth", "Air", "Water"] as const).map((tag) => ({ name: tag, tag, count: elements[tag], planets: elementPlanets[tag] })),
    modalities: (["Cardinal", "Fixed", "Mutable"] as const).map((tag) => ({ name: tag, tag, count: modalities[tag], planets: modalityPlanets[tag] })),
    polarity: (["Yang", "Yin"] as const).map((tag) => {
      const name = tag === "Yang" ? "Yang (Active)" : "Yin (Receptive)";
      return { name, tag, count: polarity[tag], planets: polarityPlanets[tag] };
    }),
  };
};

/**
 * Build a `modality_element` section object from deterministic tallies.
 * The `balance_interpretation` field is intentionally left empty — the
 * existing `enforceNonZeroCoverage` hygiene pass will fill it with a
 * coverage clause that names every non-zero element/modality/polarity.
 */
export const buildModalityElementSection = (tallies: DeterministicTallies): any => {
  const pickDominant = (arr: Array<{ name: string; count: number }>): string => {
    const max = arr.reduce((a, b) => (b.count > a.count ? b : a), arr[0]);
    return max?.name ?? "";
  };
  return {
    type: "modality_element",
    title: "Natal Elemental & Modal Balance",
    elements: tallies.elements,
    modalities: tallies.modalities,
    polarity: tallies.polarity,
    dominant_element: pickDominant(tallies.elements as any),
    dominant_modality: pickDominant(tallies.modalities as any),
    dominant_polarity: pickDominant(tallies.polarity as any),
    balance_interpretation: "",
    body: "",
    _deterministic: true,
  };
};

/**
 * Insert (or replace) the modality_element section in the merged sections
 * array at the spot indicated by MERGE_ORDER. Idempotent.
 *
 * PRESERVATION RULE: when replacing an existing modality_element section,
 * any non-empty `body` or `balance_interpretation` the AI authored is
 * preserved on the new section. We only overwrite the deterministic count
 * arrays (elements/modalities/polarity) and dominant_* fields; prose is
 * AI-authored and must survive the inject so downstream body backfills
 * have something to copy from.
 */
export const injectDeterministicModalityElement = (
  parsedContent: any,
  chartContext: string,
): { injected: boolean; tallies: DeterministicTallies } => {
  if (!parsedContent || !Array.isArray(parsedContent.sections)) {
    return { injected: false, tallies: { elements: [], modalities: [], polarity: [] } };
  }

  const isNonEmptyString = (v: unknown): v is string =>
    typeof v === "string" && v.trim().length > 0;

  // Detect whether the existing modality_element section is SR-flavored
  // by its title. If so, deterministic counts MUST be computed from the
  // SR Planetary Positions block, not the natal block — otherwise the
  // section's prose ends up describing natal element/modality balance
  // under an SR title and the external gate flags BALANCE_CLAIM_MISMATCH.
  const existingIdx = parsedContent.sections.findIndex((s: any) => s?.type === "modality_element");
  const existing = existingIdx >= 0 ? parsedContent.sections[existingIdx] : null;
  const existingTitle = isNonEmptyString(existing?.title) ? existing.title : "";
  const isSrSection = /\b(solar\s*return|sr)\b/i.test(existingTitle);

  // Pick the right block. If the caller passed the full chartContext,
  // we extract the matching block; if they passed a pre-isolated natal
  // block (relationship 3-call path), the extractor falls back to the
  // input string and behavior is unchanged.
  const tallies = computeDeterministicTallies(chartContext, { source: isSrSection ? "SR" : "NATAL" });
  const newSection = buildModalityElementSection(tallies);
  if (isSrSection) {
    newSection.title = existingTitle || "Solar Return Elemental & Modal Balance";
  }

  // Replace any existing modality_element section, otherwise insert at the
  // canonical slot (just before the summary_box at the end).
  if (existingIdx >= 0) {
    const prev = existing || {};
    // Preserve AI-authored prose so the body backfill has source material.
    if (isNonEmptyString(prev.body)) newSection.body = prev.body;
    if (isNonEmptyString(prev.balance_interpretation)) {
      newSection.balance_interpretation = prev.balance_interpretation;
    }
    if (isNonEmptyString(prev.title)) newSection.title = prev.title;
    parsedContent.sections[existingIdx] = newSection;
    return { injected: true, tallies };
  }
  // Insert before the first summary_box; if none, append.
  const summaryIdx = parsedContent.sections.findIndex((s: any) => s?.type === "summary_box");
  const insertAt = summaryIdx >= 0 ? summaryIdx : parsedContent.sections.length;
  parsedContent.sections.splice(insertAt, 0, newSection);
  return { injected: true, tallies };
};

/**
 * After merge, overwrite any AI-authored polarity counts in any
 * modality_element section with the deterministic values. Defensive:
 * even if a future call sneaks one in, polarity counts are guaranteed
 * to sum to 10 in the final JSON.
 */
export const overwriteAllPolarityCounts = (
  parsedContent: any,
  chartContext: string,
): number => {
  if (!parsedContent || !Array.isArray(parsedContent.sections)) return 0;
  // Pre-compute tallies for both possible sources so each section gets
  // numbers from the correct chart (natal vs SR). For relationship 3-call
  // path the input is already an isolated natal block — extractPositionsBlock
  // returns "" and computeDeterministicTallies falls back to the full input,
  // so behavior on that path is unchanged.
  const natalTallies = computeDeterministicTallies(chartContext, { source: "NATAL" });
  const srTallies = computeDeterministicTallies(chartContext, { source: "SR" });
  let overwritten = 0;
  for (const section of parsedContent.sections) {
    if (section?.type !== "modality_element") continue;
    const title = typeof section.title === "string" ? section.title : "";
    const isSr = /\b(solar\s*return|sr)\b/i.test(title);
    const t = isSr ? srTallies : natalTallies;
    // Only overwrite when the chosen source actually parsed planets, so a
    // missing SR block can't blank an SR section's counts to all zeros.
    const hasData = t.polarity.some((p) => p.count > 0);
    if (!hasData) continue;
    section.polarity = t.polarity;
    section.elements = t.elements;
    section.modalities = t.modalities;
    overwritten++;
  }
  return overwritten;
};

// ─── Resume support: read prior outputs from the ask_jobs row ──────────────

export interface AskJobRow {
  call_a_output?: any;
  call_b_output?: any;
  call_c_output?: any;
  call_status?: Record<string, "done" | "failed"> | null;
}

/**
 * Build a priorOutputs map from a job row, only including calls whose
 * status was "done" AND whose output column actually contains data.
 * If call_status is empty (fresh job), returns {}.
 */
export const buildPriorOutputs = (row: AskJobRow): Partial<Record<CallId, PriorCallOutput>> => {
  const status = row.call_status || {};
  const out: Partial<Record<CallId, PriorCallOutput>> = {};
  if (status.a === "done" && row.call_a_output) out.a = { json: row.call_a_output };
  if (status.b === "done" && row.call_b_output) out.b = { json: row.call_b_output };
  if (status.c === "done" && row.call_c_output) out.c = { json: row.call_c_output };
  return out;
};
